# -*- coding: utf-8 -*-
"""Blog — rotina do lojista.

Estas páginas NÃO falam do SoftPay como assunto principal. Falam do problema
que a pessoa tem antes de saber que precisa de um sistema: precificar, perder
mercadoria por validade, montar vitrine, lidar com troca. É a etapa mais larga
do funil, e era a única que o site não cobria — o concorrente Nex tem 444 posts
desse tipo contra 0 daqui (medido em 2026-09-08).

A regra de escrita é a mesma das demais: número em vez de adjetivo, o erro
antes da lição, e nada de recurso inventado. O produto aparece no fim, como
consequência, nunca como resposta para tudo.
"""
from blocks import sec, p, ul, ol, h3, nota, exemplo, tabela

C = [("Blog", "/blog/")]
def _c(n): return C + [(n, None)]

PAGINAS = [

dict(
  artigo=True,
  slug="blog/como-precificar-produto",
  title="Como Precificar um Produto na Loja: Markup e Margem | SoftPay",
  description="A diferença entre markup e margem, a fórmula de cada um e o erro que faz o lojista achar que ganha 40% quando ganha 28%. Com exemplo numérico.",
  h1="Como precificar um produto na loja",
  intro="O erro mais comum na precificação não é errar a conta: é confundir markup com margem. São coisas diferentes, e quem troca uma pela outra acha que ganha 40% quando ganha 28%. Esta página mostra a diferença com número.",
  breadcrumbs=_c("Como precificar um produto"),
  blocks=[
    sec("O erro que quase todo lojista comete",
      p("Você compra um produto por R$ 100 e quer ganhar 40%. Vende por R$ 140, certo?"),
      p("Você acabou de aplicar um <strong>markup</strong> de 40%. Mas a sua <strong>margem</strong> não é 40% — é 28,6%. E a diferença entre esses dois números é dinheiro que você achou que tinha e não tem."),
      exemplo("Por que R$ 140 não dá 40% de margem", [
        ("Custo do produto", "R$ 100,00", ""),
        ("Preço de venda (custo + 40%)", "R$ 140,00", ""),
        ("Lucro em reais", "R$ 40,00", "result"),
        ("Margem real (40 ÷ 140)", "28,6%", "result final"),
      ], "O markup se calcula <strong>sobre o custo</strong>. A margem se calcula <strong>sobre o preço de venda</strong>. Mesma venda, dois números diferentes."),
    ),
    sec("A diferença entre markup e margem",
      tabela(["", "Markup", "Margem"], [
        ["Calculado sobre", "o custo", "o preço de venda"],
        ["Pergunta que responde", "quanto acrescento ao custo?", "quanto sobra de cada venda?"],
        ["No exemplo acima", "40%", "28,6%"],
        ["Serve para", "formar o preço", "saber o resultado"],
      ]),
      p("Os dois são úteis: o markup é como você <em>chega</em> ao preço, a margem é o que você <em>ganha</em>. O problema é usar um pensando que é o outro."),
    ),
    sec("Se você quer uma margem específica, use esta fórmula",
      p("Para ter <strong>40% de margem de verdade</strong>, o preço não é custo + 40%. É:"),
      exemplo("Preço para uma margem-alvo de 40%", [
        ("Custo do produto", "R$ 100,00", ""),
        ("Divisor: 1 − 0,40", "0,60", ""),
        ("Preço de venda (100 ÷ 0,60)", "R$ 166,67", "result"),
        ("Lucro em reais", "R$ 66,67", ""),
        ("Margem real (66,67 ÷ 166,67)", "40,0%", "result final"),
      ], "A fórmula é <strong>preço = custo ÷ (1 − margem desejada)</strong>. Guarde essa, ela resolve a maior parte dos casos."),
    ),
    sec("O custo não é só o que você pagou no produto",
      p("O segundo erro mais caro é formar o custo só com a nota do fornecedor. Entram também:"),
      ul("<strong>Frete da compra</strong>, rateado por unidade.",
         "<strong>Impostos</strong> que incidem na venda — confirme com o seu contador quais se aplicam ao seu regime.",
         "<strong>Taxa da maquininha</strong>, que numa venda no cartão come de 2% a 5%.",
         "<strong>Embalagem</strong>, sacola, etiqueta.",
         "<strong>Perda</strong>: o que quebra, vence ou some. Se 3% do seu estoque se perde, esse custo está nos outros 97%."),
      nota("Uma loja que vende no cartão e não considera a taxa da maquininha na formação do preço perde a margem inteira de alguns produtos sem nunca descobrir por quê. Some a taxa <strong>antes</strong> de calcular o preço, não depois.", "O custo esquecido com mais frequência"),
    ),
    sec("Nem todo produto precisa da mesma margem",
      p("Aplicar o mesmo percentual em tudo é simples, mas deixa dinheiro na mesa e afasta cliente:"),
      ul("<strong>Produto de alto giro e comparável</strong> (refrigerante, arroz, o item que o cliente sabe quanto custa) pede margem menor. É por ele que a pessoa entra na loja.",
         "<strong>Produto de baixo giro ou exclusivo</strong> suporta margem maior, porque o cliente não tem parâmetro.",
         "<strong>Produto que puxa venda</strong> pode ter margem quase zero de propósito, desde que leve outros junto.",
         "<strong>Produto encalhado</strong> precisa sair, e às vezes sair com prejuízo é melhor que ocupar espaço por mais um ano."),
    ),
    sec("Como saber se seu preço está funcionando",
      p("Preço não se acerta uma vez: se acompanha. Três sinais de que o seu precisa de revisão:"),
      ol("<strong>Você vende bem e não sobra dinheiro.</strong> Sinal clássico de markup confundido com margem, ou de custo incompleto.",
         "<strong>Um produto vende muito mais que os outros.</strong> Pode estar barato demais.",
         "<strong>Um produto não vende há meses.</strong> Pode estar caro demais — ou ser um produto errado para a sua loja."),
      p("Para acompanhar isso sem planilha, é preciso ter <strong>o custo cadastrado por produto</strong>. É o passo que quase todo mundo pula, e sem ele nenhuma dessas contas existe. O método está no guia <a href=\"/guias/como-calcular-margem-de-lucro/\">como calcular margem de lucro</a>."),
    ),
  ],
  faq=[
    ("Qual a diferença entre markup e margem?",
     "O markup é calculado sobre o custo; a margem, sobre o preço de venda. Um produto que custa R$ 100 e é vendido por R$ 140 tem markup de 40% e margem de 28,6%. Confundir os dois é o erro de precificação mais comum."),
    ("Como calcular o preço para ter 40% de margem?",
     "Divida o custo por (1 − margem desejada). Para 40% de margem sobre um custo de R$ 100: 100 ÷ 0,60 = R$ 166,67."),
    ("Qual margem devo usar na minha loja?",
     "Não existe um número único. Produto de alto giro e comparável pede margem menor; produto exclusivo ou de baixo giro suporta margem maior. O que não funciona é aplicar o mesmo percentual em tudo."),
    ("Preciso incluir a taxa da maquininha no preço?",
     "Sim. A taxa come de 2% a 5% da venda no cartão. Se ela não entra na formação do preço, some direto da sua margem."),
    ("Como sei se estou vendendo com prejuízo?",
     "Só dá para saber com o custo cadastrado por produto, incluindo frete, embalagem, impostos e taxa de cartão. Sem isso, o resultado do mês é estimativa."),
    ("Devo mudar meus preços com que frequência?",
     "Sempre que o custo mudar, e ao menos uma vez por ano numa revisão geral. Preço de produto cujo fornecedor aumentou e você não repassou é margem perdida em silêncio."),
  ],
  cta_title="Cadastre o custo e veja a margem real",
  cta_text="Com custo por produto, a margem deixa de ser estimativa. 7 dias grátis, sem cartão de crédito.",
  related=[("Como calcular margem de lucro", "/guias/como-calcular-margem-de-lucro/", "O método completo"),
           ("Como calcular o lucro da loja", "/guias/como-calcular-lucro-da-loja/", "Do faturamento ao que sobra"),
           ("Perda de estoque", "/blog/perda-de-estoque-validade/", "O custo que some da conta"),
           ("Controle de estoque", "/solucoes/sistema-de-estoque/", "Custo e curva ABC"),
           ("Produtos parados", "/blog/produtos-parados-no-estoque/", "Dinheiro na prateleira"),
           ("Como controlar estoque", "/guias/como-controlar-estoque/", "O passo a passo")],
),

dict(
  artigo=True,
  slug="blog/perda-de-estoque-validade",
  title="Perda de Estoque por Validade: Como Evitar o Prejuízo | SoftPay",
  description="Produto que vence é prejuízo dobrado: você pagou por ele e ainda descarta. Veja o método PVPS, o cálculo do que a perda custa e como reduzir sem sistema caro.",
  h1="Perda de estoque por validade",
  intro="Produto vencido é prejuízo dobrado: você pagou pela mercadoria e ainda tem o trabalho de descartar. Numa loja pequena, com estoque enxuto, cada item perdido pesa mais — e quase sempre a perda tem a mesma causa, que dá para corrigir sem gastar nada.",
  breadcrumbs=_c("Perda de estoque por validade"),
  blocks=[
    sec("A causa é quase sempre a mesma",
      p("A mercadoria nova chega e é colocada onde tem espaço — normalmente na frente, porque é mais fácil. A antiga vai para o fundo. O cliente pega a da frente. A do fundo vence."),
      p("Não é descuido: é o caminho natural de quem está com pressa recebendo mercadoria. Corrigir isso não custa dinheiro, custa <strong>uma regra combinada com quem repõe</strong>."),
    ),
    sec("A regra que resolve a maior parte: PVPS",
      p("<strong>Primeiro a Vencer, Primeiro a Sair.</strong> Quando chega mercadoria nova, ela vai para <em>trás</em> da que já estava lá, e a mais antiga fica na frente."),
      ol("Ao repor a prateleira, puxe o que já está lá para a frente.",
         "Coloque a mercadoria nova atrás.",
         "Confira a validade do que ficou na frente — se estiver perto, é hora de decidir o que fazer com ele.",
         "Combine essa regra com <strong>todo mundo</strong> que repõe, não só com você."),
      nota("Essa única mudança resolve boa parte das perdas por validade em loja pequena. Não depende de sistema, não depende de investimento — depende de a regra ser combinada e repetida até virar hábito.", "O que mais rende, e é de graça"),
    ),
    sec("Quanto a perda realmente custa",
      p("O prejuízo não é o preço de venda do que venceu: é o <strong>custo</strong> do que venceu, mais o que aquele espaço deixou de gerar."),
      exemplo("Uma loja que perde 2% do estoque por mês", [
        ("Valor do estoque a custo", "R$ 30.000,00", ""),
        ("Perda mensal (2%)", "R$ 600,00", "minus"),
        ("Perda em 12 meses", "R$ 7.200,00", "result final"),
      ], "Números ilustrativos. Faça com os seus: se o resultado do ano paga um ano inteiro de sistema de gestão com sobra, a conta se resolve sozinha."),
      p("O segundo custo é invisível: o dinheiro parado naquele item não estava comprando o produto que vende."),
    ),
    sec("O que fazer com o que está perto de vencer",
      p("Decidir cedo vale mais que decidir bem. Um produto a 60 dias do vencimento tem muitas saídas; a 5 dias, quase nenhuma:"),
      ul("<strong>Remarcação progressiva.</strong> Desconto pequeno cedo costuma resolver melhor que desconto grande em cima da hora.",
         "<strong>Combo.</strong> Junte com um produto de giro alto.",
         "<strong>Ponta de gôndola ou frente de balcão.</strong> Mudar o lugar do produto às vezes basta.",
         "<strong>Devolução ao fornecedor.</strong> Alguns aceitam troca de mercadoria perto do vencimento — vale perguntar antes de assumir que não.",
         "<strong>Aceitar a perda cedo.</strong> Vender com prejuízo pequeno é melhor que descartar com prejuízo inteiro."),
    ),
    sec("Como saber o que está perto de vencer sem conferir tudo",
      p("Conferir a validade de tudo, toda semana, não é realista em loja pequena. O que funciona é concentrar o esforço:"),
      ol("<strong>Liste os produtos de validade curta</strong> — normalmente uma minoria: laticínios, pães, alguns cosméticos, medicamentos.",
         "<strong>Confira só esses, com frequência fixa.</strong> Uma vez por semana, no mesmo dia.",
         "<strong>O resto entra na conferência mensal</strong>, junto com a contagem de estoque.",
         "<strong>Anote o que perdeu e por quê.</strong> Três meses de anotação mostram o padrão — e o padrão é o que dá para corrigir."),
      nota("Sendo transparente: <strong>o controle de validade não é um recurso confirmado do SoftPay</strong>. Se ele é decisivo para o seu negócio, confirme com o suporte antes de contratar. O que o sistema resolve aqui é o lado do giro — saber o que sai devagar antes de o prazo apertar.", "O que o SoftPay faz, e o que não faz"),
    ),
  ],
  faq=[
    ("O que é o método PVPS?",
     "Primeiro a Vencer, Primeiro a Sair: a mercadoria nova vai para trás da que já está na prateleira, e a mais antiga fica na frente. É a regra que resolve a maior parte das perdas por validade em loja pequena, e não custa nada."),
    ("Qual a diferença entre ruptura e quebra de estoque?",
     "Ruptura é quando o cliente quer comprar e o produto não está lá — venda perdida. Quebra é a perda física: produto vencido, danificado ou extraviado. As duas custam dinheiro, mas por caminhos diferentes."),
    ("Quanto de perda de estoque é aceitável?",
     "Depende muito do ramo — produto perecível perde mais que produto durável. O número que importa é o seu, acompanhado ao longo dos meses: o que preocupa é a perda que cresce, não a que existe."),
    ("Vale a pena dar desconto em produto perto do vencimento?",
     "Quase sempre sim, e quanto antes melhor. Desconto pequeno com 60 dias de prazo costuma resolver melhor que desconto grande na última semana."),
    ("O SoftPay controla validade de produto?",
     "Esse é um ponto a confirmar com o suporte antes de contratar. O que o sistema faz é mostrar o giro — quais produtos saem devagar —, o que ajuda a agir antes de o prazo apertar."),
    ("Como sei quanto estou perdendo por mês?",
     "Anote o que descartou e o custo de cada item, por três meses. Sem esse registro, a perda é sentida mas nunca medida — e o que não se mede não se corrige."),
  ],
  cta_title="Saiba o que gira devagar antes de vencer",
  cta_text="Com custo e giro por produto, o item parado aparece antes de virar perda. 7 dias grátis, sem cartão.",
  related=[("Produtos parados no estoque", "/blog/produtos-parados-no-estoque/", "Dinheiro preso na prateleira"),
           ("Como controlar estoque", "/guias/como-controlar-estoque/", "O passo a passo"),
           ("Como precificar", "/blog/como-precificar-produto/", "A perda entra no custo"),
           ("Controle de estoque", "/solucoes/sistema-de-estoque/", "O recurso no SoftPay"),
           ("Mercadinho", "/segmentos/mercadinho/", "Onde a validade mais pesa"),
           ("Farmácia", "/segmentos/farmacia/", "Outro caso de validade curta")],
),

dict(
  artigo=True,
  slug="blog/produtos-parados-no-estoque",
  title="Produtos Parados no Estoque: Como Achar e o Que Fazer | SoftPay",
  description="Como identificar o produto que não gira, calcular quanto dinheiro está preso nele e decidir entre remarcar, combinar ou aceitar a perda. Com curva ABC.",
  h1="Produtos parados no estoque",
  intro="Produto parado não é neutro: é dinheiro que você já pagou, ocupando espaço, sem virar venda. E ele é difícil de ver justamente porque não acontece nada — ninguém repara no que não se move.",
  breadcrumbs=_c("Produtos parados no estoque"),
  blocks=[
    sec("Por que o produto parado é invisível",
      p("A falta de um produto é escandalosa: o cliente pergunta, ninguém acha, a venda se perde na sua frente. Já o produto que não vende não faz barulho nenhum. Ele está lá, arrumadinho, há oito meses."),
      p("É por isso que quase toda loja descobre o encalhe no inventário, quando já passou tempo demais para resolver com desconto pequeno."),
    ),
    sec("Como achar sem sistema",
      ol("<strong>Marque a data de entrada.</strong> Uma etiqueta discreta com o mês de chegada já resolve. Em três meses você começa a enxergar o que não se move.",
         "<strong>Olhe a poeira.</strong> Parece grosseiro, mas funciona: o item que ninguém pega há meses se anuncia sozinho.",
         "<strong>Pergunte à sua equipe</strong> quais produtos ninguém pede. Quem está no balcão sabe antes de qualquer relatório."),
      p("Isso resolve o diagnóstico grosseiro. O que não resolve é a pergunta seguinte: <em>quanto</em> dinheiro está preso ali."),
    ),
    sec("Como achar com sistema: a curva ABC",
      p("A curva ABC separa os produtos por participação no resultado:"),
      tabela(["Classe", "O que costuma ser", "Decisão"], [
        ["A", "poucos itens, maior parte do faturamento", "nunca deixar faltar"],
        ["B", "itens intermediários", "acompanhar"],
        ["C", "muitos itens, pouca participação", "aqui mora o encalhe"],
      ]),
      p("A classe C não é toda descartável — tem item de baixo giro que existe por conveniência do cliente. Mas é ali que está o dinheiro parado, e é ali que a análise compensa."),
      p("No SoftPay, a curva ABC está a partir do plano Loja. O método, independente de sistema, está no guia <a href=\"/guias/como-controlar-estoque/\">como controlar estoque</a>."),
    ),
    sec("Quanto dinheiro está preso",
      exemplo("Uma loja com R$ 30.000 em estoque", [
        ("Estoque total a custo", "R$ 30.000,00", ""),
        ("Itens sem venda há mais de 6 meses (18%)", "R$ 5.400,00", "minus"),
        ("= Capital parado", "R$ 5.400,00", "result final"),
      ], "Números ilustrativos. Esse valor é dinheiro que já saiu do caixa e não voltou — e que poderia estar comprando o produto que vende toda semana."),
    ),
    sec("O que fazer com o encalhe",
      p("Em ordem, do que costuma render mais para o que rende menos:"),
      ol("<strong>Mude o lugar antes de mudar o preço.</strong> Produto no fundo da loja às vezes só precisa aparecer.",
         "<strong>Combine com um produto que gira.</strong> Leve dois, pague um e meio, ou combo com o item de classe A.",
         "<strong>Remarque com desconto real.</strong> Desconto de 5% não move item parado há um ano.",
         "<strong>Devolva ao fornecedor</strong>, se houver acordo — vale perguntar.",
         "<strong>Aceite a perda e libere o espaço.</strong> Item parado há dois anos não vai vender; o que ele ocupa vale mais que ele."),
      nota("A decisão mais cara é a que não se toma. Produto parado há seis meses ainda tem saída com desconto moderado; parado há dois anos, quase sempre só sai com prejuízo. O custo de adiar é maior que o desconto que você não quis dar.", "Decidir tarde custa mais que decidir errado"),
    ),
    sec("Como não voltar a acumular",
      ul("<strong>Compre pelo que vendeu, não pelo que acha.</strong> Histórico de venda é o melhor previsor de compra.",
         "<strong>Teste em quantidade pequena.</strong> Produto novo entra em quantidade que você aceita perder.",
         "<strong>Revise a classe C a cada trimestre</strong>, não a cada inventário anual.",
         "<strong>Não repita a compra do que não girou</strong> só porque o fornecedor ofereceu desconto por volume."),
    ),
  ],
  faq=[
    ("O que é curva ABC de produtos?",
     "É a classificação dos produtos por participação no resultado: a classe A são poucos itens que respondem pela maior parte do faturamento, e a classe C são muitos itens de pouca participação — onde costuma estar o dinheiro parado."),
    ("Como sei quais produtos estão parados?",
     "Sem sistema, marque a data de entrada na etiqueta e observe o que não se move em três meses. Com sistema, a curva ABC mostra direto — no SoftPay ela está a partir do plano Loja."),
    ("Vale a pena vender com prejuízo para liberar espaço?",
     "Depende de há quanto tempo o item está parado. Produto encalhado há dois anos raramente vende sem desconto grande, e o espaço que ele ocupa costuma valer mais do que ele. Produto parado há três meses ainda tem saídas melhores."),
    ("Quanto do meu estoque pode estar parado?",
     "Não há número universal. O que importa é acompanhar: se a fatia de itens sem venda cresce a cada trimestre, a compra está desalinhada da venda."),
    ("Devo eliminar todos os produtos de classe C?",
     "Não. Alguns itens de baixo giro existem por conveniência do cliente e ajudam a segurar a compra na sua loja. O alvo é o item que não gira e ninguém procura."),
    ("Como evito comprar errado de novo?",
     "Compre com base no histórico de venda, teste produto novo em quantidade pequena e não repita a compra do que não girou só porque veio com desconto por volume."),
  ],
  cta_title="Veja o que está parado na sua loja",
  cta_text="Com custo e giro por produto, o encalhe aparece antes de virar prejuízo. 7 dias grátis, sem cartão.",
  related=[("Perda de estoque", "/blog/perda-de-estoque-validade/", "Quando o parado vence"),
           ("Como controlar estoque", "/guias/como-controlar-estoque/", "O método completo"),
           ("Como precificar", "/blog/como-precificar-produto/", "Remarcar sem perder margem"),
           ("Controle de estoque", "/solucoes/sistema-de-estoque/", "Curva ABC no SoftPay"),
           ("Loja de roupas", "/segmentos/loja-de-roupas/", "Onde a coleção encalha"),
           ("Loja de variedades", "/segmentos/loja-de-variedades/", "Muitos itens, muito encalhe")],
),

dict(
  artigo=True,
  slug="blog/troca-e-devolucao-na-loja",
  title="Troca e Devolução na Loja: Regras e Como Organizar | SoftPay",
  description="O que o Código de Defesa do Consumidor obriga, o que é política da loja, e como organizar trocas sem prejuízo. Com as regras de arrependimento e vício.",
  h1="Troca e devolução na loja",
  intro="Boa parte dos conflitos de troca vem de uma confusão simples: lojista e cliente acham que a lei diz coisas que ela não diz. Esta página separa o que é obrigação legal do que é política da loja — e como organizar isso sem perder dinheiro.",
  breadcrumbs=_c("Troca e devolução"),
  blocks=[
    sec("O que a lei obriga e o que não obriga",
      p("A confusão mais comum: <strong>a loja física não é obrigada a trocar produto por arrependimento</strong> — quando o cliente simplesmente mudou de ideia, sem defeito algum. Muita gente acha que é."),
      tabela(["Situação", "Obrigação"], [
        ["Produto com defeito (vício)", "A lei obriga a solução — o Código de Defesa do Consumidor prevê prazo para o fornecedor sanar o problema"],
        ["Compra fora do estabelecimento (internet, telefone)", "Direito de arrependimento em 7 dias, previsto no CDC"],
        ["Compra na loja física, sem defeito", "<strong>Não há obrigação legal</strong> — a troca é política da loja"],
      ]),
      nota("Esta página é orientação de rotina, <strong>não é orientação jurídica</strong>. As regras exatas, prazos e exceções estão no Código de Defesa do Consumidor (Lei nº 8.078/1990) e a aplicação ao seu caso deve ser confirmada com um advogado ou com o Procon do seu estado.", "Importante"),
    ),
    sec("Por que ter política de troca mesmo sem obrigação",
      p("A maioria das lojas troca por cortesia mesmo sem ser obrigada. E faz sentido: a troca costuma custar menos que o cliente perdido, e quem volta para trocar frequentemente sai com outra compra."),
      p("O problema não é trocar — é <strong>trocar sem regra</strong>. Sem política escrita, cada atendente decide de um jeito, o cliente insistente consegue mais que o educado, e a loja perde dinheiro sem saber quanto."),
    ),
    sec("O que a sua política precisa dizer",
      ol("<strong>Prazo.</strong> Sete, quinze, trinta dias — o número importa menos que ele existir e ser o mesmo para todos.",
         "<strong>Condição do produto.</strong> Com etiqueta, sem uso, na embalagem original.",
         "<strong>O que comprova a compra.</strong> Nota, cupom ou registro no sistema.",
         "<strong>O que não troca.</strong> Íntimos, cosméticos abertos, produto de mostruário, item em liquidação — se for a sua regra, escreva.",
         "<strong>Como devolve.</strong> Outro produto, crédito na loja ou dinheiro. Crédito costuma ser melhor para o caixa que devolução em dinheiro.",
         "<strong>Onde isso fica visível.</strong> No balcão, no cupom, no site. Regra que o cliente só descobre na hora do conflito não protege ninguém."),
    ),
    sec("Como registrar a troca sem bagunçar o estoque",
      p("É aqui que a troca vira problema de gestão, e não de atendimento:"),
      ul("<strong>O produto que volta precisa voltar ao estoque</strong> — se estiver em condição de venda. Troca não registrada é estoque errado no dia seguinte.",
         "<strong>O produto que sai precisa dar baixa.</strong> Parece óbvio, e é o passo mais esquecido no meio do atendimento.",
         "<strong>A diferença de valor precisa ir para o caixa.</strong> Se o cliente leva algo mais caro e paga a diferença, essa entrada é uma venda.",
         "<strong>Produto devolvido com defeito não volta ao estoque.</strong> Ele vira perda ou devolução ao fornecedor — e precisa estar registrado como tal, senão o seu estoque diz que você tem algo que não pode vender."),
      nota("Sendo transparente: <strong>o registro de troca com controle de crédito do cliente não é um recurso confirmado do SoftPay.</strong> Confirme com o suporte como fazer isso antes de contratar contando com esse fluxo.", "O que confirmar antes de contratar"),
    ),
    sec("Três situações que mais geram atrito",
      h3("O cliente sem nota"),
      p("Se você tem o registro da venda no sistema, com cliente cadastrado, a nota deixa de ser o único comprovante. É um dos benefícios menos falados de registrar as vendas com cliente."),
      h3("O produto em promoção"),
      p("Se item de liquidação não troca, isso precisa estar escrito <strong>e</strong> ser dito na hora da venda. Descobrir na troca é o caminho mais curto para uma reclamação pública."),
      h3("A troca fora do prazo"),
      p("Aqui a política existe justamente para você poder dizer não sem parecer arbitrário. E poder abrir exceção quando quiser, sabendo que é exceção."),
    ),
  ],
  faq=[
    ("Sou obrigado a trocar produto sem defeito?",
     "Na loja física, não. O direito de arrependimento em 7 dias previsto no Código de Defesa do Consumidor vale para compras feitas fora do estabelecimento, como internet e telefone. Na loja física, sem defeito, a troca é política da loja — mas esta página não é orientação jurídica: confirme com o Procon do seu estado."),
    ("E se o produto tiver defeito?",
     "Aí há obrigação legal prevista no Código de Defesa do Consumidor, com prazos definidos para o fornecedor sanar o vício. Consulte o CDC ou um advogado para o seu caso específico."),
    ("Posso dar crédito na loja em vez de devolver dinheiro?",
     "Em troca por cortesia, sim: a política é sua e o crédito costuma ser melhor para o caixa. Em caso de defeito, as regras do CDC se aplicam."),
    ("Preciso de nota fiscal para aceitar a troca?",
     "É a sua política que decide. Se você registra as vendas com o cliente cadastrado no sistema, o histórico funciona como comprovante mesmo sem a nota em mãos."),
    ("O produto devolvido volta para o estoque?",
     "Se estiver em condição de venda, sim, e precisa ser registrado. Se voltou com defeito, não volta ao estoque: vira perda ou devolução ao fornecedor, e também precisa ser registrado como tal."),
    ("O SoftPay registra trocas?",
     "O registro de troca com controle de crédito do cliente é um ponto a confirmar com o suporte antes de contratar."),
  ],
  cta_title="Mantenha o estoque certo depois da troca",
  cta_text="Venda registrada e cliente cadastrado fazem a troca deixar de bagunçar o estoque. 7 dias grátis, sem cartão.",
  related=[("Controle de clientes", "/solucoes/controle-de-clientes/", "Histórico como comprovante"),
           ("Como controlar estoque", "/guias/como-controlar-estoque/", "Entradas e saídas"),
           ("Loja de roupas", "/segmentos/loja-de-roupas/", "Onde a troca é rotina"),
           ("Loja de calçados", "/segmentos/loja-de-calcados/", "Troca de numeração"),
           ("Produtos parados", "/blog/produtos-parados-no-estoque/", "O que volta e não sai"),
           ("Sistema PDV", "/solucoes/sistema-pdv/", "Registro da venda")],
),

dict(
  artigo=True,
  slug="blog/como-organizar-vitrine-de-loja",
  title="Como Organizar a Vitrine de uma Loja Pequena | SoftPay",
  description="Como montar vitrine que traz cliente para dentro: o que colocar, a que altura, com que frequência trocar e o erro de expor tudo ao mesmo tempo.",
  h1="Como organizar a vitrine de uma loja pequena",
  intro="A vitrine é o único vendedor que trabalha 24 horas por dia, inclusive quando a loja está fechada. E o erro mais comum é tratá-la como depósito com visibilidade — colocando tudo, na esperança de que algo chame atenção.",
  breadcrumbs=_c("Como organizar a vitrine"),
  blocks=[
    sec("Uma vitrine, uma mensagem",
      p("Quem passa na calçada te dá dois segundos. Nesses dois segundos dá para transmitir <strong>uma</strong> ideia — não sete."),
      p("Vitrine com trinta produtos diferentes não comunica nada: o olho não sabe onde parar e segue andando. Vitrine com três peças da mesma linha comunica “é isso que essa loja tem de novo”."),
      nota("O teste é simples: pare na calçada, olhe a sua vitrine por dois segundos e desvie o olhar. O que ficou na memória? Se a resposta for “um monte de coisa”, ela ainda não está pronta.", "O teste dos dois segundos"),
    ),
    sec("O que colocar",
      ul("<strong>O produto que representa a loja.</strong> Não o mais caro nem o encalhado: aquele que, se a pessoa entrar por ele, resume o que você vende.",
         "<strong>Novidade.</strong> É o que faz quem já conhece a loja olhar de novo.",
         "<strong>Sazonal, na hora certa.</strong> Volta às aulas, dia das mães, festa junina — e retirado assim que a data passa.",
         "<strong>Produto com preço visível</strong>, se o preço for um argumento. Preço escondido faz parte das pessoas não entrarem."),
      p("O que <strong>não</strong> colocar: o encalhe. Vitrine não é lugar de resolver estoque parado — para isso, veja <a href=\"/blog/produtos-parados-no-estoque/\">produtos parados no estoque</a>. Vitrine é para trazer gente para dentro."),
    ),
    sec("Altura, luz e espaço",
      ol("<strong>A altura dos olhos é a área nobre.</strong> Entre 1,20 m e 1,70 m está o que realmente é visto. Abaixo de 60 cm quase ninguém olha.",
         "<strong>Luz aponta para o produto, não para a rua.</strong> Luminária mal direcionada ofusca quem passa e apaga o que você quer mostrar.",
         "<strong>Espaço vazio faz parte.</strong> É o vazio ao redor que faz o olho perceber o produto. Vitrine cheia até a borda não tem onde o olhar descansar.",
         "<strong>Limpeza é metade do trabalho.</strong> Vidro sujo e produto empoeirado anulam qualquer montagem."),
    ),
    sec("Com que frequência trocar",
      p("Uma vitrine parada por dois meses vira parede: quem passa todo dia deixa de enxergá-la. Uma referência realista para loja pequena:"),
      tabela(["Situação", "Frequência"], [
        ["Vitrine principal", "a cada 15 a 30 dias"],
        ["Data comercial", "montar 2 a 3 semanas antes, tirar no dia seguinte ao fim"],
        ["Ajuste pequeno (trocar uma peça, mudar posição)", "toda semana"],
      ]),
      p("Trocar não exige montagem nova do zero. Mudar a peça central e a posição de duas outras já renova o conjunto."),
    ),
    sec("Como saber se a vitrine está funcionando",
      p("Vitrine é uma das poucas ações de loja que dá para medir sem ferramenta nenhuma:"),
      ul("<strong>Conte quantas pessoas entram</strong> em um dia típico, antes e depois de trocar. Uma semana de cada lado já mostra tendência.",
         "<strong>Acompanhe a venda do produto exposto.</strong> Se ele está na vitrine e não vende, o problema é o produto, o preço ou a vitrine — e vale testar um de cada vez.",
         "<strong>Pergunte a quem entra</strong> o que viu na vitrine. A resposta costuma ser reveladora."),
      p("Se você registra as vendas com data, dá para comparar a semana da vitrine nova com a anterior sem depender de memória — é o mesmo dado que serve para tudo mais na loja."),
    ),
  ],
  faq=[
    ("Quantos produtos colocar na vitrine?",
     "Poucos e relacionados entre si. Quem passa na calçada dá dois segundos de atenção, e nesse tempo só uma mensagem passa. Vitrine com trinta produtos diferentes não comunica nada."),
    ("Devo colocar preço na vitrine?",
     "Se o preço é um argumento a seu favor, sim — preço escondido faz parte das pessoas não entrarem. Se o seu diferencial não é preço, o espaço rende mais mostrando o produto."),
    ("Com que frequência trocar a vitrine?",
     "A vitrine principal, a cada 15 a 30 dias. Ajustes pequenos, semanalmente. Vitrine parada por dois meses vira parede para quem passa todo dia."),
    ("Posso usar a vitrine para vender o que está encalhado?",
     "Não é o melhor uso. A vitrine serve para trazer gente para dentro; o encalhe se resolve com posição dentro da loja, combo e remarcação."),
    ("Qual a melhor altura para expor?",
     "Entre 1,20 m e 1,70 m — a altura dos olhos. Abaixo de 60 cm quase ninguém olha."),
    ("Como sei se a vitrine deu resultado?",
     "Conte quantas pessoas entram numa semana antes e numa semana depois da troca, e acompanhe a venda do produto exposto. Comparar as duas semanas exige apenas que as vendas estejam registradas com data."),
  ],
  cta_title="Meça o resultado da sua vitrine",
  cta_text="Com as vendas registradas por data, dá para comparar a semana da vitrine nova com a anterior. 7 dias grátis, sem cartão.",
  related=[("Como organizar uma loja", "/guias/como-organizar-uma-loja/", "O roteiro completo"),
           ("Produtos parados", "/blog/produtos-parados-no-estoque/", "O que não vai na vitrine"),
           ("Como precificar", "/blog/como-precificar-produto/", "O preço que aparece"),
           ("Loja de roupas", "/segmentos/loja-de-roupas/", "Vitrine é decisiva"),
           ("Loja de calçados", "/segmentos/loja-de-calcados/", "Exposição por modelo"),
           ("Loja de joias", "/segmentos/loja-de-joias/", "Vitrine como argumento")],
),

dict(
  artigo=True,
  slug="blog/fluxo-de-caixa-loja-pequena",
  title="Fluxo de Caixa para Loja Pequena: Como Fazer | SoftPay",
  description="Por que uma loja pode vender bem e não ter dinheiro em caixa, a diferença entre lucro e caixa, e como montar um fluxo simples que cabe na rotina.",
  h1="Fluxo de caixa para loja pequena",
  intro="Dá para vender bem e não ter dinheiro no caixa. Não é contradição nem má gestão necessariamente: é a diferença entre lucro e caixa, e entender isso resolve o susto mensal de boa parte dos lojistas.",
  breadcrumbs=_c("Fluxo de caixa"),
  blocks=[
    sec("Lucro e caixa não são a mesma coisa",
      p("O lucro é o resultado das vendas menos os custos. O caixa é o dinheiro que efetivamente entrou e saiu, <strong>na data em que entrou e saiu</strong>."),
      exemplo("A venda que dá lucro e não dá caixa", [
        ("Venda no cartão em 3x", "R$ 900,00", ""),
        ("Custo da mercadoria, pago à vista ao fornecedor", "− R$ 600,00", "minus"),
        ("Lucro da operação", "R$ 300,00", "result"),
        ("Entrou no caixa neste mês (1ª parcela, menos taxa)", "R$ 291,00", ""),
        ("Saiu do caixa neste mês", "− R$ 600,00", "minus"),
        ("= Efeito no caixa do mês", "− R$ 309,00", "result final"),
      ], "A venda deu lucro e mesmo assim tirou dinheiro do caixa neste mês. Multiplique por um mês inteiro de vendas parceladas e você tem o motivo de tantas lojas lucrativas ficarem sem dinheiro."),
    ),
    sec("Os três buracos mais comuns",
      ul("<strong>Venda parcelada com compra à vista.</strong> Você paga o fornecedor hoje e recebe do cliente em três meses. Quanto mais cresce a venda, maior o buraco.",
         "<strong>Fiado sem controle.</strong> A venda aconteceu, a mercadoria saiu, o dinheiro não entrou. E sem registro, não entra nunca.",
         "<strong>Estoque comprado além da conta.</strong> Comprar em quantidade parece economia, mas é caixa convertido em prateleira."),
    ),
    sec("O fluxo de caixa mais simples que funciona",
      p("Não precisa de planilha complexa. Precisa de duas colunas e da <strong>data certa</strong>:"),
      ol("<strong>Anote o que vai ENTRAR, na data em que entra.</strong> Venda à vista entra hoje; venda no cartão em 3x entra em três datas diferentes, já com a taxa descontada.",
         "<strong>Anote o que vai SAIR, na data em que sai.</strong> Fornecedor, aluguel, energia, salário, imposto.",
         "<strong>Olhe 30 dias à frente.</strong> O que interessa não é o saldo de hoje: é saber em que dia dos próximos trinta o saldo fica negativo.",
         "<strong>Atualize toda semana</strong>, no mesmo dia. Fluxo de caixa que não é atualizado vira ficção em duas semanas."),
      nota("O erro mais comum é lançar a venda no cartão como se o dinheiro entrasse no dia da venda. Ele entra na data do repasse, menos a taxa. Essa única correção já muda a previsão do mês.", "O detalhe que faz a previsão errar"),
    ),
    sec("O que fazer quando o caixa aperta",
      ol("<strong>Olhe o fiado primeiro.</strong> É dinheiro que já é seu e só não foi cobrado. Costuma ser a fonte mais rápida.",
         "<strong>Negocie prazo com o fornecedor antes de atrasar.</strong> Pedir 30 dias antes do vencimento é negociação; depois é inadimplência.",
         "<strong>Transforme estoque parado em dinheiro.</strong> Remarcação de encalhe vira caixa em dias.",
         "<strong>Reveja o parcelamento que você oferece.</strong> Se você paga à vista e vende em 6x, o buraco é estrutural.",
         "<strong>Crédito é a última opção</strong>, e só com a conta feita — juro sobre problema de caixa que se repete não resolve, adia."),
    ),
    sec("Como o registro diário sustenta tudo isso",
      p("Nenhum fluxo de caixa funciona sem uma coisa: <strong>toda venda registrada, com forma de pagamento e data</strong>. É isso que permite saber o que entra amanhã, e não só o que entrou hoje."),
      p("É também por isso que o fechamento de caixa diário importa: a diferença aparece no dia em que aconteceu, quando ainda dá para explicar. Veja o guia <a href=\"/guias/como-controlar-caixa-da-loja/\">como controlar o caixa da loja</a>."),
    ),
  ],
  faq=[
    ("Qual a diferença entre lucro e caixa?",
     "O lucro é venda menos custo. O caixa é o dinheiro que entrou e saiu, nas datas reais. Uma venda parcelada dá lucro no mês da venda, mas só entra no caixa ao longo dos meses seguintes — por isso uma loja pode ser lucrativa e ficar sem dinheiro."),
    ("Por que minha loja vende bem e não sobra dinheiro?",
     "As causas mais comuns são venda parcelada com compra à vista, fiado sem controle e estoque comprado além da conta. As três transformam venda em algo que ainda não é dinheiro."),
    ("Como faço um fluxo de caixa simples?",
     "Anote o que entra e o que sai nas datas reais, incluindo as parcelas futuras do cartão já com a taxa descontada, e olhe 30 dias à frente. Atualize toda semana, no mesmo dia."),
    ("Devo lançar a venda no cartão no dia da venda?",
     "No fluxo de caixa, não: lance na data do repasse, com a taxa já descontada. Lançar no dia da venda é o erro que mais estraga a previsão do mês."),
    ("O que faço quando o caixa aperta?",
     "Comece pelo fiado a receber, que é dinheiro seu ainda não cobrado. Depois negocie prazo com fornecedor antes de atrasar, e transforme estoque parado em dinheiro. Crédito é a última opção."),
    ("Com que frequência devo fechar o caixa?",
     "Todo dia. Fechamento diário faz a diferença aparecer no dia em que aconteceu, quando ainda é possível explicar de onde veio."),
  ],
  cta_title="Registre a venda com data e forma de pagamento",
  cta_text="É o que permite saber o que entra amanhã, e não só o que entrou hoje. 7 dias grátis, sem cartão.",
  related=[("Como controlar caixa da loja", "/guias/como-controlar-caixa-da-loja/", "O fechamento diário"),
           ("Como calcular o lucro", "/guias/como-calcular-lucro-da-loja/", "Do faturamento ao que sobra"),
           ("Como controlar fiado", "/guias/como-controlar-fiado/", "O dinheiro que já é seu"),
           ("Sistema financeiro", "/solucoes/sistema-financeiro/", "O recurso no SoftPay"),
           ("Como precificar", "/blog/como-precificar-produto/", "A taxa do cartão no preço"),
           ("Produtos parados", "/blog/produtos-parados-no-estoque/", "Estoque que virou caixa preso")],
),

]
