# -*- coding: utf-8 -*-
"""Comparativos — quem busca "SoftPay ou X" está a um passo de decidir.

Nenhum concorrente brasileiro verificado em 2026-09-08 tem página de comparação
(Nex: 0, Loyverse: 0, Kyte: 2 e nenhuma sobre concorrente). É a busca de maior
intenção de compra que existe e ninguém disputa.

REGRAS DESTE ARQUIVO, sem exceção:
1. Todo preço citado foi lido na página pública do concorrente com navegador,
   em 8 de setembro de 2026, e vem com a data e o pedido de conferir na fonte.
2. Toda página diz EXPLICITAMENTE quando o concorrente é a melhor escolha.
   Comparativo que só elogia a própria casa não é lido até o fim — e, pior,
   traz o cliente errado, que cancela em dois meses.
3. Nada de afirmar defeito do concorrente. Só o que está publicado por ele.
"""
from blocks import sec, p, ul, ol, h3, nota, exemplo, tabela

C = [("Comparativos", "/comparativos/")]
def _c(n): return C + [(n, None)]

AVISO = ('        <p class="page-sources">Preços e planos lidos nas páginas '
         'públicas dos fabricantes em <strong>8 de setembro de 2026</strong>: '
         '<a href="https://www.nextar.com.br/precos" target="_blank" rel="noopener nofollow">Nex</a>, '
         '<a href="https://www.kyte.com.br/planos" target="_blank" rel="noopener nofollow">Kyte</a> e '
         '<a href="https://www.bling.com.br/planos" target="_blank" rel="noopener nofollow">Bling</a>. '
         'Preço e recurso mudam sem aviso — <strong>confirme na fonte antes de decidir</strong>. '
         'Esta comparação é feita pela VisionX, que desenvolve o SoftPay; por isso '
         'ela diz também quando o concorrente é a melhor escolha.</p>')

PAGINAS = [

dict(
  artigo=True,
  slug="comparativos/softpay-ou-nex",
  title="SoftPay ou Nex: Qual Escolher para a Sua Loja | SoftPay",
  description="Comparação honesta entre SoftPay e Nex para pequeno comércio: preços, o que cada um cobre e em que situação o Nex é a melhor escolha.",
  h1="SoftPay ou Nex: qual escolher",
  intro="Os dois atendem pequeno comércio e cobram na mesma faixa. A diferença está em três pontos: o preço de entrada, o que vem incluso e o tipo de negócio que cada um cobre melhor. Esta página diz também quando o Nex é a escolha certa.",
  breadcrumbs=_c("SoftPay ou Nex"),
  blocks=[
    sec("A comparação em uma tabela",
      tabela(["", "SoftPay", "Nex"], [
        ["Faixa de preço", "R$ 65 a R$ 109/mês", "R$ 39 a R$ 169/mês"],
        ["Teste grátis", "7 dias, sem cartão", "sim — confira as condições na fonte"],
        ["PDV e estoque", "sim", "sim"],
        ["Controle de fiado", "sim, desde o plano Comércio", "confira na fonte"],
        ["Segmentos com página própria", "16", "18"],
        ["Emissão fiscal", "<strong>em ativação</strong> — confirme com o suporte", "confira na fonte"],
      ]),
      AVISO,
    ),
    sec("Quando o Nex é a melhor escolha",
      p("Começando por aqui, porque é o que torna o resto desta página confiável:"),
      ul("<strong>Se o seu orçamento é o fator decisivo.</strong> O plano de entrada do Nex é R$ 39, abaixo do menor plano do SoftPay com PDV (R$ 69). Para quem está começando e o custo mensal pesa, essa diferença é real.",
         "<strong>Se você é restaurante, lanchonete, cafeteria ou confeitaria.</strong> O Nex tem páginas e atendimento para esses segmentos; o SoftPay é sistema de loja e <strong>não tem comanda de mesa</strong>.",
         "<strong>Se a emissão fiscal é o motivo da contratação.</strong> No SoftPay ela consta como recurso em ativação — se você precisa emitir nota hoje, confirme com o nosso suporte antes de decidir e considere alternativas.",
         "<strong>Se você já usa o Nex e está satisfeito.</strong> Trocar de sistema custa tempo de cadastro e adaptação da equipe. Sem um problema concreto, não compensa."),
    ),
    sec("Quando o SoftPay tende a servir melhor",
      ul("<strong>Se o fiado é parte importante do seu negócio.</strong> O caderninho de fiado está desde o plano Comércio, e a partir do plano Loja o sistema envia cobrança por link de Pix no WhatsApp — que é a parte desconfortável de vender fiado.",
         "<strong>Se você trabalha com variações</strong> (tamanho, cor, numeração, tom). O controle por variação está a partir do plano Loja, com curva ABC para achar a grade quebrada.",
         "<strong>Se você quer registrar venda e estoque pelo WhatsApp.</strong> O bot está a partir do plano Loja.",
         "<strong>Se você tem equipe.</strong> O plano Loja inclui até 3 usuários e o ERP Completo até 10, sem cobrança por usuário adicional dentro do limite."),
    ),
    sec("O que os dois têm em comum",
      p("Vale dizer, porque a escolha não é entre bom e ruim:"),
      ul("Os dois rodam para pequeno comércio brasileiro e mostram preço público, sem “fale com vendas”.",
         "Os dois têm teste grátis — o que significa que você não precisa decidir por esta página. Pode testar os dois.",
         "Os dois cobrem o essencial: PDV, estoque, caixa e relatórios."),
    ),
    sec("Como decidir de verdade",
      p("Uma página de comparação escrita por um dos lados nunca é o critério final. Faça isto:"),
      ol("<strong>Escreva os três problemas</strong> que você quer resolver na sua loja.",
         "<strong>Teste os dois na mesma semana</strong>, com os mesmos 20 produtos de maior giro.",
         "<strong>Passe vendas de dois dias reais</strong> em cada um, incluindo o horário de pico.",
         "<strong>Ligue para o suporte dos dois</strong> durante o teste. A velocidade da resposta hoje é a melhor que você terá depois de assinar.",
         "<strong>Some o custo de 12 meses</strong>, não a mensalidade, incluindo o número de usuários que você precisa."),
      p("O roteiro completo está em <a href=\"/guias/como-escolher-sistema-de-gestao/\">como escolher um sistema de gestão</a>."),
    ),
  ],
  faq=[
    ("SoftPay ou Nex: qual é mais barato?",
     "O plano de entrada do Nex é mais barato (R$ 39 contra R$ 65 do SoftPay, valores de tabela em setembro de 2026). Mas o menor plano do SoftPay com PDV custa R$ 69 e inclui fiado e estoque. O custo real depende do que você precisa e de quantos usuários, então compare 12 meses e não a mensalidade."),
    ("Qual dos dois serve para restaurante?",
     "O Nex atende segmentos de alimentação como restaurante, lanchonete e cafeteria. O SoftPay é sistema de loja e não tem comanda de mesa — para consumo no local, ele não é o sistema indicado."),
    ("Os dois emitem nota fiscal?",
     "No SoftPay, a emissão de NF-e e NFC-e está nos planos Nota Fiscal e ERP Completo e consta como recurso em ativação — confirme com o suporte antes de contratar. Para o Nex, confirme as condições na página oficial dele."),
    ("Dá para testar os dois antes de decidir?",
     "Sim, e é o que recomendamos. O SoftPay tem 7 dias grátis sem cartão. Teste os dois na mesma semana, com os mesmos produtos, para a comparação ser justa."),
    ("Qual tem mais recursos?",
     "Depende do que você chama de recurso. A pergunta útil não é quem tem mais, e sim qual resolve os seus três problemas com menos volta — sistema com funções que você nunca vai abrir custa mais e demora mais para aprender."),
    ("Vale a pena trocar do Nex para o SoftPay?",
     "Se você está satisfeito, não. Trocar custa tempo de cadastro e adaptação da equipe. Faz sentido quando há um problema concreto: falta de controle de fiado, necessidade de variações por tamanho e cor, ou cobrança por usuário pesando na conta."),
  ],
  cta_title="Teste os dois na mesma semana",
  cta_text="7 dias grátis, sem cartão de crédito. Cadastre 20 produtos e passe as vendas de dois dias — é assim que a comparação fica honesta.",
  related=[("Como escolher um sistema", "/guias/como-escolher-sistema-de-gestao/", "Os 7 critérios"),
           ("Quanto custa um sistema", "/guias/quanto-custa-um-sistema-de-gestao/", "Preço real de 12 meses"),
           ("SoftPay ou Kyte", "/comparativos/softpay-ou-kyte/", "Outra comparação"),
           ("Alternativa ao Bling", "/comparativos/alternativa-ao-bling/", "Para quem vende online"),
           ("Vale a pena ter sistema?", "/guias/vale-a-pena-ter-sistema-de-gestao/", "Antes de escolher"),
           ("Segmentos", "/segmentos/", "O SoftPay no seu tipo de loja")],
),

dict(
  artigo=True,
  slug="comparativos/softpay-ou-kyte",
  title="SoftPay ou Kyte: Qual Escolher para a Sua Loja | SoftPay",
  description="Comparação honesta entre SoftPay e Kyte: preços, foco em celular contra loja física, e em que situação o Kyte é a melhor escolha.",
  h1="SoftPay ou Kyte: qual escolher",
  intro="A diferença principal não é preço: é o formato do negócio. O Kyte nasceu com foco em vender pelo celular; o SoftPay foi feito para a loja com balcão, estoque e fiado. Esta página diz quando cada um se encaixa melhor.",
  breadcrumbs=_c("SoftPay ou Kyte"),
  blocks=[
    sec("A comparação em uma tabela",
      tabela(["", "SoftPay", "Kyte"], [
        ["Faixa de preço", "R$ 65 a R$ 109/mês", "R$ 49,90 a R$ 99,90/mês"],
        ["Teste grátis", "7 dias, sem cartão", "7 dias"],
        ["Foco", "loja com balcão, estoque e fiado", "venda pelo celular e catálogo"],
        ["Usuários incluídos", "1 a 10, conforme o plano", "até 10, conforme o plano"],
        ["Segmentos com página própria", "16", "6"],
        ["Emissão fiscal", "<strong>em ativação</strong> — confirme com o suporte", "confira na fonte"],
      ]),
      AVISO,
    ),
    sec("Quando o Kyte é a melhor escolha",
      ul("<strong>Se você vende principalmente pelo celular</strong>, sem loja física — feiras, delivery próprio, venda por Instagram e WhatsApp. É o cenário para o qual o Kyte foi desenhado.",
         "<strong>Se o aplicativo no celular é o seu ponto de venda principal</strong>, e não um complemento do balcão.",
         "<strong>Se você quer o menor preço de entrada entre os dois.</strong> O plano inicial do Kyte é R$ 49,90, contra R$ 65 do SoftPay.",
         "<strong>Se você já usa e está satisfeito.</strong> Vale sempre: sem problema concreto, trocar só custa tempo."),
    ),
    sec("Quando o SoftPay tende a servir melhor",
      ul("<strong>Se você tem loja física com balcão e movimento.</strong> O PDV foi feito para o pico do caixa, com baixa de estoque na hora da venda.",
         "<strong>Se o fiado faz parte do negócio.</strong> Caderninho de fiado desde o plano Comércio, com cobrança por link de Pix no WhatsApp a partir do plano Loja.",
         "<strong>Se você precisa de curva ABC e custo por produto</strong> para decidir compra e remarcação.",
         "<strong>Se o seu segmento é específico.</strong> São 16 páginas de segmento com o detalhamento do que serve e do que não serve em cada tipo de loja."),
    ),
    sec("A pergunta que resolve a escolha",
      p("Uma pergunta separa os dois melhor que qualquer tabela:"),
      nota("<strong>Onde a maior parte das suas vendas acontece: no balcão da loja ou no seu celular?</strong> Se a resposta é o balcão, o SoftPay foi feito para isso. Se é o celular, vale olhar o Kyte com atenção.", "A pergunta que decide"),
      p("Quem faz as duas coisas deve decidir pela que move mais dinheiro hoje — e não pela que pretende fazer no ano que vem."),
    ),
    sec("Como decidir de verdade",
      ol("<strong>Teste os dois na mesma semana</strong>, com os mesmos 20 produtos.",
         "<strong>Passe vendas reais</strong> no formato que você mais usa — se é balcão, teste no horário de pico.",
         "<strong>Peça para outra pessoa da loja registrar uma venda</strong> sem você ensinar.",
         "<strong>Ligue para o suporte dos dois</strong> durante o teste.",
         "<strong>Compare o custo de 12 meses</strong> com o número de usuários que você realmente precisa."),
    ),
  ],
  faq=[
    ("SoftPay ou Kyte: qual é melhor para loja física?",
     "Para loja com balcão, movimento e fiado, o SoftPay foi desenhado para esse uso. O Kyte tem foco em venda pelo celular e catálogo, o que serve melhor a quem vende sem ponto fixo."),
    ("Qual dos dois é mais barato?",
     "O plano de entrada do Kyte é R$ 49,90 e o do SoftPay R$ 65 (tabelas públicas em setembro de 2026). A comparação justa é do plano que atende o que você precisa, não do mais barato de cada um."),
    ("Os dois funcionam no celular?",
     "Sim. O SoftPay roda no navegador, inclusive no celular. A diferença é o foco: no Kyte o celular é o centro da operação; no SoftPay ele é um complemento do balcão."),
    ("Qual dos dois controla fiado?",
     "No SoftPay o fiado está desde o plano Comércio, com saldo e histórico por cliente, e a partir do plano Loja há cobrança por link de Pix no WhatsApp. Para o Kyte, confirme na fonte oficial."),
    ("Vale a pena trocar do Kyte para o SoftPay?",
     "Se você abriu loja física e o balcão passou a ser o centro da operação, faz sentido avaliar. Se a sua venda continua majoritariamente pelo celular, provavelmente não."),
    ("Dá para testar os dois?",
     "Sim, os dois têm 7 dias de teste. Teste na mesma semana, com os mesmos produtos, para a comparação ser justa."),
  ],
  cta_title="Teste com as vendas do seu balcão",
  cta_text="7 dias grátis, sem cartão. Passe as vendas do horário de pico — é ali que a diferença entre um sistema e outro aparece.",
  related=[("SoftPay ou Nex", "/comparativos/softpay-ou-nex/", "Outra comparação"),
           ("Alternativa ao Bling", "/comparativos/alternativa-ao-bling/", "Para quem vende online"),
           ("Como escolher um sistema", "/guias/como-escolher-sistema-de-gestao/", "Os 7 critérios"),
           ("Sistema PDV", "/solucoes/sistema-pdv/", "O PDV do SoftPay"),
           ("Controle de fiado", "/solucoes/controle-de-fiado/", "O caderninho no sistema"),
           ("Quanto custa um sistema", "/guias/quanto-custa-um-sistema-de-gestao/", "Preço real")],
),

dict(
  artigo=True,
  slug="comparativos/alternativa-ao-bling",
  title="Alternativa ao Bling para Loja Física | SoftPay",
  description="Quando o Bling é a escolha certa e quando um sistema de loja atende melhor. Comparação honesta para quem vende no balcão e não em marketplace.",
  h1="Alternativa ao Bling para loja física",
  intro="O Bling é forte no que foi feito para fazer: integrar marketplaces e e-commerce. A pergunta desta página é outra — se a sua venda acontece no balcão e não na internet, você precisa de tudo aquilo?",
  breadcrumbs=_c("Alternativa ao Bling"),
  blocks=[
    sec("Quando o Bling é a escolha certa",
      p("Sem rodeio: em vários cenários ele é melhor que o SoftPay, e não faz sentido esconder isso."),
      ul("<strong>Se você vende em marketplace.</strong> Mercado Livre, Shopee, Amazon, Magalu — integração de estoque e pedido é o forte do Bling, e o SoftPay <strong>não integra com marketplace</strong>.",
         "<strong>Se você tem e-commerce próprio</strong> e precisa sincronizar estoque entre a loja virtual e o físico.",
         "<strong>Se você emite muita nota fiscal e precisa disso funcionando hoje.</strong> No SoftPay a emissão consta como recurso em ativação.",
         "<strong>Se você precisa de emissão de etiqueta e logística de envio</strong> integradas ao pedido."),
      nota("Se dois ou mais desses pontos descrevem a sua operação, <strong>o Bling provavelmente é a escolha certa</strong> e você não precisa continuar lendo esta página. Preferimos dizer isso a vender um sistema que vai frustrar em dois meses.", "Sendo direto"),
    ),
    sec("Quando um sistema de loja atende melhor",
      p("O cenário oposto, que é o mais comum no comércio de bairro:"),
      ul("<strong>Sua venda acontece no balcão.</strong> Você não vende em marketplace e não pretende vender.",
         "<strong>Você vende fiado.</strong> É a realidade do comércio de bairro, e um sistema focado em e-commerce raramente trata isso bem.",
         "<strong>Você quer simplicidade.</strong> Um sistema com integrações que você nunca vai usar custa mais caro e demora mais para a equipe aprender.",
         "<strong>Você precisa de PDV rápido no pico</strong>, com baixa de estoque na hora da venda."),
    ),
    sec("A comparação em uma tabela",
      tabela(["", "SoftPay", "Bling"], [
        ["Feito para", "loja física com balcão", "integração de e-commerce e marketplace"],
        ["Integração com marketplace", "<strong>não tem</strong>", "sim — é o forte dele"],
        ["Controle de fiado", "sim, desde o plano Comércio", "confira na fonte"],
        ["PDV para balcão", "sim", "sim"],
        ["Faixa de preço", "R$ 65 a R$ 109/mês", "faixas variadas por número de usuários e recursos — confira na fonte"],
        ["Teste grátis", "7 dias, sem cartão", "confira na fonte"],
      ]),
      AVISO,
    ),
    sec("A conta que costuma decidir",
      p("Sistema com muitos módulos cobra por eles, mesmo que você use três. A pergunta prática:"),
      exemplo("Quanto você paga pelo que não usa", [
        ("Mensalidade de um sistema completo", "R$ 120,00", ""),
        ("Módulos que você realmente abre (PDV, estoque, caixa)", "3 de 12", ""),
        ("Mensalidade de um sistema focado em loja", "R$ 69,00", ""),
        ("= Diferença em 12 meses", "R$ 612,00", "result final"),
      ], "Números ilustrativos, para mostrar o raciocínio. <strong>Só vale se você realmente não precisa dos outros módulos</strong> — se precisa de marketplace, o sistema mais barato sai caro em retrabalho."),
    ),
    sec("Como decidir sem errar",
      ol("<strong>Responda uma pergunta:</strong> quantos por cento das suas vendas acontecem fora do balcão? Se for mais de 20%, integração importa.",
         "<strong>Liste os módulos que você abriria toda semana.</strong> Se são três, sistema focado tende a servir melhor.",
         "<strong>Teste antes de contratar</strong>, com produtos e vendas reais.",
         "<strong>Some 12 meses</strong> de cada um, com o número de usuários que você precisa."),
      p("O roteiro completo está em <a href=\"/guias/como-escolher-sistema-de-gestao/\">como escolher um sistema de gestão</a>."),
    ),
  ],
  faq=[
    ("O SoftPay integra com Mercado Livre ou Shopee?",
     "Não. O SoftPay não sincroniza estoque com marketplace. Se boa parte da sua venda acontece nesses canais, o Bling ou outro sistema com integração atende melhor."),
    ("Qual a diferença entre o SoftPay e o Bling?",
     "O Bling foi feito para integrar e-commerce e marketplace; o SoftPay, para a loja física com balcão, estoque e fiado. São produtos para operações diferentes, e não versões melhor e pior do mesmo produto."),
    ("Vale a pena trocar o Bling pelo SoftPay?",
     "Só se a sua venda for majoritariamente no balcão e você estiver pagando por integrações que não usa. Se você vende em marketplace, não troque."),
    ("O SoftPay é mais barato que o Bling?",
     "Depende do plano e do número de usuários dos dois. O que decide não é a mensalidade isolada: é o custo de 12 meses considerando o que você realmente usa."),
    ("Preciso de um sistema com e-commerce integrado?",
     "Só se você vende fora do balcão. Uma regra prática: se mais de 20% das suas vendas acontecem em marketplace ou loja virtual, a integração compensa; abaixo disso, costuma ser módulo pago e não usado."),
    ("O SoftPay tem loja online?",
     "Tem catálogo online com Pix a partir do plano Loja — é um catálogo próprio para vender por WhatsApp e Instagram, não uma integração com marketplace."),
  ],
  cta_title="Se a sua venda é no balcão, teste",
  cta_text="7 dias grátis, sem cartão de crédito. Se você vende em marketplace, o Bling atende melhor — e preferimos dizer isso agora.",
  related=[("SoftPay ou Nex", "/comparativos/softpay-ou-nex/", "Outra comparação"),
           ("SoftPay ou Kyte", "/comparativos/softpay-ou-kyte/", "Balcão ou celular"),
           ("Como escolher um sistema", "/guias/como-escolher-sistema-de-gestao/", "Os 7 critérios"),
           ("Loja online", "/solucoes/loja-online/", "O catálogo com Pix"),
           ("Quanto custa um sistema", "/guias/quanto-custa-um-sistema-de-gestao/", "Preço real de 12 meses"),
           ("Vale a pena ter sistema?", "/guias/vale-a-pena-ter-sistema-de-gestao/", "Antes de escolher")],
),

]
