# -*- coding: utf-8 -*-
from blocks import sec as _sec, p, ul, ol, h3, nota, exemplo, tabela, cards


def sec(titulo, *partes, id=None):
    """Igual ao sec() de blocks, mas com o id aceito em qualquer posicao."""
    return _sec(titulo, *partes, id=id)

PAGINAS = [

# ------------------------------------------------------------- PÁGINA PILAR
dict(
  slug="sistema-de-gestao-para-pequenos-negocios",
  title="Sistema de Gestão para Pequenos Negócios: Guia Completo | SoftPay",
  description="O que é um sistema de gestão, para quem serve, quanto custa e o que ele resolve numa loja pequena: estoque, PDV, caixa, fiado, notas fiscais e lucro.",
  h1="Sistema de gestão para pequenos negócios",
  intro="Um guia completo para quem está avaliando se vale a pena, o que um sistema de gestão realmente faz e como escolher sem pagar por aquilo que a sua loja não usa.",
  breadcrumbs=[("Sistema de gestão para pequenos negócios", None)],
  blocks=[
    sec("O que é um sistema de gestão",
      p("Sistema de gestão é o lugar onde as informações da sua loja param de viver em pedaços. Em vez de vendas no caderno, estoque na memória, fiado em outra folha e o lucro numa estimativa de fim de mês, tudo passa a alimentar a mesma base."),
      p("Na prática, ele junta quatro coisas que hoje você já faz separado: registrar a venda, controlar o que tem em estoque, conferir o caixa e acompanhar quem deve. A diferença é que, ligadas entre si, essas informações começam a responder perguntas que antes eram impossíveis."),
      h3("ERP, PDV, sistema de gestão: qual a diferença?"),
      p("<strong>PDV</strong> é a frente de caixa: onde a venda é registrada. <strong>ERP</strong> é o sistema que integra as áreas do negócio. <strong>Sistema de gestão</strong> é o termo mais amplo. Para uma loja pequena, a distinção importa pouco — o que importa é se cobre a sua operação."),
    ),
    sec("Para quem serve",
      p("O perfil típico é o pequeno comércio com estoque: mercadinho, loja de roupas, loja de variedades, papelaria, farmácia, distribuidora. Geralmente com uma ou duas pessoas, faturamento crescendo e controle ainda no caderno ou na planilha."),
      cards([
        ("Mercadinho", "Muitos itens, giro rápido, fiado de bairro", "/segmentos/mercadinho/"),
        ("Loja de roupas", "Grade de tamanho e cor, recompra", "/segmentos/loja-de-roupas/"),
        ("Loja de variedades", "Centenas de itens de baixo valor", "/segmentos/loja-de-variedades/"),
        ("Papelaria", "Varejo, atacado e pico da volta às aulas", "/segmentos/papelaria/"),
        ("Farmácia", "Gestão comercial do balcão", "/segmentos/farmacia/"),
        ("Distribuidora", "Volume, atacado e nota fiscal", "/segmentos/distribuidora/"),
        ("Pequeno comércio", "Loja de uma ou duas pessoas", "/segmentos/pequeno-comercio/"),
      ]),
    ),
    sec("Minha loja pequena precisa de um?",
      p("Não existe faturamento mínimo. O indicador é a perda de controle: você não sabe de cabeça o estoque de um produto que vende todo dia, o fiado passou do ponto de lembrar, o caixa não bate, ou você vendeu bem e não sobrou dinheiro."),
      p("Se nada disso acontece — poucos produtos, sem fiado, sem funcionário — o caderno provavelmente ainda dá conta. Aprofunde em <a href=\"/perguntas/loja-pequena-precisa-de-sistema/\">loja pequena precisa de sistema?</a>"),
    ),
    sec("Quanto custa",
      p("Sistemas para pequeno varejo no Brasil são vendidos por assinatura mensal. No SoftPay os planos vão de R$ 65 a R$ 109 por mês, com 7 dias de teste grátis sem cartão."),
      tabela(["Plano", "Preço", "Para quem"], [
        ["Nota Fiscal", "R$ 65/mês", "Só emissão de notas, sem PDV nem estoque"],
        ["Comércio", "R$ 69/mês", "PDV, caixa, fiado e estoque essencial. 1 usuário"],
        ["Loja", "R$ 89/mês", "Fiado que cobra sozinho, loja online, estoque avançado. Até 3 usuários"],
        ["ERP Completo", "R$ 109/mês", "Tudo da Loja + NFC-e e NF-e. Até 10 usuários"],
      ]),
      p("Mais detalhes em <a href=\"/perguntas/quanto-custa-um-sistema-para-loja/\">quanto custa um sistema para loja</a>."),
    ),
    sec("O que um sistema de gestão resolve",
      h3("Estoque"),
      p("A venda dá baixa sozinha, o custo fica registrado junto do preço e a curva ABC mostra o que gira e o que está parado. É o que responde “quanto dinheiro eu tenho na prateleira”. Veja o <a href=\"/guias/como-controlar-estoque/\">guia de estoque</a> e a <a href=\"/solucoes/sistema-de-estoque/\">solução</a>."),
      h3("Vendas e PDV"),
      p("O PDV registra produto, preço, forma de pagamento e cliente no ato da venda. É de onde vem todo dado confiável do resto do sistema. Veja <a href=\"/solucoes/sistema-pdv/\">sistema PDV</a>."),
      h3("Caixa"),
      p("Fundo de troco, formas de pagamento separadas, saídas registradas e fechamento diário. Veja o <a href=\"/guias/como-controlar-caixa-da-loja/\">guia de caixa</a>."),
      h3("Fiado"),
      p("Saldo por cliente com histórico, e cobrança por link de Pix pelo WhatsApp a partir do plano Loja. Veja o <a href=\"/guias/como-controlar-fiado/\">guia de fiado</a> e a <a href=\"/solucoes/controle-de-fiado/\">solução</a>."),
      h3("Clientes e CRM"),
      p("Cadastro ligado às vendas, base para fiado, cupom e fidelidade. Veja <a href=\"/solucoes/controle-de-clientes/\">controle de clientes</a>."),
      h3("NF-e e NFC-e"),
      p("Emissão nos planos Nota Fiscal e ERP Completo, com cadastro fiscal e pacote do contador. Veja <a href=\"/solucoes/nfe/\">NF-e</a> e <a href=\"/solucoes/nfce/\">NFC-e</a>."),
      h3("Loja online"),
      p("Catálogo alimentado pelo mesmo estoque, com Pix que confirma o pedido sozinho. Veja <a href=\"/solucoes/loja-online/\">loja online</a>."),
      h3("Funcionários e filiais"),
      p("Multi-login com acesso individual e controle de filiais na mesma conta. Veja <a href=\"/solucoes/multiplas-lojas/\">múltiplas lojas</a>."),
      h3("Celular"),
      p("Acesso pelo navegador, sem instalar aplicativo. Veja <a href=\"/perguntas/posso-usar-o-softpay-no-celular/\">uso no celular</a>."),
      h3("Segurança e backup"),
      p("Banco de dados na nuvem com infraestrutura Supabase, backup automático e recuperação de conta. Veja <a href=\"/perguntas/sistema-de-gestao-e-seguro/\">é seguro?</a>"),
      h3("Suporte"),
      p("Atendimento humano pelo WhatsApp, inclusive na configuração inicial. Veja <a href=\"/perguntas/tem-suporte-humano/\">suporte humano</a>."),
    ),
    sec("Lucro e margem: a parte que decide o negócio",
      p("É aqui que um sistema deixa de ser um registro e vira uma ferramenta de decisão. Faturamento é o que entrou; lucro é o que sobrou depois do custo da mercadoria e das despesas."),
      exemplo("Do faturamento ao resultado", [
        ("Vendas do mês", "R$ 25.480,00", ""),
        ("Custo dos produtos vendidos (CMV)", "− R$ 16.560,00", "minus"),
        ("= Lucro bruto", "R$ 8.920,00", "result"),
        ("Despesas do período", "− R$ 3.400,00", "minus"),
        ("= Resultado estimado", "R$ 5.520,00", "result final"),
      ], "Números fictícios. Método completo em <a href=\"/guias/como-calcular-lucro-da-loja/\">como calcular o lucro da loja</a> e <a href=\"/guias/como-calcular-margem-de-lucro/\">como calcular a margem</a>."),
    ),
    sec("Caderno, Excel ou sistema",
      p("Caderno funciona enquanto uma pessoa só opera e o volume cabe na memória; ele quebra quando você precisa de totais. Planilha é ótima para análise, mas na loja a baixa de estoque depende de alguém lembrar de digitar depois da venda."),
      cards([
        ("Caderno ou sistema?", "O que o caderno faz bem e onde falha", "/perguntas/caderno-ou-sistema/"),
        ("Excel ou sistema?", "Por que a planilha desatualiza", "/perguntas/excel-ou-sistema-de-gestao/"),
        ("Como sair do caderno", "Migração em 7 dias", "/guias/como-sair-do-caderno/"),
      ]),
    ),
    sec("Como escolher sem errar",
      ol("Liste as três dores que mais te incomodam hoje. Ignore o resto.",
         "Confira se o sistema cobre essas três — e em qual plano.",
         "Verifique quantos usuários estão inclusos no preço anunciado.",
         "Teste com os seus produtos reais, não com dados de exemplo.",
         "Confirme se o suporte é humano e em qual canal.",
         "Pergunte se você consegue exportar seus dados caso queira sair."),
      nota("Recurso que você não vai usar não é vantagem: é complexidade a mais para aprender. Uma loja de bairro raramente precisa de gestão de produção ou integração com marketplace no primeiro ano.", "O erro mais caro na escolha"),
    ),
  ],
  faq=[
    ("O que é um sistema de gestão?",
     "É o sistema que reúne as informações da loja em uma base só: vendas, estoque, caixa, fiado, clientes e notas fiscais, em vez de cada coisa em um lugar."),
    ("Qual a diferença entre ERP e PDV?",
     "PDV é a frente de caixa, onde a venda é registrada. ERP é o sistema que integra as áreas do negócio. Para uma loja pequena, o que importa é se cobre a sua operação."),
    ("Minha loja é pequena demais para isso?",
     "Não existe faturamento mínimo. O que indica a necessidade é a perda de controle sobre estoque, fiado e resultado."),
    ("Quanto custa um sistema de gestão?",
     "No SoftPay, de R$ 65 a R$ 109 por mês conforme o plano, com 7 dias de teste grátis sem cartão de crédito."),
    ("Preciso instalar alguma coisa?",
     "Não. O SoftPay roda no navegador, sem instalação e sem servidor na loja."),
    ("O sistema calcula meu lucro?",
     "Ele reúne os dados que formam a conta — vendas registradas e custo cadastrado. A precisão depende de esses dados estarem completos, e ele não substitui a contabilidade."),
    ("Meus dados ficam seguros?",
     "Ficam em banco de dados na nuvem com infraestrutura Supabase, backup automático e acesso individual por usuário. Nenhum sistema garante segurança absoluta."),
    ("Consigo migrar da minha planilha?",
     "Sim. A importação de dados está disponível a partir do plano Loja; confirme o formato com o suporte."),
    ("Tem teste grátis?",
     "Sim, 7 dias com acesso aos recursos do plano e sem cartão de crédito."),
    ("Serve para qualquer tipo de loja?",
     "O SoftPay atende pequenos comércios com estoque. Segmentos regulados, como farmácia, têm obrigações específicas que ele não substitui."),
  ],
  cta_title="Descubra na prática, com a sua loja",
  cta_text="Sete dias com acesso aos recursos do plano, sem cartão de crédito. Cadastre seus produtos e veja se faz diferença.",
  related=[("Segmentos", "/segmentos/", "Seu tipo de loja"),
           ("Soluções", "/solucoes/", "Por recurso"),
           ("Guias", "/guias/", "Aprenda o método")],
),

# ------------------------------------------------------------------- SOBRE
dict(
  slug="sobre",
  title="Sobre o SoftPay | Quem Está por Trás do Sistema",
  description="Conheça o SoftPay: sistema de gestão para pequenos negócios brasileiros, desenvolvido pela VisionX Inova Simples (IS), com atendimento nacional.",
  h1="Sobre o SoftPay",
  intro="O SoftPay é um sistema de gestão feito para o pequeno comércio brasileiro — aquele que vende no balcão, controla estoque e ainda anota fiado.",
  breadcrumbs=[("Sobre", None)],
  blocks=[
    sec("O que é o SoftPay",
      p("O SoftPay reúne PDV, controle de estoque, caixa, fiado, cadastro de clientes, notas fiscais e loja online em um único sistema, acessado pelo navegador."),
      p("Ele foi desenhado para um público específico: lojas com uma ou duas pessoas, faturamento crescendo e controle ainda no caderno ou na planilha. Não é um ERP corporativo simplificado — é uma ferramenta pensada desde o começo para a rotina de quem está atrás do balcão."),
    ),
    sec("A ideia central",
      p("Muito sistema mostra número. O que falta ao pequeno lojista raramente é dado: é entender o que aquele dado quer dizer e o que fazer com ele."),
      p("Por isso o SoftPay insiste em coisas como registrar o custo junto do preço, mostrar o total do fiado em aberto e separar faturamento de lucro. São informações que mudam decisão, não apenas relatórios que enchem a tela."),
    ),
    sec("Quem desenvolve",
      p("O SoftPay é um produto da <strong>VisionX Inova Simples (IS)</strong>, CNPJ <strong>61.427.918/0001-06</strong>, com sede em Pedreiras, no Maranhão."),
      p("O atendimento é nacional: como o sistema é usado pela internet, não há necessidade de representante local ou visita técnica."),
    ),
    sec("Como trabalhamos o suporte",
      p("O atendimento é feito por pessoas da equipe, pelo WhatsApp, e cobre desde a configuração inicial até as dúvidas do dia a dia. Para quem está saindo do caderno, essa costuma ser a diferença entre implantar o sistema e desistir na primeira dificuldade."),
    ),
    sec("Transparência sobre o produto",
      p("Ao longo deste site você vai encontrar observações do tipo “confirme com o suporte antes de contratar”. Isso é proposital: preferimos que você pergunte antes a descobrir depois que um recurso específico não atende ao seu caso."),
      nota("Se algum recurso é decisivo para a sua operação — controle de validade, permissões por perfil, situação da emissão fiscal, estrutura de filiais —, pergunte antes de assinar. O suporte responde pelo WhatsApp.", "Nosso pedido"),
    ),
    sec("Contato",
      ul("WhatsApp: <a href=\"https://wa.me/558698193851\" target=\"_blank\" rel=\"noopener\">(86) 9 9819-3851</a>",
         "E-mail: <a href=\"mailto:suporte@softpaybr.com\">suporte@softpaybr.com</a>",
         "Empresa: VisionX Inova Simples (IS) — CNPJ 61.427.918/0001-06",
         "Endereço: Pedreiras/MA, Brasil"),
      p("Veja também a página de <a href=\"/contato/\">contato</a>."),
    ),
  ],
  faq=[
    ("Quem é a empresa por trás do SoftPay?",
     "O SoftPay é um produto da VisionX Inova Simples (IS), CNPJ 61.427.918/0001-06, com sede em Pedreiras/MA."),
    ("O SoftPay atende todo o Brasil?",
     "Sim. O sistema é usado pela internet e o atendimento é nacional, pelo WhatsApp."),
    ("Para que tipo de negócio o SoftPay foi feito?",
     "Para pequenos comércios com estoque: mercadinhos, lojas de roupas, lojas de variedades, papelarias, farmácias, distribuidoras e lojas em geral."),
    ("Como falo com a equipe?",
     "Pelo WhatsApp (86) 9 9819-3851 ou pelo e-mail suporte@softpaybr.com."),
    ("Tem teste grátis?",
     "Sim, 7 dias com acesso aos recursos do plano e sem cartão de crédito."),
  ],
  cta_title="Conheça o SoftPay na prática",
  cta_text="Sete dias de teste com acesso aos recursos do plano, sem cartão de crédito.",
  related=[("Contato", "/contato/", "Todos os canais"),
           ("É seguro?", "/perguntas/sistema-de-gestao-e-seguro/", "Como cuidamos dos dados"),
           ("Suporte humano", "/perguntas/tem-suporte-humano/", "Como atendemos")],
),

# ------------------------------------------------------------------ CONTATO
dict(
  slug="contato",
  title="Contato | SoftPay",
  description="Fale com o SoftPay: WhatsApp (86) 9 9819-3851, e-mail suporte@softpaybr.com. Atendimento humano em todo o Brasil.",
  h1="Fale com a gente",
  intro="Atendimento humano, pelo WhatsApp, para dúvidas antes de contratar e para o dia a dia de quem já usa.",
  breadcrumbs=[("Contato", None)],
  blocks=[
    sec("Canais de atendimento",
      cards([
        ("WhatsApp", "(86) 9 9819-3851 — canal principal, atendimento humano"),
        ("E-mail", "suporte@softpaybr.com"),
        ("Perguntas frequentes", "Respostas diretas às dúvidas mais comuns"),
      ]),
      p("O WhatsApp é o caminho mais rápido: <a href=\"https://wa.me/558698193851\" target=\"_blank\" rel=\"noopener\">clique aqui para abrir a conversa</a>."),
    ),
    sec("Antes de contratar, pergunte",
      p("Se algum recurso é decisivo para a sua operação, confirme antes de assinar. As perguntas que mais valem a pena fazer:"),
      ul("A emissão fiscal que eu preciso está ativa hoje, no meu estado?",
         "Existe controle de validade de produtos?",
         "Dá para definir limite de fiado por cliente?",
         "Existem perfis de permissão diferentes por funcionário?",
         "Minha estrutura de filiais é atendida?",
         "Meu leitor de código de barras é compatível?",
         "Consigo importar a planilha que eu já tenho?"),
    ),
    sec("Dados da empresa",
      ul("<strong>VisionX Inova Simples (IS)</strong>",
         "CNPJ: 61.427.918/0001-06",
         "Pedreiras/MA — Brasil",
         "Atendimento: todo o território nacional"),
    ),
    sec("Documentos",
      ul("<a href=\"/termos\">Termos de Uso</a>",
         "<a href=\"/privacidade\">Política de Privacidade</a>",
         "<a href=\"/reembolso\">Política de Reembolso</a>"),
    ),
  ],
  faq=[
    ("Qual o WhatsApp do SoftPay?",
     "(86) 9 9819-3851. É o canal principal de atendimento, com resposta humana."),
    ("Qual o e-mail de suporte?",
     "suporte@softpaybr.com."),
    ("O atendimento é humano?",
     "Sim, feito por pessoas da equipe, não por robô de autoatendimento."),
    ("Vocês atendem antes de eu contratar?",
     "Sim. Se algum recurso é decisivo para a sua operação, pergunte antes de assinar."),
    ("Atendem em todo o Brasil?",
     "Sim, o atendimento é nacional."),
  ],
  cta_title="Prefere testar antes de conversar?",
  cta_text="São 7 dias com acesso aos recursos do plano, sem cartão de crédito.",
  related=[("Sobre o SoftPay", "/sobre/", "Quem está por trás"),
           ("Perguntas", "/perguntas/", "Dúvidas frequentes"),
           ("Suporte humano", "/perguntas/tem-suporte-humano/", "Como funciona")],
),
]
