# -*- coding: utf-8 -*-
from blocks import sec, p, ul, ol, h3, nota, exemplo, tabela

C = [("Guias", "/guias/")]
def _c(n): return C + [(n, None)]

FONTE = ('        <p class="page-sources">Referências sobre CMV e margem: '
         '<a href="https://www.totvs.com/blog/gestao-varejista/cmv/" target="_blank" rel="noopener nofollow">TOTVS</a>, '
         '<a href="https://www.serasaexperian.com.br/conteudos/cmv-o-que-e/" target="_blank" rel="noopener nofollow">Serasa Experian</a> e '
         '<a href="https://conteudo.stone.com.br/o-que-e-cmv-como-calcular/" target="_blank" rel="noopener nofollow">Stone</a>. '
         'Para obrigações fiscais, consulte o seu contador e os portais oficiais (gov.br, Receita Federal e SEFAZ do seu estado).</p>')

PAGINAS = [

dict(
  slug="guias/como-controlar-estoque",
  title="Como Controlar o Estoque de uma Loja: Guia Prático | SoftPay",
  description="Passo a passo para controlar o estoque da sua loja: inventário inicial, custo por produto, baixa automática e curva ABC. Guia completo e prático.",
  h1="Como controlar o estoque de uma loja",
  intro="Resposta curta: registre o que entra, registre o que sai e cadastre o custo de cada item. Todo o resto do controle de estoque é consequência desses três hábitos.",
  breadcrumbs=_c("Como controlar estoque"),
  blocks=[
    sec("Por que o controle sempre desanda",
      p("O motivo mais comum não é preguiça: é que venda e estoque viram dois controles separados. A venda acontece no balcão e a baixa do estoque fica para depois. Como o “depois” depende de alguém lembrar, o desencontro começa em dias."),
      p("A correção estrutural é fazer a baixa acontecer no mesmo ato da venda. É isso que um PDV resolve — não por ser sofisticado, mas por eliminar a segunda etapa."),
    ),
    sec("Passo 1 — Faça o inventário inicial (sem tentar fazer tudo)",
      p("O erro clássico é parar a loja para contar todos os produtos e desistir no meio. Comece diferente:"),
      ol("Liste os produtos que você vende com mais frequência — normalmente uma minoria responde pela maior parte das vendas.",
         "Conte a quantidade real desses itens na prateleira e no depósito.",
         "Registre quantidade, preço de venda e <strong>custo de compra</strong> de cada um.",
         "Vá completando o restante conforme repõe: quando chegar mercadoria nova, cadastre antes de colocar na prateleira."),
      nota("Cadastrar só o preço de venda responde quanto entrou. É o custo que permite responder quanto sobrou. Sem ele, você tem controle de quantidade, não controle de estoque.", "O passo que quase todo mundo pula"),
    ),
    sec("Passo 2 — Faça toda venda passar pelo mesmo lugar",
      p("Não adianta o cadastro estar perfeito se metade das vendas sai sem registro. Isso inclui a venda fiada, a venda para conhecido e a que o funcionário fez enquanto você não estava. Toda saída de mercadoria precisa gerar um registro."),
    ),
    sec("Passo 3 — Registre também o que entra",
      p("Compra de fornecedor, devolução de cliente, perda por quebra ou validade vencida. Estoque que só registra saída fica errado tão rápido quanto o que não registra nada."),
    ),
    sec("Passo 4 — Descubra quanto dinheiro está parado",
      p("Com quantidade e custo cadastrados, esse número deixa de ser chute:"),
      exemplo("Dinheiro investido em mercadoria", [
        ("Categoria A — 120 itens", "R$ 8.400,00", ""),
        ("Categoria B — 340 itens", "R$ 5.100,00", ""),
        ("Categoria C — 890 itens", "R$ 3.200,00", ""),
        ("= Total parado na prateleira", "R$ 16.700,00", "result final"),
      ], "Números fictícios. Para muita loja pequena, esse total é maior que o saldo em conta — e é a explicação de vender bem e não ter dinheiro."),
    ),
    sec("Passo 5 — Use a curva ABC para decidir a compra",
      p("Com centenas de itens, analisar tudo é impossível. A curva ABC classifica os produtos por participação no resultado:"),
      tabela(["Classe", "O que costuma ser", "O que fazer"], [
        ["A", "Poucos itens, maior parte do faturamento", "Nunca deixar faltar"],
        ["B", "Giro intermediário", "Repor com regularidade"],
        ["C", "Muitos itens, pouca participação", "Comprar menos, avaliar remarcação"],
      ]),
      p("A conversa útil está na classe C: é onde costuma estar o dinheiro parado que você nem sabia que tinha."),
    ),
    sec("Erros comuns",
      ul("Contar estoque uma vez por ano e achar que o número vale o ano inteiro.",
         "Cadastrar preço de venda e esquecer o custo.",
         "Deixar a venda fiada fora do registro.",
         "Repor por memória em vez de olhar o que saiu.",
         "Tratar perda e quebra como se não existissem."),
      FONTE,
    ),
  ],
  faq=[
    ("Preciso parar a loja para fazer inventário?",
     "Não. O caminho prático é começar pelos itens de maior giro e completar o restante conforme você repõe a mercadoria."),
    ("Com que frequência devo conferir o estoque?",
     "Uma conferência periódica dos itens de maior giro costuma bastar para pegar desvios cedo. O inventário completo pode ser feito por partes ao longo do tempo."),
    ("Planilha resolve?",
     "Resolve enquanto o volume é pequeno e uma pessoa só mexe nela. O problema não é a planilha em si: é que a baixa depende de alguém lembrar de fazer depois da venda."),
    ("O que é curva ABC?",
     "É a classificação dos produtos por participação no resultado. Serve para concentrar a atenção nos poucos itens que realmente movem o faturamento."),
    ("Como o SoftPay ajuda nisso?",
     "A venda registrada no PDV dá baixa automática no estoque, e o cadastro guarda custo e quantidade. A curva ABC está disponível a partir do plano Loja."),
  ],
  cta_title="Comece pelo estoque que mais te incomoda",
  cta_text="Cadastre os produtos de maior giro com custo e quantidade e veja o estoque acompanhar as vendas sozinho.",
  related=[("Controle de estoque", "/solucoes/sistema-de-estoque/", "Como funciona no SoftPay"),
           ("Como calcular lucro", "/guias/como-calcular-lucro-da-loja/", "O custo entra aqui"),
           ("Como sair do caderno", "/guias/como-sair-do-caderno/", "A migração completa")],
),

dict(
  slug="guias/como-controlar-caixa-da-loja",
  title="Como Controlar o Caixa de uma Loja: Guia Prático | SoftPay",
  description="Como fazer o controle e o fechamento de caixa da loja: rotina diária, conferência, sangria e o que fazer quando não bate. Guia passo a passo.",
  h1="Como controlar o caixa de uma loja",
  intro="Resposta curta: registre toda entrada e toda saída no momento em que acontecem e confira o caixa no fim de cada dia. Caixa que só é conferido no fim do mês não é controle, é arqueologia.",
  breadcrumbs=_c("Como controlar o caixa"),
  blocks=[
    sec("A diferença entre gaveta e caixa",
      p("Gaveta é onde o dinheiro fica. Caixa é o registro do que entrou e do que saiu. Muita loja pequena tem gaveta e acha que tem caixa — e é por isso que a conta nunca fecha."),
      p("O sintoma é sempre o mesmo: sobra ou falta dinheiro no fim do dia e ninguém consegue explicar. Não porque houve desonestidade, mas porque não existe registro contra o qual comparar."),
    ),
    sec("Passo 1 — Defina o fundo de troco",
      p("Comece o dia com um valor fixo em espécie para troco e registre esse valor. Sem um ponto de partida conhecido, qualquer conferência no fim do dia é impossível."),
    ),
    sec("Passo 2 — Registre a venda com a forma de pagamento",
      p("Dinheiro, Pix, débito e crédito não são a mesma coisa na hora de conferir. O dinheiro está na gaveta; o resto chega depois, na conta. Se a forma de pagamento não é registrada, o fechamento não tem como bater."),
    ),
    sec("Passo 3 — Registre as saídas, inclusive as pequenas",
      p("Pagar o motoboy, comprar água, adiantar dinheiro para alguém. Essas saídas somem da memória e aparecem como “falta” no fechamento. Toda retirada precisa ser registrada — inclusive a sangria, quando você tira dinheiro do caixa para o cofre ou para o banco."),
    ),
    sec("Passo 4 — Feche o caixa todo dia",
      p("O fechamento compara o que o sistema registrou com o que existe fisicamente:"),
      exemplo("Fechamento de um dia", [
        ("Fundo de troco inicial", "R$ 150,00", ""),
        ("Vendas em dinheiro", "+ R$ 1.240,00", ""),
        ("Sangria para o cofre", "− R$ 900,00", "minus"),
        ("Pagamentos em dinheiro", "− R$ 85,00", "minus"),
        ("= Deveria ter na gaveta", "R$ 405,00", "result"),
        ("Contagem física", "R$ 397,00", ""),
        ("= Diferença a explicar", "− R$ 8,00", "result final"),
      ], "Números fictícios. O valor da diferença importa menos que o hábito: conferida no mesmo dia, ela ainda tem explicação."),
      nota("Diferença pequena e recorrente costuma ser erro de troco. Diferença grande e isolada costuma ser saída não registrada. Diferença crescente merece atenção real.", "Como ler a diferença"),
    ),
    sec("Passo 5 — Não confunda caixa com lucro",
      p("Dinheiro na gaveta não é lucro. Parte dele é o custo da mercadoria que você vai repor. Vender bem e ter caixa cheio no dia 5 não significa que o mês fechou no azul — essa conta é outra, e está no guia de <a href=\"/guias/como-calcular-lucro-da-loja/\">como calcular o lucro da loja</a>."),
      FONTE,
    ),
  ],
  faq=[
    ("Com que frequência devo fechar o caixa?",
     "Todo dia, ao fim do expediente. É o que permite explicar uma diferença enquanto ela ainda é lembrada."),
    ("O que fazer quando o caixa não bate?",
     "Verifique primeiro as saídas não registradas e os erros de troco. Diferença pequena e recorrente costuma ser troco; diferença grande e isolada costuma ser retirada sem registro."),
    ("Preciso separar as formas de pagamento?",
     "Sim. Dinheiro está na gaveta hoje; cartão e Pix entram depois na conta. Sem separar, o fechamento não fecha."),
    ("O que é sangria de caixa?",
     "É a retirada de dinheiro do caixa durante o expediente, normalmente para o cofre ou o banco, por segurança. Precisa ser registrada como saída."),
    ("Como o SoftPay ajuda?",
     "A venda registrada no PDV entra no caixa já com a forma de pagamento, e o fechamento compara o registrado com a contagem física."),
  ],
  cta_title="Feche seu primeiro caixa hoje",
  cta_text="Registre o fundo de troco, passe as vendas do dia no PDV e faça a conferência no fim do expediente.",
  related=[("Sistema financeiro", "/solucoes/sistema-financeiro/", "Caixa e resultado"),
           ("Sistema PDV", "/solucoes/sistema-pdv/", "Onde a venda é registrada"),
           ("Como calcular lucro", "/guias/como-calcular-lucro-da-loja/", "Caixa não é lucro")],
),

dict(
  slug="guias/como-controlar-fiado",
  title="Como Controlar Vendas Fiadas na Loja | SoftPay",
  description="Como organizar o fiado da sua loja: registro por cliente, limite, prazo, cobrança sem constrangimento e como sair do caderno. Guia prático.",
  h1="Como controlar vendas fiadas",
  intro="Resposta curta: registre cada venda fiada no nome do cliente, com data e valor, e combine prazo antes de vender. O caderno não é o problema por ser papel — é por não ter total.",
  breadcrumbs=_c("Como controlar fiado"),
  blocks=[
    sec("Por que o fiado some",
      p("O dinheiro fiado é o mais fácil de perder porque ele não dói na hora. A mercadoria sai, a venda parece feita e o buraco só aparece quando falta dinheiro para repor o estoque."),
      p("No caderno, três coisas conspiram contra você: não existe um total visível de quanto a loja tem a receber, a anotação depende de quem estava no balcão, e quando o cliente contesta não há histórico para mostrar."),
    ),
    sec("Passo 1 — Decida a quem você vende fiado",
      p("Fiado para todo mundo não é política, é ausência de política. Defina um critério — cliente conhecido, tempo de relacionamento, valor máximo — e aplique igual para todos. Isso evita a conversa difícil caso a caso."),
    ),
    sec("Passo 2 — Combine prazo antes, não depois",
      p("“Me paga quando puder” é a origem da maioria das dívidas que nunca são pagas. Um prazo combinado no momento da venda transforma a cobrança em lembrete, não em conflito."),
    ),
    sec("Passo 3 — Registre no nome do cliente",
      p("Cada venda fiada precisa ficar ligada a um cadastro, com data, valor e os produtos. Assim, quando o cliente perguntar quanto deve, a resposta é uma lista, não uma afirmação."),
    ),
    sec("Passo 4 — Olhe o total, não os nomes",
      p("A pergunta que muda a gestão não é “quem me deve”, é “quanto a loja tem a receber”. Esse total costuma surpreender:"),
      exemplo("Fiado em aberto de uma loja", [
        ("18 clientes com saldo em aberto", "R$ 4.380,00", ""),
        ("Desses, vencidos há mais de 30 dias", "R$ 1.910,00", ""),
        ("= Dinheiro fora do caixa", "R$ 4.380,00", "result final"),
      ], "Números fictícios. Para muita loja pequena, o fiado em aberto é maior que o saldo em conta corrente."),
    ),
    sec("Passo 5 — Cobre sem constrangimento",
      p("A cobrança pessoal no balcão é o que mais trava o lojista, porque mistura relação e dinheiro. Uma mensagem com link de pagamento resolve o problema: é impessoal, chega na hora certa e o cliente paga sem precisar voltar à loja."),
      nota("No SoftPay, o caderninho de fiado está no plano Comércio. A partir do plano Loja, o sistema envia cobrança por link de Pix pelo WhatsApp.", "Como isso funciona no SoftPay"),
    ),
    sec("Como passar o caderno atual para o sistema",
      ol("Some o saldo em aberto de cada cliente do caderno.",
         "Cadastre os clientes que têm dívida.",
         "Lance o saldo de cada um como venda fiada, com a data aproximada.",
         "A partir dali, toda venda fiada nova entra direto pelo sistema.",
         "Guarde o caderno antigo por um tempo, até a conferência estar redonda."),
      FONTE,
    ),
  ],
  faq=[
    ("Devo parar de vender fiado?",
     "Não necessariamente. No comércio de bairro o fiado sustenta a fidelidade do cliente. O que precisa mudar é o controle: critério para conceder, prazo combinado e registro por cliente."),
    ("Como cobrar sem perder o cliente?",
     "Cobrança impessoal funciona melhor: uma mensagem com link de pagamento chega na hora certa sem transformar o balcão em conversa constrangedora."),
    ("Dá para definir limite por cliente?",
     "Como prática de gestão, sim, e é recomendável. Sobre o limite automático dentro do SoftPay, confirme com o suporte antes de contratar."),
    ("A venda fiada baixa o estoque?",
     "Sim. É uma venda como qualquer outra: a mercadoria sai e o valor fica registrado como a receber."),
    ("Como levo o caderno para o sistema?",
     "Some o saldo de cada cliente, cadastre essas pessoas e lance os saldos como vendas fiadas. Depois disso, toda venda nova entra direto pelo sistema."),
  ],
  cta_title="Descubra quanto sua loja tem a receber",
  cta_text="Cadastre os clientes com saldo em aberto e veja o total do fiado da sua loja em um número só.",
  related=[("Controle de fiado", "/solucoes/controle-de-fiado/", "Como funciona no SoftPay"),
           ("Mercadinho", "/segmentos/mercadinho/", "O fiado do bairro"),
           ("Como sair do caderno", "/guias/como-sair-do-caderno/", "Migração completa")],
),

dict(
  slug="guias/como-calcular-lucro-da-loja",
  title="Como Calcular o Lucro de uma Loja (com Exemplo) | SoftPay",
  description="Aprenda a calcular o lucro da sua loja: faturamento, CMV, lucro bruto, despesas e resultado. Com fórmula, exemplo prático e os erros mais comuns.",
  h1="Como calcular o lucro de uma loja",
  intro="Resposta curta: lucro bruto é o faturamento menos o custo da mercadoria vendida. O resultado é o lucro bruto menos as despesas. Faturamento sozinho não diz nada sobre o seu ganho.",
  breadcrumbs=_c("Como calcular o lucro"),
  blocks=[
    sec("Faturamento não é lucro",
      p("Faturamento é o total que passou pelo caixa. Dentro dele está o dinheiro que pertence ao fornecedor da mercadoria, ao aluguel, à energia e ao funcionário. O que sobra depois de tudo isso é o seu."),
      p("É por isso que existe a frase mais repetida do varejo pequeno: “vendo muito e não tenho dinheiro”. Quase sempre não é problema de venda — é a margem sendo consumida sem acompanhamento."),
    ),
    sec("As duas fórmulas que você precisa",
      p("A primeira separa o custo da mercadoria:"),
      ul("<strong>Lucro bruto = Faturamento − CMV</strong> (custo da mercadoria vendida)"),
      p("A segunda desconta o custo de manter a loja aberta:"),
      ul("<strong>Resultado = Lucro bruto − Despesas do período</strong>"),
    ),
    sec("O que é CMV e como calcular",
      p("CMV é o custo daquilo que efetivamente saiu da prateleira no período — não o quanto você comprou. A fórmula clássica é:"),
      ul("<strong>CMV = Estoque inicial + Compras − Estoque final</strong>"),
      p("Se você tinha R$ 10.000 em estoque, comprou R$ 5.000 no mês e terminou com R$ 8.000, o CMV foi R$ 7.000. Esse é o custo do que você vendeu."),
      nota("Com o custo de cada produto cadastrado em sistema e a baixa acontecendo na venda, o CMV deixa de depender de inventário manual no fim do mês.", "Por que o sistema muda isso"),
    ),
    sec("Exemplo completo, do faturamento ao bolso",
      exemplo("Fechamento de um mês", [
        ("Vendas do mês (faturamento)", "R$ 25.480,00", ""),
        ("Custo da mercadoria vendida (CMV)", "− R$ 16.560,00", "minus"),
        ("= Lucro bruto", "R$ 8.920,00", "result"),
        ("Aluguel", "− R$ 1.200,00", "minus"),
        ("Energia, água e internet", "− R$ 600,00", "minus"),
        ("Funcionário e encargos", "− R$ 1.600,00", "minus"),
        ("= Resultado estimado", "R$ 5.520,00", "result final"),
      ], "Números fictícios, para explicar o método. Faturar R$ 25 mil e ganhar R$ 5,5 mil é uma realidade comum — e só fica visível quando o custo é acompanhado."),
      p("Repare que a margem bruta desse exemplo é de 35% (8.920 ÷ 25.480). É com ela que a loja paga todas as despesas. Se as despesas crescem e a margem não, o resultado desaparece mesmo com a venda estável."),
    ),
    sec("Os erros que mais distorcem a conta",
      ul("<strong>Contar a venda fiada como dinheiro recebido.</strong> A mercadoria saiu, mas o dinheiro não entrou.",
         "<strong>Esquecer a retirada do dono.</strong> Se você tira dinheiro da loja para despesa pessoal, isso precisa aparecer.",
         "<strong>Usar o preço de compra do mês em vez do custo do que foi vendido.</strong> Comprar não é vender.",
         "<strong>Ignorar perdas, quebras e furtos.</strong> Eles saíram do estoque sem gerar receita.",
         "<strong>Confundir dinheiro em caixa com lucro.</strong> Parte do caixa é o custo da próxima reposição."),
      nota("Este guia trata de gestão, não de contabilidade ou tributos. Para apuração fiscal e escolha de regime tributário, consulte o seu contador.", "Sobre o alcance deste guia"),
      FONTE,
    ),
  ],
  faq=[
    ("Qual a diferença entre faturamento e lucro?",
     "Faturamento é tudo que entrou com as vendas. Lucro é o que sobra depois de descontar o custo da mercadoria vendida e as despesas do período."),
    ("O que é CMV?",
     "Custo da Mercadoria Vendida: o custo daquilo que efetivamente saiu da prateleira no período. A fórmula clássica é estoque inicial mais compras menos estoque final."),
    ("Por que vendo muito e não tenho dinheiro?",
     "Quase sempre porque a margem está sendo consumida pelo custo da mercadoria e pelas despesas sem acompanhamento, ou porque parte da venda foi fiada e ainda não virou dinheiro."),
    ("A retirada do dono entra na conta?",
     "Sim. Se você retira dinheiro da loja para despesas pessoais, isso precisa aparecer, senão o resultado fica superestimado."),
    ("O SoftPay calcula isso para mim?",
     "Ele reúne os dados que formam a conta: vendas registradas no PDV e custo dos produtos cadastrado. A precisão depende de esses dados estarem completos. Ele não substitui a contabilidade."),
  ],
  cta_title="Tenha os números para fazer essa conta",
  cta_text="Cadastre o custo dos produtos, registre as vendas por um mês e a conta deixa de ser estimativa.",
  related=[("Como calcular margem", "/guias/como-calcular-margem-de-lucro/", "Formação de preço"),
           ("Sistema financeiro", "/solucoes/sistema-financeiro/", "Caixa e resultado"),
           ("Como controlar estoque", "/guias/como-controlar-estoque/", "De onde vem o custo")],
),

dict(
  slug="guias/como-calcular-margem-de-lucro",
  title="Como Calcular a Margem de Lucro e o Preço de Venda | SoftPay",
  description="Como calcular margem de lucro e formar preço de venda: markup, margem sobre venda, o erro de somar a porcentagem no custo e exemplos práticos.",
  h1="Como calcular a margem de lucro",
  intro="Resposta curta: margem é o lucro dividido pelo preço de venda, não pelo custo. Confundir os dois é o erro de precificação mais caro do varejo pequeno.",
  breadcrumbs=_c("Como calcular margem"),
  blocks=[
    sec("Margem e markup não são a mesma coisa",
      p("Essa distinção parece detalhe e destrói a rentabilidade de muita loja. As duas contas partem do mesmo lucro, mas dividem por bases diferentes:"),
      ul("<strong>Margem</strong> = lucro ÷ <strong>preço de venda</strong>",
         "<strong>Markup</strong> = lucro ÷ <strong>custo</strong>"),
      p("Um produto que custa R$ 60 e é vendido por R$ 100 tem R$ 40 de lucro bruto. O markup é 66,7% (40 ÷ 60). A margem é 40% (40 ÷ 100). Se você achou que estava ganhando 66,7% sobre a venda, seu preço está errado."),
    ),
    sec("O erro de somar a porcentagem no custo",
      p("A prática mais comum — e mais perigosa — é pegar o custo e somar a porcentagem desejada. Quem quer 30% de margem e faz “custo × 1,30” não chega a 30% de margem:"),
      exemplo("Custo R$ 60, querendo 30% de margem", [
        ("Cálculo errado: 60 × 1,30", "R$ 78,00", ""),
        ("Margem real desse preço: 18 ÷ 78", "23,1%", "minus"),
        ("Cálculo certo: 60 ÷ (1 − 0,30)", "R$ 85,71", "result"),
        ("Margem real desse preço: 25,71 ÷ 85,71", "30,0%", "result final"),
      ], "Quase 8 reais de diferença por produto. Multiplicado pelo volume de um mês, é a diferença entre lucro e prejuízo."),
    ),
    sec("A fórmula certa para formar preço",
      p("Para chegar a uma margem desejada, divida o custo pelo complemento da margem:"),
      ul("<strong>Preço de venda = Custo ÷ (1 − margem desejada)</strong>"),
      p("Com custo de R$ 60 e margem alvo de 40%: 60 ÷ (1 − 0,40) = 60 ÷ 0,60 = <strong>R$ 100,00</strong>."),
      nota("A margem precisa cobrir mais que o custo da mercadoria: impostos, taxa de cartão, perdas e a sua parcela das despesas fixas saem dela. Uma margem que só cobre o custo não é lucro, é empate.", "O que a margem precisa cobrir"),
    ),
    sec("Margem por produto, não margem média",
      p("Trabalhar com uma margem única para a loja inteira esconde os produtos que dão prejuízo. Em geral, os itens de maior giro puxam a margem para baixo e são compensados por outros — mas você só descobre isso olhando produto a produto."),
      tabela(["Produto", "Custo", "Venda", "Margem"], [
        ["Item de alto giro", "R$ 8,00", "R$ 10,00", "20,0%"],
        ["Item intermediário", "R$ 22,00", "R$ 35,00", "37,1%"],
        ["Item de baixo giro", "R$ 45,00", "R$ 89,00", "49,4%"],
      ]),
      p("Números fictícios. O ponto é o padrão: dá para vender muito do produto de 20% e ainda assim fechar o mês bem — desde que você saiba que ele é de 20%."),
      FONTE,
    ),
  ],
  faq=[
    ("Qual a diferença entre margem e markup?",
     "Margem divide o lucro pelo preço de venda; markup divide o lucro pelo custo. O mesmo produto tem margem menor que markup, e confundir os dois leva a preço abaixo do necessário."),
    ("Como formar o preço para ter a margem que eu quero?",
     "Use preço = custo ÷ (1 − margem desejada). Somar a porcentagem sobre o custo produz uma margem menor que a pretendida."),
    ("Qual margem é a ideal para minha loja?",
     "Não existe número universal: depende do segmento, do giro e da sua estrutura de custos. A margem precisa cobrir impostos, taxas, perdas e as despesas fixas, além do custo da mercadoria."),
    ("Devo usar a mesma margem para todos os produtos?",
     "Não. Margem média esconde produtos que dão prejuízo. O ideal é acompanhar por produto, ou pelo menos por categoria."),
    ("Onde entram as taxas de cartão?",
     "Elas reduzem o que efetivamente entra na sua conta, então precisam ser consideradas na formação do preço junto com impostos e perdas."),
  ],
  cta_title="Confira a margem dos seus produtos",
  cta_text="Cadastre custo e preço de venda e veja a margem real de cada item, em vez de trabalhar com média.",
  related=[("Como calcular lucro", "/guias/como-calcular-lucro-da-loja/", "A conta completa"),
           ("Controle de estoque", "/solucoes/sistema-de-estoque/", "Custo por produto"),
           ("Sistema financeiro", "/solucoes/sistema-financeiro/", "Resultado do período")],
),

dict(
  slug="guias/como-organizar-uma-loja",
  title="Como Organizar uma Loja: Guia Prático de Gestão | SoftPay",
  description="Como organizar a gestão de uma loja do zero: cadastro de produtos, rotina de caixa, estoque, fiado e clientes. Um roteiro em etapas realista.",
  h1="Como organizar uma loja",
  intro="Resposta curta: organize uma coisa de cada vez, na ordem em que cada uma sustenta a próxima. Tentar arrumar tudo no mesmo mês é o motivo mais comum de desistir na segunda semana.",
  breadcrumbs=_c("Como organizar uma loja"),
  blocks=[
    sec("A ordem importa mais que a velocidade",
      p("Existe uma sequência natural: sem cadastro de produto não há venda registrada; sem venda registrada não há estoque confiável; sem estoque confiável não há custo; sem custo não há lucro conhecido. Pular etapas produz números que ninguém acredita — e um sistema abandonado em duas semanas."),
    ),
    sec("Etapa 1 — Cadastre os produtos que giram",
      p("Não tente cadastrar o catálogo inteiro. Comece pelos itens que você vende toda semana, com preço de venda, custo e categoria. Complete o resto conforme repõe."),
    ),
    sec("Etapa 2 — Faça toda venda passar pelo mesmo lugar",
      p("Inclusive a fiada, a do conhecido e a que o funcionário fez. Enquanto existir venda fora do registro, todo relatório será uma aproximação."),
    ),
    sec("Etapa 3 — Estabeleça a rotina de caixa",
      p("Fundo de troco no início, forma de pagamento registrada em cada venda, saídas anotadas e conferência no fim do dia. É a rotina que mais rápido devolve resultado visível."),
    ),
    sec("Etapa 4 — Traga o fiado para dentro",
      p("Lance os saldos em aberto no nome de cada cliente. Só de enxergar o total, muita loja descobre que tem mais dinheiro na rua do que no banco."),
    ),
    sec("Etapa 5 — Só então olhe os números",
      p("Com produto cadastrado, venda registrada, caixa fechado e fiado no sistema, os relatórios passam a significar alguma coisa. Aí vale calcular <a href=\"/guias/como-calcular-lucro-da-loja/\">lucro</a> e <a href=\"/guias/como-calcular-margem-de-lucro/\">margem</a> e usar a curva ABC para decidir compras."),
    ),
    sec("Um cronograma realista",
      tabela(["Período", "Foco", "Resultado esperado"], [
        ["Semana 1", "Cadastro dos itens de maior giro", "Vendas já passam pelo sistema"],
        ["Semana 2", "Rotina de caixa e fechamento diário", "Caixa começa a bater"],
        ["Semana 3", "Fiado em aberto lançado", "Total a receber visível"],
        ["Semana 4", "Conferência de estoque dos itens A", "Estoque confiável no que importa"],
        ["Mês 2", "Leitura de margem e curva ABC", "Decisão de compra com base em dado"],
      ]),
      p("O período de teste de 7 dias cobre bem a primeira etapa — o suficiente para você saber se o sistema faz sentido antes de pagar."),
    ),
    sec("O que costuma dar errado",
      ul("Tentar cadastrar tudo antes de começar a usar.",
         "Deixar uma parte das vendas fora do registro.",
         "Adiar o fechamento de caixa para “quando sobrar tempo”.",
         "Cadastrar preço e esquecer o custo.",
         "Trocar de método no meio do caminho."),
      FONTE,
    ),
  ],
  faq=[
    ("Por onde eu começo?",
     "Pelo cadastro dos produtos de maior giro e por fazer toda venda passar pelo mesmo lugar. Sem esses dois, nenhuma outra etapa se sustenta."),
    ("Quanto tempo leva para organizar uma loja?",
     "Com foco em uma etapa por semana, cerca de um mês para ter uma base confiável. Tentar fazer tudo de uma vez costuma terminar em desistência."),
    ("Preciso parar a loja para organizar?",
     "Não. O método é justamente ir cadastrando e registrando durante o funcionamento normal, começando pelo que gira mais."),
    ("Dá para fazer isso em planilha?",
     "Dá para começar, mas a planilha depende de alguém lembrar de dar baixa depois da venda — e é aí que o controle se perde conforme o volume cresce."),
    ("O teste de 7 dias dá tempo?",
     "Dá para cobrir a primeira etapa: cadastrar os itens de maior giro e passar as vendas pelo PDV. É o suficiente para avaliar se faz sentido."),
  ],
  cta_title="Comece pela etapa 1 hoje",
  cta_text="Cadastre os produtos que você vende toda semana e passe as vendas do dia pelo sistema.",
  related=[("Como controlar estoque", "/guias/como-controlar-estoque/", "Etapa do estoque"),
           ("Como controlar o caixa", "/guias/como-controlar-caixa-da-loja/", "Rotina diária"),
           ("Pequeno comércio", "/segmentos/pequeno-comercio/", "Para lojas pequenas")],
),

dict(
  slug="guias/como-sair-do-caderno",
  title="Como Sair do Caderno e Controlar a Loja em Sistema | SoftPay",
  description="Passo a passo para migrar do caderno ou da planilha para um sistema de gestão sem parar a loja: o que levar, em que ordem e o que fazer com o caderno antigo.",
  h1="Como sair do caderno",
  intro="Resposta curta: não transcreva o caderno inteiro. Leve o que ainda está vivo — estoque atual, fiado em aberto e clientes — e comece a registrar as vendas novas no sistema desde o primeiro dia.",
  breadcrumbs=_c("Como sair do caderno"),
  blocks=[
    sec("Por que a migração costuma travar",
      p("Quase todo mundo tenta começar transcrevendo tudo: meses de vendas passadas, todos os produtos, o caderno inteiro. É um trabalho enorme, sem retorno imediato, feito nas horas vagas — e por isso é abandonado no meio."),
      p("Venda passada não muda nada na sua decisão de amanhã. O que importa migrar é o que ainda está em aberto."),
    ),
    sec("O que levar (e o que deixar para trás)",
      tabela(["Levar", "Por quê"], [
        ["Estoque atual dos itens de giro", "É o que decide reposição"],
        ["Fiado em aberto", "É dinheiro a receber"],
        ["Clientes com quem você tem relação", "Base de recompra e fiado"],
        ["Custo dos produtos", "Sem ele não há margem"],
      ]),
      tabela(["Deixar no caderno", "Por quê"], [
        ["Vendas de meses anteriores", "Não muda decisão futura"],
        ["Fiado já quitado", "Encerrado"],
        ["Produtos que você não vende mais", "Só polui o cadastro"],
      ]),
    ),
    sec("O passo a passo, em uma semana",
      ol("<strong>Dia 1 — Produtos de giro.</strong> Cadastre os itens que você vende toda semana, com preço, custo e categoria.",
         "<strong>Dia 2 — Quantidades.</strong> Conte esses itens e registre a quantidade real.",
         "<strong>Dia 3 — Comece a vender pelo sistema.</strong> A partir daqui, toda venda passa pelo PDV. É a virada de chave.",
         "<strong>Dia 4 — Clientes e fiado.</strong> Cadastre quem tem saldo em aberto e lance o valor como venda fiada.",
         "<strong>Dia 5 — Rotina de caixa.</strong> Fundo de troco, formas de pagamento e fechamento no fim do dia.",
         "<strong>Dias 6 e 7 — Conferência.</strong> O estoque bate? O caixa fecha? Ajuste o que estiver fora antes de seguir."),
      nota("Repare que a venda pelo sistema começa no dia 3, não no fim. Registrar as vendas novas é o que dá retorno imediato e mantém a motivação — o cadastro do restante vai acontecendo em paralelo.", "A ordem não é acidental"),
    ),
    sec("Não jogue o caderno fora",
      p("Mantenha o caderno por algumas semanas, em paralelo, até ter confiança de que o sistema está com tudo. Ele é a sua rede de segurança durante a transição — e a referência para conferir qualquer divergência de fiado."),
    ),
    sec("O que muda depois",
      ul("Você passa a saber o total do fiado em aberto, não só quem deve.",
         "O estoque acompanha a venda sem alguém lembrar de dar baixa.",
         "O caixa fecha no mesmo dia, com a diferença ainda explicável.",
         "A margem por produto deixa de ser média e vira número.",
         "Mais de uma pessoa consegue operar a loja sem depender da sua memória."),
      FONTE,
    ),
  ],
  faq=[
    ("Preciso transcrever todo o caderno?",
     "Não. Leve apenas o que está em aberto: estoque atual dos itens de giro, fiado a receber e clientes. Vendas passadas não mudam decisões futuras."),
    ("Vou precisar parar a loja?",
     "Não. A migração acontece durante o funcionamento normal, começando pelos produtos de maior giro."),
    ("Quanto tempo leva?",
     "Uma semana costuma bastar para ter a base funcionando, com as vendas já passando pelo sistema a partir do terceiro dia."),
    ("Posso importar de uma planilha?",
     "A importação de dados está disponível a partir do plano Loja. Fale com o suporte antes para conferir o formato do arquivo."),
    ("E se eu não conseguir sozinho?",
     "O suporte do SoftPay é humano e atende pelo WhatsApp, inclusive na configuração inicial."),
  ],
  cta_title="Faça a virada nesta semana",
  cta_text="Sete dias de teste é exatamente o tempo do roteiro acima. Sem cartão de crédito.",
  related=[("Como organizar uma loja", "/guias/como-organizar-uma-loja/", "O roteiro completo"),
           ("Caderno ou sistema?", "/perguntas/caderno-ou-sistema/", "A comparação"),
           ("Como controlar fiado", "/guias/como-controlar-fiado/", "Levar o fiado junto")],
),
]
