# -*- coding: utf-8 -*-
from blocks import sec, p, ul, ol, h3, nota, exemplo, tabela

C = [("Guias", "/guias/")]
def _c(n): return C + [(n, None)]

FONTE = ('        <p class="page-sources">Referências sobre CMV e margem: '
         '<a href="https://www.totvs.com/blog/gestao-varejista/cmv/" target="_blank" rel="noopener nofollow">TOTVS</a>, '
         '<a href="https://www.serasaexperian.com.br/conteudos/cmv-o-que-e/" target="_blank" rel="noopener nofollow">Serasa Experian</a> e '
         '<a href="https://conteudo.stone.com.br/o-que-e-cmv-como-calcular/" target="_blank" rel="noopener nofollow">Stone</a>. '
         'Para obrigações fiscais, consulte o seu contador e os portais oficiais (gov.br, Receita Federal e SEFAZ do seu estado).</p>')

FONTE_REFORMA = (
    '        <p class="page-sources">Fontes oficiais: '
    '<a href="https://www.gov.br/receitafederal/pt-br/acesso-a-informacao/acoes-e-programas/programas-e-atividades/reforma-tributaria-do-consumo/orientacoes-2026" target="_blank" rel="noopener nofollow">Receita Federal — Orientações 2026</a> e '
    '<a href="https://www.cgibs.gov.br/novo-marco-da-reforma-tributaria-inicia-em-03-de-agosto-com-preenchimento-obrigatorio-dos-campos-relativos-ao-ibs-e-a-cbs" target="_blank" rel="noopener nofollow">Comitê Gestor do IBS</a> '
    '(Ato Conjunto RFB/CGIBS nº 4, de 30 de julho de 2026). '
    'Datas conferidas em 8 de setembro de 2026. <strong>Esta página não é orientação '
    'contábil:</strong> o enquadramento do seu negócio deve ser confirmado com o seu '
    'contador.</p>')

PAGINAS = [

dict(
  artigo=True,
  slug="guias/como-controlar-estoque",
  passos=[
    ('Faça o inventário inicial', 'Liste os produtos de maior giro, conte a quantidade real e registre quantidade, preço de venda e custo de compra de cada um.', 'passo-1-faca-o-inventario-inicial-sem-tentar-fazer-tudo'),
    ('Faça toda venda passar pelo mesmo lugar', 'Inclua a venda fiada, a venda para conhecido e a que o funcionário fez. Toda saída de mercadoria precisa gerar registro.', 'passo-2-faca-toda-venda-passar-pelo-mesmo-lugar'),
    ('Registre também o que entra', 'Compra de fornecedor, devolução de cliente e perda por quebra ou validade vencida.', 'passo-3-registre-tambem-o-que-entra'),
    ('Descubra quanto dinheiro está parado', 'Com quantidade e custo cadastrados, o total investido em mercadoria deixa de ser chute.', 'passo-4-descubra-quanto-dinheiro-esta-parado'),
    ('Use a curva ABC para decidir a compra', 'Classifique os produtos por participação no resultado e concentre a decisão nos que movem o faturamento.', 'passo-5-use-a-curva-abc-para-decidir-a-compra'),
  ],
  figura=("/assets/lojistas/loja-de-variedades.webp",
          "Lojista organizando o estoque na prateleira"),
  title="Como Controlar o Estoque de uma Loja: Guia Prático | SoftPay",
  description="Passo a passo para controlar o estoque da sua loja: inventário inicial, custo por produto, baixa automática e curva ABC. Guia completo e prático.",
  h1="Como controlar o estoque de uma loja",
  intro="Resposta curta: registre o que entra, registre o que sai e cadastre o custo de cada item. Todo o resto do controle de estoque é consequência desses três hábitos.",
  breadcrumbs=_c("Como controlar estoque"),
  blocks=[
    sec("Por que o controle sempre desanda",
      p("O motivo mais comum não é preguiça: é que venda e estoque viram dois controles separados. A venda acontece no balcão e a baixa do estoque fica para depois. Como o “depois” depende de alguém lembrar, o desencontro começa em dias."),
      p("A correção estrutural é fazer a baixa acontecer no mesmo ato da venda. É isso que um PDV resolve — não por ser sofisticado, mas por eliminar a segunda etapa."),
    ),
    sec("Passo 1 — Faça o inventário inicial (sem tentar fazer tudo)",
      p("O erro clássico é parar a loja para contar todos os produtos e desistir no meio. Comece diferente:"),
      ol("Liste os produtos que você vende com mais frequência — normalmente uma minoria responde pela maior parte das vendas.",
         "Conte a quantidade real desses itens na prateleira e no depósito.",
         "Registre quantidade, preço de venda e <strong>custo de compra</strong> de cada um.",
         "Vá completando o restante conforme repõe: quando chegar mercadoria nova, cadastre antes de colocar na prateleira."),
      nota("Cadastrar só o preço de venda responde quanto entrou. É o custo que permite responder quanto sobrou. Sem ele, você tem controle de quantidade, não controle de estoque.", "O passo que quase todo mundo pula"),
    ),
    sec("Passo 2 — Faça toda venda passar pelo mesmo lugar",
      p("Não adianta o cadastro estar perfeito se metade das vendas sai sem registro. Isso inclui a venda fiada, a venda para conhecido e a que o funcionário fez enquanto você não estava. Toda saída de mercadoria precisa gerar um registro."),
    ),
    sec("Passo 3 — Registre também o que entra",
      p("Compra de fornecedor, devolução de cliente, perda por quebra ou validade vencida. Estoque que só registra saída fica errado tão rápido quanto o que não registra nada."),
    ),
    sec("Passo 4 — Descubra quanto dinheiro está parado",
      p("Com quantidade e custo cadastrados, esse número deixa de ser chute:"),
      exemplo("Dinheiro investido em mercadoria", [
        ("Categoria A — 120 itens", "R$ 8.400,00", ""),
        ("Categoria B — 340 itens", "R$ 5.100,00", ""),
        ("Categoria C — 890 itens", "R$ 3.200,00", ""),
        ("= Total parado na prateleira", "R$ 16.700,00", "result final"),
      ], "Números fictícios. Para muita loja pequena, esse total é maior que o saldo em conta — e é a explicação de vender bem e não ter dinheiro."),
    ),
    sec("Passo 5 — Use a curva ABC para decidir a compra",
      p("Com centenas de itens, analisar tudo é impossível. A curva ABC classifica os produtos por participação no resultado:"),
      tabela(["Classe", "O que costuma ser", "O que fazer"], [
        ["A", "Poucos itens, maior parte do faturamento", "Nunca deixar faltar"],
        ["B", "Giro intermediário", "Repor com regularidade"],
        ["C", "Muitos itens, pouca participação", "Comprar menos, avaliar remarcação"],
      ]),
      p("A conversa útil está na classe C: é onde costuma estar o dinheiro parado que você nem sabia que tinha."),
    ),
    sec("Erros comuns",
      ul("Contar estoque uma vez por ano e achar que o número vale o ano inteiro.",
         "Cadastrar preço de venda e esquecer o custo.",
         "Deixar a venda fiada fora do registro.",
         "Repor por memória em vez de olhar o que saiu.",
         "Tratar perda e quebra como se não existissem."),
      FONTE,
    ),
  ],
  faq=[
    ("Preciso parar a loja para fazer inventário?",
     "Não. O caminho prático é começar pelos itens de maior giro e completar o restante conforme você repõe a mercadoria."),
    ("Com que frequência devo conferir o estoque?",
     "Uma conferência periódica dos itens de maior giro costuma bastar para pegar desvios cedo. O inventário completo pode ser feito por partes ao longo do tempo."),
    ("Planilha resolve?",
     "Resolve enquanto o volume é pequeno e uma pessoa só mexe nela. O problema não é a planilha em si: é que a baixa depende de alguém lembrar de fazer depois da venda."),
    ("O que é curva ABC?",
     "É a classificação dos produtos por participação no resultado. Serve para concentrar a atenção nos poucos itens que realmente movem o faturamento."),
    ("Como o SoftPay ajuda nisso?",
     "A venda registrada no PDV dá baixa automática no estoque, e o cadastro guarda custo e quantidade. A curva ABC está disponível a partir do plano Loja."),
  ],
  cta_title="Comece pelo estoque que mais te incomoda",
  cta_text="Cadastre os produtos de maior giro com custo e quantidade e veja o estoque acompanhar as vendas sozinho.",
  related=[("Controle de estoque", "/solucoes/sistema-de-estoque/", "Como funciona no SoftPay"),
           ("Como calcular lucro", "/guias/como-calcular-lucro-da-loja/", "O custo entra aqui"),
           ("Como sair do caderno", "/guias/como-sair-do-caderno/", "A migração completa")],
),

dict(
  artigo=True,
  slug="guias/como-controlar-caixa-da-loja",
  passos=[
    ('Defina o fundo de troco', 'Comece o dia com um valor fixo em espécie e registre esse valor.', 'passo-1-defina-o-fundo-de-troco'),
    ('Registre a venda com a forma de pagamento', 'Dinheiro, Pix, débito e crédito não são a mesma coisa na hora de conferir.', 'passo-2-registre-a-venda-com-a-forma-de-pagamento'),
    ('Registre as saídas, inclusive as pequenas', 'Toda retirada precisa ser registrada, incluindo a sangria para o cofre ou o banco.', 'passo-3-registre-as-saidas-inclusive-as-pequenas'),
    ('Feche o caixa todo dia', 'Compare o que o sistema registrou com o que existe fisicamente na gaveta.', 'passo-4-feche-o-caixa-todo-dia'),
    ('Não confunda caixa com lucro', 'Parte do dinheiro na gaveta é o custo da mercadoria que você vai repor.', 'passo-5-nao-confunda-caixa-com-lucro'),
  ],
  figura=("/assets/lojistas/mercadinho.webp",
          "Lojista no balcão do mercadinho, onde o caixa é fechado"),
  title="Como Controlar o Caixa de uma Loja: Guia Prático | SoftPay",
  description="Como fazer o controle e o fechamento de caixa da loja: rotina diária, conferência, sangria e o que fazer quando não bate. Guia passo a passo.",
  h1="Como controlar o caixa de uma loja",
  intro="Resposta curta: registre toda entrada e toda saída no momento em que acontecem e confira o caixa no fim de cada dia. Caixa que só é conferido no fim do mês não é controle, é arqueologia.",
  breadcrumbs=_c("Como controlar o caixa"),
  blocks=[
    sec("A diferença entre gaveta e caixa",
      p("Gaveta é onde o dinheiro fica. Caixa é o registro do que entrou e do que saiu. Muita loja pequena tem gaveta e acha que tem caixa — e é por isso que a conta nunca fecha."),
      p("O sintoma é sempre o mesmo: sobra ou falta dinheiro no fim do dia e ninguém consegue explicar. Não porque houve desonestidade, mas porque não existe registro contra o qual comparar."),
    ),
    sec("Passo 1 — Defina o fundo de troco",
      p("Comece o dia com um valor fixo em espécie para troco e registre esse valor. Sem um ponto de partida conhecido, qualquer conferência no fim do dia é impossível."),
    ),
    sec("Passo 2 — Registre a venda com a forma de pagamento",
      p("Dinheiro, Pix, débito e crédito não são a mesma coisa na hora de conferir. O dinheiro está na gaveta; o resto chega depois, na conta. Se a forma de pagamento não é registrada, o fechamento não tem como bater."),
    ),
    sec("Passo 3 — Registre as saídas, inclusive as pequenas",
      p("Pagar o motoboy, comprar água, adiantar dinheiro para alguém. Essas saídas somem da memória e aparecem como “falta” no fechamento. Toda retirada precisa ser registrada — inclusive a sangria, quando você tira dinheiro do caixa para o cofre ou para o banco."),
    ),
    sec("Passo 4 — Feche o caixa todo dia",
      p("O fechamento compara o que o sistema registrou com o que existe fisicamente:"),
      exemplo("Fechamento de um dia", [
        ("Fundo de troco inicial", "R$ 150,00", ""),
        ("Vendas em dinheiro", "+ R$ 1.240,00", ""),
        ("Sangria para o cofre", "− R$ 900,00", "minus"),
        ("Pagamentos em dinheiro", "− R$ 85,00", "minus"),
        ("= Deveria ter na gaveta", "R$ 405,00", "result"),
        ("Contagem física", "R$ 397,00", ""),
        ("= Diferença a explicar", "− R$ 8,00", "result final"),
      ], "Números fictícios. O valor da diferença importa menos que o hábito: conferida no mesmo dia, ela ainda tem explicação."),
      nota("Diferença pequena e recorrente costuma ser erro de troco. Diferença grande e isolada costuma ser saída não registrada. Diferença crescente merece atenção real.", "Como ler a diferença"),
    ),
    sec("Passo 5 — Não confunda caixa com lucro",
      p("Dinheiro na gaveta não é lucro. Parte dele é o custo da mercadoria que você vai repor. Vender bem e ter caixa cheio no dia 5 não significa que o mês fechou no azul — essa conta é outra, e está no guia de <a href=\"/guias/como-calcular-lucro-da-loja/\">como calcular o lucro da loja</a>."),
      FONTE,
    ),
  ],
  faq=[
    ("Com que frequência devo fechar o caixa?",
     "Todo dia, ao fim do expediente. É o que permite explicar uma diferença enquanto ela ainda é lembrada."),
    ("O que fazer quando o caixa não bate?",
     "Verifique primeiro as saídas não registradas e os erros de troco. Diferença pequena e recorrente costuma ser troco; diferença grande e isolada costuma ser retirada sem registro."),
    ("Preciso separar as formas de pagamento?",
     "Sim. Dinheiro está na gaveta hoje; cartão e Pix entram depois na conta. Sem separar, o fechamento não fecha."),
    ("O que é sangria de caixa?",
     "É a retirada de dinheiro do caixa durante o expediente, normalmente para o cofre ou o banco, por segurança. Precisa ser registrada como saída."),
    ("Como o SoftPay ajuda?",
     "A venda registrada no PDV entra no caixa já com a forma de pagamento, e o fechamento compara o registrado com a contagem física."),
  ],
  cta_title="Feche seu primeiro caixa hoje",
  cta_text="Registre o fundo de troco, passe as vendas do dia no PDV e faça a conferência no fim do expediente.",
  related=[("Sistema financeiro", "/solucoes/sistema-financeiro/", "Caixa e resultado"),
           ("Sistema PDV", "/solucoes/sistema-pdv/", "Onde a venda é registrada"),
           ("Como calcular lucro", "/guias/como-calcular-lucro-da-loja/", "Caixa não é lucro")],
),

dict(
  artigo=True,
  slug="guias/como-controlar-fiado",
  passos=[
    ('Decida a quem você vende fiado', 'Defina um critério e aplique igual para todos.', 'passo-1-decida-a-quem-voce-vende-fiado'),
    ('Combine prazo antes, não depois', 'Um prazo combinado na venda transforma a cobrança em lembrete, não em conflito.', 'passo-2-combine-prazo-antes-nao-depois'),
    ('Registre no nome do cliente', 'Cada venda fiada ligada a um cadastro, com data, valor e produtos.', 'passo-3-registre-no-nome-do-cliente'),
    ('Olhe o total, não os nomes', 'A pergunta que muda a gestão é quanto a loja tem a receber no conjunto.', 'passo-4-olhe-o-total-nao-os-nomes'),
    ('Cobre sem constrangimento', 'Uma mensagem com link de pagamento chega na hora certa sem transformar o balcão em conversa difícil.', 'passo-5-cobre-sem-constrangimento'),
  ],
  figura=("/assets/lojistas/casal-comerciantes.webp",
          "Comerciantes conferindo o que os clientes ainda têm a pagar"),
  title="Como Controlar Vendas Fiadas na Loja | SoftPay",
  description="Como organizar o fiado da sua loja: registro por cliente, limite, prazo, cobrança sem constrangimento e como sair do caderno. Guia prático.",
  h1="Como controlar vendas fiadas",
  intro="Resposta curta: registre cada venda fiada no nome do cliente, com data e valor, e combine prazo antes de vender. O caderno não é o problema por ser papel — é por não ter total.",
  breadcrumbs=_c("Como controlar fiado"),
  blocks=[
    sec("Por que o fiado some",
      p("O dinheiro fiado é o mais fácil de perder porque ele não dói na hora. A mercadoria sai, a venda parece feita e o buraco só aparece quando falta dinheiro para repor o estoque."),
      p("No caderno, três coisas conspiram contra você: não existe um total visível de quanto a loja tem a receber, a anotação depende de quem estava no balcão, e quando o cliente contesta não há histórico para mostrar."),
    ),
    sec("Passo 1 — Decida a quem você vende fiado",
      p("Fiado para todo mundo não é política, é ausência de política. Defina um critério — cliente conhecido, tempo de relacionamento, valor máximo — e aplique igual para todos. Isso evita a conversa difícil caso a caso."),
    ),
    sec("Passo 2 — Combine prazo antes, não depois",
      p("“Me paga quando puder” é a origem da maioria das dívidas que nunca são pagas. Um prazo combinado no momento da venda transforma a cobrança em lembrete, não em conflito."),
    ),
    sec("Passo 3 — Registre no nome do cliente",
      p("Cada venda fiada precisa ficar ligada a um cadastro, com data, valor e os produtos. Assim, quando o cliente perguntar quanto deve, a resposta é uma lista, não uma afirmação."),
    ),
    sec("Passo 4 — Olhe o total, não os nomes",
      p("A pergunta que muda a gestão não é “quem me deve”, é “quanto a loja tem a receber”. Esse total costuma surpreender:"),
      exemplo("Fiado em aberto de uma loja", [
        ("18 clientes com saldo em aberto", "R$ 4.380,00", ""),
        ("Desses, vencidos há mais de 30 dias", "R$ 1.910,00", ""),
        ("= Dinheiro fora do caixa", "R$ 4.380,00", "result final"),
      ], "Números fictícios. Para muita loja pequena, o fiado em aberto é maior que o saldo em conta corrente."),
    ),
    sec("Passo 5 — Cobre sem constrangimento",
      p("A cobrança pessoal no balcão é o que mais trava o lojista, porque mistura relação e dinheiro. Uma mensagem com link de pagamento resolve o problema: é impessoal, chega na hora certa e o cliente paga sem precisar voltar à loja."),
      nota("No SoftPay, o caderninho de fiado está no plano Comércio. A partir do plano Loja, o sistema envia cobrança por link de Pix pelo WhatsApp.", "Como isso funciona no SoftPay"),
    ),
    sec("Como passar o caderno atual para o sistema",
      ol("Some o saldo em aberto de cada cliente do caderno.",
         "Cadastre os clientes que têm dívida.",
         "Lance o saldo de cada um como venda fiada, com a data aproximada.",
         "A partir dali, toda venda fiada nova entra direto pelo sistema.",
         "Guarde o caderno antigo por um tempo, até a conferência estar redonda."),
      FONTE,
    ),
  ],
  faq=[
    ("Devo parar de vender fiado?",
     "Não necessariamente. No comércio de bairro o fiado sustenta a fidelidade do cliente. O que precisa mudar é o controle: critério para conceder, prazo combinado e registro por cliente."),
    ("Como cobrar sem perder o cliente?",
     "Cobrança impessoal funciona melhor: uma mensagem com link de pagamento chega na hora certa sem transformar o balcão em conversa constrangedora."),
    ("Dá para definir limite por cliente?",
     "Como prática de gestão, sim, e é recomendável. Sobre o limite automático dentro do SoftPay, confirme com o suporte antes de contratar."),
    ("A venda fiada baixa o estoque?",
     "Sim. É uma venda como qualquer outra: a mercadoria sai e o valor fica registrado como a receber."),
    ("Como levo o caderno para o sistema?",
     "Some o saldo de cada cliente, cadastre essas pessoas e lance os saldos como vendas fiadas. Depois disso, toda venda nova entra direto pelo sistema."),
  ],
  cta_title="Descubra quanto sua loja tem a receber",
  cta_text="Cadastre os clientes com saldo em aberto e veja o total do fiado da sua loja em um número só.",
  related=[("Controle de fiado", "/solucoes/controle-de-fiado/", "Como funciona no SoftPay"),
           ("Mercadinho", "/segmentos/mercadinho/", "O fiado do bairro"),
           ("Como sair do caderno", "/guias/como-sair-do-caderno/", "Migração completa")],
),

dict(
  artigo=True,
  slug="guias/como-calcular-lucro-da-loja",
  figura=("/assets/lojistas/casal-comerciantes.webp",
          "Casal de comerciantes analisando os números da loja"),
  title="Como Calcular o Lucro de uma Loja (com Exemplo) | SoftPay",
  description="Aprenda a calcular o lucro da sua loja: faturamento, CMV, lucro bruto, despesas e resultado. Com fórmula, exemplo prático e os erros mais comuns.",
  h1="Como calcular o lucro de uma loja",
  intro="Resposta curta: lucro bruto é o faturamento menos o custo da mercadoria vendida. O resultado é o lucro bruto menos as despesas. Faturamento sozinho não diz nada sobre o seu ganho.",
  breadcrumbs=_c("Como calcular o lucro"),
  blocks=[
    sec("Faturamento não é lucro",
      p("Faturamento é o total que passou pelo caixa. Dentro dele está o dinheiro que pertence ao fornecedor da mercadoria, ao aluguel, à energia e ao funcionário. O que sobra depois de tudo isso é o seu."),
      p("É por isso que existe a frase mais repetida do varejo pequeno: “vendo muito e não tenho dinheiro”. Quase sempre não é problema de venda — é a margem sendo consumida sem acompanhamento."),
    ),
    sec("As duas fórmulas que você precisa",
      p("A primeira separa o custo da mercadoria:"),
      ul("<strong>Lucro bruto = Faturamento − CMV</strong> (custo da mercadoria vendida)"),
      p("A segunda desconta o custo de manter a loja aberta:"),
      ul("<strong>Resultado = Lucro bruto − Despesas do período</strong>"),
    ),
    sec("O que é CMV e como calcular",
      p("CMV é o custo daquilo que efetivamente saiu da prateleira no período — não o quanto você comprou. A fórmula clássica é:"),
      ul("<strong>CMV = Estoque inicial + Compras − Estoque final</strong>"),
      p("Se você tinha R$ 10.000 em estoque, comprou R$ 5.000 no mês e terminou com R$ 8.000, o CMV foi R$ 7.000. Esse é o custo do que você vendeu."),
      nota("Com o custo de cada produto cadastrado em sistema e a baixa acontecendo na venda, o CMV deixa de depender de inventário manual no fim do mês.", "Por que o sistema muda isso"),
    ),
    sec("Exemplo completo, do faturamento ao bolso",
      exemplo("Fechamento de um mês", [
        ("Vendas do mês (faturamento)", "R$ 25.480,00", ""),
        ("Custo da mercadoria vendida (CMV)", "− R$ 16.560,00", "minus"),
        ("= Lucro bruto", "R$ 8.920,00", "result"),
        ("Aluguel", "− R$ 1.200,00", "minus"),
        ("Energia, água e internet", "− R$ 600,00", "minus"),
        ("Funcionário e encargos", "− R$ 1.600,00", "minus"),
        ("= Resultado estimado", "R$ 5.520,00", "result final"),
      ], "Números fictícios, para explicar o método. Faturar R$ 25 mil e ganhar R$ 5,5 mil é uma realidade comum — e só fica visível quando o custo é acompanhado."),
      p("Repare que a margem bruta desse exemplo é de 35% (8.920 ÷ 25.480). É com ela que a loja paga todas as despesas. Se as despesas crescem e a margem não, o resultado desaparece mesmo com a venda estável."),
    ),
    sec("Os erros que mais distorcem a conta",
      ul("<strong>Contar a venda fiada como dinheiro recebido.</strong> A mercadoria saiu, mas o dinheiro não entrou.",
         "<strong>Esquecer a retirada do dono.</strong> Se você tira dinheiro da loja para despesa pessoal, isso precisa aparecer.",
         "<strong>Usar o preço de compra do mês em vez do custo do que foi vendido.</strong> Comprar não é vender.",
         "<strong>Ignorar perdas, quebras e furtos.</strong> Eles saíram do estoque sem gerar receita.",
         "<strong>Confundir dinheiro em caixa com lucro.</strong> Parte do caixa é o custo da próxima reposição."),
      nota("Este guia trata de gestão, não de contabilidade ou tributos. Para apuração fiscal e escolha de regime tributário, consulte o seu contador.", "Sobre o alcance deste guia"),
      FONTE,
    ),
  ],
  faq=[
    ("Qual a diferença entre faturamento e lucro?",
     "Faturamento é tudo que entrou com as vendas. Lucro é o que sobra depois de descontar o custo da mercadoria vendida e as despesas do período."),
    ("O que é CMV?",
     "Custo da Mercadoria Vendida: o custo daquilo que efetivamente saiu da prateleira no período. A fórmula clássica é estoque inicial mais compras menos estoque final."),
    ("Por que vendo muito e não tenho dinheiro?",
     "Quase sempre porque a margem está sendo consumida pelo custo da mercadoria e pelas despesas sem acompanhamento, ou porque parte da venda foi fiada e ainda não virou dinheiro."),
    ("A retirada do dono entra na conta?",
     "Sim. Se você retira dinheiro da loja para despesas pessoais, isso precisa aparecer, senão o resultado fica superestimado."),
    ("O SoftPay calcula isso para mim?",
     "Ele reúne os dados que formam a conta: vendas registradas no PDV e custo dos produtos cadastrado. A precisão depende de esses dados estarem completos. Ele não substitui a contabilidade."),
  ],
  cta_title="Tenha os números para fazer essa conta",
  cta_text="Cadastre o custo dos produtos, registre as vendas por um mês e a conta deixa de ser estimativa.",
  related=[("Como calcular margem", "/guias/como-calcular-margem-de-lucro/", "Formação de preço"),
           ("Sistema financeiro", "/solucoes/sistema-financeiro/", "Caixa e resultado"),
           ("Como controlar estoque", "/guias/como-controlar-estoque/", "De onde vem o custo")],
),

dict(
  artigo=True,
  slug="guias/como-calcular-margem-de-lucro",
  figura=("/assets/lojistas/loja-de-roupas.webp",
          "Lojista avaliando preço e margem das peças da loja"),
  title="Como Calcular a Margem de Lucro e o Preço de Venda | SoftPay",
  description="Como calcular margem de lucro e formar preço de venda: markup, margem sobre venda, o erro de somar a porcentagem no custo e exemplos práticos.",
  h1="Como calcular a margem de lucro",
  intro="Resposta curta: margem é o lucro dividido pelo preço de venda, não pelo custo. Confundir os dois é o erro de precificação mais caro do varejo pequeno.",
  breadcrumbs=_c("Como calcular margem"),
  blocks=[
    sec("Margem e markup não são a mesma coisa",
      p("Essa distinção parece detalhe e destrói a rentabilidade de muita loja. As duas contas partem do mesmo lucro, mas dividem por bases diferentes:"),
      ul("<strong>Margem</strong> = lucro ÷ <strong>preço de venda</strong>",
         "<strong>Markup</strong> = lucro ÷ <strong>custo</strong>"),
      p("Um produto que custa R$ 60 e é vendido por R$ 100 tem R$ 40 de lucro bruto. O markup é 66,7% (40 ÷ 60). A margem é 40% (40 ÷ 100). Se você achou que estava ganhando 66,7% sobre a venda, seu preço está errado."),
    ),
    sec("O erro de somar a porcentagem no custo",
      p("A prática mais comum — e mais perigosa — é pegar o custo e somar a porcentagem desejada. Quem quer 30% de margem e faz “custo × 1,30” não chega a 30% de margem:"),
      exemplo("Custo R$ 60, querendo 30% de margem", [
        ("Cálculo errado: 60 × 1,30", "R$ 78,00", ""),
        ("Margem real desse preço: 18 ÷ 78", "23,1%", "minus"),
        ("Cálculo certo: 60 ÷ (1 − 0,30)", "R$ 85,71", "result"),
        ("Margem real desse preço: 25,71 ÷ 85,71", "30,0%", "result final"),
      ], "Quase 8 reais de diferença por produto. Multiplicado pelo volume de um mês, é a diferença entre lucro e prejuízo."),
    ),
    sec("A fórmula certa para formar preço",
      p("Para chegar a uma margem desejada, divida o custo pelo complemento da margem:"),
      ul("<strong>Preço de venda = Custo ÷ (1 − margem desejada)</strong>"),
      p("Com custo de R$ 60 e margem alvo de 40%: 60 ÷ (1 − 0,40) = 60 ÷ 0,60 = <strong>R$ 100,00</strong>."),
      nota("A margem precisa cobrir mais que o custo da mercadoria: impostos, taxa de cartão, perdas e a sua parcela das despesas fixas saem dela. Uma margem que só cobre o custo não é lucro, é empate.", "O que a margem precisa cobrir"),
    ),
    sec("Margem por produto, não margem média",
      p("Trabalhar com uma margem única para a loja inteira esconde os produtos que dão prejuízo. Em geral, os itens de maior giro puxam a margem para baixo e são compensados por outros — mas você só descobre isso olhando produto a produto."),
      tabela(["Produto", "Custo", "Venda", "Margem"], [
        ["Item de alto giro", "R$ 8,00", "R$ 10,00", "20,0%"],
        ["Item intermediário", "R$ 22,00", "R$ 35,00", "37,1%"],
        ["Item de baixo giro", "R$ 45,00", "R$ 89,00", "49,4%"],
      ]),
      p("Números fictícios. O ponto é o padrão: dá para vender muito do produto de 20% e ainda assim fechar o mês bem — desde que você saiba que ele é de 20%."),
      FONTE,
    ),
  ],
  faq=[
    ("Qual a diferença entre margem e markup?",
     "Margem divide o lucro pelo preço de venda; markup divide o lucro pelo custo. O mesmo produto tem margem menor que markup, e confundir os dois leva a preço abaixo do necessário."),
    ("Como formar o preço para ter a margem que eu quero?",
     "Use preço = custo ÷ (1 − margem desejada). Somar a porcentagem sobre o custo produz uma margem menor que a pretendida."),
    ("Qual margem é a ideal para minha loja?",
     "Não existe número universal: depende do segmento, do giro e da sua estrutura de custos. A margem precisa cobrir impostos, taxas, perdas e as despesas fixas, além do custo da mercadoria."),
    ("Devo usar a mesma margem para todos os produtos?",
     "Não. Margem média esconde produtos que dão prejuízo. O ideal é acompanhar por produto, ou pelo menos por categoria."),
    ("Onde entram as taxas de cartão?",
     "Elas reduzem o que efetivamente entra na sua conta, então precisam ser consideradas na formação do preço junto com impostos e perdas."),
  ],
  cta_title="Confira a margem dos seus produtos",
  cta_text="Cadastre custo e preço de venda e veja a margem real de cada item, em vez de trabalhar com média.",
  related=[("Como calcular lucro", "/guias/como-calcular-lucro-da-loja/", "A conta completa"),
           ("Controle de estoque", "/solucoes/sistema-de-estoque/", "Custo por produto"),
           ("Sistema financeiro", "/solucoes/sistema-financeiro/", "Resultado do período")],
),

dict(
  artigo=True,
  slug="guias/como-organizar-uma-loja",
  figura=("/assets/lojistas/mercadinho.webp",
          "Lojista organizando a rotina do mercadinho"),
  title="Como Organizar uma Loja: Guia Prático de Gestão | SoftPay",
  description="Como organizar a gestão de uma loja do zero: cadastro de produtos, rotina de caixa, estoque, fiado e clientes. Um roteiro em etapas realista.",
  h1="Como organizar uma loja",
  intro="Resposta curta: organize uma coisa de cada vez, na ordem em que cada uma sustenta a próxima. Tentar arrumar tudo no mesmo mês é o motivo mais comum de desistir na segunda semana.",
  breadcrumbs=_c("Como organizar uma loja"),
  blocks=[
    sec("A ordem importa mais que a velocidade",
      p("Existe uma sequência natural: sem cadastro de produto não há venda registrada; sem venda registrada não há estoque confiável; sem estoque confiável não há custo; sem custo não há lucro conhecido. Pular etapas produz números que ninguém acredita — e um sistema abandonado em duas semanas."),
    ),
    sec("Etapa 1 — Cadastre os produtos que giram",
      p("Não tente cadastrar o catálogo inteiro. Comece pelos itens que você vende toda semana, com preço de venda, custo e categoria. Complete o resto conforme repõe."),
    ),
    sec("Etapa 2 — Faça toda venda passar pelo mesmo lugar",
      p("Inclusive a fiada, a do conhecido e a que o funcionário fez. Enquanto existir venda fora do registro, todo relatório será uma aproximação."),
    ),
    sec("Etapa 3 — Estabeleça a rotina de caixa",
      p("Fundo de troco no início, forma de pagamento registrada em cada venda, saídas anotadas e conferência no fim do dia. É a rotina que mais rápido devolve resultado visível."),
    ),
    sec("Etapa 4 — Traga o fiado para dentro",
      p("Lance os saldos em aberto no nome de cada cliente. Só de enxergar o total, muita loja descobre que tem mais dinheiro na rua do que no banco."),
    ),
    sec("Etapa 5 — Só então olhe os números",
      p("Com produto cadastrado, venda registrada, caixa fechado e fiado no sistema, os relatórios passam a significar alguma coisa. Aí vale calcular <a href=\"/guias/como-calcular-lucro-da-loja/\">lucro</a> e <a href=\"/guias/como-calcular-margem-de-lucro/\">margem</a> e usar a curva ABC para decidir compras."),
    ),
    sec("Um cronograma realista",
      tabela(["Período", "Foco", "Resultado esperado"], [
        ["Semana 1", "Cadastro dos itens de maior giro", "Vendas já passam pelo sistema"],
        ["Semana 2", "Rotina de caixa e fechamento diário", "Caixa começa a bater"],
        ["Semana 3", "Fiado em aberto lançado", "Total a receber visível"],
        ["Semana 4", "Conferência de estoque dos itens A", "Estoque confiável no que importa"],
        ["Mês 2", "Leitura de margem e curva ABC", "Decisão de compra com base em dado"],
      ]),
      p("O período de teste de 7 dias cobre bem a primeira etapa — o suficiente para você saber se o sistema faz sentido antes de pagar."),
    ),
    sec("O que costuma dar errado",
      ul("Tentar cadastrar tudo antes de começar a usar.",
         "Deixar uma parte das vendas fora do registro.",
         "Adiar o fechamento de caixa para “quando sobrar tempo”.",
         "Cadastrar preço e esquecer o custo.",
         "Trocar de método no meio do caminho."),
      FONTE,
    ),
  ],
  faq=[
    ("Por onde eu começo?",
     "Pelo cadastro dos produtos de maior giro e por fazer toda venda passar pelo mesmo lugar. Sem esses dois, nenhuma outra etapa se sustenta."),
    ("Quanto tempo leva para organizar uma loja?",
     "Com foco em uma etapa por semana, cerca de um mês para ter uma base confiável. Tentar fazer tudo de uma vez costuma terminar em desistência."),
    ("Preciso parar a loja para organizar?",
     "Não. O método é justamente ir cadastrando e registrando durante o funcionamento normal, começando pelo que gira mais."),
    ("Dá para fazer isso em planilha?",
     "Dá para começar, mas a planilha depende de alguém lembrar de dar baixa depois da venda — e é aí que o controle se perde conforme o volume cresce."),
    ("O teste de 7 dias dá tempo?",
     "Dá para cobrir a primeira etapa: cadastrar os itens de maior giro e passar as vendas pelo PDV. É o suficiente para avaliar se faz sentido."),
  ],
  cta_title="Comece pela etapa 1 hoje",
  cta_text="Cadastre os produtos que você vende toda semana e passe as vendas do dia pelo sistema.",
  related=[("Como controlar estoque", "/guias/como-controlar-estoque/", "Etapa do estoque"),
           ("Como controlar o caixa", "/guias/como-controlar-caixa-da-loja/", "Rotina diária"),
           ("Pequeno comércio", "/segmentos/pequeno-comercio/", "Para lojas pequenas")],
),

dict(
  artigo=True,
  slug="guias/como-sair-do-caderno",
  passos=[
    ('Cadastre os produtos de giro', 'Comece pelos itens que você vende toda semana, com preço, custo e categoria.', 'o-passo-a-passo-em-uma-semana'),
    ('Registre as quantidades', 'Conte esses itens e registre a quantidade real em estoque.', 'o-passo-a-passo-em-uma-semana'),
    ('Comece a vender pelo sistema', 'A partir daqui toda venda passa pelo PDV — é a virada de chave.', 'o-passo-a-passo-em-uma-semana'),
    ('Traga clientes e fiado', 'Cadastre quem tem saldo em aberto e lance o valor como venda fiada.', 'o-passo-a-passo-em-uma-semana'),
    ('Estabeleça a rotina de caixa', 'Fundo de troco, formas de pagamento e fechamento no fim do dia.', 'o-passo-a-passo-em-uma-semana'),
    ('Confira', 'O estoque bate? O caixa fecha? Ajuste o que estiver fora antes de seguir.', 'o-passo-a-passo-em-uma-semana'),
  ],
  figura=("/assets/lojistas/papelaria.webp",
          "Atendente registrando a venda no sistema, no lugar do caderno"),
  title="Como Sair do Caderno e Controlar a Loja em Sistema | SoftPay",
  description="Passo a passo para migrar do caderno ou da planilha para um sistema de gestão sem parar a loja: o que levar, em que ordem e o que fazer com o caderno antigo.",
  h1="Como sair do caderno",
  intro="Resposta curta: não transcreva o caderno inteiro. Leve o que ainda está vivo — estoque atual, fiado em aberto e clientes — e comece a registrar as vendas novas no sistema desde o primeiro dia.",
  breadcrumbs=_c("Como sair do caderno"),
  blocks=[
    sec("Por que a migração costuma travar",
      p("Quase todo mundo tenta começar transcrevendo tudo: meses de vendas passadas, todos os produtos, o caderno inteiro. É um trabalho enorme, sem retorno imediato, feito nas horas vagas — e por isso é abandonado no meio."),
      p("Venda passada não muda nada na sua decisão de amanhã. O que importa migrar é o que ainda está em aberto."),
    ),
    sec("O que levar (e o que deixar para trás)",
      tabela(["Levar", "Por quê"], [
        ["Estoque atual dos itens de giro", "É o que decide reposição"],
        ["Fiado em aberto", "É dinheiro a receber"],
        ["Clientes com quem você tem relação", "Base de recompra e fiado"],
        ["Custo dos produtos", "Sem ele não há margem"],
      ]),
      tabela(["Deixar no caderno", "Por quê"], [
        ["Vendas de meses anteriores", "Não muda decisão futura"],
        ["Fiado já quitado", "Encerrado"],
        ["Produtos que você não vende mais", "Só polui o cadastro"],
      ]),
    ),
    sec("O passo a passo, em uma semana",
      ol("<strong>Dia 1 — Produtos de giro.</strong> Cadastre os itens que você vende toda semana, com preço, custo e categoria.",
         "<strong>Dia 2 — Quantidades.</strong> Conte esses itens e registre a quantidade real.",
         "<strong>Dia 3 — Comece a vender pelo sistema.</strong> A partir daqui, toda venda passa pelo PDV. É a virada de chave.",
         "<strong>Dia 4 — Clientes e fiado.</strong> Cadastre quem tem saldo em aberto e lance o valor como venda fiada.",
         "<strong>Dia 5 — Rotina de caixa.</strong> Fundo de troco, formas de pagamento e fechamento no fim do dia.",
         "<strong>Dias 6 e 7 — Conferência.</strong> O estoque bate? O caixa fecha? Ajuste o que estiver fora antes de seguir."),
      nota("Repare que a venda pelo sistema começa no dia 3, não no fim. Registrar as vendas novas é o que dá retorno imediato e mantém a motivação — o cadastro do restante vai acontecendo em paralelo.", "A ordem não é acidental"),
    ),
    sec("Não jogue o caderno fora",
      p("Mantenha o caderno por algumas semanas, em paralelo, até ter confiança de que o sistema está com tudo. Ele é a sua rede de segurança durante a transição — e a referência para conferir qualquer divergência de fiado."),
    ),
    sec("O que muda depois",
      ul("Você passa a saber o total do fiado em aberto, não só quem deve.",
         "O estoque acompanha a venda sem alguém lembrar de dar baixa.",
         "O caixa fecha no mesmo dia, com a diferença ainda explicável.",
         "A margem por produto deixa de ser média e vira número.",
         "Mais de uma pessoa consegue operar a loja sem depender da sua memória."),
      FONTE,
    ),
  ],
  faq=[
    ("Preciso transcrever todo o caderno?",
     "Não. Leve apenas o que está em aberto: estoque atual dos itens de giro, fiado a receber e clientes. Vendas passadas não mudam decisões futuras."),
    ("Vou precisar parar a loja?",
     "Não. A migração acontece durante o funcionamento normal, começando pelos produtos de maior giro."),
    ("Quanto tempo leva?",
     "Uma semana costuma bastar para ter a base funcionando, com as vendas já passando pelo sistema a partir do terceiro dia."),
    ("Posso importar de uma planilha?",
     "A importação de dados está disponível a partir do plano Loja. Fale com o suporte antes para conferir o formato do arquivo."),
    ("E se eu não conseguir sozinho?",
     "O suporte do SoftPay é humano e atende pelo WhatsApp, inclusive na configuração inicial."),
  ],
  cta_title="Faça a virada nesta semana",
  cta_text="Sete dias de teste é exatamente o tempo do roteiro acima. Sem cartão de crédito.",
  related=[("Como organizar uma loja", "/guias/como-organizar-uma-loja/", "O roteiro completo"),
           ("Caderno ou sistema?", "/perguntas/caderno-ou-sistema/", "A comparação"),
           ("Como controlar fiado", "/guias/como-controlar-fiado/", "Levar o fiado junto")],
),

# ============================================================ CONTEÚDO DE DECISÃO
# Estas três páginas falam com quem AINDA NÃO decidiu ter um sistema. As demais
# falam com quem já decidiu e está escolhendo qual. É a etapa anterior do funil,
# e é onde o site não tinha nada.

dict(
  artigo=True,
  slug="guias/vale-a-pena-ter-sistema-de-gestao",
  title="Vale a Pena Ter um Sistema de Gestão na Loja? | SoftPay",
  description="A resposta honesta: depende do tamanho da sua loja e de quantas vendas você faz por dia. Veja quando compensa, quando não compensa e como fazer a conta.",
  h1="Vale a pena ter um sistema de gestão na loja?",
  intro="Resposta curta e honesta: depende de quantas vendas você faz por dia e de quanto dinheiro está parado em estoque. Abaixo de um certo movimento, caderno resolve. Acima dele, o caderno começa a custar mais caro que o sistema — e esta página mostra como descobrir de que lado você está.",
  breadcrumbs=_c("Vale a pena ter sistema de gestão"),
  blocks=[
    sec("Quando NÃO vale a pena",
      p("Começando pelo lado que quase nenhum site de sistema escreve, porque não é do interesse de quem vende:"),
      ul("<strong>Você faz menos de 5 a 10 vendas por dia.</strong> Nesse volume, um caderno bem feito dá conta. O sistema vai custar tempo de cadastro sem devolver informação que você já não saiba de cabeça.",
         "<strong>Você tem menos de 30 ou 40 produtos.</strong> Dá para saber o estoque olhando a prateleira. O ganho de um sistema aparece quando a memória não alcança mais.",
         "<strong>Você não vende fiado e recebe tudo à vista.</strong> Some o maior motivo isolado para sair do papel.",
         "<strong>Você está começando agora e ainda testa o que vender.</strong> Primeiro descubra se o negócio se sustenta; a organização vem depois.",
         "<strong>Você não tem internet estável no ponto.</strong> O SoftPay é web e depende de conexão. Sem internet confiável, a experiência vai ser ruim — e é melhor saber antes."),
      nota("Se três ou mais dos itens acima descrevem a sua loja, <strong>não contrate sistema nenhum agora</strong> — nem o SoftPay. Volte quando o movimento crescer. Vender para quem ainda não precisa gera cancelamento em dois meses, e isso não interessa a ninguém.", "Sendo direto"),
    ),
    sec("Quando passa a valer",
      p("O ponto de virada quase nunca é o faturamento. São estes cinco sinais:"),
      ul("<strong>Você já perdeu venda por não saber se tinha o produto.</strong> O cliente perguntou, alguém foi olhar, não achou. Isso é dinheiro que saiu pela porta.",
         "<strong>Mais de uma pessoa mexe no caixa ou no estoque.</strong> No momento em que o controle deixa de estar na cabeça de uma pessoa só, ele precisa estar escrito em algum lugar que todos leiam.",
         "<strong>Você não sabe quanto sobrou no fim do mês.</strong> Sabe quanto entrou — todo mundo sabe. Quanto sobrou depois do custo da mercadoria é outra pergunta, e é a que decide o negócio.",
         "<strong>O fiado passou de umas poucas pessoas.</strong> Quando o caderno de fiado tem mais de dez nomes ativos, alguém vai ser esquecido.",
         "<strong>Você repõe mercadoria por intuição.</strong> Compra o que acha que vende, e descobre no inventário que comprou errado."),
      p("Dois desses sinais já justificam testar. Três ou mais e o caderno provavelmente já está custando mais caro que qualquer mensalidade."),
    ),
    sec("A conta que ninguém faz",
      p("A pergunta “vale a pena?” costuma ser feita comparando a mensalidade com zero. Mas o caderno também tem custo — ele só não vem com boleto."),
      exemplo("O que o descontrole custa por mês numa loja média", [
        ("Venda perdida por falta do produto (2 por semana, ticket R$ 60)", "R$ 480,00", "minus"),
        ("Fiado esquecido ou não cobrado", "R$ 250,00", "minus"),
        ("Compra errada: mercadoria que encalha", "R$ 300,00", "minus"),
        ("Diferença de caixa sem explicação", "R$ 120,00", "minus"),
        ("= Custo mensal de não ter controle", "R$ 1.150,00", "result final"),
      ], "Números ilustrativos, para mostrar o raciocínio — não são promessa de resultado. Faça a sua própria conta com os seus números: o valor exato importa menos que perceber que <strong>a coluna existe</strong>. Se der R$ 200, um sistema de R$ 69 ainda não se paga. Se der R$ 800, a conta já virou."),
      p("O critério prático: <strong>se o descontrole custa mais do que a mensalidade, vale. Se custa menos, não vale ainda.</strong> É simples assim, e a única pessoa que pode fazer essa conta é você."),
    ),
    sec("O que um sistema resolve de verdade — e o que não resolve",
      h3("Resolve"),
      ul("Saber o que tem em estoque sem ir olhar",
         "Saber quem deve fiado, quanto e desde quando",
         "Fechar o caixa no mesmo dia, com a diferença ainda explicável",
         "Saber a margem real depois do custo da mercadoria",
         "Permitir que outra pessoa opere a loja sem depender da sua memória"),
      h3("Não resolve"),
      ul("<strong>Não traz cliente.</strong> Sistema organiza o que já acontece; quem traz cliente é preço, ponto, atendimento e divulgação.",
         "<strong>Não aumenta a margem sozinho.</strong> Ele mostra a margem. Melhorá-la continua sendo decisão sua de compra e de preço.",
         "<strong>Não funciona se ninguém alimentar.</strong> Venda que não passa pelo sistema é venda que não existe para ele — e um sistema pela metade é pior que um caderno inteiro.",
         "<strong>Não substitui contador.</strong> Obrigação fiscal continua sendo assunto do seu contador."),
    ),
    sec("Quanto custa, na prática",
      p("Para um pequeno comércio no Brasil, a faixa de mercado em 2026 vai de cerca de R$ 39 a R$ 199 por mês, dependendo do que está incluso e de quantos usuários. Os preços do SoftPay:"),
      tabela(["Plano", "Preço", "Para quem"], [
        ["Nota Fiscal", "R$ 65/mês", "Só emissão de notas, sem PDV nem estoque"],
        ["Comércio", "R$ 69/mês", "PDV, caixa, fiado e estoque essencial — 1 usuário"],
        ["Loja", "R$ 89/mês", "Variações, curva ABC, cobrança por Pix e loja online — até 3 usuários"],
        ["ERP Completo", "R$ 109/mês", "Emissão de NF-e e NFC-e, equipe maior — até 10 usuários"],
      ]),
      p("Todos com 7 dias grátis, sem cartão de crédito. A comparação com outros sistemas está no guia <a href=\"/guias/quanto-custa-um-sistema-de-gestao/\">quanto custa um sistema de gestão</a>."),
    ),
    sec("Como decidir sem arriscar dinheiro",
      ol("<strong>Faça a conta do descontrole</strong> com os seus números, usando o exemplo acima. Cinco minutos.",
         "<strong>Se a conta justificar, teste antes de pagar.</strong> Procure sistema com teste grátis sem cartão — se pedem cartão para testar, você já começou a pagar.",
         "<strong>No teste, cadastre só os 20 produtos que mais vendem.</strong> Não tente cadastrar tudo; você vai desistir no meio.",
         "<strong>Passe as vendas de dois dias inteiros pelo sistema.</strong> É o único jeito de saber se ele é rápido o bastante para o seu balcão.",
         "<strong>No fim, faça uma pergunta:</strong> “o que eu passei a saber que não sabia antes?”. Se a resposta for nada, não contrate."),
    ),
  ],
  faq=[
    ("Vale a pena para uma loja muito pequena, de uma pessoa só?",
     "Depende do movimento, não do tamanho. Se você faz menos de 5 a 10 vendas por dia e tem poucos produtos, o caderno ainda resolve. Se já perdeu venda por não saber o estoque ou tem fiado com mais de dez pessoas, passa a valer."),
    ("Quanto custa um sistema de gestão para comércio pequeno?",
     "A faixa de mercado no Brasil em 2026 vai de cerca de R$ 39 a R$ 199 por mês. O SoftPay vai de R$ 65 a R$ 109, dependendo do plano, com 7 dias grátis e sem cartão."),
    ("Dá para usar planilha em vez de sistema?",
     "Dá, e por um tempo funciona. A planilha quebra quando mais de uma pessoa precisa usar ao mesmo tempo, quando a venda e a baixa de estoque viram duas etapas separadas e quando não há trava contra o dado errado. Veja a comparação em Excel ou sistema de gestão."),
    ("Preciso ter internet o tempo todo?",
     "Sim. O SoftPay roda no navegador e depende de conexão. Se a internet do seu ponto é instável, leve isso em conta antes de contratar."),
    ("Quanto tempo até o sistema começar a ajudar?",
     "Do primeiro dia, se você cadastrar os produtos de maior giro e passar as vendas por ele. O que leva semanas é ter a base completa — e não é necessário esperar isso para começar a se beneficiar."),
    ("E se eu contratar e não usar?",
     "É o risco real, e o mais comum. Um sistema pela metade é pior que um caderno inteiro. Por isso o teste de 7 dias existe: se você não conseguiu passar as vendas de dois dias por ele durante o teste, provavelmente não vai passar depois."),
    ("Sistema de gestão aumenta as vendas?",
     "Não diretamente. Ele evita perdas — venda perdida por falta de produto, fiado não cobrado, compra errada. Quem aumenta venda é preço, atendimento, ponto e divulgação."),
  ],
  cta_title="Faça a conta antes de decidir",
  cta_text="Se o descontrole custa mais que R$ 69 por mês na sua loja, o teste de 7 dias responde o resto. Sem cartão de crédito.",
  related=[("Quanto custa um sistema", "/guias/quanto-custa-um-sistema-de-gestao/", "Faixa de mercado e comparação"),
           ("Como escolher um sistema", "/guias/como-escolher-sistema-de-gestao/", "Os 7 critérios que importam"),
           ("Caderno ou sistema?", "/perguntas/caderno-ou-sistema/", "A comparação direta"),
           ("Como sair do caderno", "/guias/como-sair-do-caderno/", "O roteiro da migração"),
           ("Excel ou sistema?", "/perguntas/excel-ou-sistema-de-gestao/", "Quando a planilha quebra"),
           ("Loja pequena precisa?", "/perguntas/loja-pequena-precisa-de-sistema/", "A pergunta por tamanho")],
),

dict(
  artigo=True,
  slug="guias/quanto-custa-um-sistema-de-gestao",
  title="Quanto Custa um Sistema de Gestão para Comércio em 2026 | SoftPay",
  description="Faixa real de preço de sistema de gestão para pequeno comércio no Brasil, o que costuma vir escondido na conta e como comparar planos sem se enganar.",
  h1="Quanto custa um sistema de gestão para comércio",
  intro="A faixa de mercado para pequeno comércio no Brasil, em 2026, vai de cerca de R$ 39 a R$ 199 por mês. Mas o preço da tabela é só parte da conta — e esta página mostra as partes que costumam aparecer depois da contratação.",
  breadcrumbs=_c("Quanto custa um sistema de gestão"),
  blocks=[
    sec("A faixa de preço, sem rodeio",
      p("Sistemas de gestão para pequeno comércio no Brasil se concentram em três faixas:"),
      tabela(["Faixa", "Preço mensal", "O que costuma vir"], [
        ["Entrada", "R$ 39 a R$ 69", "PDV e estoque básico, 1 usuário. Às vezes sem emissão fiscal"],
        ["Intermediária", "R$ 70 a R$ 120", "Estoque com variações, relatórios melhores, 2 a 3 usuários, emissão fiscal"],
        ["Completa", "R$ 120 a R$ 300+", "Multi-loja, integrações, equipe maior, às vezes com implantação cobrada à parte"],
      ]),
      p("Onde o SoftPay fica: <strong>R$ 65 a R$ 109</strong>, entre a entrada e a intermediária, com 7 dias grátis e sem cartão."),
    ),
    sec("O que costuma não estar no preço anunciado",
      p("Esta é a parte que muda a conta, e quase nunca aparece na página de preços:"),
      ul("<strong>Taxa de implantação.</strong> Alguns sistemas cobram uma entrada única de R$ 200 a R$ 1.000 para configurar. O SoftPay não cobra.",
         "<strong>Preço por usuário.</strong> Muitos cobram por pessoa que acessa. Uma loja com três funcionários pode triplicar a conta sem mudar de plano.",
         "<strong>Fidelidade de 12 meses.</strong> O preço baixo às vezes é do plano anual; no mensal, é outro. E sair antes tem multa.",
         "<strong>Módulo vendido à parte.</strong> Emissão fiscal, loja online ou app de celular como cobrança adicional.",
         "<strong>Reajuste no segundo ano.</strong> Preço promocional no primeiro ano e valor cheio depois.",
         "<strong>Suporte pago.</strong> Em alguns, o atendimento humano é plano à parte."),
      nota("Ao comparar, pergunte sempre estas quatro coisas: <strong>tem taxa de implantação? cobra por usuário? tem fidelidade? o preço é o mesmo no segundo ano?</strong> As respostas mudam a conta mais que a diferença de mensalidade entre um sistema e outro.", "As quatro perguntas que revelam o preço real"),
    ),
    sec("Comparação de preços públicos",
      p("Valores de tabela consultados diretamente nos sites em setembro de 2026. Preço muda — confirme na fonte antes de decidir:"),
      tabela(["Sistema", "Faixa mensal (tabela pública)", "Teste grátis"], [
        ["Nex (Nextar)", "R$ 39 a R$ 169", "sim"],
        ["<strong>SoftPay</strong>", "<strong>R$ 65 a R$ 109</strong>", "<strong>7 dias, sem cartão</strong>"],
        ["Kyte", "R$ 49,90 a R$ 99,90", "7 dias"],
        ["GestãoClick", "R$ 119 a R$ 379", "10 dias"],
      ]),
      p("Duas observações honestas sobre esta tabela. Primeira: <strong>o mais barato nem sempre é o mais barato</strong> — o que decide é o que está incluso e quantos usuários você precisa. Segunda: cada um desses sistemas atende melhor a um perfil diferente, e a comparação de preço sozinha não diz qual serve para você. Para isso, veja <a href=\"/guias/como-escolher-sistema-de-gestao/\">como escolher um sistema de gestão</a>."),
    ),
    sec("Quanto custa não ter sistema",
      p("A comparação justa não é entre a mensalidade e zero — é entre a mensalidade e o que o descontrole custa:"),
      exemplo("Numa loja com movimento médio", [
        ("Venda perdida por falta de produto", "R$ 480,00", "minus"),
        ("Fiado esquecido", "R$ 250,00", "minus"),
        ("Mercadoria que encalhou", "R$ 300,00", "minus"),
        ("= Por mês", "R$ 1.030,00", "result final"),
      ], "Números ilustrativos. Faça com os seus: se o resultado for menor que a mensalidade, ainda não é hora de contratar."),
    ),
    sec("Como comparar dois sistemas sem se enganar",
      ol("<strong>Some o custo de 12 meses</strong>, não a mensalidade. Inclua implantação e o valor do segundo ano.",
         "<strong>Conte quantas pessoas vão acessar</strong> e verifique se há cobrança por usuário.",
         "<strong>Liste os 3 recursos que você realmente vai usar.</strong> Não pague por módulo que não vai abrir.",
         "<strong>Teste os dois na mesma semana</strong>, com os mesmos produtos, passando vendas de verdade.",
         "<strong>Ligue para o suporte durante o teste.</strong> É a hora em que você descobre como será atendido depois de assinar."),
    ),
  ],
  faq=[
    ("Quanto custa um sistema de gestão para uma loja pequena?",
     "A faixa de mercado no Brasil em 2026 vai de cerca de R$ 39 a R$ 199 por mês para pequeno comércio. O SoftPay fica entre R$ 65 e R$ 109, com 7 dias grátis e sem cartão de crédito."),
    ("Existe sistema de gestão gratuito?",
     "Existem versões gratuitas, quase sempre com limite de produtos, de vendas ou sem emissão fiscal. Costumam servir para começar; a conta aparece quando o negócio cresce. Vale ler o limite antes de investir tempo cadastrando."),
    ("O SoftPay cobra taxa de implantação?",
     "Não. Não há taxa de implantação nem contrato de fidelidade."),
    ("O preço muda conforme o número de usuários?",
     "No SoftPay o número de usuários está incluído no plano: 1 no Comércio, até 3 no Loja e até 10 no ERP Completo. Não há cobrança por usuário adicional dentro desses limites."),
    ("O preço do primeiro ano é o mesmo do segundo?",
     "No SoftPay, sim — não há preço promocional de primeiro ano que sobe depois. É uma pergunta que vale fazer a qualquer sistema que você avaliar."),
    ("Vale mais a pena o plano anual?",
     "Depende de quanto você tem de certeza. Plano anual costuma sair mais barato, mas prende. Se é a sua primeira experiência com sistema, comece no mensal."),
    ("Preciso pagar para testar?",
     "No SoftPay, não: são 7 dias grátis sem cartão de crédito. Se um sistema pede cartão para testar, você já começou a pagar — leve isso em conta."),
  ],
  cta_title="Compare com os seus números",
  cta_text="Sete dias grátis, sem cartão, sem implantação e sem fidelidade. O preço da tabela é o preço.",
  related=[("Vale a pena ter sistema?", "/guias/vale-a-pena-ter-sistema-de-gestao/", "Antes do preço, a decisão"),
           ("Como escolher um sistema", "/guias/como-escolher-sistema-de-gestao/", "Os 7 critérios"),
           ("Quanto custa para loja", "/perguntas/quanto-custa-um-sistema-para-loja/", "A resposta curta"),
           ("Como calcular margem", "/guias/como-calcular-margem-de-lucro/", "Para saber o que cabe"),
           ("Planos do SoftPay", "/#pricing", "Os quatro planos"),
           ("Caderno ou sistema?", "/perguntas/caderno-ou-sistema/", "A comparação")],
),

dict(
  artigo=True,
  slug="guias/como-escolher-sistema-de-gestao",
  passos=[
    ('Escreva os três problemas que você quer resolver', 'Antes de olhar qualquer sistema, defina o que precisa mudar na sua loja. Sem isso você compra por lista de recursos.', 'passo-1-escreva-os-tres-problemas-que-voce-quer-resolver'),
    ('Descarte o que não atende o seu tipo de negócio', 'Comércio com estoque, serviço com agenda e restaurante com comanda são três produtos diferentes.', 'passo-2-descarte-o-que-nao-atende-o-seu-tipo-de-negocio'),
    ('Verifique o preço real, não o anunciado', 'Implantação, cobrança por usuário, fidelidade e valor do segundo ano.', 'passo-3-verifique-o-preco-real-nao-o-anunciado'),
    ('Teste com dados de verdade', 'Cadastre os 20 produtos de maior giro e passe as vendas de dois dias inteiros.', 'passo-4-teste-com-dados-de-verdade'),
    ('Ligue para o suporte durante o teste', 'É quando você descobre como será atendido depois de assinar.', 'passo-5-ligue-para-o-suporte-durante-o-teste'),
    ('Confirme como você sai', 'Exportação dos dados e cancelamento. Perguntar antes evita ficar preso depois.', 'passo-6-confirme-como-voce-sai'),
  ],
  title="Como Escolher um Sistema de Gestão: 7 Critérios | SoftPay",
  description="Guia para escolher sistema de gestão sem se arrepender: os 7 critérios que importam, as perguntas a fazer antes de assinar e os sinais de alerta.",
  h1="Como escolher um sistema de gestão",
  intro="A maioria das escolhas ruins tem a mesma origem: comparar listas de recursos em vez de partir dos problemas da própria loja. Este guia inverte a ordem — primeiro o que você precisa resolver, depois qual sistema resolve.",
  breadcrumbs=_c("Como escolher um sistema de gestão"),
  blocks=[
    sec("Passo 1 — Escreva os três problemas que você quer resolver",
      p("Antes de abrir o site de qualquer sistema, escreva num papel os três problemas concretos da sua loja. Não “melhorar a gestão” — algo específico:"),
      ul("“Não sei quanto tenho de cada produto.”",
         "“O fiado está num caderno que só eu leio.”",
         "“Não sei quanto sobrou no fim do mês.”"),
      p("Esses três viram o seu critério de decisão. Recurso que não atende nenhum deles é irrelevante para você, por mais impressionante que pareça na página de vendas."),
      nota("Comprar por lista de recursos é o erro mais caro. Sistema com 200 funcionalidades das quais você usa 4 custa mais, demora mais para aprender e tem mais lugares para errar. O melhor sistema é o que resolve os seus três problemas com o mínimo de estrada.", "O erro mais comum"),
    ),
    sec("Passo 2 — Descarte o que não atende o seu tipo de negócio",
      p("Antes de comparar preço, elimine os que não foram feitos para o seu caso. São três famílias diferentes de produto, e misturá-las é fonte de frustração:"),
      tabela(["Seu negócio", "O que você precisa", "Cuidado"], [
        ["Comércio com estoque", "PDV, estoque, custo, fiado", "É o caso do SoftPay"],
        ["Serviço com hora marcada", "Agenda, ficha do cliente, comanda", "Sistema de loja não tem agenda"],
        ["Restaurante, bar, delivery", "Comanda de mesa, ficha de pedido, integração de delivery", "Sistema de loja não tem comanda"],
      ]),
      p("Se você faz as duas coisas — vende produto <em>e</em> presta serviço com hora marcada —, decida qual das duas move mais dinheiro e escolha por ela."),
    ),
    sec("Passo 3 — Verifique o preço real, não o anunciado",
      p("Quatro perguntas mudam a conta mais que a diferença de mensalidade:"),
      ol("Tem taxa de implantação?",
         "Cobra por usuário que acessa?",
         "Tem fidelidade? Qual a multa por sair antes?",
         "O preço do segundo ano é o mesmo?"),
      p("Detalhe: some o custo de <strong>12 meses</strong>, não da mensalidade. O detalhamento está em <a href=\"/guias/quanto-custa-um-sistema-de-gestao/\">quanto custa um sistema de gestão</a>."),
    ),
    sec("Passo 4 — Teste com dados de verdade",
      p("Teste grátis só serve se for usado a sério. O roteiro que funciona:"),
      ol("Cadastre os <strong>20 produtos que mais vendem</strong> — não tente cadastrar tudo, você desiste no meio.",
         "Passe as vendas de <strong>dois dias inteiros</strong> pelo sistema, incluindo as fiadas e as do horário de pico.",
         "Faça o <strong>fechamento de caixa</strong> nos dois dias e veja se bate.",
         "Peça para <strong>outra pessoa da loja</strong> registrar uma venda sem você ensinar. Se ela não conseguir, o sistema é complicado demais para o seu time.",
         "No fim, responda: <strong>“o que eu passei a saber que não sabia antes?”</strong>"),
      nota("Se o sistema exige cartão de crédito para começar o teste, você não está testando — está assinando com prazo para desistir. Não é a mesma coisa, e a diferença aparece na hora de cancelar.", "Teste com cartão não é teste"),
    ),
    sec("Passo 5 — Ligue para o suporte durante o teste",
      p("Este é o critério mais subestimado e o que mais dói depois. Durante o teste, mande uma dúvida real pelo canal de atendimento e observe três coisas: <strong>quanto tempo demora</strong>, <strong>se responde uma pessoa ou um robô</strong> e <strong>se a resposta resolve ou empurra para uma central de ajuda</strong>."),
      p("O suporte que você recebe como cliente em teste é o melhor que ele será. Depois de assinar, não melhora."),
    ),
    sec("Passo 6 — Confirme como você sai",
      p("Pergunte antes de entrar: <strong>como cancelo e como levo meus dados embora?</strong> Um sistema que dificulta a saída está apostando na dificuldade, não na qualidade."),
      ul("O cancelamento é feito por onde? Tem multa?",
         "Consigo exportar produtos, clientes e vendas?",
         "Em que formato saem os dados?"),
    ),
    sec("Os 7 critérios, em uma lista",
      p("Resumo para levar na comparação:"),
      ul("<strong>1. Resolve os seus três problemas?</strong> Não os 200 recursos dele.",
         "<strong>2. É do tipo certo?</strong> Loja, serviço e restaurante são produtos diferentes.",
         "<strong>3. O preço real de 12 meses cabe?</strong> Com implantação, usuários e segundo ano.",
         "<strong>4. Sua equipe consegue usar?</strong> Teste com outra pessoa, não só com você.",
         "<strong>5. É rápido no horário de pico?</strong> Teste no movimento, não no domingo à noite.",
         "<strong>6. O suporte responde?</strong> Ligue durante o teste.",
         "<strong>7. Dá para sair?</strong> Cancelamento e exportação de dados."),
    ),
    sec("Sinais de alerta",
      ul("<strong>Não mostra preço no site.</strong> “Fale com um consultor” costuma significar que o preço varia conforme o que acharem que você pode pagar.",
         "<strong>Exige cartão para testar.</strong> Ver acima.",
         "<strong>Contrato de fidelidade longo logo na entrada.</strong> Quem confia no produto não precisa prender o cliente.",
         "<strong>Promete aumento de faturamento.</strong> Sistema evita perda; quem aumenta venda é preço, ponto e atendimento. Promessa de lucro é sinal de vendedor, não de produto.",
         "<strong>Não diz o que não faz.</strong> Todo sistema tem limite. Quem não conta o dele antes, conta depois da assinatura."),
    ),
  ],
  faq=[
    ("Qual o melhor sistema de gestão para pequeno comércio?",
     "Não existe um melhor para todos. Existe o que resolve os seus três problemas específicos, do tipo certo para o seu negócio, com preço real de 12 meses que cabe e suporte que responde. Este guia é o roteiro para chegar a essa resposta."),
    ("Quantos sistemas devo testar antes de decidir?",
     "Dois ou três, na mesma semana, com os mesmos produtos e as mesmas vendas. Testar em semanas diferentes atrapalha a comparação, porque o movimento da loja muda."),
    ("Sistema mais caro é melhor?",
     "Não necessariamente. Preço maior costuma significar mais recursos, e recurso que você não usa é custo sem retorno. O que importa é a cobertura dos seus três problemas."),
    ("Como sei se minha equipe vai conseguir usar?",
     "Peça para outra pessoa da loja registrar uma venda durante o teste, sem você ensinar. Se ela não conseguir sozinha, o sistema é complicado demais para o seu time."),
    ("Devo escolher pelo que já usei antes?",
     "Familiaridade ajuda, mas não é critério. Um sistema que você conhece e não resolve seus problemas continua não resolvendo."),
    ("E se eu escolher errado?",
     "Por isso os passos 3 e 6 existem: sem fidelidade e com exportação de dados, trocar custa tempo, não dinheiro. Com fidelidade de 12 meses, o erro fica caro."),
    ("Preciso de um sistema com emissão fiscal?",
     "Depende do seu regime — confirme com o seu contador. Muitos pequenos comércios não emitem nota em toda venda, e nesse caso pagar por emissão fiscal é custo sem uso."),
  ],
  cta_title="Teste o SoftPay com esse roteiro",
  cta_text="Cadastre 20 produtos, passe dois dias de vendas e ligue para o suporte. 7 dias grátis, sem cartão de crédito.",
  related=[("Vale a pena ter sistema?", "/guias/vale-a-pena-ter-sistema-de-gestao/", "A decisão antes da escolha"),
           ("Quanto custa um sistema", "/guias/quanto-custa-um-sistema-de-gestao/", "Preço real e comparação"),
           ("Como sair do caderno", "/guias/como-sair-do-caderno/", "Depois de escolher"),
           ("É difícil aprender?", "/perguntas/e-dificil-aprender/", "A dúvida da equipe"),
           ("Posso migrar de outro sistema?", "/perguntas/posso-migrar-de-outro-sistema/", "Trocar de sistema"),
           ("Segmentos", "/segmentos/", "O SoftPay no seu tipo de loja")],
),

# ==================================================== REFORMA TRIBUTÁRIA (pilar)
dict(
  artigo=True,
  slug="guias/reforma-tributaria-comercio",
  title="Reforma Tributária no Comércio: O Que Muda e Quando | SoftPay",
  description="O que a reforma tributária muda para o pequeno comércio, com as datas oficiais: 3 de agosto de 2026 para o regime regular e 1º de janeiro de 2027 para o Simples Nacional e o MEI.",
  h1="Reforma tributária no comércio: o que muda e quando",
  intro="Duas datas resolvem a maior parte da dúvida. Se a sua empresa é do regime regular, a obrigação já começou em 3 de agosto de 2026. Se é do Simples Nacional ou MEI, ela começa em 1º de janeiro de 2027. Esta página explica o que muda na prática para quem tem loja, sem termo de contador.",
  breadcrumbs=_c("Reforma tributária no comércio"),
  blocks=[
    sec("As duas datas que importam para você",
      tabela(["Quem", "Desde quando", "O que passa a ser obrigatório"], [
        ["Regime regular (Lucro Real e Presumido)", "<strong>3 de agosto de 2026</strong>", "Destacar IBS e CBS no documento fiscal. Nota incompleta é rejeitada automaticamente"],
        ["Simples Nacional e MEI", "<strong>1º de janeiro de 2027</strong>", "Emitir documento fiscal com as informações de IBS e CBS"],
      ]),
      nota("Se você é do Simples Nacional ou MEI, <strong>nada mudou ainda</strong> — e é exatamente por isso que este é o momento de se preparar. Quem deixa para dezembro descobre o problema no dia em que a nota é recusada.", "Onde a maioria dos pequenos comércios está"),
    ),
    sec("O que é IBS e CBS, sem termo técnico",
      p("A reforma substitui cinco tributos — PIS, Cofins, IPI, ICMS e ISS — por dois:"),
      ul("<strong>CBS</strong> (Contribuição sobre Bens e Serviços), federal.",
         "<strong>IBS</strong> (Imposto sobre Bens e Serviços), estadual e municipal."),
      p("Para quem tem loja, a mudança visível não é a conta de imposto: é <strong>a nota fiscal</strong>. Ela passa a ter campos novos, que precisam vir preenchidos. Documento fiscal sem esses campos é rejeitado pelo sistema — não é multa depois, é a venda que não fecha na hora."),
      p("2026 é ano de transição, com alíquotas de teste baixas. O peso real do novo modelo vem depois, de forma escalonada até 2033."),
    ),
    sec("O que muda para quem tem loja pequena",
      h3("1. A nota fiscal ganha campos novos"),
      p("É a mudança que atinge todo mundo. O sistema que emite a sua nota precisa estar atualizado para preencher IBS e CBS. Sistema desatualizado deixa de emitir."),
      h3("2. Em 2027, o MEI passa a emitir nota em qualquer venda"),
      p("Inclusive para pessoa física. Para muitos MEI que hoje quase não emitem nota, essa é a mudança mais concreta da reforma — e a que mais exige preparação, porque muda a rotina do balcão, não só a papelada."),
      h3("3. O registro do que você vende deixa de ser opcional"),
      p("Quando toda venda gera documento fiscal, vender sem registrar deixa de ser possível. Quem já passa tudo por um sistema não sente diferença; quem anota no caderno vai sentir."),
      h3("4. O crédito de imposto muda a conta da compra"),
      p("O novo modelo permite abater o imposto pago na compra de mercadoria. Na prática, isso torna mais importante ter <strong>nota de entrada registrada</strong> — a compra sem nota passa a custar mais caro do que parece."),
    ),
    sec("O que NÃO muda",
      p("Vale dizer também o que ficou igual, porque circula muita informação errada:"),
      ul("<strong>Você não precisa trocar de computador.</strong> A exigência é sobre o documento fiscal, não sobre o equipamento da loja.",
         "<strong>O Simples Nacional não acabou.</strong> Ele continua existindo; em 2027 passa a existir a opção de recolher IBS e CBS por fora, se for vantajoso.",
         "<strong>Não há mudança de alíquota para o pequeno em 2026.</strong> Este ano é de teste.",
         "<strong>Você não precisa entender a reforma inteira.</strong> Precisa saber a sua data e ter um sistema que emita a nota no formato novo."),
    ),
    sec("Como se preparar, na prática",
      ol("<strong>Confirme o seu regime com o contador.</strong> Regime regular, Simples ou MEI — é isso que define a sua data.",
         "<strong>Pergunte ao seu sistema atual se ele já está adequado.</strong> Se a resposta demorar ou for vaga, é sinal de alerta.",
         "<strong>Comece a registrar as notas de entrada</strong> das compras de mercadoria, se ainda não faz.",
         "<strong>Se você é MEI e quase não emite nota, comece a emitir agora.</strong> Aprender a rotina com calma é melhor que aprender em janeiro, com a obrigação valendo.",
         "<strong>Não deixe para dezembro.</strong> Migrar sistema no mês da virada é a pior hora possível."),
      FONTE_REFORMA,
    ),
    sec("Onde o SoftPay entra",
      p("Sendo transparente sobre o que o sistema faz hoje: o SoftPay emite NF-e e NFC-e nos planos Nota Fiscal e ERP Completo, e <strong>a emissão fiscal consta como recurso em ativação</strong> — confirme a situação para o seu caso com o suporte antes de contratar contando com ela."),
      p("O que já está pronto e vale independentemente da reforma: registrar toda venda, controlar o estoque com custo e ter as notas de entrada organizadas. Esses três hábitos são o que a reforma vai exigir de qualquer forma, e são úteis mesmo que a sua data ainda esteja longe."),
      p("Veja também <a href=\"/guias/reforma-tributaria-mei/\">o que muda para o MEI</a> e <a href=\"/guias/meu-sistema-precisa-mudar-reforma-tributaria/\">se o seu sistema precisa mudar</a>."),
    ),
  ],
  faq=[
    ("Quando a reforma tributária começa a valer para o meu comércio?",
     "Depende do regime. Para empresas do regime regular (Lucro Real e Lucro Presumido), o destaque de IBS e CBS no documento fiscal é obrigatório desde 3 de agosto de 2026. Para o Simples Nacional e o MEI, a obrigação começa em 1º de janeiro de 2027."),
    ("O que acontece se a nota fiscal não tiver os campos de IBS e CBS?",
     "Ela é rejeitada automaticamente pelo sistema. Não é uma multa que chega depois: é a nota que não é emitida na hora da venda."),
    ("Preciso trocar meu sistema de gestão por causa da reforma?",
     "Não necessariamente — precisa de um sistema que emita o documento fiscal no formato novo. Se o seu atual será atualizado a tempo, ele serve. A pergunta a fazer ao fornecedor é direta: o sistema já emite nota com IBS e CBS destacados?"),
    ("Sou MEI. O que muda para mim?",
     "A partir de 1º de janeiro de 2027, a emissão de nota fiscal passa a ser obrigatória em qualquer venda, inclusive para pessoa física. Para quem hoje quase não emite nota, é a mudança mais concreta da reforma."),
    ("O Simples Nacional vai acabar?",
     "Não. O Simples continua existindo. A partir de 2027 passa a haver a opção de recolher IBS e CBS por fora do DAS, quando isso for mais vantajoso — é uma escolha, não uma obrigação."),
    ("A minha carga de imposto vai aumentar em 2026?",
     "2026 é ano de transição, com alíquotas de teste. As mudanças de fato na conta do imposto vêm de forma escalonada nos anos seguintes. Confirme o efeito no seu caso com o seu contador."),
    ("Preciso de contador para lidar com isso?",
     "Sim. Esta página explica o que muda na rotina da loja, mas o enquadramento do seu negócio e o cálculo do imposto são trabalho do contador."),
  ],
  cta_title="Organize a loja antes da virada",
  cta_text="Registrar toda venda, controlar o estoque com custo e guardar as notas de entrada é o que a reforma vai exigir de qualquer jeito. 7 dias grátis, sem cartão.",
  related=[("Reforma tributária e o MEI", "/guias/reforma-tributaria-mei/", "A obrigação de 2027"),
           ("Meu sistema precisa mudar?", "/guias/meu-sistema-precisa-mudar-reforma-tributaria/", "A pergunta prática"),
           ("Checklist até janeiro", "/guias/checklist-reforma-tributaria-2027/", "O que fazer, em ordem"),
           ("O que é NF-e e NFC-e", "/guias/nfe-nfce-o-que-e/", "A diferença entre as duas"),
           ("Emissão de NF-e", "/solucoes/nfe/", "O recurso no SoftPay"),
           ("Como sair do caderno", "/guias/como-sair-do-caderno/", "O primeiro passo")],
),

dict(
  artigo=True,
  slug="guias/reforma-tributaria-mei",
  title="Reforma Tributária e o MEI: Nota Fiscal Obrigatória em 2027 | SoftPay",
  description="A partir de 1º de janeiro de 2027 o MEI passa a emitir nota fiscal em qualquer venda, inclusive para pessoa física. Veja o que muda e como se preparar.",
  h1="Reforma tributária e o MEI",
  intro="A mudança mais concreta para o MEI tem data: 1º de janeiro de 2027. A partir dali, a emissão de nota fiscal passa a ser obrigatória em qualquer venda — inclusive para pessoa física. Para quem hoje quase não emite nota, isso muda a rotina do balcão, não só a papelada.",
  breadcrumbs=_c("Reforma tributária e o MEI"),
  blocks=[
    sec("O que muda, em uma frase",
      p("Hoje muitos MEI emitem nota apenas quando o cliente é empresa e pede. A partir de <strong>1º de janeiro de 2027</strong>, a nota passa a ser obrigatória em qualquer venda, para qualquer cliente."),
      nota("Faltam poucos meses. Não é uma mudança que se resolve em uma tarde de dezembro: é um hábito novo no balcão, e hábito leva semanas para pegar.", "Por que começar agora"),
    ),
    sec("O que isso significa no dia a dia",
      ul("<strong>Toda venda gera documento.</strong> A venda para o vizinho, a venda pequena, a venda em dinheiro — todas.",
         "<strong>O cadastro de produto deixa de ser opcional.</strong> Para emitir nota é preciso ter o produto cadastrado, com descrição e valor.",
         "<strong>O tempo do atendimento muda.</strong> Emitir nota leva segundos quando o produto está cadastrado, e leva minutos quando não está. No balcão cheio, essa diferença aparece.",
         "<strong>A compra sem nota passa a pesar.</strong> Com crédito de imposto no novo modelo, mercadoria comprada sem nota fica mais cara do que parece."),
    ),
    sec("O erro que vai custar caro",
      p("O erro previsível é deixar para dezembro de 2026. Três coisas dão errado ao mesmo tempo nesse cenário:"),
      ol("<strong>Você cadastra os produtos com pressa</strong>, e o cadastro fica ruim — descrição incompleta, preço errado, item faltando.",
         "<strong>Ninguém aprende a rotina antes.</strong> A primeira nota do ano é emitida com cliente esperando no balcão.",
         "<strong>O suporte de todo mundo está lotado</strong>, porque todo MEI do país deixou para a mesma semana."),
      p("Começar em setembro ou outubro custa o mesmo e evita os três."),
    ),
    sec("Como se preparar, em quatro passos",
      ol("<strong>Confirme com o seu contador</strong> que você é MEI e que a sua data é 1º de janeiro de 2027.",
         "<strong>Cadastre os produtos que mais vendem.</strong> Não precisa ser tudo: comece pelos de maior giro e complete conforme repõe.",
         "<strong>Comece a emitir nota agora</strong>, mesmo sem obrigação, em algumas vendas por dia. É assim que a rotina entra antes do prazo.",
         "<strong>Guarde as notas de entrada</strong> das compras de mercadoria."),
      FONTE_REFORMA,
    ),
    sec("O que o SoftPay faz e o que não faz aqui",
      p("Direto ao ponto: a emissão de NF-e e NFC-e está nos planos Nota Fiscal (R$ 65/mês) e ERP Completo (R$ 109/mês), e <strong>consta como recurso em ativação</strong> — confirme a situação para o seu caso com o suporte antes de contratar contando com ela."),
      p("O que o sistema resolve desde já, e que você vai precisar de qualquer forma: cadastro de produtos, registro de toda venda e controle das entradas de mercadoria. Esse é o trabalho que leva tempo, e é ele que dá para adiantar agora."),
    ),
  ],
  faq=[
    ("MEI vai ser obrigado a emitir nota fiscal?",
     "Sim, a partir de 1º de janeiro de 2027, em qualquer venda, inclusive para pessoa física. Até lá, a regra atual continua valendo."),
    ("O MEI vai acabar com a reforma tributária?",
     "Não. O MEI continua existindo. O que muda é a obrigação de emitir documento fiscal em todas as vendas a partir de 2027."),
    ("Preciso de um sistema para emitir nota como MEI?",
     "Você precisa de alguma forma de emitir o documento fiscal. Um sistema integrado ao PDV reduz o trabalho porque o produto já está cadastrado e a nota sai da própria venda, em vez de ser digitada de novo."),
    ("Quanto custa um sistema que emite nota?",
     "No SoftPay, o plano Nota Fiscal custa R$ 65/mês e o ERP Completo R$ 109/mês. A faixa de mercado para pequeno comércio vai de cerca de R$ 39 a R$ 199."),
    ("Posso continuar vendendo sem nota para pessoa física?",
     "Até 31 de dezembro de 2026, a regra atual continua. A partir de 1º de janeiro de 2027, a nota passa a ser obrigatória também nessas vendas."),
    ("O que acontece se eu não emitir?",
     "A falta de emissão fica sujeita às penalidades previstas. O detalhe do seu caso deve ser confirmado com o seu contador."),
    ("Preciso cadastrar todos os produtos antes de janeiro?",
     "Não todos de uma vez. Comece pelos de maior giro, que respondem pela maior parte das vendas, e complete o restante conforme repõe o estoque."),
  ],
  cta_title="Comece a rotina antes da obrigação",
  cta_text="Cadastre os produtos de maior giro e passe as vendas pelo sistema. Quando janeiro chegar, o trabalho já está feito. 7 dias grátis, sem cartão.",
  related=[("Reforma tributária no comércio", "/guias/reforma-tributaria-comercio/", "A visão completa"),
           ("Meu sistema precisa mudar?", "/guias/meu-sistema-precisa-mudar-reforma-tributaria/", "A pergunta prática"),
           ("Checklist até janeiro", "/guias/checklist-reforma-tributaria-2027/", "O que fazer, em ordem"),
           ("O que é NF-e e NFC-e", "/guias/nfe-nfce-o-que-e/", "A diferença entre as duas"),
           ("Emissão de NFC-e", "/solucoes/nfce/", "O recurso no SoftPay"),
           ("Como sair do caderno", "/guias/como-sair-do-caderno/", "Sair do papel primeiro")],
),

dict(
  artigo=True,
  slug="guias/meu-sistema-precisa-mudar-reforma-tributaria",
  title="Meu Sistema Precisa Mudar por Causa da Reforma Tributária? | SoftPay",
  description="Como saber se o seu sistema de gestão está pronto para a reforma tributária, as perguntas exatas a fazer ao fornecedor e o que fazer se a resposta for vaga.",
  h1="Meu sistema precisa mudar por causa da reforma tributária?",
  intro="Resposta curta: não necessariamente. O que precisa mudar é a nota fiscal, não o computador nem o sistema — desde que o seu sistema seja atualizado a tempo. Esta página traz as perguntas exatas para descobrir se ele será.",
  breadcrumbs=_c("Meu sistema precisa mudar"),
  blocks=[
    sec("O que a reforma exige do sistema",
      p("A exigência é específica: o documento fiscal precisa sair com os campos de <strong>IBS e CBS</strong> preenchidos. Documento sem esses campos é rejeitado automaticamente."),
      p("Isso significa que a mudança é no <em>software que emite a nota</em>. Não é sobre o computador da loja, nem sobre a impressora, nem sobre a maquininha."),
    ),
    sec("As quatro perguntas para fazer ao seu fornecedor",
      p("Mande estas perguntas ao suporte do sistema que você usa hoje. As respostas dizem tudo:"),
      ol("<strong>O sistema já emite nota com IBS e CBS destacados?</strong> Se sim, peça para ver uma nota de exemplo.",
         "<strong>Se ainda não, qual a data prevista?</strong> Data vaga (“estamos trabalhando nisso”) é resposta ruim quando existe prazo legal.",
         "<strong>A atualização tem custo adicional?</strong> Alguns cobram o módulo fiscal à parte.",
         "<strong>O que preciso fazer do meu lado?</strong> Recadastrar produto, informar código fiscal, atualizar algum dado."),
      nota("Se o fornecedor não responde em alguns dias, ou responde sem data, considere isso um dado sobre o suporte que você terá em janeiro — quando todo mundo estiver perguntando ao mesmo tempo.", "A resposta que mais importa é a velocidade dela"),
    ),
    sec("Quando trocar de sistema faz sentido",
      ul("<strong>O fornecedor não dá data.</strong> Prazo legal com resposta vaga é risco real.",
         "<strong>O sistema não emite nota fiscal de jeito nenhum.</strong> Aí não é atualização: é recurso que não existe.",
         "<strong>A atualização vem com aumento grande de preço.</strong> Vale comparar antes de aceitar.",
         "<strong>Você já estava insatisfeito por outros motivos.</strong> A reforma é uma boa hora para resolver, não a causa."),
    ),
    sec("Quando NÃO faz sentido trocar",
      ul("<strong>O sistema atual já está adequado ou tem data definida.</strong> Trocar por trocar só cria trabalho.",
         "<strong>Você é do Simples ou MEI e ainda tem meses.</strong> Há tempo para o seu fornecedor se adequar — cobre, mas não corra.",
         "<strong>Alguém te disse que “todo sistema vai parar”.</strong> Não vai. Sistema que se atualizar continua funcionando."),
      nota("Se você está sendo pressionado a decidir hoje por causa da reforma, desconfie. Existe prazo, mas ele não é amanhã — e decisão apressada é como se troca um problema por outro.", "Cuidado com pressa vendida"),
    ),
    sec("Se decidir trocar, faça na ordem certa",
      ol("<strong>Confirme a sua data</strong> com o contador: agosto de 2026 (regime regular) ou janeiro de 2027 (Simples e MEI).",
         "<strong>Teste antes de contratar</strong>, com produtos e vendas de verdade.",
         "<strong>Pergunte ao novo fornecedor as mesmas quatro perguntas</strong> acima. Vale para todos, inclusive para o SoftPay.",
         "<strong>Migre com folga.</strong> Pelo menos um mês antes da sua data, nunca na semana da virada.",
         "<strong>Leve os dados</strong>: produtos, clientes e o que está em aberto no fiado."),
      FONTE_REFORMA,
    ),
    sec("A resposta honesta sobre o SoftPay",
      p("Aplicando o mesmo critério ao próprio produto: a emissão de NF-e e NFC-e está nos planos Nota Fiscal e ERP Completo, e <strong>consta como recurso em ativação</strong>. Se a emissão fiscal é o motivo pelo qual você está procurando sistema, <strong>fale com o suporte antes de contratar</strong> e confirme a situação para o seu caso — não contrate no escuro."),
      p("O que está pronto e não depende disso: PDV, estoque com custo, caixa, fiado e cadastro de clientes. É o trabalho de base que a reforma vai exigir de qualquer forma."),
    ),
  ],
  faq=[
    ("Vou precisar trocar de sistema por causa da reforma tributária?",
     "Não necessariamente. Se o seu sistema atual for atualizado a tempo para emitir nota com IBS e CBS destacados, ele continua servindo. A pergunta a fazer ao fornecedor é exatamente essa."),
    ("Vou precisar trocar de computador?",
     "Não. A exigência é sobre o documento fiscal emitido pelo software, não sobre o equipamento da loja."),
    ("E se o meu fornecedor não responder sobre a data?",
     "Trate isso como informação sobre o suporte que você terá quando o prazo apertar. Vale começar a avaliar alternativas em paralelo, sem pressa."),
    ("Todo sistema de gestão vai parar de funcionar?",
     "Não. Sistemas que se atualizarem continuam funcionando normalmente. Quem afirma o contrário provavelmente está vendendo algo."),
    ("Quanto tempo antes devo migrar?",
     "Pelo menos um mês antes da sua data, para ter tempo de cadastrar produtos e aprender a rotina. Migrar na semana da virada é a pior hora possível."),
    ("O SoftPay já emite nota com IBS e CBS?",
     "A emissão de NF-e e NFC-e está nos planos Nota Fiscal e ERP Completo e consta como recurso em ativação. Confirme a situação para o seu caso com o suporte antes de contratar."),
  ],
  cta_title="Adiante o que não depende do fiscal",
  cta_text="Cadastro de produtos, registro de vendas e controle de entradas: o trabalho de base que a reforma vai exigir. 7 dias grátis, sem cartão.",
  related=[("Reforma tributária no comércio", "/guias/reforma-tributaria-comercio/", "As datas e o que muda"),
           ("Reforma tributária e o MEI", "/guias/reforma-tributaria-mei/", "A obrigação de 2027"),
           ("Checklist até janeiro", "/guias/checklist-reforma-tributaria-2027/", "O que fazer, em ordem"),
           ("Como escolher um sistema", "/guias/como-escolher-sistema-de-gestao/", "Os 7 critérios"),
           ("Posso migrar de outro sistema?", "/perguntas/posso-migrar-de-outro-sistema/", "Como é a migração"),
           ("O que é NF-e e NFC-e", "/guias/nfe-nfce-o-que-e/", "A diferença entre as duas")],
),

dict(
  artigo=True,
  slug="guias/checklist-reforma-tributaria-2027",
  passos=[
    ('Confirme a sua data com o contador', 'Regime regular já está obrigado desde agosto de 2026; Simples Nacional e MEI entram em 1º de janeiro de 2027.', 'passo-1-confirme-a-sua-data-com-o-contador'),
    ('Pergunte ao seu sistema se ele está pronto', 'Quatro perguntas objetivas ao fornecedor, com prazo de resposta.', 'passo-2-pergunte-ao-seu-sistema-se-ele-esta-pronto'),
    ('Cadastre os produtos de maior giro', 'Nota fiscal exige produto cadastrado. Comece pelos que respondem pela maior parte das vendas.', 'passo-3-cadastre-os-produtos-de-maior-giro'),
    ('Comece a registrar as notas de entrada', 'A compra de mercadoria com nota passa a valer mais no novo modelo, por causa do crédito.', 'passo-4-comece-a-registrar-as-notas-de-entrada'),
    ('Emita nota antes de ser obrigado', 'Algumas por dia, para a rotina entrar antes do prazo.', 'passo-5-emita-nota-antes-de-ser-obrigado'),
    ('Revise em dezembro, sem migrar em dezembro', 'Dezembro é para conferir, não para começar.', 'passo-6-revise-em-dezembro-sem-migrar-em-dezembro'),
  ],
  title="Checklist da Reforma Tributária até Janeiro de 2027 | SoftPay",
  description="Checklist prático para o pequeno comércio se preparar para a reforma tributária até 1º de janeiro de 2027, em seis passos e com as datas oficiais.",
  h1="Checklist da reforma tributária até janeiro de 2027",
  intro="Seis passos, em ordem, para chegar em 1º de janeiro de 2027 sem susto. Nenhum deles depende de você entender a reforma inteira — dependem de saber a sua data e organizar o que já é seu.",
  breadcrumbs=_c("Checklist da reforma tributária"),
  blocks=[
    sec("Passo 1 — Confirme a sua data com o contador",
      p("Tudo começa aqui, porque a data muda conforme o regime:"),
      tabela(["Regime", "Data", "Situação"], [
        ["Lucro Real / Lucro Presumido", "3 de agosto de 2026", "Já em vigor"],
        ["Simples Nacional", "1º de janeiro de 2027", "A preparar"],
        ["MEI", "1º de janeiro de 2027", "A preparar"],
      ]),
      p("Se você não tem certeza do seu regime, essa é a primeira pergunta ao contador — e é rápida."),
    ),
    sec("Passo 2 — Pergunte ao seu sistema se ele está pronto",
      p("Quatro perguntas ao suporte do sistema que você usa:"),
      ol("O sistema já emite nota com IBS e CBS destacados?",
         "Se não, qual a data prevista?",
         "A atualização tem custo adicional?",
         "O que preciso fazer do meu lado?"),
      p("O detalhamento está em <a href=\"/guias/meu-sistema-precisa-mudar-reforma-tributaria/\">meu sistema precisa mudar?</a>."),
    ),
    sec("Passo 3 — Cadastre os produtos de maior giro",
      p("Nota fiscal exige produto cadastrado, com descrição e valor. Este é o passo que mais consome tempo, e por isso é o que mais compensa adiantar."),
      ol("Liste os itens que respondem pela maior parte das vendas.",
         "Cadastre com descrição clara, preço de venda e custo de compra.",
         "Complete o restante conforme repõe o estoque — não pare a loja para cadastrar tudo."),
    ),
    sec("Passo 4 — Comece a registrar as notas de entrada",
      p("No novo modelo, o imposto pago na compra pode ser abatido. Isso torna a nota de entrada mais valiosa do que era — e a compra sem nota, mais cara do que parece."),
      p("Se você compra de fornecedor sem pedir nota, esse é um hábito que vale mudar agora."),
    ),
    sec("Passo 5 — Emita nota antes de ser obrigado",
      p("Se você é MEI ou do Simples e quase não emite nota hoje, comece a emitir algumas por dia. O objetivo não é a nota em si: é <strong>a rotina</strong>."),
      p("Quem já emitiu cinquenta notas até dezembro chega em janeiro sem novidade. Quem vai emitir a primeira no dia 2 de janeiro, com cliente esperando, aprende na pior hora."),
    ),
    sec("Passo 6 — Revise em dezembro, sem migrar em dezembro",
      p("Dezembro é para conferir se está tudo funcionando, não para começar. É o mês de maior movimento do varejo e o mês em que o suporte de todo fornecedor está mais cheio."),
      ul("Confira se a emissão está saindo certa.",
         "Confira se os produtos de maior giro estão cadastrados.",
         "Deixe o contato do suporte à mão."),
      FONTE_REFORMA,
    ),
  ],
  faq=[
    ("Qual o prazo para o pequeno comércio se adequar à reforma?",
     "Para Simples Nacional e MEI, 1º de janeiro de 2027. Para empresas do regime regular, a obrigação já vale desde 3 de agosto de 2026."),
    ("Por onde começo?",
     "Pela sua data: confirme com o contador se você é regime regular, Simples ou MEI. Todo o resto do checklist depende dessa resposta."),
    ("Preciso fazer tudo isso mesmo sendo uma loja pequena?",
     "Os passos 1, 2 e 3 valem para qualquer tamanho. Os demais são preparação que reduz o susto — quanto menor a estrutura, mais vale adiantar, porque não há equipe para resolver correndo."),
    ("Dá tempo se eu começar em novembro?",
     "Dá, mas com menos folga. O passo que consome tempo é o cadastro de produtos; começar em setembro ou outubro permite fazer sem parar a loja."),
    ("O que eu não devo fazer?",
     "Migrar de sistema em dezembro. É o mês de maior movimento e o de maior fila no suporte de todos os fornecedores."),
    ("Preciso entender a reforma tributária inteira?",
     "Não. Você precisa saber a sua data, ter um sistema que emita a nota no formato novo e ter os produtos cadastrados. O resto é trabalho do contador."),
  ],
  cta_title="Comece pelo passo 3, que é o mais demorado",
  cta_text="Cadastrar os produtos de maior giro leva uma tarde e resolve o passo que mais consome tempo. 7 dias grátis, sem cartão.",
  related=[("Reforma tributária no comércio", "/guias/reforma-tributaria-comercio/", "As datas e o que muda"),
           ("Reforma tributária e o MEI", "/guias/reforma-tributaria-mei/", "A obrigação de 2027"),
           ("Meu sistema precisa mudar?", "/guias/meu-sistema-precisa-mudar-reforma-tributaria/", "As perguntas ao fornecedor"),
           ("O que é NF-e e NFC-e", "/guias/nfe-nfce-o-que-e/", "A diferença entre as duas"),
           ("Como controlar estoque", "/guias/como-controlar-estoque/", "O cadastro de produtos"),
           ("Como sair do caderno", "/guias/como-sair-do-caderno/", "Sair do papel")],
),

dict(
  artigo=True,
  slug="guias/nfe-nfce-o-que-e",
  title="NF-e e NFC-e: Qual a Diferença e Quando Usar Cada Uma | SoftPay",
  description="A diferença entre NF-e e NFC-e em linguagem simples: qual usar na venda para consumidor, qual usar para empresa e o que muda com a reforma tributária.",
  h1="NF-e e NFC-e: qual a diferença",
  intro="A diferença é o cliente. NFC-e é a nota da venda no balcão, para o consumidor final. NF-e é a nota da venda para outra empresa, ou de operações que exigem documento completo. Esta página explica quando usar cada uma, sem termo de contador.",
  breadcrumbs=_c("NF-e e NFC-e"),
  blocks=[
    sec("A diferença em uma tabela",
      tabela(["", "NFC-e", "NF-e"], [
        ["Para quem", "Consumidor final, no balcão", "Outra empresa, ou operação que exige documento completo"],
        ["Onde é usada", "Loja, venda direta", "Venda para CNPJ, transporte de mercadoria"],
        ["Como o cliente recebe", "Cupom impresso ou por QR Code", "Arquivo XML e DANFE"],
        ["Situação comum", "Mercadinho, loja de roupas, pet shop", "Distribuidora, venda no atacado"],
      ]),
      p("Na prática, quem tem loja de rua usa <strong>NFC-e</strong> na maior parte das vendas, e <strong>NF-e</strong> quando vende para uma empresa."),
    ),
    sec("Quando você precisa de cada uma",
      h3("NFC-e — venda no balcão"),
      p("É o documento da venda para consumidor final. Substitui o antigo cupom fiscal. Sai na hora da venda, e o cliente pode receber impresso ou pelo celular."),
      h3("NF-e — venda para empresa"),
      p("Necessária quando o comprador é pessoa jurídica e precisa da nota para o próprio controle e crédito de imposto. Também é o documento que acompanha mercadoria em transporte."),
      nota("Se a sua loja vende no atacado <em>e</em> no varejo, você provavelmente precisa das duas. É o caso de distribuidoras e de lojas que atendem tanto o consumidor quanto o pequeno revendedor.", "Quem precisa das duas"),
    ),
    sec("O que muda com a reforma tributária",
      p("As duas passam a exigir os campos de <strong>IBS e CBS</strong> preenchidos. Documento sem esses campos é rejeitado automaticamente pelo sistema."),
      tabela(["Quem", "Desde quando"], [
        ["Regime regular (Lucro Real e Presumido)", "3 de agosto de 2026 — já em vigor"],
        ["Simples Nacional e MEI", "1º de janeiro de 2027"],
      ]),
      p("Para o MEI há uma mudança adicional: a partir de 2027, a nota passa a ser obrigatória em <strong>qualquer venda</strong>, inclusive para pessoa física. Veja <a href=\"/guias/reforma-tributaria-mei/\">reforma tributária e o MEI</a>."),
      FONTE_REFORMA,
    ),
    sec("Preciso emitir nota em toda venda?",
      p("Depende do seu regime e do seu estado — é pergunta para o seu contador, não para um site de sistema. O que dá para dizer com segurança:"),
      ul("A partir de 1º de janeiro de 2027, o MEI passa a emitir em qualquer venda.",
         "Empresas do regime regular já estão obrigadas ao formato novo desde agosto de 2026.",
         "Independentemente da obrigação, registrar toda venda em algum lugar é o que permite saber quanto a loja realmente ganhou."),
    ),
    sec("Como o SoftPay trata as duas",
      p("A emissão de NF-e e NFC-e está nos planos <strong>Nota Fiscal (R$ 65/mês)</strong> e <strong>ERP Completo (R$ 109/mês)</strong>, e <strong>consta como recurso em ativação</strong> — confirme a situação para o seu caso com o suporte antes de contratar contando com ela."),
      p("Os planos Comércio e Loja não incluem emissão fiscal: cobrem PDV, estoque, caixa, fiado e clientes."),
    ),
  ],
  faq=[
    ("Qual a diferença entre NF-e e NFC-e?",
     "A NFC-e é a nota da venda para consumidor final, emitida no balcão. A NF-e é usada na venda para outra empresa e no transporte de mercadoria. Quem tem loja de rua usa NFC-e na maior parte das vendas."),
    ("Preciso das duas?",
     "Se você vende só para consumidor final, a NFC-e costuma bastar. Se vende também para empresas, no atacado, provavelmente precisa das duas."),
    ("A NFC-e substituiu o cupom fiscal?",
     "Sim, a NFC-e é o documento eletrônico que substituiu o antigo cupom fiscal na venda ao consumidor."),
    ("O que muda nas duas com a reforma tributária?",
     "Ambas passam a exigir os campos de IBS e CBS preenchidos. Para o regime regular isso vale desde 3 de agosto de 2026; para Simples Nacional e MEI, a partir de 1º de janeiro de 2027."),
    ("O SoftPay emite as duas?",
     "A emissão de NF-e e NFC-e está nos planos Nota Fiscal e ERP Completo e consta como recurso em ativação. Confirme com o suporte antes de contratar contando com ela."),
    ("Sou obrigado a emitir nota em toda venda?",
     "Depende do seu regime e do seu estado — confirme com o seu contador. Para o MEI, a obrigação em qualquer venda começa em 1º de janeiro de 2027."),
  ],
  cta_title="Organize o cadastro antes do fiscal",
  cta_text="Emitir nota exige produto cadastrado. Comece por aí: 7 dias grátis, sem cartão de crédito.",
  related=[("Reforma tributária no comércio", "/guias/reforma-tributaria-comercio/", "As datas e o que muda"),
           ("Reforma tributária e o MEI", "/guias/reforma-tributaria-mei/", "A obrigação de 2027"),
           ("Emissão de NF-e", "/solucoes/nfe/", "O recurso no SoftPay"),
           ("Emissão de NFC-e", "/solucoes/nfce/", "O recurso no SoftPay"),
           ("Checklist até janeiro", "/guias/checklist-reforma-tributaria-2027/", "O que fazer, em ordem"),
           ("Distribuidora", "/segmentos/distribuidora/", "Quem usa as duas")],
),
]
