# -*- coding: utf-8 -*-
from blocks import sec, p, ul, ol, h3, nota, exemplo, tabela

C = [("Perguntas", "/perguntas/")]
def _c(n): return C + [(n, None)]

def resposta(texto):
    return ('      <div class="answer-lead">\n        <span class="answer-tag">Resposta direta</span>\n'
            '        <p>%s</p>\n      </div>' % texto)

PAGINAS = [

dict(
  slug="perguntas/quanto-custa-um-sistema-para-loja",
  title="Quanto Custa um Sistema para Loja? Preços 2026 | SoftPay",
  description="Quanto custa um sistema de gestão para loja no Brasil, o que faz o preço variar e o que checar antes de contratar. Planos SoftPay de R$ 65 a R$ 109/mês.",
  h1="Quanto custa um sistema para loja?",
  intro="Preço de sistema de gestão para loja pequena costuma ficar na faixa de dezenas de reais por mês. O que mais varia não é o valor: é o que está incluído.",
  breadcrumbs=_c("Quanto custa um sistema"),
  blocks=[
    resposta("Sistemas de gestão para pequeno varejo no Brasil geralmente são vendidos por assinatura mensal. No SoftPay, os planos vão de <strong>R$ 65 a R$ 109 por mês</strong>, com 7 dias de teste grátis sem cartão de crédito."),
    sec("Os planos do SoftPay",
      tabela(["Plano", "Preço", "O que inclui"], [
        ["Nota Fiscal", "R$ 65/mês", "Só emissão de notas, por formulário. Sem PDV, estoque ou relatórios. Até 2 usuários"],
        ["Comércio", "R$ 69/mês", "PDV/caixa, caderninho de fiado, estoque essencial. 1 usuário"],
        ["Loja", "R$ 89/mês", "Tudo do Comércio + fiado com cobrança por Pix, loja online, estoque avançado. Até 3 usuários"],
        ["ERP Completo", "R$ 109/mês", "Tudo da Loja + emissão de NFC-e e NF-e. Até 10 usuários"],
      ]),
    ),
    sec("O que faz o preço variar entre sistemas",
      ul("<strong>Número de usuários.</strong> Muitos sistemas cobram por acesso adicional.",
         "<strong>Emissão fiscal.</strong> NF-e e NFC-e costumam estar em planos superiores.",
         "<strong>Loja online.</strong> Pode ser módulo à parte com cobrança separada.",
         "<strong>Filiais.</strong> Mais de um ponto de venda geralmente muda o plano.",
         "<strong>Suporte.</strong> Alguns cobram atendimento à parte ou só oferecem base de ajuda."),
    ),
    sec("O que checar antes de assinar qualquer sistema",
      ol("Existe teste grátis <strong>sem cartão</strong>? Se pedem cartão, você depende de lembrar de cancelar.",
         "Há taxa de implantação ou de migração além da mensalidade?",
         "Quantos usuários estão inclusos no preço anunciado?",
         "O suporte é humano e em qual canal?",
         "Se você sair, consegue exportar os seus dados?"),
      nota("Compare o custo com o que ele evita. Uma diferença de estoque ou um fiado esquecido por mês costuma valer mais que a mensalidade — mas isso só é verdade se você realmente usar o sistema.", "Como avaliar se compensa"),
    ),
  ],
  faq=[
    ("Quanto custa o SoftPay?",
     "De R$ 65 a R$ 109 por mês, conforme o plano: Nota Fiscal R$ 65, Comércio R$ 69, Loja R$ 89 e ERP Completo R$ 109."),
    ("Tem taxa de instalação ou fidelidade?",
     "Os planos são mensais e o teste de 7 dias não pede cartão de crédito. Confirme com o suporte qualquer condição específica antes de contratar."),
    ("Qual plano é o mais indicado para começar?",
     "Para uma loja pequena que quer sair do caderno, o Comércio (R$ 69/mês) cobre PDV, caixa, fiado e estoque essencial."),
    ("Preciso pagar por usuário adicional?",
     "O número de usuários está incluído no plano: 1 no Comércio, até 3 no Loja e até 10 no ERP Completo."),
    ("Existe sistema de graça?",
     "Existem opções gratuitas no mercado, geralmente com limites de recursos ou de volume. Vale comparar o que cada uma cobre antes de decidir pelo preço."),
  ],
  related=[("Loja pequena precisa de sistema?", "/perguntas/loja-pequena-precisa-de-sistema/", "Quando vale a pena"),
           ("Caderno ou sistema?", "/perguntas/caderno-ou-sistema/", "A comparação"),
           ("Preços", "/#pricing", "Ver os planos")],
),

dict(
  slug="perguntas/loja-pequena-precisa-de-sistema",
  title="Loja Pequena Precisa de Sistema de Gestão? | SoftPay",
  description="Descubra se a sua loja pequena já precisa de um sistema de gestão: os sinais concretos, quando ainda dá para esperar e o que muda na prática.",
  h1="Loja pequena precisa de sistema?",
  intro="Não é o tamanho da loja que responde essa pergunta. É o quanto de informação já não cabe mais na sua cabeça.",
  breadcrumbs=_c("Loja pequena precisa de sistema"),
  blocks=[
    resposta("Não existe faturamento mínimo. O que indica a necessidade é a <strong>perda de controle</strong>: estoque que você não sabe de cabeça, fiado que passou do ponto de lembrar e a dúvida sobre quanto sobrou no fim do mês."),
    sec("Cinco sinais de que já passou da hora",
      ol("Você não sabe quantas unidades tem de um produto que vende todo dia.",
         "O fiado passou do ponto em que dá para lembrar quem deve o quê.",
         "O caixa não bate e ninguém consegue explicar a diferença.",
         "Você vendeu bem no mês e mesmo assim não sobrou dinheiro.",
         "Só você consegue operar a loja, porque a informação está toda com você."),
      p("O quarto sinal é o mais importante. Vender bem e não ter dinheiro quase nunca é problema de venda — é falta de controle de custo e de estoque."),
    ),
    sec("Quando ainda dá para esperar",
      p("Se você tem poucos produtos, não vende fiado, não tem funcionário e consegue dizer de cabeça o que tem em estoque, provavelmente o caderno ainda dá conta. Sistema resolve complexidade; se ela não existe, ele vira só mais uma tarefa."),
      nota("O quinto sinal costuma ser subestimado. Uma loja em que só o dono sabe operar não pode crescer, nem tirar férias. O sistema é o que transfere o conhecimento da cabeça de uma pessoa para a operação.", "O sinal que quase ninguém considera"),
    ),
    sec("O que muda de fato",
      ul("O estoque acompanha a venda sem alguém lembrar de dar baixa.",
         "O total do fiado vira um número, não uma sensação.",
         "O caixa fecha no mesmo dia, com a diferença ainda explicável.",
         "A margem por produto deixa de ser média.",
         "Outra pessoa consegue atender sem depender de você."),
    ),
  ],
  faq=[
    ("Tem faturamento mínimo para valer a pena?",
     "Não existe um número universal. O indicador prático é a perda de controle sobre estoque, fiado e resultado, não o tamanho do faturamento."),
    ("Minha loja tem só uma pessoa. Faz sentido?",
     "Sim, e é o perfil mais comum. O plano Comércio, de R$ 69/mês, foi pensado para a loja de um operador só."),
    ("É complicado de aprender?",
     "O SoftPay foi feito para quem nunca usou sistema de gestão, e o suporte humano ajuda na configuração inicial pelo WhatsApp."),
    ("E se eu testar e não gostar?",
     "O teste de 7 dias não pede cartão de crédito. Se não fizer sentido, é só não continuar."),
    ("Posso começar aos poucos?",
     "Sim. O caminho recomendado é cadastrar primeiro os produtos de maior giro e ir completando conforme repõe."),
  ],
  related=[("Quanto custa", "/perguntas/quanto-custa-um-sistema-para-loja/", "Preços e o que checar"),
           ("Como sair do caderno", "/guias/como-sair-do-caderno/", "O passo a passo"),
           ("Pequeno comércio", "/segmentos/pequeno-comercio/", "Feito para o seu caso")],
),

dict(
  slug="perguntas/caderno-ou-sistema",
  title="Caderno ou Sistema para Controlar a Loja? | SoftPay",
  description="Comparação honesta entre controlar a loja no caderno e usar um sistema de gestão: o que o caderno resolve bem, onde ele falha e quando trocar.",
  h1="Caderno ou sistema?",
  intro="O caderno tem vantagens reais e é honesto reconhecê-las. O problema aparece num ponto específico da operação — e é aí que a troca se justifica.",
  breadcrumbs=_c("Caderno ou sistema"),
  blocks=[
    resposta("O caderno funciona enquanto <strong>uma pessoa só</strong> opera a loja e o volume cabe na memória. Ele quebra quando você precisa de um <strong>total</strong> — total de estoque, total de fiado, total de margem — porque caderno registra eventos, não saldos."),
    sec("O que o caderno faz bem",
      ul("Não depende de energia, internet nem de aprender nada.",
         "É instantâneo: anotar leva menos tempo que qualquer sistema.",
         "Custa quase nada.",
         "Nunca fica fora do ar."),
      p("Essas vantagens são verdadeiras, e é por isso que tanta loja resiste à troca. Quem diz que caderno é só atraso não entende a rotina de balcão."),
    ),
    sec("Onde o caderno falha",
      tabela(["Situação", "Caderno", "Sistema"], [
        ["Quanto tenho deste produto?", "Contar na prateleira", "Consulta na tela"],
        ["Quanto a loja tem a receber?", "Somar página por página", "Um número"],
        ["Qual a margem deste item?", "Não dá", "Calculada do custo"],
        ["Outra pessoa consegue operar?", "Só quem escreveu entende", "Qualquer um com acesso"],
        ["E se molhar ou sumir?", "Perdeu", "Backup automático na nuvem"],
        ["O que está encalhado?", "Percepção", "Curva ABC"],
      ]),
      p("A linha decisiva é a segunda. Caderno registra cada venda fiada, mas não te dá o total — e sem o total você não sabe o tamanho do dinheiro que está na rua."),
    ),
    sec("O ponto de virada",
      p("Na prática, a troca se justifica quando aparece o primeiro destes três: mais de uma pessoa no balcão, fiado que não cabe mais na memória, ou a pergunta “vendi bem, cadê o dinheiro?”."),
      nota("Não jogue o caderno fora ao migrar. Mantenha por algumas semanas em paralelo, como rede de segurança e referência para conferir divergências de fiado.", "Na hora de trocar"),
    ),
  ],
  faq=[
    ("Caderno é errado?",
     "Não. Ele funciona bem enquanto uma pessoa só opera a loja e o volume cabe na memória. O limite aparece quando você precisa de totais e não só de anotações."),
    ("Qual a maior diferença prática?",
     "O total. O caderno registra cada venda fiada, mas não diz quanto a loja tem a receber no conjunto — e é esse número que muda decisões."),
    ("Posso usar os dois ao mesmo tempo?",
     "Sim, e é recomendável durante a transição. Mantenha o caderno em paralelo por algumas semanas até confiar no sistema."),
    ("E se a internet cair?",
     "O SoftPay é acessado pela internet, então depende de conexão. Se a sua região tem instabilidade frequente, converse com o suporte antes de contratar."),
    ("Como levo o que está no caderno?",
     "Leve só o que está em aberto: estoque atual dos itens de giro, fiado a receber e clientes. Vendas passadas não precisam ser transcritas."),
  ],
  related=[("Como sair do caderno", "/guias/como-sair-do-caderno/", "Passo a passo em 7 dias"),
           ("Excel ou sistema?", "/perguntas/excel-ou-sistema-de-gestao/", "A outra comparação"),
           ("Controle de fiado", "/solucoes/controle-de-fiado/", "O total do fiado")],
),

dict(
  slug="perguntas/excel-ou-sistema-de-gestao",
  title="Excel ou Sistema de Gestão para Loja? | SoftPay",
  description="Planilha ou sistema de gestão: o que o Excel resolve bem, onde ele trava numa loja com estoque e vendas diárias, e quando vale trocar.",
  h1="Excel ou sistema de gestão?",
  intro="Planilha é uma ferramenta excelente — para análise. O atrito começa quando ela precisa virar a operação diária de uma loja.",
  breadcrumbs=_c("Excel ou sistema de gestão"),
  blocks=[
    resposta("A planilha falha na loja por um motivo estrutural: a baixa do estoque <strong>depende de alguém lembrar</strong> de digitar depois da venda. Num sistema, vender e dar baixa são o mesmo ato — e é isso que mantém o dado confiável."),
    sec("Onde a planilha é boa",
      ul("Simular cenários e testar preço.",
         "Analisar um período fechado com liberdade total.",
         "Montar controles sob medida, do jeito que você pensa.",
         "Custo zero se você já tem o programa."),
    ),
    sec("Onde ela trava numa loja",
      tabela(["Problema", "Na planilha", "No sistema"], [
        ["Baixa de estoque", "Digitada depois, de memória", "Automática na venda"],
        ["Duas pessoas ao mesmo tempo", "Conflito de versão", "Acesso simultâneo"],
        ["Erro de fórmula", "Silencioso, contamina tudo", "Cálculo fixo"],
        ["Histórico por cliente", "Difícil de manter", "Ligado à venda"],
        ["Backup", "Depende de você", "Automático na nuvem"],
        ["Uso no balcão", "Inviável durante a venda", "É o PDV"],
      ]),
      p("O item mais perigoso é o erro de fórmula. Uma referência arrastada errado não avisa: ela produz números plausíveis e errados, que você usa para decidir compra e preço durante meses."),
    ),
    sec("A combinação que funciona",
      p("Não é preciso escolher para sempre. Muita loja usa o sistema como fonte da operação — vendas, estoque, custo — e exporta dados para a planilha quando quer fazer uma análise específica. A planilha volta a fazer o que faz bem, sem sustentar o dia a dia."),
      nota("Se você já tem uma planilha de produtos, ela não é trabalho perdido: a importação de dados está disponível a partir do plano Loja. Fale com o suporte para conferir o formato.", "Sua planilha atual não é desperdício"),
    ),
  ],
  faq=[
    ("Por que a planilha desatualiza tão rápido?",
     "Porque a baixa do estoque é uma segunda etapa, feita depois da venda e dependente de alguém lembrar. O desencontro começa em dias."),
    ("Dá para usar planilha e sistema juntos?",
     "Sim. O sistema sustenta a operação e a planilha serve para análises pontuais, com dados exportados."),
    ("Consigo importar minha planilha atual?",
     "A importação de dados está disponível a partir do plano Loja. Confirme o formato do arquivo com o suporte antes de migrar."),
    ("Planilha não é mais barata?",
     "O custo direto é menor, mas o custo indireto aparece em decisões tomadas com dados desatualizados ou com erro de fórmula não percebido."),
    ("E o Google Sheets, resolve o problema de duas pessoas?",
     "Resolve o acesso simultâneo, mas não o principal: a baixa de estoque continua sendo digitação manual depois da venda."),
  ],
  related=[("Caderno ou sistema?", "/perguntas/caderno-ou-sistema/", "A outra comparação"),
           ("Como controlar estoque", "/guias/como-controlar-estoque/", "O método"),
           ("Controle de estoque", "/solucoes/sistema-de-estoque/", "Baixa automática")],
),

dict(
  slug="perguntas/qual-sistema-para-mercadinho",
  title="Qual Sistema Usar em um Mercadinho? | SoftPay",
  description="O que avaliar ao escolher um sistema para mercadinho: velocidade no PDV, estoque de muitos itens, fiado e fechamento de caixa. Critérios práticos.",
  h1="Qual sistema usar em um mercadinho?",
  intro="Mercadinho tem exigências próprias: muitos itens, margem apertada, venda rápida e fiado. Nem todo sistema de gestão foi pensado para esse conjunto.",
  breadcrumbs=_c("Qual sistema para mercadinho"),
  blocks=[
    resposta("Priorize quatro coisas: <strong>PDV rápido</strong>, <strong>estoque que suporte muitos itens</strong>, <strong>controle de fiado</strong> e <strong>fechamento de caixa diário</strong>. Sem esses quatro, o resto não compensa."),
    sec("Os critérios que importam nesse segmento",
      ol("<strong>Velocidade no balcão.</strong> Em horário de pico, cada segundo a mais na venda vira fila.",
         "<strong>Baixa automática de estoque.</strong> Com centenas de itens, controle manual não sobrevive a uma semana.",
         "<strong>Custo por produto.</strong> Margem de mercadinho é apertada; sem custo, não há como saber o que dá resultado.",
         "<strong>Fiado por cliente.</strong> É parte do negócio no comércio de bairro.",
         "<strong>Fechamento de caixa.</strong> Diferença precisa aparecer no mesmo dia.",
         "<strong>Uso no celular.</strong> Para conferir preço e estoque durante a reposição."),
    ),
    sec("O que costuma ser supérfluo no começo",
      p("Muito sistema vendido para varejo traz módulos que um mercadinho de bairro não usa: gestão de produção, ordem de serviço, comissão de vendedor, integração com marketplace. Pagar por isso não melhora a sua operação — e complica o aprendizado."),
    ),
    sec("Como o SoftPay se encaixa",
      p("O plano <strong>Comércio</strong> (R$ 69/mês) cobre os quatro critérios essenciais: PDV/caixa completo, caderninho de fiado, estoque essencial e notas recebidas, com 1 usuário — que é o perfil da maioria dos mercadinhos de bairro."),
      p("Se você quiser cobrança automática do fiado por link de Pix e estoque avançado com custo e curva ABC, o plano <strong>Loja</strong> (R$ 89/mês) adiciona isso. Emissão de nota fiscal só no <strong>ERP Completo</strong> (R$ 109/mês)."),
      nota("Não decida por lista de funcionalidades. Teste com os seus próprios produtos, no seu horário de pico. É a única forma de saber se o PDV aguenta a sua rotina.", "O melhor critério é o teste"),
    ),
  ],
  faq=[
    ("Qual plano do SoftPay serve para mercadinho?",
     "O Comércio, de R$ 69/mês, cobre PDV, caixa, fiado e estoque essencial com 1 usuário — o perfil mais comum de mercadinho de bairro."),
    ("Preciso de sistema com emissão de nota?",
     "Depende do seu regime tributário e do perfil de venda. Consulte seu contador; se precisar emitir, o plano é o ERP Completo."),
    ("Funciona com leitor de código de barras?",
     "O campo de busca do PDV aceita a leitura do código. Confirme a compatibilidade do seu leitor com o suporte."),
    ("Quantos produtos consigo cadastrar?",
     "O cadastro atende a operação de um mercadinho. Se o seu catálogo for muito grande, confirme com o suporte antes de contratar."),
    ("Dá para testar antes?",
     "Sim, 7 dias sem cartão de crédito. Teste com os seus produtos e no seu horário de movimento."),
  ],
  related=[("Sistema para mercadinho", "/segmentos/mercadinho/", "A página do segmento"),
           ("Sistema PDV", "/solucoes/sistema-pdv/", "Venda no balcão"),
           ("Controle de fiado", "/solucoes/controle-de-fiado/", "Fiado do bairro")],
),

dict(
  slug="perguntas/sistema-de-gestao-e-seguro",
  title="Sistema de Gestão na Nuvem é Seguro? | SoftPay",
  description="Como funciona a segurança de um sistema de gestão na nuvem: onde ficam os dados, backup automático, acesso por usuário e o que depende de você.",
  h1="Sistema de gestão é seguro?",
  intro="A pergunta certa não é se a nuvem é segura em absoluto, e sim como ela se compara ao que você faz hoje: um caderno na gaveta ou uma planilha no computador da loja.",
  breadcrumbs=_c("Sistema de gestão é seguro"),
  blocks=[
    resposta("No SoftPay, os dados ficam em <strong>banco de dados na nuvem sobre infraestrutura Supabase</strong>, com <strong>backup automático</strong> e <strong>acesso individual por usuário</strong>. Nenhum sistema pode prometer segurança absoluta — mas seus dados deixam de depender do computador da loja."),
    sec("O risco que já existe hoje",
      p("Caderno molha, rasga e some. Computador da loja queima, é roubado ou dá pau no disco. Planilha em pen drive se perde. Esses não são cenários hipotéticos: são a causa mais comum de perda de dados no comércio pequeno."),
      p("Comparado a isso, um banco de dados na nuvem com backup automático é uma melhora concreta — não porque a nuvem seja infalível, mas porque o dado deixa de estar num único lugar físico."),
    ),
    sec("O que o SoftPay oferece",
      ul("<strong>Banco de dados na nuvem</strong> com infraestrutura Supabase.",
         "<strong>Backup automático</strong>, sem depender de você lembrar de salvar.",
         "<strong>Acesso individual</strong>: cada pessoa da equipe entra com o próprio login.",
         "<strong>Recuperação de conta</strong> caso você perca o acesso."),
      nota("Você não vai ler aqui que o SoftPay é “100% seguro” ou que é “impossível perder dados”. Nenhum sistema pode afirmar isso com honestidade.", "O que não prometemos"),
    ),
    sec("A parte que depende de você",
      ol("Use uma senha que você não use em outros lugares.",
         "Dê acesso individual a cada pessoa, em vez de compartilhar um login.",
         "Ao desligar um funcionário, remova o acesso dele.",
         "Mantenha um contato de recuperação atualizado.",
         "Cuidado com o computador do balcão deixado aberto e sem supervisão."),
      p("Boa parte dos incidentes em loja pequena não vem de invasão técnica: vem de senha compartilhada e de acesso que não foi removido."),
    ),
    sec("E os dados dos seus clientes",
      p("Se você cadastra clientes, você é responsável por esses dados perante a LGPD. Colete o necessário, informe a finalidade e consulte a <a href=\"/privacidade\">Política de Privacidade</a> do SoftPay."),
    ),
  ],
  faq=[
    ("Onde ficam os meus dados?",
     "Em banco de dados na nuvem, sobre infraestrutura Supabase, e não no computador da sua loja."),
    ("Existe backup automático?",
     "Sim. O backup é feito automaticamente, sem depender de ação manual sua."),
    ("Se eu perder o acesso, consigo recuperar?",
     "Sim, o SoftPay tem recuperação de conta. Se não conseguir concluir sozinho, o suporte ajuda pelo WhatsApp."),
    ("Meus funcionários veem tudo?",
     "Cada pessoa entra com o próprio acesso. Sobre perfis com permissões diferentes, confirme com o suporte antes de contratar."),
    ("É mais seguro que a minha planilha?",
     "Na prática, o principal ganho é o dado não depender de um único computador físico e ter backup automático. Nenhum sistema, porém, garante segurança absoluta."),
  ],
  related=[("Sobre o SoftPay", "/sobre/", "Quem está por trás"),
           ("Política de Privacidade", "/privacidade", "Como tratamos dados"),
           ("Múltiplas lojas", "/solucoes/multiplas-lojas/", "Acesso da equipe")],
),

dict(
  slug="perguntas/posso-usar-o-softpay-no-celular",
  title="Posso Usar o SoftPay no Celular? | SoftPay",
  description="Como usar o SoftPay no celular: acesso pelo navegador, sem instalar aplicativo, com os dados sincronizados entre computador e telefone.",
  h1="Posso usar o SoftPay no celular?",
  intro="Sim — e sem instalar nada. O SoftPay roda no navegador, então o celular acessa a mesma conta do computador do balcão.",
  breadcrumbs=_c("Posso usar no celular"),
  blocks=[
    resposta("Sim. O SoftPay é acessado pelo <strong>navegador</strong>, sem instalar aplicativo. Como os dados ficam na nuvem, o que você registra no computador aparece no celular e vice-versa."),
    sec("Para que o celular costuma servir na prática",
      ul("Consultar preço e estoque enquanto organiza a prateleira.",
         "Verificar o saldo de fiado de um cliente longe do balcão.",
         "Acompanhar as vendas do dia sem estar na loja.",
         "Registrar venda em feira, evento ou entrega."),
      p("Na maioria das lojas o computador continua sendo o posto principal de venda, e o celular funciona como extensão — consulta e acompanhamento."),
    ),
    sec("O que considerar",
      nota("O SoftPay depende de conexão com a internet. Se a sua loja fica em região com instabilidade de sinal, converse com o suporte antes de contratar.", "Sobre conexão"),
      p("A tela do celular é menor, então tarefas de cadastro em volume ficam mais confortáveis no computador. Consulta e venda avulsa funcionam bem no telefone."),
    ),
  ],
  faq=[
    ("Preciso baixar um aplicativo?",
     "Não. O SoftPay funciona pelo navegador do celular, sem instalação."),
    ("Funciona em Android e iPhone?",
     "Por rodar no navegador, funciona nos dois. Se tiver dúvida sobre um aparelho específico, confirme com o suporte."),
    ("Os dados ficam sincronizados?",
     "Sim. Como ficam na nuvem, o que você registra em um dispositivo aparece no outro."),
    ("Dá para vender pelo celular?",
     "Sim, o acesso é o mesmo. Para volume alto no balcão, o computador costuma ser mais confortável."),
    ("Funciona sem internet?",
     "Não. O sistema é acessado pela internet e depende de conexão."),
  ],
  related=[("Múltiplas lojas", "/solucoes/multiplas-lojas/", "Acesso de qualquer lugar"),
           ("Sistema PDV", "/solucoes/sistema-pdv/", "Venda no navegador"),
           ("Preciso instalar?", "/perguntas/preciso-instalar/", "Sobre instalação")],
),

dict(
  slug="perguntas/posso-migrar-de-outro-sistema",
  title="Posso Migrar de Outro Sistema para o SoftPay? | SoftPay",
  description="Como migrar de outro sistema ou de uma planilha para o SoftPay: o que levar, importação de dados, ordem recomendada e apoio do suporte.",
  h1="Posso migrar de outro sistema?",
  intro="Sim. E a migração dá muito menos trabalho quando você leva só o que ainda está em uso, em vez de tentar transportar todo o histórico.",
  breadcrumbs=_c("Posso migrar de outro sistema"),
  blocks=[
    resposta("Sim. A <strong>importação de dados</strong> está disponível a partir do plano Loja, e o suporte orienta o formato do arquivo. Antes de migrar, fale com o suporte para conferir o que o seu sistema atual consegue exportar."),
    sec("O que vale a pena levar",
      tabela(["Levar", "Por quê"], [
        ["Cadastro de produtos com custo", "Base de estoque e margem"],
        ["Quantidades atuais em estoque", "Decide reposição"],
        ["Clientes com quem você tem relação", "Fiado e recompra"],
        ["Saldos de fiado em aberto", "É dinheiro a receber"],
      ]),
      p("Histórico de vendas antigas raramente compensa o esforço da migração: ele não muda a decisão de amanhã e costuma ser o que mais complica a importação."),
    ),
    sec("Ordem recomendada",
      ol("Exporte do sistema atual o que der — produtos e clientes normalmente saem em planilha.",
         "Fale com o suporte do SoftPay sobre o formato antes de importar.",
         "Importe produtos e clientes.",
         "Confira as quantidades de estoque dos itens de maior giro.",
         "Lance os saldos de fiado em aberto.",
         "Rode os dois sistemas em paralelo por alguns dias, até confiar nos números."),
      nota("Antes de cancelar o sistema antigo, garanta que você conseguiu exportar tudo que precisa. Depois do cancelamento, o acesso aos dados pode acabar.", "Não cancele antes de exportar"),
    ),
  ],
  faq=[
    ("A importação está em qual plano?",
     "A partir do plano Loja, de R$ 89/mês. Fale com o suporte para conferir o formato do arquivo."),
    ("Consigo importar de uma planilha do Excel?",
     "Sim, esse é o caminho mais comum. Confirme com o suporte a estrutura de colunas esperada antes de importar."),
    ("Preciso levar o histórico de vendas?",
     "Normalmente não compensa. O histórico antigo não muda decisões futuras e é o que mais complica a migração."),
    ("O suporte ajuda na migração?",
     "Sim. O atendimento é humano, pelo WhatsApp, e cobre a configuração inicial."),
    ("Quanto tempo leva?",
     "Com os dados exportados em mãos, a base costuma ficar pronta em poucos dias. O período de teste de 7 dias dá para avaliar."),
  ],
  related=[("Como sair do caderno", "/guias/como-sair-do-caderno/", "Se você vem do papel"),
           ("Excel ou sistema?", "/perguntas/excel-ou-sistema-de-gestao/", "Se você vem da planilha"),
           ("Contato", "/contato/", "Fale com o suporte")],
),

dict(
  slug="perguntas/e-dificil-aprender",
  title="É Difícil Aprender a Usar um Sistema de Gestão? | SoftPay",
  description="Quanto tempo leva para aprender a usar um sistema de gestão de loja, por onde começar e como o suporte humano do SoftPay ajuda na configuração.",
  h1="É difícil aprender a usar?",
  intro="A dificuldade real quase nunca está no sistema. Está em tentar aprender tudo de uma vez, em vez de começar pela tarefa que você já faz todo dia.",
  breadcrumbs=_c("É difícil aprender"),
  blocks=[
    resposta("Não, desde que você comece pelo caminho certo: <strong>cadastrar alguns produtos e passar uma venda no PDV</strong>. Isso leva minutos. O resto se aprende com o uso, e o suporte humano ajuda pelo WhatsApp."),
    sec("Por onde começar (nessa ordem)",
      ol("Cadastre cinco produtos que você vende toda semana.",
         "Passe uma venda pelo PDV e veja o estoque baixar.",
         "Feche o caixa no fim do dia.",
         "Cadastre um cliente e registre uma venda fiada.",
         "Só depois olhe relatórios."),
      p("Repare que os quatro primeiros passos são coisas que você já faz — só que agora registradas. Não é uma rotina nova: é a mesma rotina, com registro."),
    ),
    sec("O que mais atrapalha quem está começando",
      ul("Tentar cadastrar o catálogo inteiro antes de usar.",
         "Explorar relatórios antes de ter dados dentro.",
         "Deixar parte das vendas fora do sistema.",
         "Mudar de método no meio do caminho."),
      nota("O SoftPay foi desenhado para quem nunca usou sistema de gestão: a tela é organizada e a venda é direta. Se travar em algum ponto, o suporte é humano e responde pelo WhatsApp.", "Você não está sozinho nisso"),
    ),
  ],
  faq=[
    ("Quanto tempo leva para aprender o básico?",
     "Cadastrar alguns produtos e passar uma venda leva minutos. A rotina completa — caixa, fiado e estoque — costuma se acomodar na primeira semana de uso."),
    ("Preciso de treinamento?",
     "Não é necessário treinamento formal. O suporte humano ajuda na configuração inicial pelo WhatsApp."),
    ("E se meu funcionário tiver dificuldade?",
     "Comece por ele no PDV, que é a parte mais direta. Cada pessoa entra com o próprio acesso, conforme o plano."),
    ("Tem material de ajuda?",
     "O suporte pelo WhatsApp é o canal principal e atende dúvidas do dia a dia."),
    ("O teste de 7 dias dá para aprender?",
     "Dá. É tempo suficiente para cadastrar os itens de giro, passar vendas e fechar o caixa alguns dias."),
  ],
  related=[("Como organizar uma loja", "/guias/como-organizar-uma-loja/", "Roteiro por etapas"),
           ("Como sair do caderno", "/guias/como-sair-do-caderno/", "Migração em 7 dias"),
           ("Tem suporte humano?", "/perguntas/tem-suporte-humano/", "Como funciona o atendimento")],
),

dict(
  slug="perguntas/preciso-instalar",
  title="Preciso Instalar o Sistema no Computador? | SoftPay",
  description="O SoftPay não precisa de instalação: roda no navegador, sem servidor na loja e sem exigir computador novo. Veja o que é necessário.",
  h1="Preciso instalar alguma coisa?",
  intro="Não. E isso muda mais do que parece: sem instalação, não há servidor na loja, não há atualização manual e não há dado preso num computador só.",
  breadcrumbs=_c("Preciso instalar"),
  blocks=[
    resposta("Não. O SoftPay roda no <strong>navegador</strong>. Não é preciso instalar programa, manter servidor na loja nem comprar computador novo."),
    sec("Por que isso importa",
      ul("<strong>Sem servidor na loja.</strong> Nada para configurar, manter ou consertar.",
         "<strong>Sem atualização manual.</strong> Você usa sempre a versão atual.",
         "<strong>Dado não preso a uma máquina.</strong> Se o computador queimar, sua informação continua na nuvem.",
         "<strong>Vários dispositivos.</strong> Computador, notebook e celular acessam a mesma conta."),
    ),
    sec("O que você precisa ter",
      ol("Um computador ou celular com navegador atualizado.",
         "Conexão com a internet.",
         "Nada além disso."),
      nota("Como o acesso é pela internet, a conexão é requisito. Se a sua região tem instabilidade frequente de sinal, converse com o suporte antes de contratar.", "O requisito real"),
    ),
  ],
  faq=[
    ("Funciona em computador antigo?",
     "Desde que tenha um navegador atualizado e conexão, sim. Não é necessário comprar equipamento novo para começar."),
    ("Preciso de servidor na loja?",
     "Não. Os dados ficam na nuvem e o sistema é acessado pelo navegador."),
    ("Como são feitas as atualizações?",
     "Automaticamente. Você acessa sempre a versão atual, sem instalar nada."),
    ("Funciona no Mac e no Windows?",
     "Sim, porque depende apenas do navegador, não do sistema operacional."),
    ("E se eu ficar sem internet?",
     "O sistema depende de conexão para funcionar. Avalie a estabilidade do sinal na sua região antes de contratar."),
  ],
  related=[("Posso usar no celular?", "/perguntas/posso-usar-o-softpay-no-celular/", "Acesso pelo telefone"),
           ("É seguro?", "/perguntas/sistema-de-gestao-e-seguro/", "Dados na nuvem"),
           ("Sistema PDV", "/solucoes/sistema-pdv/", "PDV no navegador")],
),

dict(
  slug="perguntas/tem-suporte-humano",
  title="O Suporte do SoftPay é Humano? | SoftPay",
  description="Como funciona o suporte do SoftPay: atendimento humano pelo WhatsApp, ajuda na configuração inicial e cobertura nacional.",
  h1="O suporte é humano?",
  intro="Sim. E para quem está saindo do caderno, essa costuma ser a diferença entre configurar o sistema e desistir na primeira dúvida.",
  breadcrumbs=_c("Tem suporte humano"),
  blocks=[
    resposta("Sim. O atendimento é feito por <strong>pessoas da equipe, pelo WhatsApp</strong> — não por robô de autoatendimento. O suporte ajuda inclusive na configuração inicial."),
    sec("No que o suporte costuma ajudar",
      ul("Configurar a conta e cadastrar os primeiros produtos.",
         "Orientar a importação de dados de uma planilha ou de outro sistema.",
         "Tirar dúvidas do dia a dia sobre PDV, estoque, caixa e fiado.",
         "Confirmar o que está disponível em cada plano antes de você contratar.",
         "Auxiliar na recuperação de acesso à conta."),
    ),
    sec("Como falar com a gente",
      p("O canal principal é o WhatsApp: <strong>(86) 9 9819-3851</strong>. Também dá para escrever para <strong>suporte@softpaybr.com</strong>. O atendimento cobre todo o Brasil."),
      nota("Se você tem uma dúvida específica sobre um recurso — controle de validade, permissões por perfil, limite de fiado, situação da emissão fiscal —, pergunte antes de contratar. É mais rápido que descobrir depois.", "Pergunte antes de assinar"),
    ),
  ],
  faq=[
    ("Qual o canal de atendimento?",
     "WhatsApp no (86) 9 9819-3851 e e-mail suporte@softpaybr.com."),
    ("O suporte ajuda a configurar o sistema?",
     "Sim, inclusive na configuração inicial e no cadastro dos primeiros produtos."),
    ("Atende em todo o Brasil?",
     "Sim. O sistema é usado pela internet e o atendimento é nacional."),
    ("Tenho suporte durante o teste grátis?",
     "Sim. O suporte atende durante os 7 dias de teste, que é justamente quando as dúvidas de configuração aparecem."),
    ("O suporte é robô?",
     "Não. O atendimento é feito por pessoas da equipe."),
  ],
  related=[("Contato", "/contato/", "Todos os canais"),
           ("É difícil aprender?", "/perguntas/e-dificil-aprender/", "Por onde começar"),
           ("Sobre o SoftPay", "/sobre/", "Quem está por trás")],
),

dict(
  slug="perguntas/funciona-no-brasil-inteiro",
  title="O SoftPay Funciona em Todo o Brasil? | SoftPay",
  description="O SoftPay atende lojas em todo o Brasil: sistema na nuvem acessado pela internet e suporte nacional pelo WhatsApp.",
  h1="Funciona em todo o Brasil?",
  intro="Sim. Por ser um sistema na nuvem, o SoftPay não depende de representante local nem de instalação presencial.",
  breadcrumbs=_c("Funciona no Brasil inteiro"),
  blocks=[
    resposta("Sim. O SoftPay é usado <strong>pela internet</strong>, sem instalação, e o <strong>atendimento é nacional</strong>, pelo WhatsApp. Não é preciso ter um técnico na sua cidade."),
    sec("O que isso significa na prática",
      ul("Você contrata e começa a usar no mesmo dia, de qualquer cidade.",
         "Não há visita técnica nem custo de deslocamento.",
         "As atualizações chegam para todo mundo ao mesmo tempo.",
         "O suporte atende pelo WhatsApp, sem depender de escritório local."),
    ),
    sec("O que varia por estado",
      p("A parte que muda de um estado para outro é a <strong>fiscal</strong>. Regras de credenciamento e obrigatoriedade de NFC-e e NF-e são definidas pela SEFAZ de cada estado e pelo seu regime tributário."),
      nota("Antes de contratar contando com emissão fiscal, confirme com o seu contador o que a sua empresa precisa emitir no seu estado, e com o suporte a situação atual da emissão no SoftPay.", "Fiscal depende do seu estado"),
    ),
  ],
  faq=[
    ("Preciso de representante na minha cidade?",
     "Não. O sistema é acessado pela internet e o suporte é nacional, pelo WhatsApp."),
    ("Tem visita técnica ou instalação presencial?",
     "Não. Não há instalação: o SoftPay roda no navegador."),
    ("A emissão fiscal funciona no meu estado?",
     "As regras de NFC-e e NF-e variam por estado. Confirme com seu contador e com o suporte antes de contratar."),
    ("A empresa fica onde?",
     "O SoftPay é um produto da VisionX Inova Simples (IS), CNPJ 61.427.918/0001-06, sediada em Pedreiras/MA, com atendimento em todo o Brasil."),
    ("O suporte atende em outro fuso ou região?",
     "O atendimento é nacional pelo WhatsApp. Combine o horário com o suporte se precisar."),
  ],
  related=[("Sobre o SoftPay", "/sobre/", "Quem está por trás"),
           ("Contato", "/contato/", "Fale com a gente"),
           ("NF-e", "/solucoes/nfe/", "Emissão fiscal")],
),

dict(
  slug="perguntas/posso-usar-em-varios-dispositivos",
  title="Posso Usar o SoftPay em Vários Dispositivos? | SoftPay",
  description="Use o SoftPay no computador do balcão, no notebook e no celular ao mesmo tempo, com multi-login por funcionário. Veja os limites de cada plano.",
  h1="Posso usar em vários dispositivos?",
  intro="Sim. Os dados ficam na nuvem, então o balcão, o escritório e o celular olham para a mesma informação.",
  breadcrumbs=_c("Vários dispositivos"),
  blocks=[
    resposta("Sim. Como o SoftPay é acessado pelo <strong>navegador</strong> e os dados ficam na nuvem, o computador do balcão, o notebook e o celular acessam a mesma conta, com informação sincronizada."),
    sec("Dispositivos e usuários são coisas diferentes",
      p("Uma confusão comum: acessar de vários aparelhos não é o mesmo que ter vários usuários. O <strong>multi-login</strong> é o que dá acesso individual a cada pessoa da equipe, e ele tem limite por plano."),
      tabela(["Plano", "Usuários incluídos"], [
        ["Nota Fiscal", "Até 2"],
        ["Comércio", "1"],
        ["Loja", "Até 3"],
        ["ERP Completo", "Até 10"],
      ]),
      nota("Compartilhar o mesmo login entre várias pessoas parece economia, mas tira a rastreabilidade de quem fez cada operação — e é a origem mais comum de problema de acesso em loja pequena.", "Por que não compartilhar login"),
    ),
    sec("Usos típicos",
      ul("Computador do balcão como PDV principal.",
         "Notebook no escritório para cadastro e relatórios.",
         "Celular para consulta de preço e estoque na reposição.",
         "Celular do dono para acompanhar as vendas fora da loja."),
    ),
  ],
  faq=[
    ("Posso acessar de dois lugares ao mesmo tempo?",
     "Sim. Os dados ficam na nuvem e são sincronizados entre os dispositivos."),
    ("Quantos usuários posso cadastrar?",
     "1 no Comércio, até 3 no Loja, até 10 no ERP Completo e até 2 no Nota Fiscal."),
    ("Preciso pagar por dispositivo?",
     "Não. O que o plano define é o número de usuários, não de aparelhos."),
    ("Cada funcionário precisa de login próprio?",
     "É o recomendado, para manter a rastreabilidade de quem fez cada operação."),
    ("Existem permissões diferentes por usuário?",
     "O multi-login dá acesso individual. Sobre perfis com permissões distintas, confirme com o suporte antes de contratar."),
  ],
  related=[("Múltiplas lojas", "/solucoes/multiplas-lojas/", "Equipe e filiais"),
           ("Posso usar no celular?", "/perguntas/posso-usar-o-softpay-no-celular/", "Uso no telefone"),
           ("Preços", "/#pricing", "Usuários por plano")],
),
]
