# -*- coding: utf-8 -*-
from blocks import sec, p, ul, ol, h3, nota, exemplo, tabela, cards

CRUMB = [("Segmentos", "/segmentos/")]

def _c(nome):
    return CRUMB + [(nome, None)]

PAGINAS = [

# ---------------------------------------------------------------- MERCADINHO
dict(
  slug="segmentos/mercadinho",
  title="Sistema para Mercadinho: PDV, Estoque e Fiado | SoftPay",
  description="Sistema para mercadinho com PDV rápido, controle de estoque de muitos itens, fechamento de caixa e caderninho de fiado. Teste grátis por 7 dias.",
  h1="Sistema para mercadinho",
  intro="Mercadinho é volume: muitos itens baratos, giro rápido e margem apertada. O SoftPay organiza a venda no balcão, o que está acabando na prateleira e o fiado dos clientes de sempre.",
  breadcrumbs=_c("Mercadinho"),
  blocks=[
    '      <figure class="page-figure">\n'
    '        <img src="/assets/lojistas/mercadinho.webp" width="1600" height="667"\n'
    '             alt="Dona de mercadinho embalando produtos atrás do balcão, com prateleiras de mercearia ao fundo"\n'
    '             loading="lazy" decoding="async" />\n'
    '      </figure>',
    sec("A rotina de um mercadinho não perdoa lentidão",
      p("Fila no caixa em horário de pico, cliente esperando enquanto alguém procura o preço, o refrigerante que acabou sem ninguém perceber e o caderno de fiado que só uma pessoa sabe ler. Esses quatro problemas têm a mesma origem: a informação da loja não está em lugar nenhum além da cabeça de quem trabalha ali."),
      p("Um mercadinho de bairro chega a passar centenas de itens por dia. Sem registro, o dono termina a semana sabendo quanto entrou no caixa e sem a menor ideia de quanto sobrou."),
    ),
    sec("O que muda com o SoftPay",
      h3("Venda rápida no balcão"),
      p("O PDV registra a venda, calcula o troco e já baixa o estoque. Não existe um segundo momento de digitar tudo de novo no fim do dia — a venda que passou no caixa já é o dado do relatório."),
      h3("Estoque de muitos itens sem virar bagunça"),
      p("Produtos organizados por categoria, com preço de venda e custo. Como cada venda dá baixa automática, a quantidade em sistema acompanha a prateleira em vez de virar um número que ninguém confia."),
      h3("Fiado sem caderno"),
      p("O fiado é parte do mercadinho de bairro — o problema nunca foi vender a prazo, foi anotar em papel. Cada venda fiada fica no nome do cliente, com histórico, e o saldo para de depender da memória de quem estava no balcão."),
      h3("Fechamento de caixa"),
      p("No fim do expediente você confere o que o sistema registrou contra o que está na gaveta. A diferença aparece no mesmo dia, não no fim do mês."),
    ),
    sec("A conta que todo dono de mercadinho precisa fazer",
      p("Margem de mercadinho é apertada, então o custo de cada produto importa muito mais do que em outros comércios. Vender bastante e ganhar pouco é o resultado normal de não acompanhar o custo da mercadoria."),
      exemplo("Vendi R$ 25.480 no mês. Quanto ficou?", [
        ("Vendas do mês", "R$ 25.480,00", ""),
        ("Custo dos produtos vendidos (CMV)", "− R$ 20.900,00", "minus"),
        ("= Lucro bruto", "R$ 4.580,00", "result"),
        ("Aluguel, energia, funcionário", "− R$ 3.100,00", "minus"),
        ("= Resultado estimado", "R$ 1.480,00", "result final"),
      ], "Números fictícios, só para mostrar o raciocínio. Com custo e quantidade cadastrados no sistema, essa conta deixa de ser estimativa. Aprenda a fazê-la no guia <a href=\"/guias/como-calcular-lucro-da-loja/\">como calcular o lucro da loja</a>."),
    ),
    sec("Perguntas que o dono de mercadinho costuma fazer antes de contratar",
      p("Duas dúvidas aparecem sempre. A primeira é se dá para começar sem cadastrar todos os produtos de uma vez — dá: comece pelos itens de maior giro e vá completando conforme repõe. A segunda é se precisa de computador novo: não, o SoftPay roda no navegador, inclusive no celular."),
    ),
  ],
  faq=[
    ("O SoftPay serve para mercadinho pequeno, de uma pessoa só?",
     "Sim. O plano Comércio, de R$ 69/mês, cobre PDV, caixa, fiado e estoque essencial com 1 usuário — o perfil mais comum de mercadinho de bairro."),
    ("Preciso cadastrar todos os produtos antes de começar a usar?",
     "Não. O caminho prático é cadastrar primeiro os itens de maior giro e ir completando o restante conforme você repõe o estoque. O sistema já é útil desde o primeiro dia."),
    ("Funciona com leitor de código de barras?",
     "O SoftPay roda no navegador e o campo de busca do PDV aceita a leitura do código. Confirme com o suporte a compatibilidade do seu leitor antes de contratar."),
    ("Consigo controlar o fiado dos clientes?",
     "Sim. O caderninho de fiado está no plano Comércio. A partir do plano Loja, o sistema também envia cobrança por link de Pix pelo WhatsApp."),
    ("Dá para usar no celular durante a reposição?",
     "Sim. Como é acessado pelo navegador, você consulta estoque e preço pelo celular enquanto organiza a prateleira."),
  ],
  cta_title="Organize seu mercadinho em uma tarde",
  cta_text="Cadastre os produtos de maior giro, passe as primeiras vendas no PDV e veja o estoque acompanhar sozinho.",
  related=[
    ("Controle de estoque", "/solucoes/sistema-de-estoque/", "Custo, quantidade e curva ABC"),
    ("Controle de fiado", "/solucoes/controle-de-fiado/", "Quem deve, quanto e desde quando"),
    ("Como sair do caderno", "/guias/como-sair-do-caderno/", "O passo a passo da migração"),
  ],
),

# ------------------------------------------------------------ LOJA DE ROUPAS
dict(
  slug="segmentos/loja-de-roupas",
  title="Sistema para Loja de Roupas: Grade, Estoque e Clientes | SoftPay",
  description="Sistema para loja de roupas com controle de estoque por tamanho e cor, PDV, cadastro de clientes e loja online. Teste grátis por 7 dias.",
  h1="Sistema para loja de roupas",
  intro="Na loja de roupas, o mesmo modelo existe em vários tamanhos e cores — e é aí que a planilha desiste. O SoftPay controla cada variação separadamente e liga a venda ao cliente que comprou.",
  breadcrumbs=_c("Loja de roupas"),
  blocks=[
    sec("O problema não é o produto, é a variação",
      p("Uma camisa não é um item: é uma linha para cada combinação de tamanho e cor. Um modelo em cinco tamanhos e três cores são quinze controles diferentes. Multiplique por uma coleção inteira e fica claro por que planilha de loja de roupas sempre acaba desatualizada."),
      p("O efeito prático é conhecido: a vendedora promete uma peça que não existe mais no tamanho do cliente, ou a loja recompra um modelo que ainda tem seis unidades paradas no estoque no tamanho errado."),
    ),
    sec("O que muda com o SoftPay",
      h3("Estoque por variação"),
      p("Cada tamanho e cor tem a própria quantidade. Quando a venda passa no PDV, a baixa acontece na variação certa — não no modelo genérico."),
      h3("Custo por peça e margem real"),
      p("Roupa tem margem melhor que mercearia, mas também tem remarcação, queima de estoque e peça encalhada. Com o custo cadastrado, você enxerga a margem de cada modelo em vez de trabalhar com uma média que esconde os prejuízos."),
      h3("Curva ABC para a próxima compra"),
      p("A curva ABC separa o que sustenta o faturamento do que só ocupa arara. É a informação que decide o que repor na próxima viagem de compra e o que colocar em promoção."),
      h3("Cliente que volta"),
      p("Roupa vive de recompra. Com o cadastro de clientes ligado às vendas, você sabe quem comprou o quê e quando — base para cupom, fidelidade e um WhatsApp na hora certa."),
      h3("Vender também pela internet"),
      p("A partir do plano Loja, o catálogo online usa os produtos que você já cadastrou, com pagamento por Pix. Um estoque só, dois canais de venda."),
    ),
    sec("Uma dúvida honesta sobre grade",
      p("Nem toda loja precisa de grade completa desde o começo. Se você trabalha com peças únicas ou brechó, o cadastro simples resolve. A variação vale a pena quando o mesmo modelo se repete em vários tamanhos — que é o caso da maioria das lojas de moda."),
      nota("O estoque com variações, custo e curva ABC está disponível a partir do plano Loja (R$ 89/mês). O plano Comércio tem estoque essencial, sem grade.", "Em qual plano isso está"),
    ),
  ],
  faq=[
    ("O SoftPay controla tamanho e cor separadamente?",
     "Sim. O cadastro com variações permite controlar a mesma peça em tamanhos e cores diferentes, com quantidade própria para cada combinação. Está disponível a partir do plano Loja."),
    ("Consigo saber quais peças estão encalhadas?",
     "Sim. A curva ABC separa os produtos que sustentam o faturamento daqueles com pouco giro, o que ajuda a decidir o que remarcar e o que não recomprar."),
    ("Dá para vender pela internet com o mesmo estoque?",
     "Sim, a partir do plano Loja. A loja online usa o catálogo dos produtos já cadastrados e aceita Pix com confirmação automática, sem exigir um segundo cadastro."),
    ("Tem controle de clientes para trabalhar recompra?",
     "Sim. O cadastro de clientes com histórico de compras faz parte do sistema e é o que sustenta cupons e programa de fidelidade."),
    ("E se eu vender fiado ou no crediário próprio?",
     "O SoftPay tem o caderninho de fiado, com saldo por cliente. A partir do plano Loja ele também envia cobrança por link de Pix pelo WhatsApp."),
  ],
  cta_title="Teste com a sua própria grade",
  cta_text="Cadastre um modelo com todos os tamanhos e cores e veja o estoque baixar na variação certa a cada venda.",
  related=[
    ("Controle de estoque", "/solucoes/sistema-de-estoque/", "Variações, custo e curva ABC"),
    ("Loja online", "/solucoes/loja-online/", "Catálogo e Pix no mesmo estoque"),
    ("Controle de clientes", "/solucoes/controle-de-clientes/", "Histórico, cupom e fidelidade"),
  ],
),

# -------------------------------------------------------- LOJA DE VARIEDADES
dict(
  slug="segmentos/loja-de-variedades",
  title="Sistema para Loja de Variedades e Bazar | SoftPay",
  description="Sistema para loja de variedades: centenas de produtos organizados por categoria, PDV rápido, controle de custo e curva ABC. Teste grátis por 7 dias.",
  h1="Sistema para loja de variedades",
  intro="Loja de variedades vive de muitos produtos baratos e muito diferentes entre si. O desafio não é vender: é saber o que dá resultado no meio de centenas de itens.",
  breadcrumbs=_c("Loja de variedades"),
  blocks=[
    sec("Muito item, pouco valor unitário, decisão difícil",
      p("Uma loja de variedades pode ter mais itens no cadastro do que um supermercado pequeno — utilidade doméstica, papelaria, brinquedo, cosmético, presente. Cada um com fornecedor, custo e giro diferentes."),
      p("Como o valor unitário é baixo, o erro individual parece pequeno e passa despercebido. Somado ao longo de centenas de produtos, é exatamente aí que o lucro desaparece."),
    ),
    sec("O que muda com o SoftPay",
      h3("Organização por categoria"),
      p("Produtos agrupados por categoria tornam o cadastro navegável. Sem isso, encontrar um item entre centenas no meio de uma venda vira o gargalo do balcão."),
      h3("Custo registrado item a item"),
      p("Em variedades, a margem muda muito de um produto para outro. O que parece bom porque vende muito às vezes é justamente o de menor margem. Só dá para saber com o custo cadastrado."),
      h3("Curva ABC: o filtro que essa loja mais precisa"),
      p("Com centenas de itens, olhar tudo é impossível. A curva ABC reduz a decisão a um punhado de produtos que realmente movem o resultado — e mostra a cauda de itens que só ocupa prateleira e dinheiro."),
      h3("Atacado e varejo no mesmo produto"),
      p("Muita loja de variedades vende no volume para revendedor e na unidade para o consumidor. Os dois preços convivem no mesmo cadastro."),
    ),
    sec("Quanto dinheiro está parado nas suas prateleiras",
      p("Em variedades, o estoque costuma ser o maior ativo da loja e o mais invisível. Cada item na prateleira é dinheiro que já saiu do caixa e ainda não voltou."),
      exemplo("Estoque parado em três categorias", [
        ("Utilidade doméstica — 420 itens", "R$ 6.300,00", ""),
        ("Presentes e decoração — 180 itens", "R$ 4.950,00", ""),
        ("Papelaria — 610 itens", "R$ 2.840,00", ""),
        ("= Total investido em mercadoria", "R$ 14.090,00", "result final"),
      ], "Números fictícios. Com custo e quantidade cadastrados, esse total deixa de ser chute e vira um número que você consulta."),
    ),
  ],
  faq=[
    ("Tem limite de produtos cadastrados?",
     "O cadastro de produtos atende a operação de uma loja de variedades. Se você trabalha com um catálogo muito grande, confirme com o suporte antes de contratar."),
    ("Como organizo centenas de itens diferentes?",
     "Por categoria. O agrupamento é o que torna o cadastro navegável na hora da venda e o que permite analisar o resultado por grupo de produto."),
    ("Consigo vender no atacado e no varejo?",
     "Sim. O mesmo produto aceita preço de atacado e de varejo, útil para quem atende revendedor e consumidor final no mesmo balcão."),
    ("O sistema mostra quais produtos não giram?",
     "A curva ABC, disponível a partir do plano Loja, separa os itens por participação no resultado — é o que revela a cauda de produtos parados."),
    ("Preciso de nota fiscal?",
     "Depende do seu regime e do seu perfil de venda. Se precisar emitir, os planos Nota Fiscal e ERP Completo incluem a emissão. Consulte seu contador."),
  ],
  cta_title="Descubra o que realmente vende na sua loja",
  cta_text="Cadastre suas categorias, registre as vendas por uma semana e veja quais produtos sustentam o faturamento.",
  related=[
    ("Controle de estoque", "/solucoes/sistema-de-estoque/", "Categoria, custo e curva ABC"),
    ("Sistema PDV", "/solucoes/sistema-pdv/", "Venda rápida no balcão"),
    ("Como controlar estoque", "/guias/como-controlar-estoque/", "Método passo a passo"),
  ],
),

# ----------------------------------------------------------------- PAPELARIA
dict(
  slug="segmentos/papelaria",
  title="Sistema para Papelaria: PDV, Estoque e Atacado | SoftPay",
  description="Sistema para papelaria com PDV, controle de estoque, preço de atacado e varejo e emissão de cupom. Preparado para a volta às aulas. Teste grátis 7 dias.",
  h1="Sistema para papelaria",
  intro="Papelaria vive dois negócios ao mesmo tempo: a venda unitária do dia a dia e o pico da volta às aulas. O SoftPay dá conta dos dois sem que você perca o controle do estoque.",
  breadcrumbs=_c("Papelaria"),
  blocks=[
    sec("O ano da papelaria não é uniforme",
      p("Boa parte do faturamento se concentra em poucas semanas. Nesse período o volume explode, entra gente para ajudar no balcão e o controle costuma ser a primeira coisa a se perder — justamente quando mais dinheiro está em jogo."),
      p("No resto do ano, o desafio é o oposto: giro baixo em um catálogo grande, com material escolar, escritório, presente e serviços convivendo no mesmo cadastro."),
    ),
    sec("O que muda com o SoftPay",
      h3("PDV que aguenta o pico"),
      p("Venda registrada direto no caixa, com baixa automática de estoque. Na volta às aulas isso é a diferença entre saber o que ainda tem e prometer ao cliente um caderno que acabou de manhã."),
      h3("Atacado e varejo no mesmo cadastro"),
      p("Lista escolar fechada e venda por unidade são preços diferentes do mesmo produto. Os dois convivem sem cadastro duplicado."),
      h3("Estoque antes do pico"),
      p("Com o histórico de vendas registrado, a compra da próxima temporada deixa de ser feita de memória. Você vê o que saiu, em qual volume, e usa isso para não faltar nem sobrar."),
      h3("Cupom e nota"),
      p("Se a sua papelaria precisa emitir NFC-e, os planos Nota Fiscal e ERP Completo cobrem a emissão, com cadastro fiscal e pacote do contador."),
      h3("Mais de uma pessoa no balcão"),
      p("Na temporada, cada pessoa entra com o próprio login. O plano Loja permite até 3 usuários e o ERP Completo até 10."),
    ),
    sec("Serviços também entram na conta",
      p("Muita papelaria fatura com xerox, impressão, plastificação e encadernação. Esses itens podem ser cadastrados e vendidos pelo PDV como qualquer outro produto, para que o faturamento do balcão apareça inteiro no relatório — e não só a parte que tem mercadoria."),
    ),
  ],
  faq=[
    ("O sistema aguenta o volume da volta às aulas?",
     "O PDV foi feito para venda contínua no balcão, com baixa automática de estoque. Para o pico, vale cadastrar antes os itens de lista escolar e liberar os logins de quem vai ajudar no caixa."),
    ("Consigo trabalhar preço de atacado para lista escolar?",
     "Sim. O mesmo produto aceita preço de atacado e de varejo, sem precisar de dois cadastros."),
    ("Dá para vender serviços como xerox e encadernação?",
     "Sim. Serviços podem ser cadastrados e vendidos pelo PDV como qualquer item, para que apareçam no faturamento e nos relatórios."),
    ("Quantas pessoas podem usar ao mesmo tempo?",
     "Depende do plano: 1 usuário no Comércio, até 3 no Loja e até 10 no ERP Completo. Cada pessoa entra com o próprio acesso."),
    ("Emite cupom fiscal?",
     "A emissão de NFC-e está nos planos Nota Fiscal e ERP Completo. A ativação depende do seu cadastro fiscal — confirme a situação com o suporte e com seu contador."),
  ],
  cta_title="Chegue preparado na próxima temporada",
  cta_text="Cadastre os itens de lista escolar, registre as vendas e entre na volta às aulas sabendo o que tem em estoque.",
  related=[
    ("Sistema PDV", "/solucoes/sistema-pdv/", "Venda rápida com baixa de estoque"),
    ("NFC-e", "/solucoes/nfce/", "Cupom fiscal eletrônico"),
    ("Controle de estoque", "/solucoes/sistema-de-estoque/", "O que repor e quando"),
  ],
),

# ------------------------------------------------------------------ FARMACIA
dict(
  slug="segmentos/farmacia",
  title="Sistema para Farmácia: Gestão Comercial e PDV | SoftPay",
  description="Sistema para farmácia com PDV, controle de estoque, caixa, clientes e notas fiscais. Gestão comercial do balcão. Teste grátis por 7 dias.",
  h1="Sistema para farmácia",
  intro="O SoftPay cuida da gestão comercial da farmácia: PDV, estoque, caixa, clientes e notas fiscais. É importante dizer com clareza o que ele não faz — as obrigações específicas do setor continuam com os sistemas próprios.",
  breadcrumbs=_c("Farmácia"),
  blocks=[
    sec("O que o SoftPay cobre — e o que não cobre",
      p("Farmácia é um comércio regulado. Existem obrigações específicas do setor, como a escrituração de medicamentos controlados no SNGPC, que exigem sistemas homologados para essa finalidade."),
      nota("O SoftPay é um sistema de gestão comercial. Ele <strong>não substitui</strong> o SNGPC nem outras obrigações sanitárias e regulatórias do setor farmacêutico. Antes de contratar, confirme com o seu responsável técnico e com o seu contador o que a sua farmácia precisa ter.", "Leia isto antes de contratar"),
      p("Dito isso, a parte comercial da farmácia — que é grande — funciona como a de qualquer varejo com estoque: venda no balcão, controle do que tem na prateleira, fechamento de caixa, clientes recorrentes e emissão de nota."),
    ),
    sec("O que muda com o SoftPay",
      h3("PDV e fechamento de caixa"),
      p("Venda registrada no balcão com baixa automática de estoque e conferência de caixa no fim do expediente."),
      h3("Estoque de itens não controlados"),
      p("Perfumaria, higiene, cosmético, dermocosmético, acessório e conveniência representam uma fatia relevante do faturamento e não têm exigência especial de escrituração. É onde o controle de custo e giro faz diferença direta na margem."),
      h3("Clientes e recompra"),
      p("Uso contínuo é recompra previsível. O cadastro de clientes com histórico ajuda a acompanhar quem compra com regularidade."),
      h3("Convênio e fiado"),
      p("Muita farmácia de bairro trabalha com conta no fim do mês. O caderninho de fiado registra o saldo por cliente, e a partir do plano Loja envia cobrança por link de Pix."),
      h3("Nota fiscal"),
      p("Os planos Nota Fiscal e ERP Completo incluem a emissão de NFC-e e NF-e, com cadastro fiscal e pacote do contador."),
    ),
  ],
  faq=[
    ("O SoftPay atende as exigências do SNGPC?",
     "Não. O SoftPay é um sistema de gestão comercial e não substitui o SNGPC nem outras obrigações regulatórias do setor farmacêutico. Confirme com seu responsável técnico o que a sua farmácia precisa."),
    ("Então para que serve numa farmácia?",
     "Para a gestão comercial: PDV, controle de estoque, fechamento de caixa, cadastro de clientes, fiado e emissão de notas fiscais — a mesma base de qualquer varejo com estoque."),
    ("Controla validade dos produtos?",
     "Esse é um ponto a confirmar com o suporte antes de contratar, porque o controle de validade é crítico em farmácia e não deve ser assumido sem verificação."),
    ("Dá para trabalhar com conta mensal de cliente?",
     "Sim, pelo controle de fiado, que registra o saldo por cliente. A partir do plano Loja o sistema também envia cobrança por link de Pix pelo WhatsApp."),
    ("Emite NFC-e?",
     "Sim, nos planos Nota Fiscal e ERP Completo. A ativação depende do cadastro fiscal — confirme a situação com o suporte."),
  ],
  cta_title="Teste na parte comercial da sua farmácia",
  cta_text="Comece pelos itens de perfumaria e conveniência e veja o controle de estoque e caixa funcionando antes de decidir.",
  related=[
    ("Sistema PDV", "/solucoes/sistema-pdv/", "Venda e caixa no balcão"),
    ("Controle de clientes", "/solucoes/controle-de-clientes/", "Histórico e recompra"),
    ("NF-e e NFC-e", "/solucoes/nfe/", "Emissão de notas fiscais"),
  ],
),

# -------------------------------------------------------------- DISTRIBUIDORA
dict(
  slug="segmentos/distribuidora",
  title="Sistema para Distribuidora: Atacado, Estoque e NF-e | SoftPay",
  description="Sistema para distribuidora com controle de estoque em volume, preço de atacado e varejo, emissão de NF-e e gestão de clientes. Teste grátis 7 dias.",
  h1="Sistema para distribuidora",
  intro="Distribuidora trabalha com volume alto, margem por quantidade e nota fiscal em quase toda operação. O SoftPay junta estoque, atacado, varejo e emissão fiscal no mesmo lugar.",
  breadcrumbs=_c("Distribuidora"),
  blocks=[
    sec("Volume alto deixa pouco espaço para erro",
      p("Quando a operação é de centenas ou milhares de unidades, um erro de contagem não é um item a menos: é uma carga inteira de diferença entre o que o sistema diz e o que existe no depósito."),
      p("Some a isso a convivência de dois preços — atacado para o revendedor, varejo para o consumidor — e a exigência de nota fiscal na maior parte das saídas, e fica claro por que planilha não sustenta esse tipo de negócio por muito tempo."),
    ),
    sec("O que muda com o SoftPay",
      h3("Entradas e saídas registradas"),
      p("Cada compra de fornecedor e cada venda alimentam o mesmo estoque. O saldo deixa de ser reconstruído de memória no fim do mês."),
      h3("Atacado e varejo no mesmo produto"),
      p("Os dois preços convivem no cadastro, sem duplicar item e sem depender de quem está atendendo lembrar a tabela certa."),
      h3("Emissão de nota fiscal"),
      p("O plano ERP Completo inclui emissão de NF-e e NFC-e, com cadastro fiscal e pacote do contador. O plano Nota Fiscal atende quem só precisa da parte fiscal."),
      h3("Notas de fornecedor"),
      p("As notas recebidas podem ser consultadas dentro do sistema, e manifestadas no plano Nota Fiscal — parte da rotina de quem compra em volume."),
      h3("Clientes recorrentes"),
      p("Revendedor compra sempre. O cadastro com histórico mostra frequência e volume, base para negociar preço e prever reposição."),
      h3("Equipe e mais de um ponto"),
      p("O ERP Completo permite até 10 usuários, e o sistema controla filiais dentro da mesma conta — útil para quem tem depósito e loja separados."),
    ),
    sec("Uma observação sobre MDF-e e transporte",
      p("Operações de distribuição às vezes exigem documentos de transporte além da NF-e. O MDF-e consta nos planos como recurso em ativação — antes de contratar contando com ele, confirme a situação atual com o suporte e com o seu contador."),
    ),
  ],
  faq=[
    ("O SoftPay emite NF-e para distribuidora?",
     "Sim, nos planos Nota Fiscal e ERP Completo, com cadastro fiscal e pacote do contador. A emissão consta como em ativação — confirme a situação com o suporte antes de contratar."),
    ("Consigo trabalhar preço de atacado e varejo?",
     "Sim. O mesmo produto aceita os dois preços, sem cadastro duplicado."),
    ("E o MDF-e para transporte?",
     "O MDF-e aparece nos planos como recurso em ativação. Confirme com o suporte e com seu contador antes de contar com ele na sua operação."),
    ("Dá para controlar depósito e loja separadamente?",
     "O SoftPay permite controlar filiais dentro da mesma conta. Vale detalhar sua estrutura com o suporte para confirmar que atende ao seu caso."),
    ("Quantos usuários o plano de distribuidora comporta?",
     "O ERP Completo, de R$ 109/mês, permite até 10 usuários — normalmente o plano adequado para distribuidora, por incluir também a emissão fiscal."),
  ],
  cta_title="Teste com o seu volume real",
  cta_text="Cadastre os produtos de maior saída, registre entradas e vendas por alguns dias e confira o saldo contra o depósito.",
  related=[
    ("NF-e", "/solucoes/nfe/", "Emissão para operação de atacado"),
    ("Controle de estoque", "/solucoes/sistema-de-estoque/", "Entradas, saídas e custo"),
    ("Múltiplas lojas", "/solucoes/multiplas-lojas/", "Depósito e filiais"),
  ],
),

# ---------------------------------------------------------- PEQUENO COMERCIO
dict(
  slug="segmentos/pequeno-comercio",
  title="Sistema para Pequeno Comércio e Loja Pequena | SoftPay",
  description="Sistema de gestão para pequeno comércio: PDV, estoque, caixa e fiado em um só lugar, simples de começar. Teste grátis por 7 dias, sem cartão.",
  h1="Sistema para pequeno comércio",
  intro="Loja com uma ou duas pessoas, faturamento crescendo e controle ainda no caderno ou na planilha. O SoftPay foi desenhado exatamente para esse momento.",
  breadcrumbs=_c("Pequeno comércio"),
  blocks=[
    sec("O momento em que a planilha para de servir",
      p("Não existe tamanho mínimo de loja para precisar de sistema. O que indica a necessidade não é o faturamento, é a perda de controle — e ela costuma aparecer nesta ordem:"),
      ol("Você não sabe de cabeça o que tem em estoque de um produto que vende todo dia.",
         "O fiado passou do ponto em que dá para lembrar quem deve o quê.",
         "O fechamento do caixa não bate e ninguém sabe explicar a diferença.",
         "Você vendeu bem no mês e mesmo assim não sobrou dinheiro."),
      p("O quarto item é o mais importante — e o mais mal interpretado. Vender muito e não ter dinheiro quase nunca é problema de venda: é falta de controle de custo e de estoque."),
    ),
    sec("O que muda com o SoftPay",
      h3("Um lugar só"),
      p("PDV, estoque, caixa, fiado e clientes no mesmo sistema. A venda registrada no balcão alimenta tudo, sem redigitar nada no fim do dia."),
      h3("Começar é rápido"),
      p("Não precisa instalar nada nem comprar equipamento: roda no navegador, no computador ou no celular. Dá para cadastrar os produtos de maior giro e já começar a usar no mesmo dia."),
      h3("Cresce junto"),
      p("Se a loja crescer, o mesmo sistema comporta mais usuários, filiais, loja online e emissão de nota fiscal — sem trocar de ferramenta e sem recomeçar o cadastro."),
    ),
    sec("Quanto custa e o que cabe no seu momento",
      tabela(["Plano", "Preço", "Para quem"], [
        ["Comércio", "R$ 69/mês", "Loja de uma pessoa que quer sair do caderno: PDV, caixa, fiado e estoque essencial"],
        ["Loja", "R$ 89/mês", "Quem quer cobrar o fiado sozinho, vender online e ter estoque avançado. Até 3 usuários"],
        ["ERP Completo", "R$ 109/mês", "Quem precisa emitir nota fiscal e tem equipe maior. Até 10 usuários"],
        ["Nota Fiscal", "R$ 65/mês", "Quem só precisa emitir nota, sem PDV nem estoque"],
      ]),
      p("Todos podem ser testados por 7 dias, sem cartão de crédito. Se quiser entender melhor a decisão, leia <a href=\"/perguntas/loja-pequena-precisa-de-sistema/\">loja pequena precisa de sistema?</a>."),
    ),
  ],
  faq=[
    ("Minha loja é muito pequena. Vale a pena?",
     "O que indica a necessidade não é o tamanho, é a perda de controle: estoque incerto, fiado no caderno e dúvida sobre quanto sobrou no mês. Se você reconhece esses sintomas, vale."),
    ("É difícil de aprender?",
     "O SoftPay foi feito para quem nunca usou sistema de gestão. Além disso, o suporte humano ajuda na configuração inicial pelo WhatsApp."),
    ("Preciso comprar computador ou equipamento?",
     "Não. O sistema roda no navegador, inclusive no celular. Não é preciso instalar programa nem manter servidor na loja."),
    ("Consigo migrar o que já tenho em planilha?",
     "A importação de dados está disponível a partir do plano Loja. Fale com o suporte antes de migrar para conferir o formato do arquivo."),
    ("Se eu não gostar, perco o dinheiro?",
     "O teste de 7 dias não pede cartão de crédito. Você só paga se decidir continuar depois de testar."),
  ],
  cta_title="Comece pelo problema que mais te incomoda",
  cta_text="Estoque, fiado ou caixa: escolha um, organize no SoftPay durante o teste e veja se faz diferença na sua rotina.",
  related=[
    ("O que é sistema de gestão", "/sistema-de-gestao-para-pequenos-negocios/", "O guia completo"),
    ("Como sair do caderno", "/guias/como-sair-do-caderno/", "Passo a passo da migração"),
    ("Caderno ou sistema?", "/perguntas/caderno-ou-sistema/", "Comparação honesta"),
  ],
),
]
