# -*- coding: utf-8 -*-
from blocks import sec, p, ul, ol, h3, nota, exemplo, tabela, cards

CRUMB = [("Segmentos", "/segmentos/")]

def _c(nome):
    return CRUMB + [(nome, None)]

PAGINAS = [

# ---------------------------------------------------------------- MERCADINHO
dict(
  slug="segmentos/mercadinho",
  figura=("/assets/lojistas/mercadinho.webp",
          "Dona de mercadinho embalando produtos atrás do balcão, com prateleiras de mercearia ao fundo"),
  title="Sistema para Mercadinho: PDV, Estoque e Fiado | SoftPay",
  description="Sistema para mercadinho com PDV rápido, controle de estoque de muitos itens, fechamento de caixa e caderninho de fiado. Teste grátis por 7 dias.",
  h1="Sistema para mercadinho",
  intro="Mercadinho é volume: muitos itens baratos, giro rápido e margem apertada. O SoftPay organiza a venda no balcão, o que está acabando na prateleira e o fiado dos clientes de sempre.",
  breadcrumbs=_c("Mercadinho"),
  blocks=[
    sec("A rotina de um mercadinho não perdoa lentidão",
      p("Fila no caixa em horário de pico, cliente esperando enquanto alguém procura o preço, o refrigerante que acabou sem ninguém perceber e o caderno de fiado que só uma pessoa sabe ler. Esses quatro problemas têm a mesma origem: a informação da loja não está em lugar nenhum além da cabeça de quem trabalha ali."),
      p("Um mercadinho de bairro chega a passar centenas de itens por dia. Sem registro, o dono termina a semana sabendo quanto entrou no caixa e sem a menor ideia de quanto sobrou."),
    ),
    sec("O que muda com o SoftPay",
      h3("Venda rápida no balcão"),
      p("O PDV registra a venda, calcula o troco e já baixa o estoque. Não existe um segundo momento de digitar tudo de novo no fim do dia — a venda que passou no caixa já é o dado do relatório."),
      h3("Estoque de muitos itens sem virar bagunça"),
      p("Produtos organizados por categoria, com preço de venda e custo. Como cada venda dá baixa automática, a quantidade em sistema acompanha a prateleira em vez de virar um número que ninguém confia."),
      h3("Fiado sem caderno"),
      p("O fiado é parte do mercadinho de bairro — o problema nunca foi vender a prazo, foi anotar em papel. Cada venda fiada fica no nome do cliente, com histórico, e o saldo para de depender da memória de quem estava no balcão."),
      h3("Fechamento de caixa"),
      p("No fim do expediente você confere o que o sistema registrou contra o que está na gaveta. A diferença aparece no mesmo dia, não no fim do mês."),
    ),
    sec("A conta que todo dono de mercadinho precisa fazer",
      p("Margem de mercadinho é apertada, então o custo de cada produto importa muito mais do que em outros comércios. Vender bastante e ganhar pouco é o resultado normal de não acompanhar o custo da mercadoria."),
      exemplo("Vendi R$ 25.480 no mês. Quanto ficou?", [
        ("Vendas do mês", "R$ 25.480,00", ""),
        ("Custo dos produtos vendidos (CMV)", "− R$ 20.900,00", "minus"),
        ("= Lucro bruto", "R$ 4.580,00", "result"),
        ("Aluguel, energia, funcionário", "− R$ 3.100,00", "minus"),
        ("= Resultado estimado", "R$ 1.480,00", "result final"),
      ], "Números fictícios, só para mostrar o raciocínio. Com custo e quantidade cadastrados no sistema, essa conta deixa de ser estimativa. Aprenda a fazê-la no guia <a href=\"/guias/como-calcular-lucro-da-loja/\">como calcular o lucro da loja</a>."),
    ),
    sec("Perguntas que o dono de mercadinho costuma fazer antes de contratar",
      p("Duas dúvidas aparecem sempre. A primeira é se dá para começar sem cadastrar todos os produtos de uma vez — dá: comece pelos itens de maior giro e vá completando conforme repõe. A segunda é se precisa de computador novo: não, o SoftPay roda no navegador, inclusive no celular."),
    ),
  ],
  faq=[
    ("O SoftPay serve para mercadinho pequeno, de uma pessoa só?",
     "Sim. O plano Comércio, de R$ 69/mês, cobre PDV, caixa, fiado e estoque essencial com 1 usuário — o perfil mais comum de mercadinho de bairro."),
    ("Preciso cadastrar todos os produtos antes de começar a usar?",
     "Não. O caminho prático é cadastrar primeiro os itens de maior giro e ir completando o restante conforme você repõe o estoque. O sistema já é útil desde o primeiro dia."),
    ("Funciona com leitor de código de barras?",
     "O SoftPay roda no navegador e o campo de busca do PDV aceita a leitura do código. Confirme com o suporte a compatibilidade do seu leitor antes de contratar."),
    ("Consigo controlar o fiado dos clientes?",
     "Sim. O caderninho de fiado está no plano Comércio. A partir do plano Loja, o sistema também envia cobrança por link de Pix pelo WhatsApp."),
    ("Dá para usar no celular durante a reposição?",
     "Sim. Como é acessado pelo navegador, você consulta estoque e preço pelo celular enquanto organiza a prateleira."),
  ],
  cta_title="Organize seu mercadinho em uma tarde",
  cta_text="Cadastre os produtos de maior giro, passe as primeiras vendas no PDV e veja o estoque acompanhar sozinho.",
  related=[
    ("Controle de estoque", "/solucoes/sistema-de-estoque/", "Custo, quantidade e curva ABC"),
    ("Controle de fiado", "/solucoes/controle-de-fiado/", "Quem deve, quanto e desde quando"),
    ("Como sair do caderno", "/guias/como-sair-do-caderno/", "O passo a passo da migração"),
  ],
),

# ------------------------------------------------------------ LOJA DE ROUPAS
dict(
  slug="segmentos/loja-de-roupas",
  figura=("/assets/lojistas/loja-de-roupas.webp",
          "Lojista conferindo peças numa arara de roupas com um tablet na mão"),
  title="Sistema para Loja de Roupas com Grade | SoftPay",
  description="Sistema para loja de roupas com estoque por tamanho e cor, PDV, curva ABC para achar a peça parada, cadastro de clientes e loja online. Teste grátis 7 dias.",
  h1="Sistema para loja de roupas",
  intro="Na loja de roupas o mesmo modelo existe em vários tamanhos e cores — e é aí que a planilha desiste. O SoftPay controla cada variação separadamente, mostra qual peça está encalhada e liga a venda ao cliente que comprou.",
  breadcrumbs=_c("Loja de roupas"),
  blocks=[
    sec("A rotina de quem vende moda",
      p("O dia começa com a arrumação da vitrine e termina com o fechamento do caixa, mas entre uma coisa e outra a loja de roupas tem uma rotina que nenhum outro comércio tem: você não vende <em>um produto</em>, vende uma <strong>combinação</strong>."),
      p("A cliente pergunta se tem aquele vestido no M, na cor verde. A resposta certa exige saber o saldo de uma combinação específica, não do modelo. Multiplique por uma coleção inteira e você tem centenas de saldos para acompanhar — enquanto atende, prova e fecha venda."),
      p("Some a isso o calendário próprio da moda: coleção que entra, peça que precisa sair antes da próxima estação, remarcação, queima. Uma peça parada não é só espaço ocupado; é dinheiro que perde valor a cada mês."),
    ),
    sec("Os problemas que aparecem sempre",
      ul("<strong>A vendedora promete o que não existe.</strong> Diz que tem no tamanho da cliente, vai buscar e não acha. A venda morre ali.",
         "<strong>Você recompra o que já tem.</strong> Vê o modelo vendendo bem, repõe, e descobre que ainda havia seis unidades — todas no tamanho que ninguém pede.",
         "<strong>A peça encalhada só aparece no inventário.</strong> Quando você percebe, já passou da estação e a remarcação precisa ser agressiva.",
         "<strong>A margem é uma média que engana.</strong> Sem custo por peça, o modelo que dá 20% e o que dá 50% viram um número só.",
         "<strong>A cliente que volta é tratada como nova.</strong> Ninguém lembra o que ela levou da última vez, nem o tamanho dela."),
    ),
    sec("Como o SoftPay resolve",
      h3("Estoque por variação, não por modelo"),
      p("Cada combinação de tamanho e cor tem a própria quantidade. Quando a venda passa no PDV, a baixa acontece na variação certa — a resposta para “tem no M verde?” deixa de depender de alguém ir olhar na arara."),
      h3("Curva ABC para achar a peça parada"),
      p("A curva ABC separa o que sustenta o faturamento do que só ocupa espaço. É a informação que decide o que repor na próxima compra e o que precisa de remarcação <strong>antes</strong> de virar encalhe."),
      h3("Custo por peça e margem real"),
      p("Com o custo cadastrado, você enxerga a margem de cada modelo. Um item de giro alto com margem baixa pode ser ótimo negócio — mas você precisa saber que ele é de margem baixa para decidir."),
      h3("A cliente que volta"),
      p("O cadastro ligado às vendas mostra o que ela comprou e quando. É a base para cupom, fidelidade e um contato com propósito, em vez de disparo para uma lista inteira."),
      h3("Vender além da loja"),
      p("A partir do plano Loja, o catálogo online usa os mesmos produtos já cadastrados, com pagamento por Pix. Um estoque só, dois canais de venda."),
      h3("Registrar sem parar o atendimento"),
      p("A partir do plano Loja, você registra venda, entrada de mercadoria e fiado mandando uma mensagem ou um áudio pelo WhatsApp. Numa loja em que a vendedora está de pé, com a cliente no provador, isso muda quando o registro acontece. Veja o <a href=\"/solucoes/bot-whatsapp/\">bot do WhatsApp</a>."),
    ),
    sec("Um dia comum, do jeito que acontece",
      p("Sexta de movimento. A cliente pergunta por um vestido específico:"),
      ol("Você consulta o modelo no sistema e vê: <strong>P esgotado, M com 2, G com 1</strong>, todos na cor verde.",
         "Vende o M. A baixa acontece na variação certa, sem mexer no saldo dos outros tamanhos.",
         "A cliente já tem cadastro — a compra entra no histórico dela.",
         "No fim do dia, o fechamento de caixa compara o registrado com o que está na gaveta.",
         "No fim do mês, a curva ABC mostra que aquele vestido é classe A e que uma blusa da coleção passada não sai há sessenta dias."),
      p("A quinta linha é a que muda a compra do mês seguinte."),
      nota("Exemplo ilustrativo do fluxo. Os números da sua loja dependem dos seus próprios dados de venda e de custo.", "Sobre este exemplo"),
    ),
    sec("Perguntas que você passa a conseguir responder",
      ul("Tenho esse modelo no tamanho e na cor que a cliente quer?",
         "Quais peças não vendem há mais de 60 dias?",
         "Qual a margem real deste modelo, depois do custo?",
         "Quanto tenho investido em mercadoria parada?",
         "Quais clientes compraram nesta coleção e podem voltar na próxima?",
         "Que tamanho mais sai na minha loja — e qual eu compro demais?"),
    ),
    sec("Qual plano faz sentido",
      tabela(["Plano", "Preço", "Para a loja de roupas"], [
        ["Comércio", "R$ 69/mês", "PDV, caixa e estoque essencial. Serve para quem trabalha com peça única ou brechó, sem grade"],
        ["Loja", "R$ 89/mês", "<strong>O plano da loja de moda:</strong> variações de tamanho e cor, custo, curva ABC, loja online, fidelidade e registro pelo WhatsApp. Até 3 usuários"],
        ["ERP Completo", "R$ 109/mês", "Tudo da Loja mais emissão de NF-e e NFC-e, para quem precisa de nota. Até 10 usuários"],
      ]),
      p("Todos podem ser testados por 7 dias, sem cartão de crédito. Veja os <a href=\"/#pricing\">planos completos</a>."),
    ),
  ],
  faq=[
    ("O SoftPay controla tamanho e cor separadamente?",
     "Sim. O cadastro com variações permite controlar a mesma peça em tamanhos e cores diferentes, com quantidade própria para cada combinação. Está disponível a partir do plano Loja."),
    ("Como descubro quais peças estão encalhadas?",
     "Pela curva ABC, que separa os produtos por participação no resultado. Os itens de classe C são os que giram pouco — é onde costuma estar o dinheiro parado."),
    ("Dá para vender online com o mesmo estoque?",
     "Sim, a partir do plano Loja. A loja online usa o catálogo dos produtos já cadastrados e aceita Pix com confirmação automática, sem exigir um segundo cadastro."),
    ("Consigo saber a margem de cada modelo?",
     "Sim, desde que o custo esteja cadastrado. Sem custo, o sistema mostra faturamento; com custo, mostra margem."),
    ("Tem controle de clientes para trabalhar recompra?",
     "Sim. O cadastro com histórico de compras faz parte do sistema e sustenta cupons e programa de fidelidade, disponíveis a partir do plano Loja."),
    ("E se eu vender no crediário próprio ou fiado?",
     "O SoftPay tem o caderninho de fiado, com saldo por cliente. A partir do plano Loja ele também envia cobrança por link de Pix pelo WhatsApp."),
    ("Consigo registrar a venda sem parar o atendimento?",
     "A partir do plano Loja, sim: você manda uma mensagem ou áudio no WhatsApp e o SoftPay registra, respondendo em cerca de dois segundos."),
    ("Serve para brechó ou peça única?",
     "Serve. Se você não trabalha com grade, o cadastro simples do plano Comércio resolve. A variação vale a pena quando o mesmo modelo se repete em vários tamanhos."),
    ("Consigo importar minha planilha de produtos?",
     "A importação está disponível a partir do plano Loja. Fale com o suporte antes de migrar para conferir o formato do arquivo."),
  ],
  cta_title="Teste com a sua própria grade",
  cta_text="Cadastre um modelo com todos os tamanhos e cores e veja o estoque baixar na variação certa a cada venda. 7 dias grátis, sem cartão.",
  related=[("Controle de estoque", "/solucoes/sistema-de-estoque/", "Variações, custo e curva ABC"),
           ("Loja online", "/solucoes/loja-online/", "Catálogo e Pix no mesmo estoque"),
           ("Controle de clientes", "/solucoes/controle-de-clientes/", "Histórico, cupom e fidelidade"),
           ("Bot do WhatsApp", "/solucoes/bot-whatsapp/", "Registrar sem parar o atendimento"),
           ("Como controlar estoque", "/guias/como-controlar-estoque/", "O método, passo a passo"),
           ("Loja de variedades", "/segmentos/loja-de-variedades/", "Outro segmento com muitos itens")],
),

dict(
  slug="segmentos/loja-de-variedades",
  figura=("/assets/lojistas/loja-de-variedades.webp",
          "Dona de loja de variedades organizando produtos de utilidade doméstica na prateleira"),
  title="Sistema para Loja de Variedades e Bazar | SoftPay",
  description="Sistema para loja de variedades: centenas de produtos organizados por categoria, PDV rápido, controle de custo e curva ABC. Teste grátis por 7 dias.",
  h1="Sistema para loja de variedades",
  intro="Loja de variedades vive de muitos produtos baratos e muito diferentes entre si. O desafio não é vender: é saber o que dá resultado no meio de centenas de itens.",
  breadcrumbs=_c("Loja de variedades"),
  blocks=[
    sec("Muito item, pouco valor unitário, decisão difícil",
      p("Uma loja de variedades pode ter mais itens no cadastro do que um supermercado pequeno — utilidade doméstica, papelaria, brinquedo, cosmético, presente. Cada um com fornecedor, custo e giro diferentes."),
      p("Como o valor unitário é baixo, o erro individual parece pequeno e passa despercebido. Somado ao longo de centenas de produtos, é exatamente aí que o lucro desaparece."),
    ),
    sec("O que muda com o SoftPay",
      h3("Organização por categoria"),
      p("Produtos agrupados por categoria tornam o cadastro navegável. Sem isso, encontrar um item entre centenas no meio de uma venda vira o gargalo do balcão."),
      h3("Custo registrado item a item"),
      p("Em variedades, a margem muda muito de um produto para outro. O que parece bom porque vende muito às vezes é justamente o de menor margem. Só dá para saber com o custo cadastrado."),
      h3("Curva ABC: o filtro que essa loja mais precisa"),
      p("Com centenas de itens, olhar tudo é impossível. A curva ABC reduz a decisão a um punhado de produtos que realmente movem o resultado — e mostra a cauda de itens que só ocupa prateleira e dinheiro."),
      h3("Atacado e varejo no mesmo produto"),
      p("Muita loja de variedades vende no volume para revendedor e na unidade para o consumidor. Os dois preços convivem no mesmo cadastro."),
    ),
    sec("Quanto dinheiro está parado nas suas prateleiras",
      p("Em variedades, o estoque costuma ser o maior ativo da loja e o mais invisível. Cada item na prateleira é dinheiro que já saiu do caixa e ainda não voltou."),
      exemplo("Estoque parado em três categorias", [
        ("Utilidade doméstica — 420 itens", "R$ 6.300,00", ""),
        ("Presentes e decoração — 180 itens", "R$ 4.950,00", ""),
        ("Papelaria — 610 itens", "R$ 2.840,00", ""),
        ("= Total investido em mercadoria", "R$ 14.090,00", "result final"),
      ], "Números fictícios. Com custo e quantidade cadastrados, esse total deixa de ser chute e vira um número que você consulta."),
    ),
  ],
  faq=[
    ("Tem limite de produtos cadastrados?",
     "O cadastro de produtos atende a operação de uma loja de variedades. Se você trabalha com um catálogo muito grande, confirme com o suporte antes de contratar."),
    ("Como organizo centenas de itens diferentes?",
     "Por categoria. O agrupamento é o que torna o cadastro navegável na hora da venda e o que permite analisar o resultado por grupo de produto."),
    ("Consigo vender no atacado e no varejo?",
     "Sim. O mesmo produto aceita preço de atacado e de varejo, útil para quem atende revendedor e consumidor final no mesmo balcão."),
    ("O sistema mostra quais produtos não giram?",
     "A curva ABC, disponível a partir do plano Loja, separa os itens por participação no resultado — é o que revela a cauda de produtos parados."),
    ("Preciso de nota fiscal?",
     "Depende do seu regime e do seu perfil de venda. Se precisar emitir, os planos Nota Fiscal e ERP Completo incluem a emissão. Consulte seu contador."),
  ],
  cta_title="Descubra o que realmente vende na sua loja",
  cta_text="Cadastre suas categorias, registre as vendas por uma semana e veja quais produtos sustentam o faturamento.",
  related=[
    ("Controle de estoque", "/solucoes/sistema-de-estoque/", "Categoria, custo e curva ABC"),
    ("Sistema PDV", "/solucoes/sistema-pdv/", "Venda rápida no balcão"),
    ("Como controlar estoque", "/guias/como-controlar-estoque/", "Método passo a passo"),
  ],
),

# ----------------------------------------------------------------- PAPELARIA
dict(
  slug="segmentos/papelaria",
  figura=("/assets/lojistas/papelaria.webp",
          "Atendente de papelaria finalizando a venda no caixa, com material escolar ao fundo"),
  title="Sistema para Papelaria: PDV, Estoque e Atacado | SoftPay",
  description="Sistema para papelaria com PDV, controle de estoque, preço de atacado e varejo e emissão de cupom. Preparado para a volta às aulas. Teste grátis 7 dias.",
  h1="Sistema para papelaria",
  intro="Papelaria vive dois negócios ao mesmo tempo: a venda unitária do dia a dia e o pico da volta às aulas. O SoftPay dá conta dos dois sem que você perca o controle do estoque.",
  breadcrumbs=_c("Papelaria"),
  blocks=[
    sec("O ano da papelaria não é uniforme",
      p("Boa parte do faturamento se concentra em poucas semanas. Nesse período o volume explode, entra gente para ajudar no balcão e o controle costuma ser a primeira coisa a se perder — justamente quando mais dinheiro está em jogo."),
      p("No resto do ano, o desafio é o oposto: giro baixo em um catálogo grande, com material escolar, escritório, presente e serviços convivendo no mesmo cadastro."),
    ),
    sec("O que muda com o SoftPay",
      h3("PDV que aguenta o pico"),
      p("Venda registrada direto no caixa, com baixa automática de estoque. Na volta às aulas isso é a diferença entre saber o que ainda tem e prometer ao cliente um caderno que acabou de manhã."),
      h3("Atacado e varejo no mesmo cadastro"),
      p("Lista escolar fechada e venda por unidade são preços diferentes do mesmo produto. Os dois convivem sem cadastro duplicado."),
      h3("Estoque antes do pico"),
      p("Com o histórico de vendas registrado, a compra da próxima temporada deixa de ser feita de memória. Você vê o que saiu, em qual volume, e usa isso para não faltar nem sobrar."),
      h3("Cupom e nota"),
      p("Se a sua papelaria precisa emitir NFC-e, os planos Nota Fiscal e ERP Completo cobrem a emissão, com cadastro fiscal e pacote do contador."),
      h3("Mais de uma pessoa no balcão"),
      p("Na temporada, cada pessoa entra com o próprio login. O plano Loja permite até 3 usuários e o ERP Completo até 10."),
    ),
    sec("Serviços também entram na conta",
      p("Muita papelaria fatura com xerox, impressão, plastificação e encadernação. Esses itens podem ser cadastrados e vendidos pelo PDV como qualquer outro produto, para que o faturamento do balcão apareça inteiro no relatório — e não só a parte que tem mercadoria."),
    ),
  ],
  faq=[
    ("O sistema aguenta o volume da volta às aulas?",
     "O PDV foi feito para venda contínua no balcão, com baixa automática de estoque. Para o pico, vale cadastrar antes os itens de lista escolar e liberar os logins de quem vai ajudar no caixa."),
    ("Consigo trabalhar preço de atacado para lista escolar?",
     "Sim. O mesmo produto aceita preço de atacado e de varejo, sem precisar de dois cadastros."),
    ("Dá para vender serviços como xerox e encadernação?",
     "Sim. Serviços podem ser cadastrados e vendidos pelo PDV como qualquer item, para que apareçam no faturamento e nos relatórios."),
    ("Quantas pessoas podem usar ao mesmo tempo?",
     "Depende do plano: 1 usuário no Comércio, até 3 no Loja e até 10 no ERP Completo. Cada pessoa entra com o próprio acesso."),
    ("Emite cupom fiscal?",
     "A emissão de NFC-e está nos planos Nota Fiscal e ERP Completo. A ativação depende do seu cadastro fiscal — confirme a situação com o suporte e com seu contador."),
  ],
  cta_title="Chegue preparado na próxima temporada",
  cta_text="Cadastre os itens de lista escolar, registre as vendas e entre na volta às aulas sabendo o que tem em estoque.",
  related=[
    ("Sistema PDV", "/solucoes/sistema-pdv/", "Venda rápida com baixa de estoque"),
    ("NFC-e", "/solucoes/nfce/", "Cupom fiscal eletrônico"),
    ("Controle de estoque", "/solucoes/sistema-de-estoque/", "O que repor e quando"),
  ],
),

# ------------------------------------------------------------------ FARMACIA
dict(
  slug="segmentos/farmacia",
  figura=("/assets/lojistas/farmacia.webp",
          "Atendente de farmácia usando o computador no balcão, com prateleiras de produtos ao fundo"),
  title="Sistema para Farmácia: Gestão Comercial e PDV | SoftPay",
  description="Sistema para farmácia com PDV, controle de estoque, caixa, clientes e notas fiscais. Gestão comercial do balcão. Teste grátis por 7 dias.",
  h1="Sistema para farmácia",
  intro="O SoftPay cuida da gestão comercial da farmácia: PDV, estoque, caixa, clientes e notas fiscais. É importante dizer com clareza o que ele não faz — as obrigações específicas do setor continuam com os sistemas próprios.",
  breadcrumbs=_c("Farmácia"),
  blocks=[
    sec("O que o SoftPay cobre — e o que não cobre",
      p("Farmácia é um comércio regulado. Existem obrigações específicas do setor, como a escrituração de medicamentos controlados no SNGPC, que exigem sistemas homologados para essa finalidade."),
      nota("O SoftPay é um sistema de gestão comercial. Ele <strong>não substitui</strong> o SNGPC nem outras obrigações sanitárias e regulatórias do setor farmacêutico. Antes de contratar, confirme com o seu responsável técnico e com o seu contador o que a sua farmácia precisa ter.", "Leia isto antes de contratar"),
      p("Dito isso, a parte comercial da farmácia — que é grande — funciona como a de qualquer varejo com estoque: venda no balcão, controle do que tem na prateleira, fechamento de caixa, clientes recorrentes e emissão de nota."),
    ),
    sec("O que muda com o SoftPay",
      h3("PDV e fechamento de caixa"),
      p("Venda registrada no balcão com baixa automática de estoque e conferência de caixa no fim do expediente."),
      h3("Estoque de itens não controlados"),
      p("Perfumaria, higiene, cosmético, dermocosmético, acessório e conveniência representam uma fatia relevante do faturamento e não têm exigência especial de escrituração. É onde o controle de custo e giro faz diferença direta na margem."),
      h3("Clientes e recompra"),
      p("Uso contínuo é recompra previsível. O cadastro de clientes com histórico ajuda a acompanhar quem compra com regularidade."),
      h3("Convênio e fiado"),
      p("Muita farmácia de bairro trabalha com conta no fim do mês. O caderninho de fiado registra o saldo por cliente, e a partir do plano Loja envia cobrança por link de Pix."),
      h3("Nota fiscal"),
      p("Os planos Nota Fiscal e ERP Completo incluem a emissão de NFC-e e NF-e, com cadastro fiscal e pacote do contador."),
    ),
  ],
  faq=[
    ("O SoftPay atende as exigências do SNGPC?",
     "Não. O SoftPay é um sistema de gestão comercial e não substitui o SNGPC nem outras obrigações regulatórias do setor farmacêutico. Confirme com seu responsável técnico o que a sua farmácia precisa."),
    ("Então para que serve numa farmácia?",
     "Para a gestão comercial: PDV, controle de estoque, fechamento de caixa, cadastro de clientes, fiado e emissão de notas fiscais — a mesma base de qualquer varejo com estoque."),
    ("Controla validade dos produtos?",
     "Esse é um ponto a confirmar com o suporte antes de contratar, porque o controle de validade é crítico em farmácia e não deve ser assumido sem verificação."),
    ("Dá para trabalhar com conta mensal de cliente?",
     "Sim, pelo controle de fiado, que registra o saldo por cliente. A partir do plano Loja o sistema também envia cobrança por link de Pix pelo WhatsApp."),
    ("Emite NFC-e?",
     "Sim, nos planos Nota Fiscal e ERP Completo. A ativação depende do cadastro fiscal — confirme a situação com o suporte."),
  ],
  cta_title="Teste na parte comercial da sua farmácia",
  cta_text="Comece pelos itens de perfumaria e conveniência e veja o controle de estoque e caixa funcionando antes de decidir.",
  related=[
    ("Sistema PDV", "/solucoes/sistema-pdv/", "Venda e caixa no balcão"),
    ("Controle de clientes", "/solucoes/controle-de-clientes/", "Histórico e recompra"),
    ("NF-e e NFC-e", "/solucoes/nfe/", "Emissão de notas fiscais"),
  ],
),

# -------------------------------------------------------------- DISTRIBUIDORA
dict(
  slug="segmentos/distribuidora",
  figura=("/assets/lojistas/distribuidora.webp",
          "Funcionário de distribuidora de bebidas conferindo estoque pelo celular entre engradados"),
  title="Sistema para Distribuidora: Estoque e NF-e | SoftPay",
  description="Sistema para distribuidora com controle de estoque em volume, preço de atacado e varejo, emissão de NF-e e gestão de clientes. Teste grátis 7 dias.",
  h1="Sistema para distribuidora",
  intro="Distribuidora trabalha com volume alto, margem por quantidade e nota fiscal em quase toda operação. O SoftPay junta estoque, atacado, varejo e emissão fiscal no mesmo lugar.",
  breadcrumbs=_c("Distribuidora"),
  blocks=[
    sec("Volume alto deixa pouco espaço para erro",
      p("Quando a operação é de centenas ou milhares de unidades, um erro de contagem não é um item a menos: é uma carga inteira de diferença entre o que o sistema diz e o que existe no depósito."),
      p("Some a isso a convivência de dois preços — atacado para o revendedor, varejo para o consumidor — e a exigência de nota fiscal na maior parte das saídas, e fica claro por que planilha não sustenta esse tipo de negócio por muito tempo."),
    ),
    sec("O que muda com o SoftPay",
      h3("Entradas e saídas registradas"),
      p("Cada compra de fornecedor e cada venda alimentam o mesmo estoque. O saldo deixa de ser reconstruído de memória no fim do mês."),
      h3("Atacado e varejo no mesmo produto"),
      p("Os dois preços convivem no cadastro, sem duplicar item e sem depender de quem está atendendo lembrar a tabela certa."),
      h3("Emissão de nota fiscal"),
      p("O plano ERP Completo inclui emissão de NF-e e NFC-e, com cadastro fiscal e pacote do contador. O plano Nota Fiscal atende quem só precisa da parte fiscal."),
      h3("Notas de fornecedor"),
      p("As notas recebidas podem ser consultadas dentro do sistema, e manifestadas no plano Nota Fiscal — parte da rotina de quem compra em volume."),
      h3("Clientes recorrentes"),
      p("Revendedor compra sempre. O cadastro com histórico mostra frequência e volume, base para negociar preço e prever reposição."),
      h3("Equipe e mais de um ponto"),
      p("O ERP Completo permite até 10 usuários, e o sistema controla filiais dentro da mesma conta — útil para quem tem depósito e loja separados."),
    ),
    sec("Uma observação sobre MDF-e e transporte",
      p("Operações de distribuição às vezes exigem documentos de transporte além da NF-e. O MDF-e consta nos planos como recurso em ativação — antes de contratar contando com ele, confirme a situação atual com o suporte e com o seu contador."),
    ),
  ],
  faq=[
    ("O SoftPay emite NF-e para distribuidora?",
     "Sim, nos planos Nota Fiscal e ERP Completo, com cadastro fiscal e pacote do contador. A emissão consta como em ativação — confirme a situação com o suporte antes de contratar."),
    ("Consigo trabalhar preço de atacado e varejo?",
     "Sim. O mesmo produto aceita os dois preços, sem cadastro duplicado."),
    ("E o MDF-e para transporte?",
     "O MDF-e aparece nos planos como recurso em ativação. Confirme com o suporte e com seu contador antes de contar com ele na sua operação."),
    ("Dá para controlar depósito e loja separadamente?",
     "O SoftPay permite controlar filiais dentro da mesma conta. Vale detalhar sua estrutura com o suporte para confirmar que atende ao seu caso."),
    ("Quantos usuários o plano de distribuidora comporta?",
     "O ERP Completo, de R$ 109/mês, permite até 10 usuários — normalmente o plano adequado para distribuidora, por incluir também a emissão fiscal."),
  ],
  cta_title="Teste com o seu volume real",
  cta_text="Cadastre os produtos de maior saída, registre entradas e vendas por alguns dias e confira o saldo contra o depósito.",
  related=[
    ("NF-e", "/solucoes/nfe/", "Emissão para operação de atacado"),
    ("Controle de estoque", "/solucoes/sistema-de-estoque/", "Entradas, saídas e custo"),
    ("Múltiplas lojas", "/solucoes/multiplas-lojas/", "Depósito e filiais"),
  ],
),

# ---------------------------------------------------------- PEQUENO COMERCIO
# ------------------------------------------------- CELULARES E ACESSÓRIOS
dict(
  slug="segmentos/loja-de-celulares-e-acessorios",
  figura=("/assets/lojistas/celular-balcao.webp",
          "Comerciante usando o celular sobre o balcão da loja"),
  title="Sistema para Loja de Celulares e Acessórios | SoftPay",
  description="Sistema para loja de celulares com controle de aparelhos e acessórios, custo e margem por categoria, PDV, fiado e nota fiscal. Teste grátis por 7 dias.",
  h1="Sistema para loja de celulares e acessórios",
  intro="Na mesma loja convivem dois negócios: o aparelho, que é caro e sai pouco, e o acessório, que é barato e sai o tempo todo. Eles precisam de controles diferentes — e é isso que costuma faltar.",
  breadcrumbs=_c("Celulares e acessórios"),
  blocks=[
    sec("Dois negócios no mesmo balcão",
      p("Um aparelho representa centenas ou milhares de reais parados na vitrine, com margem apertada e risco de desvalorizar a cada lançamento. Uma capa custa poucos reais, tem margem larga e sai às dezenas."),
      p("Tratar os dois com o mesmo controle é o erro mais comum. O faturamento vem dos aparelhos, mas boa parte do <strong>lucro</strong> costuma vir dos acessórios — e sem custo cadastrado por item, isso fica invisível."),
      p("Some a rotina de troca rápida: modelo novo sai, o anterior precisa girar antes de perder valor. Aparelho encalhado não é só espaço ocupado, é dinheiro que encolhe sozinho."),
    ),
    sec("Os problemas que aparecem sempre",
      ul("<strong>Você não sabe qual categoria dá lucro.</strong> Vende bem em aparelho, mas o resultado do mês não acompanha.",
         "<strong>Acessório some sem explicação.</strong> Item pequeno e barato é o que mais sai do estoque sem registro.",
         "<strong>O aparelho antigo fica.</strong> Quando você percebe, o modelo já desvalorizou e a margem virou prejuízo.",
         "<strong>A mesma capa tem dez versões.</strong> Modelo de aparelho, cor, material — e a planilha não dá conta.",
         "<strong>O fiado do cliente conhecido</strong> vira caderno, e o valor de um aparelho fiado não é pequeno."),
    ),
    sec("Como o SoftPay resolve",
      h3("Custo e margem por item, não por média"),
      p("Com o custo cadastrado em cada produto, você vê a margem do aparelho e a do acessório separadamente. É o que revela de onde vem o lucro de verdade."),
      h3("Variações para acessório"),
      p("Capa, película e cabo existem em versões por modelo e cor. O cadastro com variações controla cada combinação com quantidade própria, a partir do plano Loja."),
      h3("Curva ABC para girar o que está parado"),
      p("A curva ABC mostra o que sustenta o faturamento e o que está encalhado. Num segmento em que o produto desvaloriza com o tempo, saber disso cedo vale dinheiro."),
      h3("Fiado com valor alto"),
      p("Vender um aparelho fiado é diferente de fiar uma bebida. O saldo fica registrado no nome do cliente e, a partir do plano Loja, o sistema envia cobrança por link de Pix pelo WhatsApp."),
      h3("Nota fiscal"),
      p("Se você precisa emitir, os planos Nota Fiscal e ERP Completo cobrem NFC-e e NF-e, com cadastro fiscal e pacote do contador. A emissão consta como em ativação — confirme com o suporte."),
      nota("O SoftPay controla o produto, o custo e a venda. Ele <strong>não</strong> faz controle de IMEI, ordem de serviço nem gestão de assistência técnica. Se a sua loja depende disso, confirme com o suporte antes de contratar.", "O que ele não faz"),
    ),
    sec("Um dia comum, do jeito que acontece",
      p("Cliente entra para comprar um aparelho e sai com mais duas coisas:"),
      ol("Você registra a venda do aparelho no PDV, com a forma de pagamento.",
         "Acrescenta a capa e a película na mesma venda — cada uma baixa do próprio estoque.",
         "O cliente fica com metade fiada; o saldo entra no nome dele.",
         "No fim do mês, o relatório mostra que o aparelho deu 12% de margem e os acessórios, 55%.",
         "A curva ABC aponta dois modelos parados há 90 dias, ainda a tempo de remarcar."),
      nota("Exemplo ilustrativo do fluxo. As margens da sua loja dependem dos seus próprios dados de custo e venda.", "Sobre este exemplo"),
    ),
    sec("Perguntas que você passa a conseguir responder",
      ul("Qual margem real do aparelho e qual a do acessório?",
         "Quanto tenho investido em aparelhos parados na vitrine?",
         "Que modelo não vende há mais de 60 dias?",
         "Quanto os clientes ainda me devem em aparelho fiado?",
         "Qual acessório mais sai junto com cada aparelho?"),
    ),
    sec("Qual plano faz sentido",
      tabela(["Plano", "Preço", "Para a loja de celulares"], [
        ["Comércio", "R$ 69/mês", "PDV, caixa, fiado e estoque essencial. Para quem trabalha com poucos itens"],
        ["Loja", "R$ 89/mês", "<strong>O plano da loja de celulares:</strong> custo, curva ABC, variações de acessório, cobrança do fiado por Pix e registro pelo WhatsApp"],
        ["ERP Completo", "R$ 109/mês", "Tudo da Loja mais emissão de NFC-e e NF-e, para quem precisa dar nota no aparelho"],
      ]),
      p("Todos com 7 dias de teste, sem cartão. Veja os <a href=\"/#pricing\">planos completos</a>."),
    ),
  ],
  faq=[
    ("O SoftPay controla IMEI de aparelho?",
     "Não. Ele controla produto, custo, estoque e venda. Controle de IMEI e ordem de serviço não fazem parte do sistema — confirme com o suporte se isso for decisivo para a sua loja."),
    ("Consigo separar a margem de aparelho e de acessório?",
     "Sim, desde que o custo esteja cadastrado em cada produto. É o que mostra de onde vem o lucro, já que faturamento e lucro costumam vir de categorias diferentes nesse segmento."),
    ("Dá para controlar capa por modelo de aparelho e cor?",
     "Sim, com o cadastro de variações, disponível a partir do plano Loja."),
    ("Como controlo aparelho vendido fiado?",
     "O saldo fica registrado no nome do cliente. A partir do plano Loja, o sistema envia cobrança por link de Pix pelo WhatsApp."),
    ("Emite nota fiscal para a venda do aparelho?",
     "Sim, nos planos Nota Fiscal e ERP Completo. A emissão consta como em ativação — confirme a situação com o suporte antes de contratar."),
    ("Como descubro aparelho parado antes de desvalorizar?",
     "Pela curva ABC, que separa os produtos por giro. Num segmento em que o produto perde valor com o tempo, é a informação que evita prejuízo."),
    ("Serve para assistência técnica?",
     "O SoftPay cobre a parte comercial: venda, estoque, caixa e clientes. Não tem ordem de serviço nem controle de reparo."),
  ],
  cta_title="Descubra de onde vem o seu lucro",
  cta_text="Cadastre alguns aparelhos e acessórios com custo e veja a margem de cada categoria. 7 dias grátis, sem cartão.",
  related=[("Controle de estoque", "/solucoes/sistema-de-estoque/", "Custo, variações e curva ABC"),
           ("Controle de fiado", "/solucoes/controle-de-fiado/", "Fiado de valor alto"),
           ("NF-e e NFC-e", "/solucoes/nfe/", "Nota na venda do aparelho"),
           ("Como calcular margem", "/guias/como-calcular-margem-de-lucro/", "A conta por trás do preço")],
),

# ---------------------------------------------------------------- AUTOPEÇAS
dict(
  slug="segmentos/loja-de-autopecas",
  figura=("/assets/lojistas/distribuidora.webp",
          "Funcionário conferindo estoque entre prateleiras do depósito"),
  title="Sistema para Loja de Autopeças | SoftPay",
  description="Sistema para autopeças com catálogo amplo, busca rápida de peça, controle de estoque, curva ABC para itens parados, fiado e nota fiscal. Teste grátis 7 dias.",
  h1="Sistema para loja de autopeças",
  intro="Autopeças é o comércio do catálogo gigante: milhares de códigos, muitos que saem uma vez por ano e alguns que não podem faltar nunca. O problema não é vender — é achar, e saber o que vale a pena manter.",
  breadcrumbs=_c("Autopeças"),
  blocks=[
    sec("A rotina de quem vende peça",
      p("O cliente chega com o carro, o ano e uma dúvida. Alguém precisa descobrir se a peça existe, onde ela está e quanto custa — enquanto o cliente espera no balcão e, muitas vezes, com o carro parado na oficina."),
      p("O catálogo de uma autopeças pequena já passa de mil itens. Boa parte é de <strong>baixo giro</strong>: peça que sai uma ou duas vezes por ano, mas que precisa estar lá quando alguém pedir. Esse é o dilema do segmento — cada item parado é dinheiro investido, e tirar do estoque significa perder a venda."),
      p("Ainda há a rotina do crédito: oficina que compra durante o mês e acerta depois. Não é fiado de bairro; são valores que se acumulam."),
    ),
    sec("Os problemas que aparecem sempre",
      ul("<strong>Ninguém acha a peça.</strong> Ela existe no estoque, mas quem está no balcão não localiza e a venda vai embora.",
         "<strong>O catálogo cresce sem critério.</strong> Item entra e nunca mais sai, e o capital vai ficando preso na prateleira.",
         "<strong>Você não sabe quanto tem parado.</strong> Sem custo e quantidade cadastrados, o valor investido é um chute.",
         "<strong>A conta da oficina descontrola.</strong> Compras ao longo do mês, sem um saldo confiável no fechamento.",
         "<strong>Falta o que não podia faltar.</strong> A peça de giro alto acaba e ninguém percebeu a tempo."),
    ),
    sec("Como o SoftPay resolve",
      h3("Cadastro que permite encontrar"),
      p("Produtos com código, descrição e categoria. A busca do PDV localiza pelo que você cadastrou — quanto melhor o cadastro, mais rápido o atendimento no balcão."),
      h3("Curva ABC: o filtro que este segmento mais precisa"),
      p("Com mil itens, olhar tudo é impossível. A curva ABC separa os poucos que sustentam o faturamento da longa cauda de baixo giro. É a informação que decide o que repor sempre e o que não comprar mais."),
      h3("Quanto dinheiro está parado"),
      p("Com custo e quantidade cadastrados, o valor investido em peças deixa de ser estimativa. Em autopeças esse número costuma ser o maior ativo da loja — e o mais invisível."),
      h3("Conta da oficina"),
      p("O caderninho de fiado registra o saldo por cliente, com o histórico das compras que o formam. A partir do plano Loja, a cobrança sai por link de Pix no WhatsApp."),
      h3("Atacado e varejo"),
      p("Oficina compra num preço, consumidor final em outro. Os dois convivem no mesmo cadastro, sem produto duplicado."),
      h3("Nota fiscal"),
      p("Venda para oficina normalmente exige nota. Os planos Nota Fiscal e ERP Completo cobrem NF-e e NFC-e, com cadastro fiscal e pacote do contador."),
      nota("O SoftPay <strong>não</strong> traz catálogo de peças por montadora, aplicação por veículo nem tabela de equivalência. O cadastro dos produtos é seu. Se a sua operação depende de catálogo automotivo pronto, confirme com o suporte antes de contratar.", "O que ele não faz"),
    ),
    sec("Um dia comum, do jeito que acontece",
      p("Segunda de manhã, oficina liga pedindo três itens:"),
      ol("Você busca cada peça pelo código no PDV e confere o saldo na hora.",
         "Registra a venda no preço de atacado, na conta da oficina.",
         "O saldo do mês da oficina fica visível no cadastro dela.",
         "Emite a nota da operação, se o seu plano incluir emissão.",
         "No fim do mês, a curva ABC mostra 40 itens sem saída há mais de um ano — capital que dá para liberar."),
      nota("Exemplo ilustrativo do fluxo. Os números da sua loja dependem dos seus próprios dados.", "Sobre este exemplo"),
    ),
    sec("Perguntas que você passa a conseguir responder",
      ul("Tenho essa peça e quanto custa?",
         "Quanto dinheiro está parado em itens que não giram?",
         "Quais peças nunca saíram desde que entraram?",
         "Quanto cada oficina me deve neste mês?",
         "Quais peças não podem faltar, pelo histórico de saída?"),
    ),
    sec("Qual plano faz sentido",
      tabela(["Plano", "Preço", "Para a autopeças"], [
        ["Comércio", "R$ 69/mês", "PDV, caixa, fiado e estoque essencial. Catálogo pequeno, sem nota"],
        ["Loja", "R$ 89/mês", "Custo, curva ABC, cobrança do fiado por Pix e registro pelo WhatsApp. Até 3 usuários"],
        ["ERP Completo", "R$ 109/mês", "<strong>O plano de quem vende para oficina:</strong> tudo da Loja mais NF-e e NFC-e. Até 10 usuários"],
      ]),
      p("Todos com 7 dias de teste, sem cartão. Veja os <a href=\"/#pricing\">planos completos</a>."),
    ),
  ],
  faq=[
    ("O SoftPay tem catálogo de peças por veículo?",
     "Não. Ele não traz catálogo automotivo, aplicação por montadora nem tabela de equivalência — o cadastro dos produtos é feito por você. Se a sua operação depende disso, confirme com o suporte antes de contratar."),
    ("Como encontro uma peça rapidamente no balcão?",
     "Pela busca do PDV, usando código, descrição ou categoria. A rapidez depende de quão bem o produto foi cadastrado."),
    ("Consigo saber quanto tenho parado em peça de baixo giro?",
     "Sim, com custo e quantidade cadastrados. A curva ABC, disponível a partir do plano Loja, separa os itens por participação no resultado."),
    ("Dá para trabalhar preço de oficina e de consumidor?",
     "Sim. O mesmo produto aceita preço de atacado e de varejo, sem cadastro duplicado."),
    ("Como controlo a conta mensal das oficinas?",
     "Pelo controle de fiado, que mantém o saldo e o histórico por cliente. A partir do plano Loja, a cobrança sai por link de Pix no WhatsApp."),
    ("Emite nota fiscal para venda a oficina?",
     "Sim, nos planos Nota Fiscal e ERP Completo. A emissão consta como em ativação — confirme com o suporte e com seu contador."),
    ("Quantos produtos consigo cadastrar?",
     "O cadastro atende a operação de uma autopeças. Se o seu catálogo for muito grande, confirme com o suporte antes de contratar."),
  ],
  cta_title="Descubra quanto está parado na sua prateleira",
  cta_text="Cadastre os itens de maior saída com custo e quantidade e veja a curva ABC do seu catálogo. 7 dias grátis, sem cartão.",
  related=[("Controle de estoque", "/solucoes/sistema-de-estoque/", "Curva ABC e custo por item"),
           ("Controle de fiado", "/solucoes/controle-de-fiado/", "A conta das oficinas"),
           ("NF-e", "/solucoes/nfe/", "Nota na venda para oficina"),
           ("Distribuidora", "/segmentos/distribuidora/", "Outro segmento de atacado")],
),

# ------------------------------------------------- MATERIAIS DE CONSTRUÇÃO
dict(
  slug="segmentos/materiais-de-construcao",
  figura=("/assets/lojistas/distribuidora.webp",
          "Conferência de estoque em depósito de materiais"),
  title="Sistema para Loja de Material de Construção | SoftPay",
  description="Sistema para material de construção com atacado e varejo, controle de estoque, fiado de obra, venda de valor alto e nota fiscal. Teste grátis por 7 dias.",
  h1="Sistema para loja de material de construção",
  intro="Material de construção mistura a venda de um saco de cimento com o orçamento de uma obra inteira. São dois ritmos, dois preços e dois tipos de cliente — no mesmo balcão.",
  breadcrumbs=_c("Materiais de construção"),
  blocks=[
    sec("A rotina de quem vende material",
      p("De um lado, o consumidor final que vem buscar meia dúzia de itens para um reparo. Do outro, o pedreiro ou a construtora que leva volume, negocia preço e paga depois. O ticket varia de dez reais a alguns milhares."),
      p("O estoque é fisicamente pesado e ocupa espaço: areia, cimento, tijolo, tubo, tinta. Muito capital imobilizado, com itens que têm quebra, validade de argamassa e sazonalidade de obra."),
      p("E há o crédito. Fiado de obra não é fiado de padaria: são valores altos, prazos longos e um cliente que só volta quando a obra anda."),
    ),
    sec("Os problemas que aparecem sempre",
      ul("<strong>Dois preços, uma confusão.</strong> Quem está no balcão erra o preço de atacado ou dá desconto que não existia.",
         "<strong>O fiado de obra sai de controle.</strong> Valores altos, várias retiradas, e no fim ninguém sabe o saldo exato.",
         "<strong>Falta o que mais sai.</strong> Cimento e areia acabam justamente no dia de maior movimento.",
         "<strong>Capital parado em item de giro lento.</strong> Louça, metal e acabamento ficam meses na prateleira.",
         "<strong>A margem some no desconto.</strong> Sem custo cadastrado, a negociação vira intuição."),
    ),
    sec("Como o SoftPay resolve",
      h3("Atacado e varejo no mesmo produto"),
      p("Os dois preços convivem no mesmo cadastro. Quem atende não precisa lembrar da tabela — e não erra na hora de fechar."),
      h3("Custo cadastrado para negociar com segurança"),
      p("Com o custo do produto no sistema, você sabe até onde pode ir no desconto sem apagar a margem. Numa venda de volume, alguns pontos percentuais são muito dinheiro."),
      h3("Fiado de obra com histórico"),
      p("Cada retirada fica registrada no nome do cliente, com data e valor. O saldo deixa de depender de anotação, e a cobrança sai por link de Pix no WhatsApp a partir do plano Loja."),
      h3("Estoque do que não pode faltar"),
      p("A baixa automática pelo PDV mantém o saldo dos itens de alto giro acompanhando a realidade. A curva ABC separa o que sustenta o faturamento do que está parado."),
      h3("Nota fiscal"),
      p("Venda para construtora e para pessoa jurídica normalmente exige nota. Os planos Nota Fiscal e ERP Completo cobrem NF-e e NFC-e, com cadastro fiscal e pacote do contador."),
      h3("Mais de uma pessoa no balcão"),
      p("Loja de material costuma ter atendente, caixa e alguém no depósito. Cada um entra com o próprio acesso: até 3 usuários no plano Loja e até 10 no ERP Completo."),
      nota("O SoftPay <strong>não</strong> faz orçamento de obra, composição de custo de serviço nem controle de entrega e frete. Ele cobre a gestão comercial: produto, estoque, venda, caixa, fiado e nota.", "O que ele não faz"),
    ),
    sec("Um dia comum, do jeito que acontece",
      p("Pedreiro chega para retirar material de uma obra em andamento:"),
      ol("Você registra a saída no preço de atacado, na conta do cliente.",
         "O estoque de cimento e areia baixa na hora, sem conferência manual.",
         "O saldo da obra fica visível no cadastro, somando as retiradas do mês.",
         "Emite a nota, se o seu plano incluir emissão.",
         "Quando a obra fecha, você envia o link de Pix com o total — sem precisar puxar o assunto pessoalmente."),
      nota("Exemplo ilustrativo do fluxo. Os valores da sua loja dependem dos seus próprios dados.", "Sobre este exemplo"),
    ),
    sec("Perguntas que você passa a conseguir responder",
      ul("Quanto esta obra já retirou e qual o saldo?",
         "Até onde posso dar desconto sem perder margem?",
         "Quanto tenho investido em acabamento parado?",
         "Quais itens não podem faltar, pelo histórico?",
         "Qual a diferença de margem entre atacado e varejo?"),
    ),
    sec("Qual plano faz sentido",
      tabela(["Plano", "Preço", "Para material de construção"], [
        ["Comércio", "R$ 69/mês", "PDV, caixa, fiado e estoque essencial. Loja pequena, sem nota"],
        ["Loja", "R$ 89/mês", "Custo, curva ABC, cobrança do fiado por Pix e registro pelo WhatsApp. Até 3 usuários"],
        ["ERP Completo", "R$ 109/mês", "<strong>O plano de quem vende para construtora:</strong> tudo da Loja mais NF-e e NFC-e. Até 10 usuários"],
      ]),
      p("Todos com 7 dias de teste, sem cartão. Veja os <a href=\"/#pricing\">planos completos</a>."),
    ),
  ],
  faq=[
    ("Dá para trabalhar preço de atacado e de varejo?",
     "Sim. O mesmo produto aceita os dois preços, sem cadastro duplicado — é o que evita erro de quem está no balcão."),
    ("Como controlo o fiado de uma obra?",
     "Cada retirada é registrada no nome do cliente, com data e valor, formando o saldo. A partir do plano Loja, a cobrança sai por link de Pix pelo WhatsApp."),
    ("O SoftPay faz orçamento de obra?",
     "Não. Ele cobre a gestão comercial: produto, estoque, venda, caixa, fiado e nota fiscal. Orçamento de obra e composição de custo de serviço não fazem parte do sistema."),
    ("Controla entrega e frete?",
     "Não. Se a sua operação depende de roteirização ou controle de entrega, confirme com o suporte antes de contratar."),
    ("Emite nota fiscal para construtora?",
     "Sim, nos planos Nota Fiscal e ERP Completo, com cadastro fiscal e pacote do contador. A emissão consta como em ativação — confirme com o suporte."),
    ("Quantas pessoas podem usar ao mesmo tempo?",
     "Até 3 no plano Loja e até 10 no ERP Completo, cada uma com o próprio acesso."),
    ("Consigo saber a margem antes de dar desconto?",
     "Sim, desde que o custo esteja cadastrado no produto. É o que permite negociar volume sem apagar a margem."),
  ],
  cta_title="Teste com a sua tabela de atacado",
  cta_text="Cadastre alguns produtos com preço de atacado e varejo e registre uma retirada de obra. 7 dias grátis, sem cartão.",
  related=[("Controle de fiado", "/solucoes/controle-de-fiado/", "O saldo de cada obra"),
           ("Controle de estoque", "/solucoes/sistema-de-estoque/", "Custo e curva ABC"),
           ("NF-e", "/solucoes/nfe/", "Nota para construtora"),
           ("Distribuidora", "/segmentos/distribuidora/", "Outro segmento de volume")],
),

dict(
  slug="segmentos/pequeno-comercio",
  figura=("/assets/lojistas/casal-comerciantes.webp",
          "Casal de comerciantes olhando juntos a tela do computador atrás do balcão da loja"),
  title="Sistema para Pequeno Comércio e Loja Pequena | SoftPay",
  description="Sistema de gestão para pequeno comércio: PDV, estoque, caixa e fiado em um só lugar, simples de começar. Teste grátis por 7 dias, sem cartão.",
  h1="Sistema para pequeno comércio",
  intro="Loja com uma ou duas pessoas, faturamento crescendo e controle ainda no caderno ou na planilha. O SoftPay foi desenhado exatamente para esse momento.",
  breadcrumbs=_c("Pequeno comércio"),
  blocks=[
    sec("O momento em que a planilha para de servir",
      p("Não existe tamanho mínimo de loja para precisar de sistema. O que indica a necessidade não é o faturamento, é a perda de controle — e ela costuma aparecer nesta ordem:"),
      ol("Você não sabe de cabeça o que tem em estoque de um produto que vende todo dia.",
         "O fiado passou do ponto em que dá para lembrar quem deve o quê.",
         "O fechamento do caixa não bate e ninguém sabe explicar a diferença.",
         "Você vendeu bem no mês e mesmo assim não sobrou dinheiro."),
      p("O quarto item é o mais importante — e o mais mal interpretado. Vender muito e não ter dinheiro quase nunca é problema de venda: é falta de controle de custo e de estoque."),
    ),
    sec("O que muda com o SoftPay",
      h3("Um lugar só"),
      p("PDV, estoque, caixa, fiado e clientes no mesmo sistema. A venda registrada no balcão alimenta tudo, sem redigitar nada no fim do dia."),
      h3("Começar é rápido"),
      p("Não precisa instalar nada nem comprar equipamento: roda no navegador, no computador ou no celular. Dá para cadastrar os produtos de maior giro e já começar a usar no mesmo dia."),
      h3("Cresce junto"),
      p("Se a loja crescer, o mesmo sistema comporta mais usuários, filiais, loja online e emissão de nota fiscal — sem trocar de ferramenta e sem recomeçar o cadastro."),
    ),
    sec("Quanto custa e o que cabe no seu momento",
      tabela(["Plano", "Preço", "Para quem"], [
        ["Comércio", "R$ 69/mês", "Loja de uma pessoa que quer sair do caderno: PDV, caixa, fiado e estoque essencial"],
        ["Loja", "R$ 89/mês", "Quem quer cobrar o fiado sozinho, vender online e ter estoque avançado. Até 3 usuários"],
        ["ERP Completo", "R$ 109/mês", "Quem precisa emitir nota fiscal e tem equipe maior. Até 10 usuários"],
        ["Nota Fiscal", "R$ 65/mês", "Quem só precisa emitir nota, sem PDV nem estoque"],
      ]),
      p("Todos podem ser testados por 7 dias, sem cartão de crédito. Se quiser entender melhor a decisão, leia <a href=\"/perguntas/loja-pequena-precisa-de-sistema/\">loja pequena precisa de sistema?</a>."),
    ),
  ],
  faq=[
    ("Minha loja é muito pequena. Vale a pena?",
     "O que indica a necessidade não é o tamanho, é a perda de controle: estoque incerto, fiado no caderno e dúvida sobre quanto sobrou no mês. Se você reconhece esses sintomas, vale."),
    ("É difícil de aprender?",
     "O SoftPay foi feito para quem nunca usou sistema de gestão. Além disso, o suporte humano ajuda na configuração inicial pelo WhatsApp."),
    ("Preciso comprar computador ou equipamento?",
     "Não. O sistema roda no navegador, inclusive no celular. Não é preciso instalar programa nem manter servidor na loja."),
    ("Consigo migrar o que já tenho em planilha?",
     "A importação de dados está disponível a partir do plano Loja. Fale com o suporte antes de migrar para conferir o formato do arquivo."),
    ("Se eu não gostar, perco o dinheiro?",
     "O teste de 7 dias não pede cartão de crédito. Você só paga se decidir continuar depois de testar."),
  ],
  cta_title="Comece pelo problema que mais te incomoda",
  cta_text="Estoque, fiado ou caixa: escolha um, organize no SoftPay durante o teste e veja se faz diferença na sua rotina.",
  related=[
    ("O que é sistema de gestão", "/sistema-de-gestao-para-pequenos-negocios/", "O guia completo"),
    ("Como sair do caderno", "/guias/como-sair-do-caderno/", "Passo a passo da migração"),
    ("Caderno ou sistema?", "/perguntas/caderno-ou-sistema/", "Comparação honesta"),
  ],
),
]
