# -*- coding: utf-8 -*-
from blocks import sec, p, ul, ol, h3, nota, exemplo, tabela

C = [("Soluções", "/solucoes/")]
def _c(n): return C + [(n, None)]

PAGINAS = [

dict(
  slug="solucoes/sistema-de-estoque",
  figura=("/assets/lojistas/loja-de-variedades.webp",
          "Lojista organizando produtos na prateleira da loja"),
  title="Sistema de Controle de Estoque para Loja | SoftPay",
  description="Controle de estoque com custo, quantidade, variações e curva ABC. Saiba quanto dinheiro está parado na prateleira. Teste grátis por 7 dias.",
  h1="Sistema de controle de estoque",
  intro="Cada item na prateleira é dinheiro que você já pagou e ainda não recebeu de volta. Sem custo e quantidade registrados, esse valor fica invisível — e a loja vende bem sem nunca ter dinheiro em caixa.",
  breadcrumbs=_c("Controle de estoque"),
  blocks=[
    sec("O problema",
      p("Estoque descontrolado custa dos dois lados. Falta do que vende, e o cliente compra na concorrência. Sobra do que não vende, e o dinheiro fica preso na prateleira em vez de girar."),
      p("A causa quase sempre é a mesma: a baixa do estoque depende de alguém lembrar de fazer. Quando a venda e o estoque são dois controles separados, eles se desencontram em questão de dias."),
      p("E o desencontro não avisa. Ele aparece semanas depois, na forma de um item que faltou num sábado de movimento ou de uma compra repetida do que já estava no depósito."),
    ),
    sec("Como o descontrole aparece na sua loja",
      ul("<strong>Você promete o que não tem.</strong> Diz que tem, vai buscar e não acha. A venda morre na hora.",
         "<strong>Compra o que já está lá.</strong> O fornecedor chega, você repõe pela impressão, e o item aparece em dobro.",
         "<strong>O encalhe só aparece no inventário.</strong> Quando você percebe, o dinheiro já está parado há meses.",
         "<strong>A margem é uma média que engana.</strong> Sem custo por item, o produto de 15% e o de 60% viram um número só.",
         "<strong>Ninguém confia no número da tela.</strong> E quando o sistema perde a confiança, todo mundo volta a conferir na prateleira."),
    ),
    sec("Como o SoftPay resolve",
      h3("A venda dá baixa sozinha"),
      p("O estoque é alimentado pelo PDV. Toda venda registrada no balcão baixa a quantidade do produto na hora, sem segunda digitação. É o que impede o desencontro de nascer."),
      h3("Custo junto com o preço"),
      p("Cadastrar só o preço de venda responde quanto entrou. Cadastrar o custo é o que permite responder quanto sobrou — e é o que separa faturamento de lucro."),
      h3("Variações de tamanho e cor"),
      p("Para quem vende roupa e calçado, cada combinação tem a própria quantidade. A baixa acontece na variação certa, não no modelo genérico. A partir do plano Loja."),
      h3("Curva ABC"),
      p("Separa os produtos por participação no resultado. É o filtro que transforma um cadastro de centenas de itens numa decisão de compra concreta: o que repor, o que remarcar e o que não comprar mais. A partir do plano Loja."),
      h3("Atacado e varejo"),
      p("Dois preços no mesmo produto, para quem atende revendedor e consumidor final, sem cadastro duplicado."),
      h3("Entrada de mercadoria pelo WhatsApp"),
      p("A partir do plano Loja, a entrada de estoque pode ser registrada por mensagem ou áudio. No momento em que a carga chega, ninguém está sentado na frente do computador — e é aí que o registro costuma não acontecer. Veja o <a href=\"/solucoes/bot-whatsapp/\">bot do WhatsApp</a>."),
    ),
    sec("O que o controle de estoque não faz",
      p("Os limites, antes de você contratar contando com eles:"),
      ul("<strong>Não integra com balança.</strong> Venda por peso — frios, hortifrúti, granel — entra como produto comum, com o valor digitado no PDV.",
         "<strong>Não faz inventário por coletor.</strong> A contagem é feita por você e lançada no sistema; não há aparelho de leitura em massa.",
         "<strong>Não faz pedido de compra automático.</strong> O sistema mostra o que está acabando; a compra continua sendo sua, pelo canal de sempre.",
         "<strong>Não monta kit nem ficha técnica.</strong> Produto composto de outros produtos, com baixa dos componentes, não faz parte do sistema.",
         "<strong>Validade e lote não estão confirmados.</strong> Se a sua operação depende disso, verifique com o suporte antes de contratar.",
         "<strong>Estoque separado por filial não está confirmado.</strong> Descreva sua estrutura ao suporte se você tem mais de um ponto."),
    ),
    sec("Quanto dinheiro está parado, na prática",
      p("O número que quase nenhuma loja pequena sabe de cabeça é o valor do próprio estoque a preço de custo. Com custo e quantidade cadastrados, ele deixa de ser chute:"),
      exemplo("O que a prateleira vale, a preço de custo", [
        ("Classe A — 40 itens que giram", "R$ 9.200,00", ""),
        ("Classe B — 120 itens de giro médio", "R$ 7.400,00", ""),
        ("Classe C — 380 itens parados", "R$ 11.800,00", "minus"),
        ("= Total investido em mercadoria", "R$ 28.400,00", "result final"),
      ], "Números fictícios, só para mostrar o raciocínio. A leitura importante é a última linha da classe C: quase metade do dinheiro imobilizado nos itens que menos giram. Veja o guia <a href=\"/guias/como-controlar-estoque/\">como controlar estoque</a>."),
    ),
    sec("O que você passa a conseguir responder",
      ul("Quanto dinheiro eu tenho investido em mercadoria parada?",
         "Quais produtos sustentam o meu faturamento?",
         "O que está encalhado há tempo demais?",
         "Quanto eu realmente ganho em cada produto, depois do custo?",
         "O que preciso repor antes de acabar?",
         "Qual variação de tamanho ou cor mais sai, e qual eu compro demais?"),
    ),
    sec("Em qual plano está cada parte",
      tabela(["Plano", "Preço", "O que você tem de estoque"], [
        ["Comércio", "R$ 69/mês", "Estoque essencial: cadastro de produtos, quantidade e baixa automática pela venda"],
        ["Loja", "R$ 89/mês", "<strong>O plano do controle completo:</strong> custo por produto, variações de tamanho e cor, curva ABC e importação"],
        ["ERP Completo", "R$ 109/mês", "Tudo da Loja, mais emissão de NF-e e NFC-e e até 10 usuários"],
      ]),
      p("Todos podem ser testados por 7 dias, sem cartão de crédito. Veja os <a href=\"/#pricing\">planos completos</a>."),
    ),
  ],
  faq=[
    ("O estoque baixa sozinho quando eu vendo?",
     "Sim. A venda registrada no PDV dá baixa na quantidade do produto automaticamente, sem digitação separada."),
    ("Consigo cadastrar o custo de cada produto?",
     "Sim, a partir do plano Loja. É o custo cadastrado que permite calcular margem e saber quanto está investido em mercadoria."),
    ("O que é curva ABC?",
     "É uma classificação que separa os produtos pela participação no resultado: poucos itens costumam responder pela maior parte do faturamento. Serve para focar a decisão de compra no que importa. Está disponível a partir do plano Loja."),
    ("Dá para controlar tamanho e cor?",
     "Sim, com o cadastro de variações, disponível a partir do plano Loja. Cada combinação tem quantidade própria e a baixa acontece na variação certa."),
    ("O sistema controla validade e lote?",
     "Não está confirmado. Se você trabalha com alimento, medicamento ou qualquer item com data crítica, verifique com o suporte antes de contratar."),
    ("Vendo por peso. Funciona com balança?",
     "O SoftPay não integra com balança. Itens vendidos por peso entram como produto comum, com o valor digitado no PDV."),
    ("Dá para importar minha planilha de produtos?",
     "A importação está disponível a partir do plano Loja. Fale com o suporte antes de migrar para conferir o formato do arquivo."),
    ("Como faço o primeiro inventário?",
     "O caminho prático é cadastrar primeiro os produtos de maior giro com quantidade e custo, e completar o restante conforme repõe. O guia de estoque explica o método."),
    ("Tenho duas lojas. O estoque é separado?",
     "Esse ponto não está confirmado e depende da sua estrutura. Descreva sua operação ao suporte antes de contratar."),
  ],
  cta_title="Descubra quanto está parado na sua prateleira",
  cta_text="Cadastre os produtos de maior giro com custo e quantidade, registre as vendas por uma semana e veja o número aparecer. 7 dias grátis, sem cartão.",
  related=[("Como controlar estoque", "/guias/como-controlar-estoque/", "Método passo a passo"),
           ("Sistema PDV", "/solucoes/sistema-pdv/", "A venda que alimenta o estoque"),
           ("Bot do WhatsApp", "/solucoes/bot-whatsapp/", "Dar entrada falando"),
           ("Loja de roupas", "/segmentos/loja-de-roupas/", "Estoque com grade"),
           ("Loja de variedades", "/segmentos/loja-de-variedades/", "Centenas de itens"),
           ("Distribuidora", "/segmentos/distribuidora/", "Estoque em volume")],
),

dict(
  slug="solucoes/sistema-pdv",
  figura=("/assets/lojistas/mercadinho.webp",
          "Lojista registrando a venda no balcão do mercadinho"),
  title="Sistema PDV para Loja: Frente de Caixa | SoftPay",
  description="Sistema PDV com venda rápida, baixa automática de estoque, formas de pagamento e fechamento de caixa. Roda no navegador. Teste grátis 7 dias.",
  h1="Sistema PDV (frente de caixa)",
  intro="O PDV é onde o dinheiro entra e onde o dado nasce. Se a venda não é registrada direito ali, nenhum relatório depois vai fazer sentido.",
  breadcrumbs=_c("Sistema PDV"),
  blocks=[
    sec("O problema",
      p("Muita loja pequena trata o caixa como uma gaveta: o dinheiro entra, o produto sai e nada fica registrado. No fim do dia sobra um valor que não se explica, e no fim do mês uma dúvida sobre o resultado."),
      p("Quando existe registro, ele costuma ser em papel ou planilha — feito depois, de memória, com o movimento já terminado. O que chega ao relatório é uma reconstrução aproximada do que aconteceu."),
      p("O detalhe que quase ninguém nota: o erro não está no relatório, está na origem. Nenhuma ferramenta conserta depois um dado que nunca foi coletado."),
    ),
    sec("Como isso aparece na sua loja",
      ul("<strong>O caixa não bate</strong> e ninguém sabe em qual venda a diferença começou.",
         "<strong>O estoque mente</strong>, porque a saída do produto não foi registrada junto com a venda.",
         "<strong>A fila trava no preço.</strong> Alguém vai conferir na prateleira enquanto o cliente espera.",
         "<strong>Você não sabe como recebeu.</strong> Quanto foi Pix, quanto foi cartão, quanto foi dinheiro — tudo virou um total só.",
         "<strong>O fiado sai por fora</strong>, num caderno paralelo que ninguém mais consegue ler."),
    ),
    sec("Como o SoftPay resolve",
      h3("Venda registrada na hora"),
      p("Produto, quantidade, preço, forma de pagamento e cliente ficam gravados no momento da venda. É o mesmo ato: vender e registrar. Não existe a etapa de passar a limpo depois — que é justamente onde a informação se perde."),
      h3("Estoque e caixa alimentados juntos"),
      p("A mesma venda baixa o estoque e entra no caixa. Um registro, três consequências: a prateleira, a gaveta e o relatório passam a contar a mesma história."),
      h3("Fechamento de caixa"),
      p("No fim do expediente você compara o que o sistema registrou com o que está na gaveta. A diferença aparece no mesmo dia, enquanto ainda dá para lembrar o que houve."),
      h3("Forma de pagamento por venda"),
      p("Dinheiro, Pix, cartão e fiado ficam registrados individualmente. No fechamento você confere cada tipo de recebimento separadamente, em vez de brigar com um total único."),
      h3("Venda fiada no mesmo fluxo"),
      p("Se o cliente leva para pagar depois, a venda entra como fiado no nome dele, sem sair do PDV e sem caderno paralelo. Veja o <a href=\"/solucoes/controle-de-fiado/\">controle de fiado</a>."),
      h3("Sem instalar nada"),
      p("O PDV roda no navegador. Funciona no computador do balcão, no notebook e no celular, com os dados na nuvem — sem servidor na loja e sem licença por máquina."),
    ),
    sec("O que o PDV não faz",
      p("Os limites reais, para você não descobrir durante o teste:"),
      ul("<strong>Não funciona sem internet.</strong> O acesso é pelo navegador. Se a sua região tem queda frequente de conexão, pese isso na decisão.",
         "<strong>Não integra com balança.</strong> Venda por peso entra como produto comum, com o valor digitado.",
         "<strong>Não tem TEF nem concilia maquininha.</strong> A forma de pagamento é registrada na venda, mas o valor que a adquirente deposita não entra sozinho no sistema.",
         "<strong>Não faz comanda nem mesa.</strong> Bar, restaurante e lanchonete precisam de um fluxo que o SoftPay não tem.",
         "<strong>Impressora térmica e gaveta não estão confirmadas.</strong> Verifique o seu equipamento com o suporte antes de contratar.",
         "<strong>A emissão fiscal consta como em ativação.</strong> Se você precisa de NFC-e no ato da venda, confirme a situação atual com o suporte."),
    ),
    sec("Um dia no balcão, do jeito que acontece",
      p("A rotina que o PDV substitui:"),
      ol("Abre o caixa com o valor de troco inicial.",
         "Cada venda passa pelo PDV: produto, quantidade e forma de pagamento.",
         "O estoque baixa junto, sem ninguém precisar lembrar.",
         "A venda fiada entra no nome do cliente, no mesmo lugar.",
         "No fim do dia, o fechamento compara sistema e gaveta.",
         "A diferença, se houver, é conferida hoje — não no fim do mês."),
      nota("Exemplo ilustrativo do fluxo. O ritmo da sua loja depende do seu movimento e do tamanho do catálogo.", "Sobre este exemplo"),
    ),
    sec("O que você passa a conseguir responder",
      ul("Quanto vendi hoje, e quanto disso foi Pix, cartão e dinheiro?",
         "O caixa de ontem bateu?",
         "Qual produto mais saiu esta semana?",
         "Quanto saiu em fiado no mês?",
         "Qual o meu ticket médio?",
         "Que horas a loja vende mais?"),
    ),
    sec("Em qual plano está",
      tabela(["Plano", "Preço", "O PDV neste plano"], [
        ["Comércio", "R$ 69/mês", "<strong>PDV completo já aqui:</strong> venda, formas de pagamento, baixa de estoque, fiado e fechamento de caixa. 1 usuário"],
        ["Loja", "R$ 89/mês", "O mesmo PDV, com estoque avançado por trás: custo, variações e curva ABC. Até 3 usuários"],
        ["ERP Completo", "R$ 109/mês", "Tudo da Loja mais emissão de NF-e e NFC-e. Até 10 usuários"],
        ["Nota Fiscal", "R$ 65/mês", "<strong>Não inclui PDV.</strong> Serve só para emissão de notas"],
      ]),
      p("Todos podem ser testados por 7 dias, sem cartão de crédito. Veja os <a href=\"/#pricing\">planos completos</a>."),
    ),
  ],
  faq=[
    ("Preciso instalar o PDV no computador?",
     "Não. O SoftPay roda no navegador, sem instalação e sem servidor na loja. Funciona no computador do balcão, no notebook e no celular."),
    ("Funciona com leitor de código de barras?",
     "O campo de busca do PDV aceita a leitura do código. Confirme a compatibilidade do seu leitor com o suporte antes de contratar."),
    ("Funciona sem internet?",
     "Não. O sistema é acessado pela internet, então depende de conexão. Se a sua região tem instabilidade, converse com o suporte antes de contratar."),
    ("O PDV controla as formas de pagamento?",
     "Sim. Dinheiro, Pix, cartão e fiado são registrados individualmente na venda, o que permite conferir o caixa por tipo de recebimento no fechamento."),
    ("Ele concilia o que a maquininha me paga?",
     "Não. A forma de pagamento fica registrada na venda, mas o depósito da adquirente não entra automaticamente. A conferência com o extrato é manual."),
    ("Serve para bar ou restaurante?",
     "Não. O SoftPay não tem comanda nem controle de mesa. Ele foi feito para comércio que vende produto com estoque."),
    ("Funciona com impressora térmica e gaveta de dinheiro?",
     "Esse ponto não está confirmado. Descreva seu equipamento ao suporte antes de contratar."),
    ("O PDV emite cupom fiscal?",
     "A emissão de NFC-e está nos planos Nota Fiscal e ERP Completo, e consta como recurso em ativação. Confirme a situação com o suporte e com seu contador."),
    ("Em qual plano está o PDV?",
     "A partir do plano Comércio, de R$ 69/mês. O plano Nota Fiscal não inclui PDV — ele serve só para emissão de notas."),
  ],
  cta_title="Teste no seu próprio balcão",
  cta_text="Cadastre os produtos de maior giro, passe as vendas de um dia pelo PDV e feche o caixa no fim da tarde. 7 dias grátis, sem cartão.",
  related=[("Controle de estoque", "/solucoes/sistema-de-estoque/", "A baixa automática"),
           ("Sistema financeiro", "/solucoes/sistema-financeiro/", "Caixa e resultado"),
           ("Controle de fiado", "/solucoes/controle-de-fiado/", "A venda a prazo, no mesmo fluxo"),
           ("Bot do WhatsApp", "/solucoes/bot-whatsapp/", "Registrar sem abrir o painel"),
           ("Como controlar o caixa", "/guias/como-controlar-caixa-da-loja/", "Rotina de fechamento"),
           ("Mercadinho", "/segmentos/mercadinho/", "O balcão de maior movimento")],
),

dict(
  slug="solucoes/controle-de-fiado",
  figura=("/assets/lojistas/casal-comerciantes.webp",
          "Casal de comerciantes conferindo as contas no computador da loja"),
  title="Sistema de Controle de Fiado para Loja | SoftPay",
  description="Controle de fiado digital: saldo por cliente, histórico e cobrança por link de Pix no WhatsApp. Saia do caderno. Teste grátis por 7 dias.",
  h1="Controle de fiado",
  intro="Vender fiado não é o problema. O problema é o caderno: anotação rasurada, cliente que esquece e você sem saber quanto tem para receber.",
  breadcrumbs=_c("Controle de fiado"),
  blocks=[
    sec("O problema",
      p("No comércio de bairro o fiado é parte do negócio — é o que mantém o cliente fiel e o que atravessa o fim do mês de muita gente. Mas o dinheiro fiado é o mais fácil de perder: não tem comprovante, depende da memória de quem anotou e some quando a folha do caderno acaba."),
      p("O efeito é silencioso. A loja vendeu, o estoque saiu, mas o dinheiro não entrou — e como não há um total visível, ninguém percebe o tamanho do buraco."),
      p("Some a isso o desconforto de cobrar alguém que você encontra na rua. É por isso que muita dívida de fiado nunca é cobrada: não por falta de controle, por falta de jeito de puxar o assunto."),
    ),
    sec("Como isso aparece na sua loja",
      ul("<strong>Você não sabe o total a receber.</strong> Sabe que \"tem gente devendo\", não quanto.",
         "<strong>O saldo depende de uma pessoa só.</strong> Se quem anota falta, ninguém resolve nada no balcão.",
         "<strong>A conversa vira discussão.</strong> O cliente lembra de um valor, o caderno diz outro, e não há como provar.",
         "<strong>A cobrança não acontece.</strong> Você adia porque é constrangedor, e o valor envelhece.",
         "<strong>O caderno acaba.</strong> Folha rasgada, letra ilegível, página molhada — e o registro simplesmente deixa de existir."),
    ),
    sec("Como o SoftPay resolve",
      h3("Cada venda no nome do cliente"),
      p("A venda fiada é registrada no cadastro do cliente, com data e valor. O saldo é do sistema, não da memória de quem estava no balcão — e qualquer pessoa da loja consegue responder."),
      h3("Histórico para consultar na hora"),
      p("Quando o cliente pergunta quanto deve, a resposta está na tela, com as compras que formam o valor. Isso encerra a discussão antes de ela começar, porque não é a sua palavra contra a dele."),
      h3("Cobrança sem constrangimento"),
      p("A partir do plano Loja, o sistema envia link de pagamento por Pix pelo WhatsApp. A cobrança deixa de depender de você puxar o assunto no balcão — que é o motivo real de tanta dívida antiga não ser cobrada."),
      h3("Ligado ao resto da loja"),
      p("A venda fiada baixa o estoque como qualquer outra e fica registrada como valor a receber, aparecendo no seu resultado. Fiado deixa de ser um controle paralelo."),
      h3("Registrar e dar baixa falando"),
      p("A partir do plano Loja, você registra uma venda fiada ou dá baixa numa dívida por mensagem ou áudio no WhatsApp. O bot recusa baixa maior que o saldo e responde com o valor certo. Veja o <a href=\"/solucoes/bot-whatsapp/\">bot do WhatsApp</a>."),
    ),
    sec("O que o controle de fiado não faz",
      p("É crédito que você concede com o próprio dinheiro. Vale saber o que o sistema não cobre:"),
      ul("<strong>Não consulta SPC nem Serasa.</strong> A decisão de vender fiado continua sendo sua, baseada no que você sabe do cliente.",
         "<strong>Não negativa quem não paga.</strong> Não há qualquer integração com órgão de proteção ao crédito.",
         "<strong>Não calcula juros nem multa por atraso.</strong> O saldo é o valor das compras.",
         "<strong>Não gera carnê nem boleto.</strong> A cobrança sai por link de Pix no WhatsApp, a partir do plano Loja.",
         "<strong>Limite de crédito por cliente não está confirmado.</strong> Se você precisa travar venda acima de um valor, verifique com o suporte antes de contratar.",
         "<strong>Não cobra sozinho de tempos em tempos.</strong> O envio do link é uma ação sua, não uma régua automática."),
    ),
    sec("O tamanho do buraco, quando ele fica visível",
      p("O primeiro efeito de sair do caderno costuma ser um susto — o total a receber quase sempre é maior do que o dono imaginava:"),
      exemplo("O que estava espalhado pelo caderno", [
        ("14 clientes com saldo em aberto", "R$ 3.180,00", ""),
        ("Desses, 5 com dívida acima de 60 dias", "R$ 1.940,00", "minus"),
        ("= Dinheiro seu, fora do caixa", "R$ 3.180,00", "result final"),
      ], "Números fictícios, só para mostrar o raciocínio. A linha do meio é a que muda o comportamento: quando o vencimento fica visível, a cobrança para de ser adiada. Veja o guia <a href=\"/guias/como-controlar-fiado/\">como controlar fiado</a>."),
    ),
    sec("O que você passa a conseguir responder",
      ul("Quanto tenho a receber de fiado, no total?",
         "Quem deve, quanto e desde quando?",
         "Quais dívidas estão mais velhas?",
         "Este cliente já pagou o que devia do mês passado?",
         "Quanto do meu faturamento saiu a prazo?",
         "Vale continuar vendendo fiado para esta pessoa?"),
    ),
    sec("Em qual plano está",
      tabela(["Plano", "Preço", "O fiado neste plano"], [
        ["Comércio", "R$ 69/mês", "<strong>Caderninho digital já aqui:</strong> saldo e histórico por cliente, venda fiada pelo PDV. 1 usuário"],
        ["Loja", "R$ 89/mês", "Tudo do Comércio mais <strong>cobrança por link de Pix no WhatsApp</strong> e registro pelo bot. Até 3 usuários"],
        ["ERP Completo", "R$ 109/mês", "Tudo da Loja mais emissão de NF-e e NFC-e. Até 10 usuários"],
      ]),
      p("Todos podem ser testados por 7 dias, sem cartão de crédito. Veja os <a href=\"/#pricing\">planos completos</a>."),
    ),
  ],
  faq=[
    ("Consigo ver quanto cada cliente me deve?",
     "Sim. O saldo fica no cadastro do cliente, com o histórico das compras que formam o valor — dá para mostrar na tela quando ele perguntar."),
    ("O sistema cobra o cliente automaticamente?",
     "A partir do plano Loja, o SoftPay envia link de pagamento por Pix pelo WhatsApp. O envio é uma ação sua: não existe régua de cobrança que dispara sozinha."),
    ("Dá para definir um limite de fiado por cliente?",
     "Esse ponto não está confirmado. Se travar venda acima de um valor é importante para você, verifique com o suporte antes de contratar."),
    ("O sistema cobra juros de quem atrasa?",
     "Não. O saldo é o valor das compras; não há cálculo de juros nem multa por atraso."),
    ("Consigo consultar SPC ou negativar quem não paga?",
     "Não. O SoftPay não consulta órgão de proteção ao crédito nem negativa ninguém. A decisão de vender a prazo continua sendo sua."),
    ("A venda fiada baixa o estoque?",
     "Sim. Ela é uma venda como qualquer outra: o produto sai do estoque e o valor fica registrado como a receber."),
    ("Dá para registrar fiado pelo WhatsApp?",
     "Sim, a partir do plano Loja — tanto a venda fiada quanto a baixa da dívida. O bot recusa baixa maior que o saldo e responde com o valor correto."),
    ("Emite carnê ou boleto?",
     "Não. A cobrança sai por link de Pix pelo WhatsApp, disponível a partir do plano Loja."),
    ("Como faço para passar o caderno atual para o sistema?",
     "O caminho prático é lançar os saldos em aberto como vendas fiadas no nome de cada cliente. O guia de fiado explica o processo."),
  ],
  cta_title="Descubra quanto você tem para receber",
  cta_text="Lance os saldos do caderno no nome de cada cliente e veja o total aparecer. Costuma ser maior do que a gente imagina. 7 dias grátis, sem cartão.",
  related=[("Como controlar fiado", "/guias/como-controlar-fiado/", "Método e cobrança"),
           ("Controle de clientes", "/solucoes/controle-de-clientes/", "Cadastro e histórico"),
           ("Sistema PDV", "/solucoes/sistema-pdv/", "A venda a prazo no balcão"),
           ("Bot do WhatsApp", "/solucoes/bot-whatsapp/", "Registrar e dar baixa falando"),
           ("Mercadinho", "/segmentos/mercadinho/", "O fiado do bairro"),
           ("Loja de joias", "/segmentos/loja-de-joias/", "Crediário de alto valor")],
),

dict(
  slug="solucoes/sistema-financeiro",
  figura=("/assets/lojistas/casal-comerciantes.webp",
          "Comerciantes analisando os números da loja no computador"),
  title="Sistema Financeiro para Loja: Caixa e Resultado | SoftPay",
  description="Controle de caixa, entradas e saídas, e visão do resultado da loja. Entenda a diferença entre faturamento e lucro. Teste grátis por 7 dias.",
  h1="Controle financeiro da loja",
  intro="Faturamento é o que entrou. Lucro é o que sobrou. A maior parte dos problemas de caixa em loja pequena nasce de confundir os dois.",
  breadcrumbs=_c("Financeiro"),
  blocks=[
    sec("O problema",
      p("“Vendi muito e não tenho dinheiro” é a frase mais comum do varejo pequeno. Quase nunca é problema de venda: é o custo da mercadoria e as despesas comendo a margem sem que ninguém acompanhe."),
      p("Sem separar essas camadas, qualquer decisão vira aposta — desde formar preço até saber se dá para contratar alguém."),
    ),
    sec("Como o SoftPay resolve",
      h3("Caixa alimentado pela venda"),
      p("O que passa no PDV entra no caixa com a forma de pagamento registrada. O fechamento diário compara o registrado com o que está na gaveta."),
      h3("Custo dentro da conta"),
      p("Com o custo dos produtos cadastrado, o sistema tem os dois lados da operação — o que entrou e o que a mercadoria custou —, que é a base do lucro bruto."),
      h3("Visão do período"),
      p("Painel e relatórios reúnem vendas, estoque, caixa e fiado no mesmo lugar, para você olhar o mês inteiro em vez de um dia isolado."),
    ),
    sec("A conta, camada por camada",
      exemplo("Do faturamento ao resultado", [
        ("Vendas do mês", "R$ 25.480,00", ""),
        ("Custo dos produtos vendidos (CMV)", "− R$ 16.560,00", "minus"),
        ("= Lucro bruto", "R$ 8.920,00", "result"),
        ("Despesas do período", "− R$ 3.400,00", "minus"),
        ("= Resultado estimado", "R$ 5.520,00", "result final"),
      ], "Números fictícios. O resultado da sua loja depende dos seus próprios dados de venda, custo e despesa. Veja o método em <a href=\"/guias/como-calcular-lucro-da-loja/\">como calcular o lucro da loja</a>."),
      nota("O SoftPay ajuda a organizar os dados que formam essa conta. Ele não substitui a contabilidade da empresa nem dispensa o seu contador.", "Sobre o alcance disto"),
    ),
  ],
  faq=[
    ("O SoftPay substitui meu contador?",
     "Não. Ele organiza os dados da operação — vendas, custos, caixa e notas. A contabilidade da empresa continua com o seu contador."),
    ("Ele calcula o meu lucro automaticamente?",
     "O sistema reúne os dados que formam a conta: vendas registradas e custo dos produtos cadastrado. A precisão do resultado depende de esses dados estarem completos."),
    ("Consigo lançar despesas da loja?",
     "Confirme com o suporte o alcance do lançamento de despesas no seu plano antes de contratar."),
    ("Como o fiado aparece no financeiro?",
     "A venda fiada é registrada como valor a receber, o que evita contar como caixa um dinheiro que ainda não entrou."),
    ("Dá para fechar o caixa todo dia?",
     "Sim, e é a prática recomendada: a diferença aparece no mesmo dia, enquanto ainda dá para identificar a causa."),
  ],
  related=[("Como calcular lucro", "/guias/como-calcular-lucro-da-loja/", "Faturamento não é lucro"),
           ("Como calcular margem", "/guias/como-calcular-margem-de-lucro/", "Formação de preço"),
           ("Sistema PDV", "/solucoes/sistema-pdv/", "De onde vem o dado")],
),

dict(
  slug="solucoes/nfe",
  figura=("/assets/lojistas/distribuidora.webp",
          "Operação de distribuidora, onde a nota fiscal faz parte da rotina"),
  title="Sistema para Emitir NF-e (Nota Fiscal Eletrônica) | SoftPay",
  description="Emissão de NF-e com cadastro fiscal e pacote do contador. Planos a partir de R$ 65/mês. Teste grátis por 7 dias, sem cartão.",
  h1="Emissão de NF-e",
  intro="A NF-e é a nota fiscal eletrônica usada nas operações entre empresas e em vendas que exigem documento fiscal completo. O SoftPay cobre a emissão nos planos Nota Fiscal e ERP Completo.",
  breadcrumbs=_c("NF-e"),
  blocks=[
    sec("Quando você precisa de NF-e",
      p("A obrigatoriedade depende do seu regime tributário, da atividade e do tipo de operação. Venda para outra empresa, transporte de mercadoria e algumas operações específicas normalmente exigem NF-e."),
      nota("Obrigação fiscal não se resolve por artigo em site. Confirme com o seu contador o que a sua empresa precisa emitir antes de contratar qualquer sistema. Informações oficiais estão no portal da NF-e e na SEFAZ do seu estado.", "Consulte seu contador"),
    ),
    sec("Como funciona no SoftPay",
      h3("Dois caminhos"),
      p("Se você só precisa emitir notas, o plano <strong>Nota Fiscal</strong> (R$ 65/mês) resolve: você preenche um formulário e emite, sem PDV, estoque ou relatórios. Se quer a gestão completa com a emissão junto, o <strong>ERP Completo</strong> (R$ 109/mês) inclui tudo."),
      h3("Cadastro fiscal e pacote do contador"),
      p("Os dois planos incluem o cadastro fiscal e o pacote do contador, para que o seu contabilista receba o que precisa sem trabalho manual seu."),
      h3("Notas recebidas"),
      p("Além de emitir, dá para visualizar as notas recebidas de fornecedores, e manifestá-las no plano Nota Fiscal."),
      nota("A emissão de NFC-e, NF-e, NFS-e e MDF-e consta nos planos como recurso <strong>em ativação</strong>. Antes de contratar contando com um documento específico, confirme a situação atual com o suporte.", "Situação da emissão"),
    ),
  ],
  faq=[
    ("Qual a diferença entre NF-e e NFC-e?",
     "A NF-e costuma ser usada em operações entre empresas e em vendas que exigem documento fiscal completo. A NFC-e é o cupom fiscal eletrônico, usado na venda ao consumidor final no balcão."),
    ("Preciso de certificado digital?",
     "A emissão de documentos fiscais eletrônicos normalmente exige certificado digital. Confirme com o suporte e com seu contador o que é necessário no seu caso."),
    ("Em quais planos está a emissão?",
     "Nos planos Nota Fiscal (R$ 65/mês) e ERP Completo (R$ 109/mês). Os planos Comércio e Loja não incluem emissão."),
    ("O plano Nota Fiscal tem PDV e estoque?",
     "Não. Ele é só a nota: você preenche um formulário e emite. Sem PDV, estoque, clientes ou relatórios."),
    ("Consigo ver as notas que recebo dos fornecedores?",
     "Sim. A visualização de notas recebidas está disponível a partir do plano Comércio, e a manifestação no plano Nota Fiscal."),
  ],
  related=[("NFC-e", "/solucoes/nfce/", "Cupom fiscal no balcão"),
           ("Distribuidora", "/segmentos/distribuidora/", "Operação com nota"),
           ("Preços", "/#pricing", "Planos com emissão fiscal")],
),

dict(
  slug="solucoes/nfce",
  figura=("/assets/lojistas/papelaria.webp",
          "Atendente finalizando a venda no caixa da papelaria"),
  title="Sistema para Emitir NFC-e (Cupom Fiscal) | SoftPay",
  description="Emissão de NFC-e, o cupom fiscal eletrônico da venda no balcão, integrada ao PDV. Planos com emissão a partir de R$ 65/mês. Teste grátis 7 dias.",
  h1="Emissão de NFC-e",
  intro="A NFC-e é o cupom fiscal eletrônico da venda ao consumidor final — o documento do balcão. No SoftPay ela vive junto do PDV, no plano ERP Completo.",
  breadcrumbs=_c("NFC-e"),
  blocks=[
    sec("O que é a NFC-e",
      p("A NFC-e substituiu o antigo cupom fiscal impresso por equipamento próprio. É o documento emitido na venda ao consumidor final, no varejo, e sua exigência varia conforme o estado e o perfil da empresa."),
      nota("Cada estado tem regras próprias de credenciamento e obrigatoriedade para NFC-e. Confirme com o seu contador e com a SEFAZ do seu estado antes de contratar.", "Regras variam por estado"),
    ),
    sec("Como funciona no SoftPay",
      h3("Junto da venda"),
      p("No ERP Completo, a emissão convive com o PDV: a mesma venda que baixa o estoque e entra no caixa é a que gera o documento fiscal."),
      h3("Só a nota, se for o caso"),
      p("Se você não precisa de PDV e estoque, o plano Nota Fiscal (R$ 65/mês) permite emitir preenchendo um formulário."),
      h3("Cadastro fiscal e contador"),
      p("Os planos com emissão incluem cadastro fiscal e pacote do contador."),
      nota("A emissão consta nos planos como recurso <strong>em ativação</strong>. Confirme a situação atual com o suporte antes de contratar contando com ela.", "Situação da emissão"),
    ),
  ],
  faq=[
    ("NFC-e é o mesmo que cupom fiscal?",
     "A NFC-e é o cupom fiscal eletrônico. Ela substituiu o cupom impresso por equipamento fiscal próprio na venda ao consumidor final."),
    ("Minha loja é obrigada a emitir NFC-e?",
     "Depende do estado, do regime tributário e da atividade. Confirme com seu contador e com a SEFAZ do seu estado."),
    ("Em qual plano está a NFC-e?",
     "Nos planos Nota Fiscal (R$ 65/mês) e ERP Completo (R$ 109/mês)."),
    ("Precisa de impressora fiscal?",
     "A NFC-e não exige o antigo equipamento emissor de cupom fiscal. Sobre impressão do DANFE e equipamentos, confirme os detalhes com o suporte."),
    ("A emissão está funcionando hoje?",
     "Os planos descrevem a emissão como em ativação. Confirme a situação atual com o suporte antes de contratar."),
  ],
  related=[("NF-e", "/solucoes/nfe/", "Nota fiscal eletrônica"),
           ("Sistema PDV", "/solucoes/sistema-pdv/", "A venda que gera o cupom"),
           ("Papelaria", "/segmentos/papelaria/", "Cupom no varejo")],
),

dict(
  slug="solucoes/loja-online",
  figura=("/assets/lojistas/celular-balcao.webp",
          "Mãos de um comerciante usando o celular sobre o balcão"),
  title="Loja Online com Catálogo e Pix | SoftPay",
  description="Loja online integrada ao seu estoque, com catálogo, pagamento por Pix e confirmação automática do pedido. A partir do plano Loja. Teste grátis 7 dias.",
  h1="Loja online com Pix",
  intro="Nem todo cliente vai até o balcão. Com a loja online do SoftPay, seu catálogo fica disponível para quem prefere escolher pelo celular e pagar por Pix.",
  breadcrumbs=_c("Loja online"),
  blocks=[
    sec("O problema de manter dois negócios",
      p("Vender pela internet costuma significar um segundo cadastro de produtos, um segundo estoque e uma segunda conta para acompanhar. Na prática, o lojista pequeno abandona um dos dois — quase sempre o online."),
    ),
    sec("Como o SoftPay resolve",
      h3("Um cadastro só"),
      p("O catálogo online é alimentado pelos produtos que você já cadastrou para o balcão. Não existe um segundo cadastro para manter."),
      h3("Pix que confirma sozinho"),
      p("O cliente paga por Pix e o pedido é confirmado automaticamente, sem você precisar conferir comprovante no WhatsApp."),
      h3("Pedidos dentro do sistema"),
      p("Os pedidos chegam no mesmo lugar onde você já acompanha a loja física."),
      h3("Cupom e fidelidade"),
      p("Cupons de desconto e programa de fidelidade ajudam a trazer o cliente de volta, online ou no balcão."),
      nota("A loja online está disponível a partir do plano Loja (R$ 89/mês).", "Em qual plano"),
    ),
  ],
  faq=[
    ("A loja online usa o mesmo estoque da loja física?",
     "Sim. O catálogo é alimentado pelos produtos já cadastrados, o que evita manter dois cadastros em paralelo."),
    ("Como o cliente paga?",
     "Por Pix, com confirmação automática do pedido — sem você precisar conferir comprovante manualmente."),
    ("Aceita cartão de crédito?",
     "Confirme com o suporte as formas de pagamento disponíveis hoje na loja online antes de contratar."),
    ("Preciso de domínio próprio?",
     "Converse com o suporte sobre como o endereço da sua loja online é configurado."),
    ("Em qual plano está?",
     "A partir do plano Loja, de R$ 89/mês."),
  ],
  related=[("Controle de estoque", "/solucoes/sistema-de-estoque/", "O catálogo vem daqui"),
           ("Controle de clientes", "/solucoes/controle-de-clientes/", "Cupom e fidelidade"),
           ("Loja de roupas", "/segmentos/loja-de-roupas/", "Vender moda online")],
),

dict(
  slug="solucoes/controle-de-clientes",
  figura=("/assets/lojistas/loja-de-roupas.webp",
          "Lojista atendendo com o tablet na mão numa loja de roupas"),
  title="Controle de Clientes e CRM para Loja | SoftPay",
  description="Cadastro de clientes com histórico de compras, base para fiado, cupons e fidelidade. Saiba quem volta a comprar. Teste grátis por 7 dias.",
  h1="Controle de clientes (CRM)",
  intro="Conquistar cliente novo custa caro. O cliente que já comprou é o mais barato de trazer de volta — desde que você saiba quem ele é e o que ele comprou.",
  breadcrumbs=_c("Controle de clientes"),
  blocks=[
    sec("O problema",
      p("Na maioria das lojas pequenas, o conhecimento sobre os clientes está na cabeça do dono. Funciona enquanto o movimento é pequeno e a mesma pessoa atende todo mundo. Quando entra outra pessoa no balcão ou o volume cresce, esse conhecimento não se transfere."),
    ),
    sec("Como o SoftPay resolve",
      h3("Cadastro ligado à venda"),
      p("A venda registrada no PDV pode ser vinculada ao cliente, formando um histórico real de compras — não uma lista solta de nomes e telefones."),
      h3("Base do fiado"),
      p("O saldo do fiado vive no cadastro do cliente, com as compras que o formam."),
      h3("Cupom e fidelidade"),
      p("A partir do plano Loja, cupons de desconto e programa de fidelidade usam essa base para trazer o cliente de volta."),
      h3("Contato com propósito"),
      p("Saber o que a pessoa comprou e quando permite um contato útil, em vez de disparo genérico para uma lista inteira."),
    ),
  ],
  faq=[
    ("O cadastro de clientes está em qual plano?",
     "O cadastro de clientes faz parte do sistema a partir do plano Comércio. Cupons e fidelidade ficam disponíveis a partir do plano Loja."),
    ("Consigo ver o histórico de compras de cada cliente?",
     "Sim, quando a venda é vinculada ao cliente no momento do registro no PDV."),
    ("Serve para trabalhar recompra?",
     "Sim. Saber o que a pessoa comprou e quando é a base para um contato com propósito, especialmente em segmentos de recompra previsível."),
    ("E a LGPD?",
     "Você é responsável pelos dados dos seus clientes. Colete o necessário, informe a finalidade e consulte a Política de Privacidade do SoftPay."),
    ("Dá para importar minha lista atual?",
     "A importação está disponível a partir do plano Loja. Fale com o suporte para conferir o formato do arquivo."),
  ],
  related=[("Controle de fiado", "/solucoes/controle-de-fiado/", "Saldo por cliente"),
           ("Loja online", "/solucoes/loja-online/", "Cupom e fidelidade"),
           ("Loja de roupas", "/segmentos/loja-de-roupas/", "Cliente que volta")],
),

dict(
  slug="solucoes/bot-whatsapp",
  figura=("/assets/lojistas/celular-balcao.webp",
          "Comerciante registrando uma venda pelo celular no balcão"),
  title="Registre a Venda pelo WhatsApp | Bot do SoftPay",
  description="Registre venda, despesa, estoque e fiado mandando uma mensagem ou um áudio no WhatsApp. O SoftPay responde em segundos, sem você abrir o sistema.",
  h1="Registre a venda pelo WhatsApp",
  intro="O lojista não deixa de registrar porque o sistema é ruim. Deixa porque registrar exige parar. Com o bot do SoftPay, a venda entra no sistema enquanto o cliente ainda está na sua frente.",
  breadcrumbs=_c("Bot do WhatsApp"),
  blocks=[
    sec("O problema não é o sistema. É o momento.",
      p("Atrás do balcão, com o cliente na frente e a mão no troco, abrir o aplicativo é um movimento que não acontece. Falar, sim. Então a venda acontece e o registro não — e a partir daí a loja inteira desanda:"),
      ul("O <strong>estoque mente</strong>, e você compra o que já tem ou não repõe o que acabou.",
         "O <strong>caixa não fecha</strong>, e você passa a desconfiar do próprio sistema.",
         "O <strong>relatório não decide nada</strong>, porque descreve metade da loja.",
         "E o fiado volta para o caderno de papel."),
      p("Esse buraco entre o que aconteceu na loja e o que o sistema sabe é o problema de verdade. Não falta recurso no painel: falta o momento de abrir o painel."),
    ),
    sec("Como funciona",
      p("Você manda uma mensagem ou um áudio no WhatsApp, como falaria com um funcionário. O SoftPay entende, registra e responde confirmando — em cerca de dois segundos."),
      h3("O que dá para fazer falando"),
      ul("Registrar venda, com forma de pagamento",
         "Lançar despesa",
         "Dar entrada de estoque",
         "Registrar venda fiada no nome do cliente",
         "Dar baixa em dívida de fiado",
         "Lançar suprimento e sangria de caixa",
         "Consultar saldo, estoque e o que foi vendido"),
      p("São 17 operações no total. Um áudio típico de lojista tem <strong>7 a 8 segundos</strong> de fala."),
      nota("O bot está disponível <strong>a partir do plano Loja</strong>. Ele não substitui o painel: correções, configuração e análise mais funda continuam lá.", "Em qual plano"),
    ),
    sec("Uma conversa real, cronometrada",
      p("Esta sequência aconteceu de verdade, em 46 segundos, sem o painel ser aberto uma única vez:"),
      exemplo("Do problema descoberto à venda registrada", [
        ("16:08:12 — “Vendi duas cocas no pix”", "recusado: estoque 0", "minus"),
        ("16:08:27 — “Registre no estoque 10 coca”", "entrada registrada", ""),
        ("16:08:38 — “Vende duas cocas no Pix”", "venda de R$ 10,00", "result final"),
      ], "Repare no mais importante: o bot <strong>recusou</strong> a primeira venda porque o estoque estava zerado. Ele não deixa o sistema mentir para agradar."),
    ),
    sec("Por que dá para confiar dinheiro a ele",
      p("Um bot que registra venda mexe no caixa da sua loja. O que sustenta isso:"),
      h3("Ele prefere perguntar a adivinhar"),
      p("Produto ambíguo, forma de pagamento ausente, cliente homônimo, valor muito alto — em todos, ele pergunta. Chutar “dinheiro” numa venda bagunçaria o seu fechamento em silêncio, e silêncio é o pior defeito num sistema que mexe com dinheiro."),
      h3("Ele recusa em vez de mentir"),
      p("Estoque insuficiente barra a venda. Baixa maior que a dívida é recusada, com o saldo certo na resposta. Fiado sem cliente identificado não entra."),
      h3("Nada acontece duas vezes"),
      p("Se o WhatsApp reentregar a mesma mensagem, ela não é registrada de novo."),
      h3("Dá para desfazer"),
      p("Por 15 minutos, “DESFAZER” cancela o último registro — venda, despesa, cadastro, entrada de estoque, suprimento ou baixa de fiado."),
      h3("A mesma frase dá sempre o mesmo resultado"),
      p("A maior parte das frases é resolvida por regra fixa, não por adivinhação: o mesmo áudio registra sempre a mesma venda."),
    ),
    sec("Onde ele ajuda pouco",
      p("Vale ser honesto sobre o tamanho da coisa:"),
      ul("<strong>Loja com fila constante e movimento alto.</strong> Quem passa centenas de itens por dia precisa de PDV, não de conversa. O bot é para o comércio onde a venda é esparsa o bastante para caber numa frase.",
         "<strong>Quem já registra tudo pelo painel</strong> ganha pouco. O ganho é proporcional ao buraco que existia.",
         "<strong>Configuração continua no painel</strong>, de propósito: é decisão rara e de consequência larga, onde a tela dá um contexto que uma mensagem não dá."),
    ),
    sec("O que ele não é",
      ul("<strong>Não é um chatbot de atendimento.</strong> Ele fala com você, o dono — não com o seu cliente.",
         "<strong>Não é um assistente que conversa.</strong> Fora dos comandos, ele diz o que sabe fazer. Não improvisa.",
         "<strong>Não substitui o painel.</strong> É a porta de entrada rápida; o painel continua sendo onde se corrige, configura e analisa."),
    ),
  ],
  faq=[
    ("Como registro uma venda pelo WhatsApp?",
     "Mandando uma mensagem ou um áudio, como falaria com um funcionário — por exemplo, “vendi duas cocas no pix”. O SoftPay entende, registra e responde confirmando em cerca de dois segundos."),
    ("Preciso falar de um jeito específico?",
     "Não. Você fala do seu jeito. Quando a frase fica ambígua — produto parecido, forma de pagamento não dita — ele pergunta em vez de adivinhar."),
    ("E se eu registrar errado?",
     "Responda DESFAZER em até 15 minutos e o último registro é cancelado, seja venda, despesa, entrada de estoque ou baixa de fiado."),
    ("Ele vende mesmo sem eu ter estoque?",
     "Não. Estoque insuficiente barra a venda e ele avisa quanto há disponível. O bot recusa em vez de deixar o sistema mentir."),
    ("Em qual plano o bot está disponível?",
     "A partir do plano Loja, de R$ 89/mês. Confirme com o suporte a situação da sua conta antes de contratar contando com ele."),
    ("O bot atende meus clientes?",
     "Não. Ele fala com você, o dono da loja. Não é um chatbot de atendimento ao consumidor."),
    ("Funciona por áudio?",
     "Sim. Um áudio típico de lojista tem de 7 a 8 segundos de fala e vira registro em cerca de dois segundos e meio."),
    ("Ele substitui o painel do SoftPay?",
     "Não. É a porta de entrada rápida para registrar no momento em que a coisa acontece. Correções, configuração e análise mais funda continuam no painel."),
  ],
  cta_title="Teste registrando pelo WhatsApp",
  cta_text="Sete dias grátis, sem cartão. Fale uma venda e veja ela aparecer no sistema.",
  related=[("Sistema PDV", "/solucoes/sistema-pdv/", "A venda no balcão"),
           ("Controle de estoque", "/solucoes/sistema-de-estoque/", "O que o registro alimenta"),
           ("Controle de fiado", "/solucoes/controle-de-fiado/", "Fiado também pelo WhatsApp")],
),

dict(
  slug="solucoes/multiplas-lojas",
  figura=("/assets/lojistas/distribuidora.webp",
          "Funcionário conferindo estoque no depósito da distribuidora"),
  title="Sistema para Múltiplas Lojas e Filiais | SoftPay",
  description="Controle de filiais na mesma conta, multi-login por funcionário e acesso de qualquer dispositivo. Até 10 usuários no ERP Completo. Teste grátis 7 dias.",
  h1="Múltiplas lojas e filiais",
  intro="Quando abre o segundo ponto, muita loja acaba com dois sistemas separados e nenhuma visão do conjunto. O SoftPay controla filiais dentro da mesma conta.",
  breadcrumbs=_c("Múltiplas lojas"),
  blocks=[
    sec("O problema",
      p("Dois pontos de venda com sistemas independentes significam dois cadastros de produto, dois estoques que não conversam e dois relatórios que precisam ser somados na mão. O dono passa a gastar tempo consolidando informação em vez de decidir com ela."),
    ),
    sec("Como o SoftPay resolve",
      h3("Filiais na mesma conta"),
      p("O SoftPay permite controlar filiais dentro da mesma conta, sem contratar um sistema separado para cada ponto."),
      h3("Multi-login"),
      p("Cada pessoa da equipe entra com o próprio acesso, em vez de todo mundo dividir a mesma senha. A quantidade varia por plano: 1 no Comércio, até 3 no Loja e até 10 no ERP Completo."),
      h3("Acesso de qualquer lugar"),
      p("Como os dados ficam na nuvem, você acompanha as duas lojas do celular, sem estar fisicamente em nenhuma delas."),
      nota("Estruturas com filiais variam muito. Antes de contratar, descreva a sua ao suporte — quantos pontos, se o estoque é compartilhado ou separado — para confirmar que o SoftPay atende ao seu caso.", "Vale confirmar antes"),
    ),
  ],
  faq=[
    ("Quantas filiais dá para controlar?",
     "O SoftPay permite controlar filiais dentro da mesma conta. Descreva sua estrutura ao suporte para confirmar o atendimento ao seu caso."),
    ("Cada loja tem estoque separado?",
     "Esse é um ponto a confirmar com o suporte, porque depende de como a sua operação funciona."),
    ("Quantos usuários posso cadastrar?",
     "1 no plano Comércio, até 3 no Loja e até 10 no ERP Completo. O plano Nota Fiscal permite até 2."),
    ("Existem permissões diferentes por funcionário?",
     "O multi-login dá acesso individual a cada pessoa. Sobre perfis de permissão distintos, confirme com o suporte antes de contratar."),
    ("Consigo acompanhar as lojas de longe?",
     "Sim. Os dados ficam na nuvem e o sistema é acessado pelo navegador, inclusive no celular."),
  ],
  related=[("Distribuidora", "/segmentos/distribuidora/", "Depósito e loja"),
           ("Controle de estoque", "/solucoes/sistema-de-estoque/", "Estoque por ponto"),
           ("Preços", "/#pricing", "Usuários por plano")],
),
]
