# -*- coding: utf-8 -*-
from blocks import sec, p, ul, ol, h3, nota, exemplo, tabela

C = [("Soluções", "/solucoes/")]
def _c(n): return C + [(n, None)]

PAGINAS = [

dict(
  slug="solucoes/sistema-de-estoque",
  figura=("/assets/lojistas/loja-de-variedades.webp",
          "Lojista organizando produtos na prateleira da loja"),
  title="Sistema de Controle de Estoque para Loja | SoftPay",
  description="Controle de estoque com custo, quantidade, variações e curva ABC. Saiba quanto dinheiro está parado na prateleira. Teste grátis por 7 dias.",
  h1="Sistema de controle de estoque",
  intro="Cada item na prateleira é dinheiro que você já pagou e ainda não recebeu de volta. Sem custo e quantidade registrados, esse valor fica invisível — e a loja vende bem sem nunca ter dinheiro em caixa.",
  breadcrumbs=_c("Controle de estoque"),
  blocks=[
    sec("O problema",
      p("Estoque descontrolado custa dos dois lados. Falta do que vende, e o cliente compra na concorrência. Sobra do que não vende, e o dinheiro fica preso na prateleira em vez de girar."),
      p("A causa quase sempre é a mesma: a baixa do estoque depende de alguém lembrar de fazer. Quando a venda e o estoque são dois controles separados, eles se desencontram em questão de dias."),
    ),
    sec("Como o SoftPay resolve",
      h3("A venda dá baixa sozinha"),
      p("O estoque é alimentado pelo PDV. Toda venda registrada no balcão baixa a quantidade do produto na hora, sem segunda digitação."),
      h3("Custo junto com o preço"),
      p("Cadastrar só o preço de venda responde quanto entrou. Cadastrar o custo é o que permite responder quanto sobrou — e é o que separa faturamento de lucro."),
      h3("Variações de tamanho e cor"),
      p("Para quem vende roupa e calçado, cada combinação tem a própria quantidade. A baixa acontece na variação certa, não no modelo genérico."),
      h3("Curva ABC"),
      p("Separa os produtos por participação no resultado. É o filtro que transforma um cadastro de centenas de itens numa decisão de compra concreta: o que repor, o que remarcar e o que não comprar mais."),
      h3("Atacado e varejo"),
      p("Dois preços no mesmo produto, para quem atende revendedor e consumidor final."),
    ),
    sec("O que você passa a conseguir responder",
      ul("Quanto dinheiro eu tenho investido em mercadoria parada?",
         "Quais produtos sustentam o meu faturamento?",
         "O que está encalhado há tempo demais?",
         "Quanto eu realmente ganho em cada produto, depois do custo?",
         "O que preciso repor antes de acabar?"),
      nota("Estoque essencial já está no plano Comércio (R$ 69/mês). Variações, custo e curva ABC ficam disponíveis a partir do plano Loja (R$ 89/mês).", "Em qual plano"),
    ),
  ],
  faq=[
    ("O estoque baixa sozinho quando eu vendo?",
     "Sim. A venda registrada no PDV dá baixa na quantidade do produto automaticamente, sem digitação separada."),
    ("Consigo cadastrar o custo de cada produto?",
     "Sim, a partir do plano Loja. É o custo cadastrado que permite calcular margem e saber quanto está investido em mercadoria."),
    ("O que é curva ABC?",
     "É uma classificação que separa os produtos pela participação no resultado: poucos itens costumam responder pela maior parte do faturamento. Serve para focar a decisão de compra no que importa."),
    ("Dá para controlar tamanho e cor?",
     "Sim, com o cadastro de variações, disponível a partir do plano Loja."),
    ("Como faço o primeiro inventário?",
     "O caminho prático é cadastrar primeiro os produtos de maior giro com quantidade e custo, e completar o restante conforme repõe. O guia de estoque explica o método."),
  ],
  related=[("Como controlar estoque", "/guias/como-controlar-estoque/", "Método passo a passo"),
           ("Sistema PDV", "/solucoes/sistema-pdv/", "A venda que alimenta o estoque"),
           ("Loja de roupas", "/segmentos/loja-de-roupas/", "Estoque com grade")],
),

dict(
  slug="solucoes/sistema-pdv",
  figura=("/assets/lojistas/mercadinho.webp",
          "Lojista registrando a venda no balcão do mercadinho"),
  title="Sistema PDV para Loja: Frente de Caixa | SoftPay",
  description="Sistema PDV com venda rápida, baixa automática de estoque, formas de pagamento e fechamento de caixa. Roda no navegador. Teste grátis 7 dias.",
  h1="Sistema PDV (frente de caixa)",
  intro="O PDV é onde o dinheiro entra e onde o dado nasce. Se a venda não é registrada direito ali, nenhum relatório depois vai fazer sentido.",
  breadcrumbs=_c("Sistema PDV"),
  blocks=[
    sec("O problema",
      p("Muita loja pequena trata o caixa como uma gaveta: o dinheiro entra, o produto sai e nada fica registrado. No fim do dia sobra um valor que não se explica, e no fim do mês uma dúvida sobre o resultado."),
      p("Quando existe registro, ele costuma ser em papel ou planilha — feito depois, de memória, com o movimento já terminado. O que chega ao relatório é uma reconstrução aproximada do que aconteceu."),
    ),
    sec("Como o SoftPay resolve",
      h3("Venda registrada na hora"),
      p("Produto, quantidade, preço, forma de pagamento e cliente ficam gravados no momento da venda. É o mesmo ato: vender e registrar."),
      h3("Estoque e caixa alimentados juntos"),
      p("A mesma venda baixa o estoque e entra no caixa. Não existe a etapa de passar a limpo depois — que é justamente onde as informações se perdem."),
      h3("Fechamento de caixa"),
      p("No fim do expediente você compara o que o sistema registrou com o que está na gaveta. A diferença aparece no mesmo dia, enquanto ainda dá para lembrar o que houve."),
      h3("Venda fiada no mesmo fluxo"),
      p("Se o cliente leva para pagar depois, a venda entra como fiado no nome dele, sem sair do PDV e sem caderno paralelo."),
      h3("Sem instalar nada"),
      p("O PDV roda no navegador. Funciona no computador do balcão, no notebook e no celular, com os dados na nuvem."),
    ),
  ],
  faq=[
    ("Preciso instalar o PDV no computador?",
     "Não. O SoftPay roda no navegador, sem instalação e sem servidor na loja."),
    ("Funciona com leitor de código de barras?",
     "O campo de busca do PDV aceita a leitura do código. Confirme a compatibilidade do seu leitor com o suporte antes de contratar."),
    ("Funciona sem internet?",
     "O sistema é acessado pela internet, então depende de conexão. Se a sua região tem instabilidade, converse com o suporte antes de contratar."),
    ("O PDV controla as formas de pagamento?",
     "Sim. A forma de pagamento é registrada na venda, o que permite conferir o caixa por tipo de recebimento no fechamento."),
    ("Em qual plano está o PDV?",
     "A partir do plano Comércio, de R$ 69/mês. O plano Nota Fiscal não inclui PDV — ele serve só para emissão de notas."),
  ],
  related=[("Controle de estoque", "/solucoes/sistema-de-estoque/", "A baixa automática"),
           ("Sistema financeiro", "/solucoes/sistema-financeiro/", "Caixa e resultado"),
           ("Como controlar o caixa", "/guias/como-controlar-caixa-da-loja/", "Rotina de fechamento")],
),

dict(
  slug="solucoes/controle-de-fiado",
  figura=("/assets/lojistas/casal-comerciantes.webp",
          "Casal de comerciantes conferindo as contas no computador da loja"),
  title="Sistema de Controle de Fiado para Loja | SoftPay",
  description="Controle de fiado digital: saldo por cliente, histórico e cobrança por link de Pix no WhatsApp. Saia do caderno. Teste grátis por 7 dias.",
  h1="Controle de fiado",
  intro="Vender fiado não é o problema. O problema é o caderno: anotação rasurada, cliente que esquece e você sem saber quanto tem para receber.",
  breadcrumbs=_c("Controle de fiado"),
  blocks=[
    sec("O problema",
      p("No comércio de bairro o fiado é parte do negócio — é o que mantém o cliente fiel e o que atravessa o fim do mês de muita gente. Mas o dinheiro fiado é o mais fácil de perder: não tem comprovante, depende da memória de quem anotou e some quando a folha do caderno acaba."),
      p("O efeito é silencioso. A loja vendeu, o estoque saiu, mas o dinheiro não entrou — e como não há um total visível, ninguém percebe o tamanho do buraco."),
    ),
    sec("Como o SoftPay resolve",
      h3("Cada venda no nome do cliente"),
      p("A venda fiada é registrada no cadastro do cliente, com data e valor. O saldo é do sistema, não da memória de quem estava no balcão."),
      h3("Histórico para consultar na hora"),
      p("Quando o cliente pergunta quanto deve, a resposta está na tela — com as compras que formam o valor. Isso encerra a discussão antes de ela começar."),
      h3("Cobrança sem constrangimento"),
      p("A partir do plano Loja, o sistema envia link de pagamento por Pix pelo WhatsApp. A cobrança deixa de depender de você puxar o assunto no balcão."),
      h3("Ligado ao resto da loja"),
      p("A venda fiada baixa o estoque como qualquer outra e fica registrada como valor a receber, aparecendo no seu resultado."),
      nota("O caderninho de fiado está no plano Comércio (R$ 69/mês). A cobrança automática com link de Pix pelo WhatsApp fica disponível a partir do plano Loja (R$ 89/mês).", "Em qual plano"),
    ),
  ],
  faq=[
    ("Consigo ver quanto cada cliente me deve?",
     "Sim. O saldo fica no cadastro do cliente, com o histórico das compras que formam o valor."),
    ("O sistema cobra o cliente automaticamente?",
     "A partir do plano Loja, o SoftPay envia link de pagamento por Pix pelo WhatsApp, o que tira de você a tarefa de puxar o assunto da cobrança."),
    ("Dá para definir um limite de fiado por cliente?",
     "Confirme esse ponto com o suporte antes de contratar — não assuma que existe sem verificar."),
    ("A venda fiada baixa o estoque?",
     "Sim. Ela é uma venda como qualquer outra: o produto sai do estoque e o valor fica registrado como a receber."),
    ("Como faço para passar o caderno atual para o sistema?",
     "O caminho prático é lançar os saldos em aberto como vendas fiadas no nome de cada cliente. O guia de fiado explica o processo."),
  ],
  related=[("Como controlar fiado", "/guias/como-controlar-fiado/", "Método e cobrança"),
           ("Controle de clientes", "/solucoes/controle-de-clientes/", "Cadastro e histórico"),
           ("Mercadinho", "/segmentos/mercadinho/", "O fiado do bairro")],
),

dict(
  slug="solucoes/sistema-financeiro",
  figura=("/assets/lojistas/casal-comerciantes.webp",
          "Comerciantes analisando os números da loja no computador"),
  title="Sistema Financeiro para Loja: Caixa e Resultado | SoftPay",
  description="Controle de caixa, entradas e saídas, e visão do resultado da loja. Entenda a diferença entre faturamento e lucro. Teste grátis por 7 dias.",
  h1="Controle financeiro da loja",
  intro="Faturamento é o que entrou. Lucro é o que sobrou. A maior parte dos problemas de caixa em loja pequena nasce de confundir os dois.",
  breadcrumbs=_c("Financeiro"),
  blocks=[
    sec("O problema",
      p("“Vendi muito e não tenho dinheiro” é a frase mais comum do varejo pequeno. Quase nunca é problema de venda: é o custo da mercadoria e as despesas comendo a margem sem que ninguém acompanhe."),
      p("Sem separar essas camadas, qualquer decisão vira aposta — desde formar preço até saber se dá para contratar alguém."),
    ),
    sec("Como o SoftPay resolve",
      h3("Caixa alimentado pela venda"),
      p("O que passa no PDV entra no caixa com a forma de pagamento registrada. O fechamento diário compara o registrado com o que está na gaveta."),
      h3("Custo dentro da conta"),
      p("Com o custo dos produtos cadastrado, o sistema tem os dois lados da operação — o que entrou e o que a mercadoria custou —, que é a base do lucro bruto."),
      h3("Visão do período"),
      p("Painel e relatórios reúnem vendas, estoque, caixa e fiado no mesmo lugar, para você olhar o mês inteiro em vez de um dia isolado."),
    ),
    sec("A conta, camada por camada",
      exemplo("Do faturamento ao resultado", [
        ("Vendas do mês", "R$ 25.480,00", ""),
        ("Custo dos produtos vendidos (CMV)", "− R$ 16.560,00", "minus"),
        ("= Lucro bruto", "R$ 8.920,00", "result"),
        ("Despesas do período", "− R$ 3.400,00", "minus"),
        ("= Resultado estimado", "R$ 5.520,00", "result final"),
      ], "Números fictícios. O resultado da sua loja depende dos seus próprios dados de venda, custo e despesa. Veja o método em <a href=\"/guias/como-calcular-lucro-da-loja/\">como calcular o lucro da loja</a>."),
      nota("O SoftPay ajuda a organizar os dados que formam essa conta. Ele não substitui a contabilidade da empresa nem dispensa o seu contador.", "Sobre o alcance disto"),
    ),
  ],
  faq=[
    ("O SoftPay substitui meu contador?",
     "Não. Ele organiza os dados da operação — vendas, custos, caixa e notas. A contabilidade da empresa continua com o seu contador."),
    ("Ele calcula o meu lucro automaticamente?",
     "O sistema reúne os dados que formam a conta: vendas registradas e custo dos produtos cadastrado. A precisão do resultado depende de esses dados estarem completos."),
    ("Consigo lançar despesas da loja?",
     "Confirme com o suporte o alcance do lançamento de despesas no seu plano antes de contratar."),
    ("Como o fiado aparece no financeiro?",
     "A venda fiada é registrada como valor a receber, o que evita contar como caixa um dinheiro que ainda não entrou."),
    ("Dá para fechar o caixa todo dia?",
     "Sim, e é a prática recomendada: a diferença aparece no mesmo dia, enquanto ainda dá para identificar a causa."),
  ],
  related=[("Como calcular lucro", "/guias/como-calcular-lucro-da-loja/", "Faturamento não é lucro"),
           ("Como calcular margem", "/guias/como-calcular-margem-de-lucro/", "Formação de preço"),
           ("Sistema PDV", "/solucoes/sistema-pdv/", "De onde vem o dado")],
),

dict(
  slug="solucoes/nfe",
  figura=("/assets/lojistas/distribuidora.webp",
          "Operação de distribuidora, onde a nota fiscal faz parte da rotina"),
  title="Sistema para Emitir NF-e (Nota Fiscal Eletrônica) | SoftPay",
  description="Emissão de NF-e com cadastro fiscal e pacote do contador. Planos a partir de R$ 65/mês. Teste grátis por 7 dias, sem cartão.",
  h1="Emissão de NF-e",
  intro="A NF-e é a nota fiscal eletrônica usada nas operações entre empresas e em vendas que exigem documento fiscal completo. O SoftPay cobre a emissão nos planos Nota Fiscal e ERP Completo.",
  breadcrumbs=_c("NF-e"),
  blocks=[
    sec("Quando você precisa de NF-e",
      p("A obrigatoriedade depende do seu regime tributário, da atividade e do tipo de operação. Venda para outra empresa, transporte de mercadoria e algumas operações específicas normalmente exigem NF-e."),
      nota("Obrigação fiscal não se resolve por artigo em site. Confirme com o seu contador o que a sua empresa precisa emitir antes de contratar qualquer sistema. Informações oficiais estão no portal da NF-e e na SEFAZ do seu estado.", "Consulte seu contador"),
    ),
    sec("Como funciona no SoftPay",
      h3("Dois caminhos"),
      p("Se você só precisa emitir notas, o plano <strong>Nota Fiscal</strong> (R$ 65/mês) resolve: você preenche um formulário e emite, sem PDV, estoque ou relatórios. Se quer a gestão completa com a emissão junto, o <strong>ERP Completo</strong> (R$ 109/mês) inclui tudo."),
      h3("Cadastro fiscal e pacote do contador"),
      p("Os dois planos incluem o cadastro fiscal e o pacote do contador, para que o seu contabilista receba o que precisa sem trabalho manual seu."),
      h3("Notas recebidas"),
      p("Além de emitir, dá para visualizar as notas recebidas de fornecedores, e manifestá-las no plano Nota Fiscal."),
      nota("A emissão de NFC-e, NF-e, NFS-e e MDF-e consta nos planos como recurso <strong>em ativação</strong>. Antes de contratar contando com um documento específico, confirme a situação atual com o suporte.", "Situação da emissão"),
    ),
  ],
  faq=[
    ("Qual a diferença entre NF-e e NFC-e?",
     "A NF-e costuma ser usada em operações entre empresas e em vendas que exigem documento fiscal completo. A NFC-e é o cupom fiscal eletrônico, usado na venda ao consumidor final no balcão."),
    ("Preciso de certificado digital?",
     "A emissão de documentos fiscais eletrônicos normalmente exige certificado digital. Confirme com o suporte e com seu contador o que é necessário no seu caso."),
    ("Em quais planos está a emissão?",
     "Nos planos Nota Fiscal (R$ 65/mês) e ERP Completo (R$ 109/mês). Os planos Comércio e Loja não incluem emissão."),
    ("O plano Nota Fiscal tem PDV e estoque?",
     "Não. Ele é só a nota: você preenche um formulário e emite. Sem PDV, estoque, clientes ou relatórios."),
    ("Consigo ver as notas que recebo dos fornecedores?",
     "Sim. A visualização de notas recebidas está disponível a partir do plano Comércio, e a manifestação no plano Nota Fiscal."),
  ],
  related=[("NFC-e", "/solucoes/nfce/", "Cupom fiscal no balcão"),
           ("Distribuidora", "/segmentos/distribuidora/", "Operação com nota"),
           ("Preços", "/#pricing", "Planos com emissão fiscal")],
),

dict(
  slug="solucoes/nfce",
  figura=("/assets/lojistas/papelaria.webp",
          "Atendente finalizando a venda no caixa da papelaria"),
  title="Sistema para Emitir NFC-e (Cupom Fiscal) | SoftPay",
  description="Emissão de NFC-e, o cupom fiscal eletrônico da venda no balcão, integrada ao PDV. Planos com emissão a partir de R$ 65/mês. Teste grátis 7 dias.",
  h1="Emissão de NFC-e",
  intro="A NFC-e é o cupom fiscal eletrônico da venda ao consumidor final — o documento do balcão. No SoftPay ela vive junto do PDV, no plano ERP Completo.",
  breadcrumbs=_c("NFC-e"),
  blocks=[
    sec("O que é a NFC-e",
      p("A NFC-e substituiu o antigo cupom fiscal impresso por equipamento próprio. É o documento emitido na venda ao consumidor final, no varejo, e sua exigência varia conforme o estado e o perfil da empresa."),
      nota("Cada estado tem regras próprias de credenciamento e obrigatoriedade para NFC-e. Confirme com o seu contador e com a SEFAZ do seu estado antes de contratar.", "Regras variam por estado"),
    ),
    sec("Como funciona no SoftPay",
      h3("Junto da venda"),
      p("No ERP Completo, a emissão convive com o PDV: a mesma venda que baixa o estoque e entra no caixa é a que gera o documento fiscal."),
      h3("Só a nota, se for o caso"),
      p("Se você não precisa de PDV e estoque, o plano Nota Fiscal (R$ 65/mês) permite emitir preenchendo um formulário."),
      h3("Cadastro fiscal e contador"),
      p("Os planos com emissão incluem cadastro fiscal e pacote do contador."),
      nota("A emissão consta nos planos como recurso <strong>em ativação</strong>. Confirme a situação atual com o suporte antes de contratar contando com ela.", "Situação da emissão"),
    ),
  ],
  faq=[
    ("NFC-e é o mesmo que cupom fiscal?",
     "A NFC-e é o cupom fiscal eletrônico. Ela substituiu o cupom impresso por equipamento fiscal próprio na venda ao consumidor final."),
    ("Minha loja é obrigada a emitir NFC-e?",
     "Depende do estado, do regime tributário e da atividade. Confirme com seu contador e com a SEFAZ do seu estado."),
    ("Em qual plano está a NFC-e?",
     "Nos planos Nota Fiscal (R$ 65/mês) e ERP Completo (R$ 109/mês)."),
    ("Precisa de impressora fiscal?",
     "A NFC-e não exige o antigo equipamento emissor de cupom fiscal. Sobre impressão do DANFE e equipamentos, confirme os detalhes com o suporte."),
    ("A emissão está funcionando hoje?",
     "Os planos descrevem a emissão como em ativação. Confirme a situação atual com o suporte antes de contratar."),
  ],
  related=[("NF-e", "/solucoes/nfe/", "Nota fiscal eletrônica"),
           ("Sistema PDV", "/solucoes/sistema-pdv/", "A venda que gera o cupom"),
           ("Papelaria", "/segmentos/papelaria/", "Cupom no varejo")],
),

dict(
  slug="solucoes/loja-online",
  figura=("/assets/lojistas/celular-balcao.webp",
          "Mãos de um comerciante usando o celular sobre o balcão"),
  title="Loja Online com Catálogo e Pix | SoftPay",
  description="Loja online integrada ao seu estoque, com catálogo, pagamento por Pix e confirmação automática do pedido. A partir do plano Loja. Teste grátis 7 dias.",
  h1="Loja online com Pix",
  intro="Nem todo cliente vai até o balcão. Com a loja online do SoftPay, seu catálogo fica disponível para quem prefere escolher pelo celular e pagar por Pix.",
  breadcrumbs=_c("Loja online"),
  blocks=[
    sec("O problema de manter dois negócios",
      p("Vender pela internet costuma significar um segundo cadastro de produtos, um segundo estoque e uma segunda conta para acompanhar. Na prática, o lojista pequeno abandona um dos dois — quase sempre o online."),
    ),
    sec("Como o SoftPay resolve",
      h3("Um cadastro só"),
      p("O catálogo online é alimentado pelos produtos que você já cadastrou para o balcão. Não existe um segundo cadastro para manter."),
      h3("Pix que confirma sozinho"),
      p("O cliente paga por Pix e o pedido é confirmado automaticamente, sem você precisar conferir comprovante no WhatsApp."),
      h3("Pedidos dentro do sistema"),
      p("Os pedidos chegam no mesmo lugar onde você já acompanha a loja física."),
      h3("Cupom e fidelidade"),
      p("Cupons de desconto e programa de fidelidade ajudam a trazer o cliente de volta, online ou no balcão."),
      nota("A loja online está disponível a partir do plano Loja (R$ 89/mês).", "Em qual plano"),
    ),
  ],
  faq=[
    ("A loja online usa o mesmo estoque da loja física?",
     "Sim. O catálogo é alimentado pelos produtos já cadastrados, o que evita manter dois cadastros em paralelo."),
    ("Como o cliente paga?",
     "Por Pix, com confirmação automática do pedido — sem você precisar conferir comprovante manualmente."),
    ("Aceita cartão de crédito?",
     "Confirme com o suporte as formas de pagamento disponíveis hoje na loja online antes de contratar."),
    ("Preciso de domínio próprio?",
     "Converse com o suporte sobre como o endereço da sua loja online é configurado."),
    ("Em qual plano está?",
     "A partir do plano Loja, de R$ 89/mês."),
  ],
  related=[("Controle de estoque", "/solucoes/sistema-de-estoque/", "O catálogo vem daqui"),
           ("Controle de clientes", "/solucoes/controle-de-clientes/", "Cupom e fidelidade"),
           ("Loja de roupas", "/segmentos/loja-de-roupas/", "Vender moda online")],
),

dict(
  slug="solucoes/controle-de-clientes",
  figura=("/assets/lojistas/loja-de-roupas.webp",
          "Lojista atendendo com o tablet na mão numa loja de roupas"),
  title="Controle de Clientes e CRM para Loja | SoftPay",
  description="Cadastro de clientes com histórico de compras, base para fiado, cupons e fidelidade. Saiba quem volta a comprar. Teste grátis por 7 dias.",
  h1="Controle de clientes (CRM)",
  intro="Conquistar cliente novo custa caro. O cliente que já comprou é o mais barato de trazer de volta — desde que você saiba quem ele é e o que ele comprou.",
  breadcrumbs=_c("Controle de clientes"),
  blocks=[
    sec("O problema",
      p("Na maioria das lojas pequenas, o conhecimento sobre os clientes está na cabeça do dono. Funciona enquanto o movimento é pequeno e a mesma pessoa atende todo mundo. Quando entra outra pessoa no balcão ou o volume cresce, esse conhecimento não se transfere."),
    ),
    sec("Como o SoftPay resolve",
      h3("Cadastro ligado à venda"),
      p("A venda registrada no PDV pode ser vinculada ao cliente, formando um histórico real de compras — não uma lista solta de nomes e telefones."),
      h3("Base do fiado"),
      p("O saldo do fiado vive no cadastro do cliente, com as compras que o formam."),
      h3("Cupom e fidelidade"),
      p("A partir do plano Loja, cupons de desconto e programa de fidelidade usam essa base para trazer o cliente de volta."),
      h3("Contato com propósito"),
      p("Saber o que a pessoa comprou e quando permite um contato útil, em vez de disparo genérico para uma lista inteira."),
    ),
  ],
  faq=[
    ("O cadastro de clientes está em qual plano?",
     "O cadastro de clientes faz parte do sistema a partir do plano Comércio. Cupons e fidelidade ficam disponíveis a partir do plano Loja."),
    ("Consigo ver o histórico de compras de cada cliente?",
     "Sim, quando a venda é vinculada ao cliente no momento do registro no PDV."),
    ("Serve para trabalhar recompra?",
     "Sim. Saber o que a pessoa comprou e quando é a base para um contato com propósito, especialmente em segmentos de recompra previsível."),
    ("E a LGPD?",
     "Você é responsável pelos dados dos seus clientes. Colete o necessário, informe a finalidade e consulte a Política de Privacidade do SoftPay."),
    ("Dá para importar minha lista atual?",
     "A importação está disponível a partir do plano Loja. Fale com o suporte para conferir o formato do arquivo."),
  ],
  related=[("Controle de fiado", "/solucoes/controle-de-fiado/", "Saldo por cliente"),
           ("Loja online", "/solucoes/loja-online/", "Cupom e fidelidade"),
           ("Loja de roupas", "/segmentos/loja-de-roupas/", "Cliente que volta")],
),

dict(
  slug="solucoes/bot-whatsapp",
  figura=("/assets/lojistas/celular-balcao.webp",
          "Comerciante registrando uma venda pelo celular no balcão"),
  title="Registre a Venda pelo WhatsApp | Bot do SoftPay",
  description="Registre venda, despesa, estoque e fiado mandando uma mensagem ou um áudio no WhatsApp. O SoftPay responde em segundos, sem você abrir o sistema.",
  h1="Registre a venda pelo WhatsApp",
  intro="O lojista não deixa de registrar porque o sistema é ruim. Deixa porque registrar exige parar. Com o bot do SoftPay, a venda entra no sistema enquanto o cliente ainda está na sua frente.",
  breadcrumbs=_c("Bot do WhatsApp"),
  blocks=[
    sec("O problema não é o sistema. É o momento.",
      p("Atrás do balcão, com o cliente na frente e a mão no troco, abrir o aplicativo é um movimento que não acontece. Falar, sim. Então a venda acontece e o registro não — e a partir daí a loja inteira desanda:"),
      ul("O <strong>estoque mente</strong>, e você compra o que já tem ou não repõe o que acabou.",
         "O <strong>caixa não fecha</strong>, e você passa a desconfiar do próprio sistema.",
         "O <strong>relatório não decide nada</strong>, porque descreve metade da loja.",
         "E o fiado volta para o caderno de papel."),
      p("Esse buraco entre o que aconteceu na loja e o que o sistema sabe é o problema de verdade. Não falta recurso no painel: falta o momento de abrir o painel."),
    ),
    sec("Como funciona",
      p("Você manda uma mensagem ou um áudio no WhatsApp, como falaria com um funcionário. O SoftPay entende, registra e responde confirmando — em cerca de dois segundos."),
      h3("O que dá para fazer falando"),
      ul("Registrar venda, com forma de pagamento",
         "Lançar despesa",
         "Dar entrada de estoque",
         "Registrar venda fiada no nome do cliente",
         "Dar baixa em dívida de fiado",
         "Lançar suprimento e sangria de caixa",
         "Consultar saldo, estoque e o que foi vendido"),
      p("São 17 operações no total. Um áudio típico de lojista tem <strong>7 a 8 segundos</strong> de fala."),
      nota("O bot está disponível <strong>a partir do plano Loja</strong>. Ele não substitui o painel: correções, configuração e análise mais funda continuam lá.", "Em qual plano"),
    ),
    sec("Uma conversa real, cronometrada",
      p("Esta sequência aconteceu de verdade, em 46 segundos, sem o painel ser aberto uma única vez:"),
      exemplo("Do problema descoberto à venda registrada", [
        ("16:08:12 — “Vendi duas cocas no pix”", "recusado: estoque 0", "minus"),
        ("16:08:27 — “Registre no estoque 10 coca”", "entrada registrada", ""),
        ("16:08:38 — “Vende duas cocas no Pix”", "venda de R$ 10,00", "result final"),
      ], "Repare no mais importante: o bot <strong>recusou</strong> a primeira venda porque o estoque estava zerado. Ele não deixa o sistema mentir para agradar."),
    ),
    sec("Por que dá para confiar dinheiro a ele",
      p("Um bot que registra venda mexe no caixa da sua loja. O que sustenta isso:"),
      h3("Ele prefere perguntar a adivinhar"),
      p("Produto ambíguo, forma de pagamento ausente, cliente homônimo, valor muito alto — em todos, ele pergunta. Chutar “dinheiro” numa venda bagunçaria o seu fechamento em silêncio, e silêncio é o pior defeito num sistema que mexe com dinheiro."),
      h3("Ele recusa em vez de mentir"),
      p("Estoque insuficiente barra a venda. Baixa maior que a dívida é recusada, com o saldo certo na resposta. Fiado sem cliente identificado não entra."),
      h3("Nada acontece duas vezes"),
      p("Se o WhatsApp reentregar a mesma mensagem, ela não é registrada de novo."),
      h3("Dá para desfazer"),
      p("Por 15 minutos, “DESFAZER” cancela o último registro — venda, despesa, cadastro, entrada de estoque, suprimento ou baixa de fiado."),
      h3("A mesma frase dá sempre o mesmo resultado"),
      p("A maior parte das frases é resolvida por regra fixa, não por adivinhação: o mesmo áudio registra sempre a mesma venda."),
    ),
    sec("Onde ele ajuda pouco",
      p("Vale ser honesto sobre o tamanho da coisa:"),
      ul("<strong>Loja com fila constante e movimento alto.</strong> Quem passa centenas de itens por dia precisa de PDV, não de conversa. O bot é para o comércio onde a venda é esparsa o bastante para caber numa frase.",
         "<strong>Quem já registra tudo pelo painel</strong> ganha pouco. O ganho é proporcional ao buraco que existia.",
         "<strong>Configuração continua no painel</strong>, de propósito: é decisão rara e de consequência larga, onde a tela dá um contexto que uma mensagem não dá."),
    ),
    sec("O que ele não é",
      ul("<strong>Não é um chatbot de atendimento.</strong> Ele fala com você, o dono — não com o seu cliente.",
         "<strong>Não é um assistente que conversa.</strong> Fora dos comandos, ele diz o que sabe fazer. Não improvisa.",
         "<strong>Não substitui o painel.</strong> É a porta de entrada rápida; o painel continua sendo onde se corrige, configura e analisa."),
    ),
  ],
  faq=[
    ("Como registro uma venda pelo WhatsApp?",
     "Mandando uma mensagem ou um áudio, como falaria com um funcionário — por exemplo, “vendi duas cocas no pix”. O SoftPay entende, registra e responde confirmando em cerca de dois segundos."),
    ("Preciso falar de um jeito específico?",
     "Não. Você fala do seu jeito. Quando a frase fica ambígua — produto parecido, forma de pagamento não dita — ele pergunta em vez de adivinhar."),
    ("E se eu registrar errado?",
     "Responda DESFAZER em até 15 minutos e o último registro é cancelado, seja venda, despesa, entrada de estoque ou baixa de fiado."),
    ("Ele vende mesmo sem eu ter estoque?",
     "Não. Estoque insuficiente barra a venda e ele avisa quanto há disponível. O bot recusa em vez de deixar o sistema mentir."),
    ("Em qual plano o bot está disponível?",
     "A partir do plano Loja, de R$ 89/mês. Confirme com o suporte a situação da sua conta antes de contratar contando com ele."),
    ("O bot atende meus clientes?",
     "Não. Ele fala com você, o dono da loja. Não é um chatbot de atendimento ao consumidor."),
    ("Funciona por áudio?",
     "Sim. Um áudio típico de lojista tem de 7 a 8 segundos de fala e vira registro em cerca de dois segundos e meio."),
    ("Ele substitui o painel do SoftPay?",
     "Não. É a porta de entrada rápida para registrar no momento em que a coisa acontece. Correções, configuração e análise mais funda continuam no painel."),
  ],
  cta_title="Teste registrando pelo WhatsApp",
  cta_text="Sete dias grátis, sem cartão. Fale uma venda e veja ela aparecer no sistema.",
  related=[("Sistema PDV", "/solucoes/sistema-pdv/", "A venda no balcão"),
           ("Controle de estoque", "/solucoes/sistema-de-estoque/", "O que o registro alimenta"),
           ("Controle de fiado", "/solucoes/controle-de-fiado/", "Fiado também pelo WhatsApp")],
),

dict(
  slug="solucoes/multiplas-lojas",
  figura=("/assets/lojistas/distribuidora.webp",
          "Funcionário conferindo estoque no depósito da distribuidora"),
  title="Sistema para Múltiplas Lojas e Filiais | SoftPay",
  description="Controle de filiais na mesma conta, multi-login por funcionário e acesso de qualquer dispositivo. Até 10 usuários no ERP Completo. Teste grátis 7 dias.",
  h1="Múltiplas lojas e filiais",
  intro="Quando abre o segundo ponto, muita loja acaba com dois sistemas separados e nenhuma visão do conjunto. O SoftPay controla filiais dentro da mesma conta.",
  breadcrumbs=_c("Múltiplas lojas"),
  blocks=[
    sec("O problema",
      p("Dois pontos de venda com sistemas independentes significam dois cadastros de produto, dois estoques que não conversam e dois relatórios que precisam ser somados na mão. O dono passa a gastar tempo consolidando informação em vez de decidir com ela."),
    ),
    sec("Como o SoftPay resolve",
      h3("Filiais na mesma conta"),
      p("O SoftPay permite controlar filiais dentro da mesma conta, sem contratar um sistema separado para cada ponto."),
      h3("Multi-login"),
      p("Cada pessoa da equipe entra com o próprio acesso, em vez de todo mundo dividir a mesma senha. A quantidade varia por plano: 1 no Comércio, até 3 no Loja e até 10 no ERP Completo."),
      h3("Acesso de qualquer lugar"),
      p("Como os dados ficam na nuvem, você acompanha as duas lojas do celular, sem estar fisicamente em nenhuma delas."),
      nota("Estruturas com filiais variam muito. Antes de contratar, descreva a sua ao suporte — quantos pontos, se o estoque é compartilhado ou separado — para confirmar que o SoftPay atende ao seu caso.", "Vale confirmar antes"),
    ),
  ],
  faq=[
    ("Quantas filiais dá para controlar?",
     "O SoftPay permite controlar filiais dentro da mesma conta. Descreva sua estrutura ao suporte para confirmar o atendimento ao seu caso."),
    ("Cada loja tem estoque separado?",
     "Esse é um ponto a confirmar com o suporte, porque depende de como a sua operação funciona."),
    ("Quantos usuários posso cadastrar?",
     "1 no plano Comércio, até 3 no Loja e até 10 no ERP Completo. O plano Nota Fiscal permite até 2."),
    ("Existem permissões diferentes por funcionário?",
     "O multi-login dá acesso individual a cada pessoa. Sobre perfis de permissão distintos, confirme com o suporte antes de contratar."),
    ("Consigo acompanhar as lojas de longe?",
     "Sim. Os dados ficam na nuvem e o sistema é acessado pelo navegador, inclusive no celular."),
  ],
  related=[("Distribuidora", "/segmentos/distribuidora/", "Depósito e loja"),
           ("Controle de estoque", "/solucoes/sistema-de-estoque/", "Estoque por ponto"),
           ("Preços", "/#pricing", "Usuários por plano")],
),
]
