# -*- coding: utf-8 -*-
from blocks import sec, p, ul, ol, h3, nota, exemplo, tabela

C = [("Soluções", "/solucoes/")]
def _c(n): return C + [(n, None)]

PAGINAS = [

dict(
  slug="solucoes/sistema-de-estoque",
  figura=("/assets/lojistas/loja-de-variedades.webp",
          "Lojista organizando produtos na prateleira da loja"),
  title="Sistema de Controle de Estoque para Loja | SoftPay",
  description="Controle de estoque com custo, quantidade, variações e curva ABC. Saiba quanto dinheiro está parado na prateleira. Teste grátis por 7 dias.",
  h1="Sistema de controle de estoque",
  intro="Cada item na prateleira é dinheiro que você já pagou e ainda não recebeu de volta. Sem custo e quantidade registrados, esse valor fica invisível — e a loja vende bem sem nunca ter dinheiro em caixa.",
  breadcrumbs=_c("Controle de estoque"),
  blocks=[
    sec("O problema",
      p("Estoque descontrolado custa dos dois lados. Falta do que vende, e o cliente compra na concorrência. Sobra do que não vende, e o dinheiro fica preso na prateleira em vez de girar."),
      p("A causa quase sempre é a mesma: a baixa do estoque depende de alguém lembrar de fazer. Quando a venda e o estoque são dois controles separados, eles se desencontram em questão de dias."),
      p("E o desencontro não avisa. Ele aparece semanas depois, na forma de um item que faltou num sábado de movimento ou de uma compra repetida do que já estava no depósito."),
    ),
    sec("Como o descontrole aparece na sua loja",
      ul("<strong>Você promete o que não tem.</strong> Diz que tem, vai buscar e não acha. A venda morre na hora.",
         "<strong>Compra o que já está lá.</strong> O fornecedor chega, você repõe pela impressão, e o item aparece em dobro.",
         "<strong>O encalhe só aparece no inventário.</strong> Quando você percebe, o dinheiro já está parado há meses.",
         "<strong>A margem é uma média que engana.</strong> Sem custo por item, o produto de 15% e o de 60% viram um número só.",
         "<strong>Ninguém confia no número da tela.</strong> E quando o sistema perde a confiança, todo mundo volta a conferir na prateleira."),
    ),
    sec("Como o SoftPay resolve",
      h3("A venda dá baixa sozinha"),
      p("O estoque é alimentado pelo PDV. Toda venda registrada no balcão baixa a quantidade do produto na hora, sem segunda digitação. É o que impede o desencontro de nascer."),
      h3("Custo junto com o preço"),
      p("Cadastrar só o preço de venda responde quanto entrou. Cadastrar o custo é o que permite responder quanto sobrou — e é o que separa faturamento de lucro."),
      h3("Variações de tamanho e cor"),
      p("Para quem vende roupa e calçado, cada combinação tem a própria quantidade. A baixa acontece na variação certa, não no modelo genérico. A partir do plano Loja."),
      h3("Curva ABC"),
      p("Separa os produtos por participação no resultado. É o filtro que transforma um cadastro de centenas de itens numa decisão de compra concreta: o que repor, o que remarcar e o que não comprar mais. A partir do plano Loja."),
      h3("Atacado e varejo"),
      p("Dois preços no mesmo produto, para quem atende revendedor e consumidor final, sem cadastro duplicado."),
      h3("Entrada de mercadoria pelo WhatsApp"),
      p("A partir do plano Loja, a entrada de estoque pode ser registrada por mensagem ou áudio. No momento em que a carga chega, ninguém está sentado na frente do computador — e é aí que o registro costuma não acontecer. Veja o <a href=\"/solucoes/bot-whatsapp/\">bot do WhatsApp</a>."),
    ),
    sec("O que o controle de estoque não faz",
      p("Os limites, antes de você contratar contando com eles:"),
      ul("<strong>Não integra com balança.</strong> Venda por peso — frios, hortifrúti, granel — entra como produto comum, com o valor digitado no PDV.",
         "<strong>Não faz inventário por coletor.</strong> A contagem é feita por você e lançada no sistema; não há aparelho de leitura em massa.",
         "<strong>Não faz pedido de compra automático.</strong> O sistema mostra o que está acabando; a compra continua sendo sua, pelo canal de sempre.",
         "<strong>Não monta kit nem ficha técnica.</strong> Produto composto de outros produtos, com baixa dos componentes, não faz parte do sistema.",
         "<strong>Validade e lote não estão confirmados.</strong> Se a sua operação depende disso, verifique com o suporte antes de contratar.",
         "<strong>Estoque separado por filial não está confirmado.</strong> Descreva sua estrutura ao suporte se você tem mais de um ponto."),
    ),
    sec("Quanto dinheiro está parado, na prática",
      p("O número que quase nenhuma loja pequena sabe de cabeça é o valor do próprio estoque a preço de custo. Com custo e quantidade cadastrados, ele deixa de ser chute:"),
      exemplo("O que a prateleira vale, a preço de custo", [
        ("Classe A — 40 itens que giram", "R$ 9.200,00", ""),
        ("Classe B — 120 itens de giro médio", "R$ 7.400,00", ""),
        ("Classe C — 380 itens parados", "R$ 11.800,00", "minus"),
        ("= Total investido em mercadoria", "R$ 28.400,00", "result final"),
      ], "Números fictícios, só para mostrar o raciocínio. A leitura importante é a última linha da classe C: quase metade do dinheiro imobilizado nos itens que menos giram. Veja o guia <a href=\"/guias/como-controlar-estoque/\">como controlar estoque</a>."),
    ),
    sec("O que você passa a conseguir responder",
      ul("Quanto dinheiro eu tenho investido em mercadoria parada?",
         "Quais produtos sustentam o meu faturamento?",
         "O que está encalhado há tempo demais?",
         "Quanto eu realmente ganho em cada produto, depois do custo?",
         "O que preciso repor antes de acabar?",
         "Qual variação de tamanho ou cor mais sai, e qual eu compro demais?"),
    ),
    sec("Em qual plano está cada parte",
      tabela(["Plano", "Preço", "O que você tem de estoque"], [
        ["Comércio", "R$ 69/mês", "Estoque essencial: cadastro de produtos, quantidade e baixa automática pela venda"],
        ["Loja", "R$ 89/mês", "<strong>O plano do controle completo:</strong> custo por produto, variações de tamanho e cor, curva ABC e importação"],
        ["ERP Completo", "R$ 109/mês", "Tudo da Loja, mais emissão de NF-e e NFC-e e até 10 usuários"],
      ]),
      p("Todos podem ser testados por 7 dias, sem cartão de crédito. Veja os <a href=\"/#pricing\">planos completos</a>."),
    ),
  ],
  faq=[
    ("O estoque baixa sozinho quando eu vendo?",
     "Sim. A venda registrada no PDV dá baixa na quantidade do produto automaticamente, sem digitação separada."),
    ("Consigo cadastrar o custo de cada produto?",
     "Sim, a partir do plano Loja. É o custo cadastrado que permite calcular margem e saber quanto está investido em mercadoria."),
    ("O que é curva ABC?",
     "É uma classificação que separa os produtos pela participação no resultado: poucos itens costumam responder pela maior parte do faturamento. Serve para focar a decisão de compra no que importa. Está disponível a partir do plano Loja."),
    ("Dá para controlar tamanho e cor?",
     "Sim, com o cadastro de variações, disponível a partir do plano Loja. Cada combinação tem quantidade própria e a baixa acontece na variação certa."),
    ("O sistema controla validade e lote?",
     "Não está confirmado. Se você trabalha com alimento, medicamento ou qualquer item com data crítica, verifique com o suporte antes de contratar."),
    ("Vendo por peso. Funciona com balança?",
     "O SoftPay não integra com balança. Itens vendidos por peso entram como produto comum, com o valor digitado no PDV."),
    ("Dá para importar minha planilha de produtos?",
     "A importação está disponível a partir do plano Loja. Fale com o suporte antes de migrar para conferir o formato do arquivo."),
    ("Como faço o primeiro inventário?",
     "O caminho prático é cadastrar primeiro os produtos de maior giro com quantidade e custo, e completar o restante conforme repõe. O guia de estoque explica o método."),
    ("Tenho duas lojas. O estoque é separado?",
     "Esse ponto não está confirmado e depende da sua estrutura. Descreva sua operação ao suporte antes de contratar."),
  ],
  cta_title="Descubra quanto está parado na sua prateleira",
  cta_text="Cadastre os produtos de maior giro com custo e quantidade, registre as vendas por uma semana e veja o número aparecer. 7 dias grátis, sem cartão.",
  related=[("Como controlar estoque", "/guias/como-controlar-estoque/", "Método passo a passo"),
           ("Sistema PDV", "/solucoes/sistema-pdv/", "A venda que alimenta o estoque"),
           ("Bot do WhatsApp", "/solucoes/bot-whatsapp/", "Dar entrada falando"),
           ("Loja de roupas", "/segmentos/loja-de-roupas/", "Estoque com grade"),
           ("Loja de variedades", "/segmentos/loja-de-variedades/", "Centenas de itens"),
           ("Distribuidora", "/segmentos/distribuidora/", "Estoque em volume")],
),

dict(
  slug="solucoes/sistema-pdv",
  figura=("/assets/lojistas/mercadinho.webp",
          "Lojista registrando a venda no balcão do mercadinho"),
  title="Sistema PDV para Loja: Frente de Caixa | SoftPay",
  description="Sistema PDV com venda rápida, baixa automática de estoque, formas de pagamento e fechamento de caixa. Roda no navegador. Teste grátis 7 dias.",
  h1="Sistema PDV (frente de caixa)",
  intro="O PDV é onde o dinheiro entra e onde o dado nasce. Se a venda não é registrada direito ali, nenhum relatório depois vai fazer sentido.",
  breadcrumbs=_c("Sistema PDV"),
  blocks=[
    sec("O problema",
      p("Muita loja pequena trata o caixa como uma gaveta: o dinheiro entra, o produto sai e nada fica registrado. No fim do dia sobra um valor que não se explica, e no fim do mês uma dúvida sobre o resultado."),
      p("Quando existe registro, ele costuma ser em papel ou planilha — feito depois, de memória, com o movimento já terminado. O que chega ao relatório é uma reconstrução aproximada do que aconteceu."),
      p("O detalhe que quase ninguém nota: o erro não está no relatório, está na origem. Nenhuma ferramenta conserta depois um dado que nunca foi coletado."),
    ),
    sec("Como isso aparece na sua loja",
      ul("<strong>O caixa não bate</strong> e ninguém sabe em qual venda a diferença começou.",
         "<strong>O estoque mente</strong>, porque a saída do produto não foi registrada junto com a venda.",
         "<strong>A fila trava no preço.</strong> Alguém vai conferir na prateleira enquanto o cliente espera.",
         "<strong>Você não sabe como recebeu.</strong> Quanto foi Pix, quanto foi cartão, quanto foi dinheiro — tudo virou um total só.",
         "<strong>O fiado sai por fora</strong>, num caderno paralelo que ninguém mais consegue ler."),
    ),
    sec("Como o SoftPay resolve",
      h3("Venda registrada na hora"),
      p("Produto, quantidade, preço, forma de pagamento e cliente ficam gravados no momento da venda. É o mesmo ato: vender e registrar. Não existe a etapa de passar a limpo depois — que é justamente onde a informação se perde."),
      h3("Estoque e caixa alimentados juntos"),
      p("A mesma venda baixa o estoque e entra no caixa. Um registro, três consequências: a prateleira, a gaveta e o relatório passam a contar a mesma história."),
      h3("Fechamento de caixa"),
      p("No fim do expediente você compara o que o sistema registrou com o que está na gaveta. A diferença aparece no mesmo dia, enquanto ainda dá para lembrar o que houve."),
      h3("Forma de pagamento por venda"),
      p("Dinheiro, Pix, cartão e fiado ficam registrados individualmente. No fechamento você confere cada tipo de recebimento separadamente, em vez de brigar com um total único."),
      h3("Venda fiada no mesmo fluxo"),
      p("Se o cliente leva para pagar depois, a venda entra como fiado no nome dele, sem sair do PDV e sem caderno paralelo. Veja o <a href=\"/solucoes/controle-de-fiado/\">controle de fiado</a>."),
      h3("Sem instalar nada"),
      p("O PDV roda no navegador. Funciona no computador do balcão, no notebook e no celular, com os dados na nuvem — sem servidor na loja e sem licença por máquina."),
    ),
    sec("O que o PDV não faz",
      p("Os limites reais, para você não descobrir durante o teste:"),
      ul("<strong>Não funciona sem internet.</strong> O acesso é pelo navegador. Se a sua região tem queda frequente de conexão, pese isso na decisão.",
         "<strong>Não integra com balança.</strong> Venda por peso entra como produto comum, com o valor digitado.",
         "<strong>Não tem TEF nem concilia maquininha.</strong> A forma de pagamento é registrada na venda, mas o valor que a adquirente deposita não entra sozinho no sistema.",
         "<strong>Não faz comanda nem mesa.</strong> Bar, restaurante e lanchonete precisam de um fluxo que o SoftPay não tem.",
         "<strong>Impressora térmica e gaveta não estão confirmadas.</strong> Verifique o seu equipamento com o suporte antes de contratar.",
         "<strong>A emissão fiscal consta como em ativação.</strong> Se você precisa de NFC-e no ato da venda, confirme a situação atual com o suporte."),
    ),
    sec("Um dia no balcão, do jeito que acontece",
      p("A rotina que o PDV substitui:"),
      ol("Abre o caixa com o valor de troco inicial.",
         "Cada venda passa pelo PDV: produto, quantidade e forma de pagamento.",
         "O estoque baixa junto, sem ninguém precisar lembrar.",
         "A venda fiada entra no nome do cliente, no mesmo lugar.",
         "No fim do dia, o fechamento compara sistema e gaveta.",
         "A diferença, se houver, é conferida hoje — não no fim do mês."),
      nota("Exemplo ilustrativo do fluxo. O ritmo da sua loja depende do seu movimento e do tamanho do catálogo.", "Sobre este exemplo"),
    ),
    sec("O que você passa a conseguir responder",
      ul("Quanto vendi hoje, e quanto disso foi Pix, cartão e dinheiro?",
         "O caixa de ontem bateu?",
         "Qual produto mais saiu esta semana?",
         "Quanto saiu em fiado no mês?",
         "Qual o meu ticket médio?",
         "Que horas a loja vende mais?"),
    ),
    sec("Em qual plano está",
      tabela(["Plano", "Preço", "O PDV neste plano"], [
        ["Comércio", "R$ 69/mês", "<strong>PDV completo já aqui:</strong> venda, formas de pagamento, baixa de estoque, fiado e fechamento de caixa. 1 usuário"],
        ["Loja", "R$ 89/mês", "O mesmo PDV, com estoque avançado por trás: custo, variações e curva ABC. Até 3 usuários"],
        ["ERP Completo", "R$ 109/mês", "Tudo da Loja mais emissão de NF-e e NFC-e. Até 10 usuários"],
        ["Nota Fiscal", "R$ 65/mês", "<strong>Não inclui PDV.</strong> Serve só para emissão de notas"],
      ]),
      p("Todos podem ser testados por 7 dias, sem cartão de crédito. Veja os <a href=\"/#pricing\">planos completos</a>."),
    ),
  ],
  faq=[
    ("Preciso instalar o PDV no computador?",
     "Não. O SoftPay roda no navegador, sem instalação e sem servidor na loja. Funciona no computador do balcão, no notebook e no celular."),
    ("Funciona com leitor de código de barras?",
     "O campo de busca do PDV aceita a leitura do código. Confirme a compatibilidade do seu leitor com o suporte antes de contratar."),
    ("Funciona sem internet?",
     "Não. O sistema é acessado pela internet, então depende de conexão. Se a sua região tem instabilidade, converse com o suporte antes de contratar."),
    ("O PDV controla as formas de pagamento?",
     "Sim. Dinheiro, Pix, cartão e fiado são registrados individualmente na venda, o que permite conferir o caixa por tipo de recebimento no fechamento."),
    ("Ele concilia o que a maquininha me paga?",
     "Não. A forma de pagamento fica registrada na venda, mas o depósito da adquirente não entra automaticamente. A conferência com o extrato é manual."),
    ("Serve para bar ou restaurante?",
     "Não. O SoftPay não tem comanda nem controle de mesa. Ele foi feito para comércio que vende produto com estoque."),
    ("Funciona com impressora térmica e gaveta de dinheiro?",
     "Esse ponto não está confirmado. Descreva seu equipamento ao suporte antes de contratar."),
    ("O PDV emite cupom fiscal?",
     "A emissão de NFC-e está nos planos Nota Fiscal e ERP Completo, e consta como recurso em ativação. Confirme a situação com o suporte e com seu contador."),
    ("Em qual plano está o PDV?",
     "A partir do plano Comércio, de R$ 69/mês. O plano Nota Fiscal não inclui PDV — ele serve só para emissão de notas."),
  ],
  cta_title="Teste no seu próprio balcão",
  cta_text="Cadastre os produtos de maior giro, passe as vendas de um dia pelo PDV e feche o caixa no fim da tarde. 7 dias grátis, sem cartão.",
  related=[("Controle de estoque", "/solucoes/sistema-de-estoque/", "A baixa automática"),
           ("Sistema financeiro", "/solucoes/sistema-financeiro/", "Caixa e resultado"),
           ("Controle de fiado", "/solucoes/controle-de-fiado/", "A venda a prazo, no mesmo fluxo"),
           ("Bot do WhatsApp", "/solucoes/bot-whatsapp/", "Registrar sem abrir o painel"),
           ("Como controlar o caixa", "/guias/como-controlar-caixa-da-loja/", "Rotina de fechamento"),
           ("Mercadinho", "/segmentos/mercadinho/", "O balcão de maior movimento")],
),

dict(
  slug="solucoes/controle-de-fiado",
  figura=("/assets/lojistas/casal-comerciantes.webp",
          "Casal de comerciantes conferindo as contas no computador da loja"),
  title="Sistema de Controle de Fiado para Loja | SoftPay",
  description="Controle de fiado digital: saldo por cliente, histórico e cobrança por link de Pix no WhatsApp. Saia do caderno. Teste grátis por 7 dias.",
  h1="Controle de fiado",
  intro="Vender fiado não é o problema. O problema é o caderno: anotação rasurada, cliente que esquece e você sem saber quanto tem para receber.",
  breadcrumbs=_c("Controle de fiado"),
  blocks=[
    sec("O problema",
      p("No comércio de bairro o fiado é parte do negócio — é o que mantém o cliente fiel e o que atravessa o fim do mês de muita gente. Mas o dinheiro fiado é o mais fácil de perder: não tem comprovante, depende da memória de quem anotou e some quando a folha do caderno acaba."),
      p("O efeito é silencioso. A loja vendeu, o estoque saiu, mas o dinheiro não entrou — e como não há um total visível, ninguém percebe o tamanho do buraco."),
      p("Some a isso o desconforto de cobrar alguém que você encontra na rua. É por isso que muita dívida de fiado nunca é cobrada: não por falta de controle, por falta de jeito de puxar o assunto."),
    ),
    sec("Como isso aparece na sua loja",
      ul("<strong>Você não sabe o total a receber.</strong> Sabe que \"tem gente devendo\", não quanto.",
         "<strong>O saldo depende de uma pessoa só.</strong> Se quem anota falta, ninguém resolve nada no balcão.",
         "<strong>A conversa vira discussão.</strong> O cliente lembra de um valor, o caderno diz outro, e não há como provar.",
         "<strong>A cobrança não acontece.</strong> Você adia porque é constrangedor, e o valor envelhece.",
         "<strong>O caderno acaba.</strong> Folha rasgada, letra ilegível, página molhada — e o registro simplesmente deixa de existir."),
    ),
    sec("Como o SoftPay resolve",
      h3("Cada venda no nome do cliente"),
      p("A venda fiada é registrada no cadastro do cliente, com data e valor. O saldo é do sistema, não da memória de quem estava no balcão — e qualquer pessoa da loja consegue responder."),
      h3("Histórico para consultar na hora"),
      p("Quando o cliente pergunta quanto deve, a resposta está na tela, com as compras que formam o valor. Isso encerra a discussão antes de ela começar, porque não é a sua palavra contra a dele."),
      h3("Cobrança sem constrangimento"),
      p("A partir do plano Loja, o sistema envia link de pagamento por Pix pelo WhatsApp. A cobrança deixa de depender de você puxar o assunto no balcão — que é o motivo real de tanta dívida antiga não ser cobrada."),
      h3("Ligado ao resto da loja"),
      p("A venda fiada baixa o estoque como qualquer outra e fica registrada como valor a receber, aparecendo no seu resultado. Fiado deixa de ser um controle paralelo."),
      h3("Registrar e dar baixa falando"),
      p("A partir do plano Loja, você registra uma venda fiada ou dá baixa numa dívida por mensagem ou áudio no WhatsApp. O bot recusa baixa maior que o saldo e responde com o valor certo. Veja o <a href=\"/solucoes/bot-whatsapp/\">bot do WhatsApp</a>."),
    ),
    sec("O que o controle de fiado não faz",
      p("É crédito que você concede com o próprio dinheiro. Vale saber o que o sistema não cobre:"),
      ul("<strong>Não consulta SPC nem Serasa.</strong> A decisão de vender fiado continua sendo sua, baseada no que você sabe do cliente.",
         "<strong>Não negativa quem não paga.</strong> Não há qualquer integração com órgão de proteção ao crédito.",
         "<strong>Não calcula juros nem multa por atraso.</strong> O saldo é o valor das compras.",
         "<strong>Não gera carnê nem boleto.</strong> A cobrança sai por link de Pix no WhatsApp, a partir do plano Loja.",
         "<strong>Limite de crédito por cliente não está confirmado.</strong> Se você precisa travar venda acima de um valor, verifique com o suporte antes de contratar.",
         "<strong>Não cobra sozinho de tempos em tempos.</strong> O envio do link é uma ação sua, não uma régua automática."),
    ),
    sec("O tamanho do buraco, quando ele fica visível",
      p("O primeiro efeito de sair do caderno costuma ser um susto — o total a receber quase sempre é maior do que o dono imaginava:"),
      exemplo("O que estava espalhado pelo caderno", [
        ("14 clientes com saldo em aberto", "R$ 3.180,00", ""),
        ("Desses, 5 com dívida acima de 60 dias", "R$ 1.940,00", "minus"),
        ("= Dinheiro seu, fora do caixa", "R$ 3.180,00", "result final"),
      ], "Números fictícios, só para mostrar o raciocínio. A linha do meio é a que muda o comportamento: quando o vencimento fica visível, a cobrança para de ser adiada. Veja o guia <a href=\"/guias/como-controlar-fiado/\">como controlar fiado</a>."),
    ),
    sec("O que você passa a conseguir responder",
      ul("Quanto tenho a receber de fiado, no total?",
         "Quem deve, quanto e desde quando?",
         "Quais dívidas estão mais velhas?",
         "Este cliente já pagou o que devia do mês passado?",
         "Quanto do meu faturamento saiu a prazo?",
         "Vale continuar vendendo fiado para esta pessoa?"),
    ),
    sec("Em qual plano está",
      tabela(["Plano", "Preço", "O fiado neste plano"], [
        ["Comércio", "R$ 69/mês", "<strong>Caderninho digital já aqui:</strong> saldo e histórico por cliente, venda fiada pelo PDV. 1 usuário"],
        ["Loja", "R$ 89/mês", "Tudo do Comércio mais <strong>cobrança por link de Pix no WhatsApp</strong> e registro pelo bot. Até 3 usuários"],
        ["ERP Completo", "R$ 109/mês", "Tudo da Loja mais emissão de NF-e e NFC-e. Até 10 usuários"],
      ]),
      p("Todos podem ser testados por 7 dias, sem cartão de crédito. Veja os <a href=\"/#pricing\">planos completos</a>."),
    ),
  ],
  faq=[
    ("Consigo ver quanto cada cliente me deve?",
     "Sim. O saldo fica no cadastro do cliente, com o histórico das compras que formam o valor — dá para mostrar na tela quando ele perguntar."),
    ("O sistema cobra o cliente automaticamente?",
     "A partir do plano Loja, o SoftPay envia link de pagamento por Pix pelo WhatsApp. O envio é uma ação sua: não existe régua de cobrança que dispara sozinha."),
    ("Dá para definir um limite de fiado por cliente?",
     "Esse ponto não está confirmado. Se travar venda acima de um valor é importante para você, verifique com o suporte antes de contratar."),
    ("O sistema cobra juros de quem atrasa?",
     "Não. O saldo é o valor das compras; não há cálculo de juros nem multa por atraso."),
    ("Consigo consultar SPC ou negativar quem não paga?",
     "Não. O SoftPay não consulta órgão de proteção ao crédito nem negativa ninguém. A decisão de vender a prazo continua sendo sua."),
    ("A venda fiada baixa o estoque?",
     "Sim. Ela é uma venda como qualquer outra: o produto sai do estoque e o valor fica registrado como a receber."),
    ("Dá para registrar fiado pelo WhatsApp?",
     "Sim, a partir do plano Loja — tanto a venda fiada quanto a baixa da dívida. O bot recusa baixa maior que o saldo e responde com o valor correto."),
    ("Emite carnê ou boleto?",
     "Não. A cobrança sai por link de Pix pelo WhatsApp, disponível a partir do plano Loja."),
    ("Como faço para passar o caderno atual para o sistema?",
     "O caminho prático é lançar os saldos em aberto como vendas fiadas no nome de cada cliente. O guia de fiado explica o processo."),
  ],
  cta_title="Descubra quanto você tem para receber",
  cta_text="Lance os saldos do caderno no nome de cada cliente e veja o total aparecer. Costuma ser maior do que a gente imagina. 7 dias grátis, sem cartão.",
  related=[("Como controlar fiado", "/guias/como-controlar-fiado/", "Método e cobrança"),
           ("Controle de clientes", "/solucoes/controle-de-clientes/", "Cadastro e histórico"),
           ("Sistema PDV", "/solucoes/sistema-pdv/", "A venda a prazo no balcão"),
           ("Bot do WhatsApp", "/solucoes/bot-whatsapp/", "Registrar e dar baixa falando"),
           ("Mercadinho", "/segmentos/mercadinho/", "O fiado do bairro"),
           ("Loja de joias", "/segmentos/loja-de-joias/", "Crediário de alto valor")],
),

dict(
  slug="solucoes/sistema-financeiro",
  figura=("/assets/lojistas/casal-comerciantes.webp",
          "Comerciantes analisando os números da loja no computador"),
  title="Sistema Financeiro para Loja: Caixa e Resultado | SoftPay",
  description="Controle de caixa, entradas e saídas, e visão do resultado da loja. Entenda a diferença entre faturamento e lucro. Teste grátis por 7 dias.",
  h1="Controle financeiro da loja",
  intro="Faturamento é o que entrou. Lucro é o que sobrou. A maior parte dos problemas de caixa em loja pequena nasce de confundir os dois.",
  breadcrumbs=_c("Sistema financeiro"),
  blocks=[
    sec("O problema",
      p("O dono de loja pequena costuma saber quanto vendeu. Quase nunca sabe quanto sobrou — e essa distância é onde mora o problema. Vender bem e não ter dinheiro é o resultado normal de acompanhar só o faturamento."),
      p("Dois motivos explicam quase todos os casos: o custo da mercadoria não está registrado, e as despesas do mês vivem espalhadas entre memória, extrato e papel."),
      p("Sem essas duas peças, o resultado do mês vira sensação. E sensação não decide preço, não decide compra e não decide se dá para contratar alguém."),
    ),
    sec("Como isso aparece na sua loja",
      ul("<strong>O caixa fecha com diferença</strong> e a explicação nunca aparece.",
         "<strong>Você mistura o dinheiro da loja com o seu.</strong> Retirada não registrada vira \"sumiço\" no fim do mês.",
         "<strong>Vendeu muito, não sobrou nada.</strong> O CMV comeu a margem e ninguém viu acontecer.",
         "<strong>A despesa recorrente surpreende.</strong> Aluguel, energia e fornecedor caem sempre, mas nunca entram na conta antes.",
         "<strong>Você não sabe o quanto pode retirar.</strong> Então retira pouco e aperta, ou retira demais e quebra o caixa."),
    ),
    sec("Como o SoftPay resolve",
      h3("Caixa aberto e fechado todo dia"),
      p("Abertura com troco inicial, movimento do dia e fechamento comparando sistema e gaveta. A diferença aparece hoje, enquanto ainda dá para lembrar o que houve."),
      h3("Suprimento e sangria registrados"),
      p("Dinheiro que entra fora da venda e dinheiro que sai do caixa ficam registrados. É o que separa retirada de sumiço."),
      h3("Despesas no mesmo lugar"),
      p("A despesa lançada no sistema entra na conta do resultado. Enquanto ela vive só no extrato do banco, o cálculo do mês fica pela metade."),
      h3("Custo da mercadoria no cálculo"),
      p("Com o custo cadastrado nos produtos, o sistema mostra a margem, não só o faturamento. É a peça que transforma \"vendi R$ 25 mil\" em \"sobrou tanto\". Veja o <a href=\"/solucoes/sistema-de-estoque/\">controle de estoque</a>."),
      h3("Forma de recebimento separada"),
      p("Dinheiro, Pix, cartão e fiado ficam distintos. No fechamento você confere cada um, em vez de brigar com um total só."),
      h3("Lançar despesa falando"),
      p("A partir do plano Loja, despesa, suprimento e sangria entram por mensagem ou áudio no WhatsApp — no momento em que acontecem, que é quando costumam não ser registradas. Veja o <a href=\"/solucoes/bot-whatsapp/\">bot do WhatsApp</a>."),
    ),
    sec("O que o financeiro do SoftPay não faz",
      p("É o controle financeiro da operação da loja, não um sistema contábil. O que fica de fora:"),
      ul("<strong>Não é contabilidade.</strong> Não calcula imposto, não gera DAS, não faz apuração nem declaração. Isso é do seu contador.",
         "<strong>Não integra com banco.</strong> Não há importação de extrato (OFX), conciliação bancária nem saldo de conta.",
         "<strong>Não concilia maquininha.</strong> O que a adquirente deposita não entra sozinho no sistema.",
         "<strong>Não emite boleto nem gera cobrança bancária.</strong>",
         "<strong>Não faz contas a pagar com agenda de vencimentos</strong> de forma confirmada. Se isso é central para você, verifique com o suporte.",
         "<strong>Não faz fluxo de caixa projetado.</strong> Ele mostra o que aconteceu, não uma previsão dos próximos meses."),
    ),
    sec("A conta que separa faturamento de lucro",
      p("É a mesma conta em qualquer comércio, e quase nunca é feita:"),
      exemplo("Vendi R$ 25.480 no mês. Sobrou quanto?", [
        ("Vendas do mês", "R$ 25.480,00", ""),
        ("Custo dos produtos vendidos (CMV)", "− R$ 16.560,00", "minus"),
        ("= Lucro bruto", "R$ 8.920,00", "result"),
        ("Despesas do período", "− R$ 3.400,00", "minus"),
        ("= Resultado estimado", "R$ 5.520,00", "result final"),
      ], "Números fictícios, só para mostrar o raciocínio. Com custo cadastrado e despesa lançada, essa conta deixa de ser estimativa e vira relatório. Veja o guia <a href=\"/guias/como-calcular-lucro-da-loja/\">como calcular o lucro da loja</a>."),
    ),
    sec("O que você passa a conseguir responder",
      ul("Quanto sobrou de verdade no mês passado?",
         "O caixa de ontem bateu? Se não, onde começou a diferença?",
         "Quanto saiu de despesa neste mês?",
         "Quanto do que vendi ainda está a receber, em fiado?",
         "Quanto posso retirar sem apertar o caixa?",
         "Minha margem melhorou ou piorou em relação ao mês anterior?"),
    ),
    sec("Em qual plano está",
      tabela(["Plano", "Preço", "O financeiro neste plano"], [
        ["Comércio", "R$ 69/mês", "Caixa com abertura e fechamento, suprimento, sangria, despesas e formas de recebimento. 1 usuário"],
        ["Loja", "R$ 89/mês", "<strong>Onde o resultado fica completo:</strong> custo por produto e curva ABC entram no cálculo da margem. Até 3 usuários"],
        ["ERP Completo", "R$ 109/mês", "Tudo da Loja mais emissão de NF-e e NFC-e. Até 10 usuários"],
      ]),
      p("Todos podem ser testados por 7 dias, sem cartão de crédito. Veja os <a href=\"/#pricing\">planos completos</a>."),
    ),
  ],
  faq=[
    ("O SoftPay calcula meu imposto ou gera o DAS?",
     "Não. É um sistema de gestão comercial: registra venda, caixa, despesa e estoque. Cálculo de imposto, apuração e declaração continuam com o seu contador."),
    ("Ele importa meu extrato bancário?",
     "Não. Não há integração com banco, importação de OFX nem conciliação bancária."),
    ("Concilia o que a maquininha me paga?",
     "Não. A forma de pagamento fica registrada na venda, mas o depósito da adquirente não entra automaticamente. A conferência é manual."),
    ("Dá para registrar as despesas da loja?",
     "Sim. A despesa lançada entra na conta do resultado. A partir do plano Loja, ela também pode ser lançada por mensagem ou áudio no WhatsApp."),
    ("Tem contas a pagar com vencimento?",
     "Não está confirmado. Se agenda de vencimentos é central na sua rotina, verifique com o suporte antes de contratar."),
    ("Mostra fluxo de caixa projetado?",
     "Não. O sistema mostra o que já aconteceu — não faz previsão dos próximos meses."),
    ("Como sei quanto sobrou de verdade?",
     "Pela conta de vendas menos custo dos produtos menos despesas. Ela só fecha se o custo estiver cadastrado nos produtos, o que está disponível a partir do plano Loja."),
    ("Consigo separar o dinheiro da loja do meu?",
     "Sim, registrando retirada como sangria. É o que evita que a retirada do dono vire diferença inexplicada no fechamento."),
    ("Emite boleto?",
     "Não. A cobrança de fiado sai por link de Pix pelo WhatsApp, a partir do plano Loja."),
  ],
  cta_title="Feche o caixa por uma semana",
  cta_text="Registre as vendas, lance as despesas e feche o caixa todo dia por sete dias. No fim da semana você vê a diferença entre o que imaginava e o que aconteceu. Sem cartão.",
  related=[("Como calcular o lucro", "/guias/como-calcular-lucro-da-loja/", "A conta, passo a passo"),
           ("Como controlar o caixa", "/guias/como-controlar-caixa-da-loja/", "Rotina de fechamento"),
           ("Controle de estoque", "/solucoes/sistema-de-estoque/", "O custo que entra na conta"),
           ("Sistema PDV", "/solucoes/sistema-pdv/", "Onde a entrada é registrada"),
           ("Bot do WhatsApp", "/solucoes/bot-whatsapp/", "Lançar despesa falando"),
           ("Como calcular a margem", "/guias/como-calcular-margem-de-lucro/", "Margem contra giro")],
),

dict(
  slug="solucoes/nfe",
  figura=("/assets/lojistas/distribuidora.webp",
          "Operação de distribuidora, onde a nota fiscal faz parte da rotina"),
  title="Sistema para Emitir NF-e (Nota Fiscal Eletrônica) | SoftPay",
  description="Emissão de NF-e com cadastro fiscal e pacote do contador. Planos a partir de R$ 65/mês. Teste grátis por 7 dias, sem cartão.",
  h1="Emissão de NF-e",
  intro="A NF-e é a nota fiscal eletrônica usada nas operações entre empresas e em vendas que exigem documento fiscal completo. O SoftPay cobre a emissão nos planos Nota Fiscal e ERP Completo.",
  breadcrumbs=_c("NF-e"),
  blocks=[
    sec("Leia isto antes de contratar por causa da nota",
      nota("A emissão fiscal consta nos planos como <strong>recurso em ativação</strong>. Se a nota é condição para você fechar negócio, <strong>confirme a situação atual com o suporte antes de contratar</strong> — não assuma que está disponível hoje na sua conta e no seu estado.", "Recurso em ativação"),
      p("Colocamos esse aviso no primeiro bloco de propósito. Descobrir isso depois de assinar seria pior para você e para nós."),
    ),
    sec("O problema",
      p("Quem vende para empresa não escolhe: sem NF-e, não há venda. O cliente exige o documento para lançar a compra na contabilidade dele, e a operação simplesmente não acontece sem isso."),
      p("A saída comum é emitir a nota num sistema separado, digitando de novo o que já foi vendido. É trabalho dobrado, e cada digitação repetida é uma chance de erro — em documento que tem consequência fiscal."),
    ),
    sec("Como isso aparece na sua operação",
      ul("<strong>A venda é digitada duas vezes:</strong> uma no sistema da loja, outra no emissor de nota.",
         "<strong>O número na nota não bate com o da venda</strong>, e a diferença só aparece na conferência do contador.",
         "<strong>O contador cobra os arquivos todo mês</strong> e alguém precisa juntar tudo na mão.",
         "<strong>A nota de fornecedor se perde.</strong> Chega por e-mail, ninguém baixa, e a entrada de mercadoria fica sem documento.",
         "<strong>Você perde venda</strong> porque não consegue emitir no ato."),
    ),
    sec("Como o SoftPay resolve",
      h3("A nota sai da venda que já existe"),
      p("O documento é emitido a partir da venda registrada no sistema, sem redigitar produto, quantidade e valor em outro lugar."),
      h3("Cadastro fiscal da empresa"),
      p("Os dados fiscais ficam configurados na conta, para a emissão não depender de alguém preencher tudo de novo a cada nota."),
      h3("Pacote do contador"),
      p("Os arquivos que o contador precisa ficam disponíveis para envio, em vez de virarem uma coleta manual no fim do mês."),
      h3("Notas de fornecedor"),
      p("As notas recebidas podem ser consultadas dentro do sistema, e manifestadas no plano Nota Fiscal — parte da rotina de quem compra em volume."),
      h3("Junto do resto da operação"),
      p("No ERP Completo, a emissão convive com PDV, estoque, caixa e clientes. No plano Nota Fiscal, ela vem sozinha, para quem já tem outro sistema de gestão."),
    ),
    sec("O que o SoftPay não faz na parte fiscal",
      p("O limite entre o sistema e o seu contador, com clareza:"),
      ul("<strong>Não é contabilidade.</strong> Não apura imposto, não calcula guia, não faz declaração nem entrega obrigação acessória.",
         "<strong>Não decide a tributação da sua operação.</strong> CFOP, NCM, CST e regime são definição do seu contador — o sistema emite com o que estiver configurado.",
         "<strong>Não emite NFS-e</strong>, a nota de serviço. Ela é municipal e fica fora do SoftPay.",
         "<strong>Não emite CT-e.</strong>",
         "<strong>MDF-e consta como recurso em ativação.</strong> Se a sua operação exige documento de transporte, confirme com o suporte e com o contador.",
         "<strong>Certificado digital não está incluso.</strong> Confirme com o suporte qual tipo é aceito e o que você precisa ter."),
    ),
    sec("Quem precisa de NF-e",
      p("Nem toda loja precisa. Vale saber em qual caso você está — e confirmar com o seu contador:"),
      ul("<strong>Quem vende para outra empresa (PJ).</strong> Aqui a nota costuma ser condição da venda.",
         "<strong>Distribuidora e atacado.</strong> A maior parte das saídas exige documento fiscal.",
         "<strong>Quem faz venda interestadual</strong> ou transporta mercadoria entre praças.",
         "<strong>Quem vende para órgão público</strong> ou participa de licitação."),
      p("Para venda no balcão ao consumidor final, o documento costuma ser a <a href=\"/solucoes/nfce/\">NFC-e</a>, não a NF-e."),
    ),
    sec("Em qual plano está",
      tabela(["Plano", "Preço", "A emissão neste plano"], [
        ["Nota Fiscal", "R$ 65/mês", "<strong>Só a parte fiscal:</strong> emissão de NF-e e NFC-e, cadastro fiscal, manifestação de notas e pacote do contador. Sem PDV nem estoque. Até 2 usuários"],
        ["Comércio", "R$ 69/mês", "<strong>Não emite nota.</strong> PDV, caixa, fiado e estoque essencial"],
        ["Loja", "R$ 89/mês", "<strong>Não emite nota.</strong> Estoque avançado, curva ABC, loja online e bot do WhatsApp"],
        ["ERP Completo", "R$ 109/mês", "<strong>Gestão e nota no mesmo lugar:</strong> tudo do Loja mais NF-e e NFC-e. Até 10 usuários"],
      ]),
      p("Todos podem ser testados por 7 dias, sem cartão de crédito. Veja os <a href=\"/#pricing\">planos completos</a>."),
    ),
  ],
  faq=[
    ("O SoftPay emite NF-e?",
     "A emissão está nos planos Nota Fiscal e ERP Completo, e consta como recurso em ativação. Confirme a situação atual com o suporte antes de contratar contando com ela."),
    ("Qual a diferença entre NF-e e NFC-e?",
     "A NF-e é usada em operações entre empresas e em vendas que exigem documento fiscal completo. A NFC-e é o cupom da venda ao consumidor final, no balcão."),
    ("Em qual plano fica mais barato só a nota?",
     "No plano Nota Fiscal, de R$ 65/mês, que traz a parte fiscal sem PDV nem estoque — para quem já tem outro sistema de gestão. Até 2 usuários."),
    ("O sistema calcula meus impostos?",
     "Não. O SoftPay emite o documento com a configuração fiscal definida pelo seu contador. Apuração, guia e declaração continuam com ele."),
    ("Quem define CFOP, NCM e CST?",
     "Seu contador. O sistema emite com o que estiver configurado — ele não decide a tributação da sua operação."),
    ("Preciso de certificado digital?",
     "O certificado não está incluso. Confirme com o suporte qual tipo é aceito e o que você precisa providenciar."),
    ("Emite nota de serviço (NFS-e)?",
     "Não. A NFS-e é municipal e fica fora do SoftPay."),
    ("E o MDF-e, para transporte?",
     "Consta nos planos como recurso em ativação. Confirme com o suporte e com seu contador antes de contar com ele."),
    ("Consigo ver as notas que meus fornecedores emitiram?",
     "As notas recebidas podem ser consultadas dentro do sistema, e manifestadas no plano Nota Fiscal."),
  ],
  cta_title="Confirme a emissão antes de assinar",
  cta_text="Fale com o suporte sobre a situação da emissão fiscal no seu estado e no seu regime, e use os 7 dias grátis para testar o resto do sistema. Sem cartão.",
  related=[("NFC-e", "/solucoes/nfce/", "O cupom da venda no balcão"),
           ("Distribuidora", "/segmentos/distribuidora/", "Nota em quase toda saída"),
           ("Loja de autopeças", "/segmentos/loja-de-autopecas/", "Venda para oficina"),
           ("Materiais de construção", "/segmentos/materiais-de-construcao/", "Venda para obra e empresa"),
           ("Sistema financeiro", "/solucoes/sistema-financeiro/", "O que é do contador"),
           ("Preços", "/#pricing", "O que tem em cada plano")],
),

dict(
  slug="solucoes/nfce",
  figura=("/assets/lojistas/papelaria.webp",
          "Atendente finalizando a venda no caixa da papelaria"),
  title="Sistema para Emitir NFC-e (Cupom Fiscal) | SoftPay",
  description="Emissão de NFC-e, o cupom fiscal eletrônico da venda no balcão, integrada ao PDV. Planos com emissão a partir de R$ 65/mês. Teste grátis 7 dias.",
  h1="Emissão de NFC-e",
  intro="A NFC-e é o cupom fiscal eletrônico da venda ao consumidor final — o documento do balcão. No SoftPay ela vive junto do PDV, nos planos Nota Fiscal e ERP Completo.",
  breadcrumbs=_c("NFC-e"),
  blocks=[
    sec("Leia isto antes de contratar por causa do cupom",
      nota("A emissão fiscal consta nos planos como <strong>recurso em ativação</strong>. Se o cupom é obrigatório na sua operação, <strong>confirme a situação atual com o suporte antes de contratar</strong> — a exigência varia por estado e por regime, e quem define isso é o seu contador.", "Recurso em ativação"),
      p("Preferimos dizer isso na primeira linha a deixar você descobrir depois de assinar."),
    ),
    sec("O problema",
      p("A NFC-e substituiu o antigo cupom da impressora fiscal. Onde ela é exigida, cada venda ao consumidor final precisa gerar o documento no ato — e isso acontece no meio do movimento, com o cliente esperando."),
      p("Quando a emissão vive num programa separado do PDV, a loja passa a ter dois registros da mesma venda. Eles se desencontram, e a conferência do contador vira uma caça a diferenças."),
    ),
    sec("Como isso aparece na sua loja",
      ul("<strong>A fila para na emissão.</strong> O cupom é gerado em outro programa, com os dados digitados de novo.",
         "<strong>Venda e cupom não batem.</strong> Um item passou no PDV e não entrou no documento.",
         "<strong>O fechamento fica em dúvida:</strong> qual dos dois números é o certo?",
         "<strong>O contador pede os arquivos</strong> e alguém precisa exportar de dois lugares.",
         "<strong>Você deixa de emitir no aperto</strong> — e o problema aparece depois."),
    ),
    sec("Como o SoftPay resolve",
      h3("O cupom sai da venda do PDV"),
      p("A NFC-e é gerada a partir da venda registrada no balcão. Um registro só: o que passou no PDV é o que vai no documento."),
      h3("Estoque, caixa e cupom juntos"),
      p("A mesma venda baixa o estoque, entra no caixa e gera o documento fiscal. Não há dois números para conciliar no fim do dia."),
      h3("Cadastro fiscal configurado uma vez"),
      p("Os dados da empresa ficam na conta, para a emissão não depender de preenchimento manual a cada venda."),
      h3("Pacote do contador"),
      p("Os arquivos ficam disponíveis para envio, em vez de virarem uma coleta manual no fim do mês."),
    ),
    sec("O que o SoftPay não faz na parte fiscal",
      ul("<strong>Não é contabilidade.</strong> Não apura imposto, não gera guia, não faz declaração.",
         "<strong>Não decide a sua tributação.</strong> CFOP, NCM, CST e regime são definição do contador; o sistema emite com o que estiver configurado.",
         "<strong>Não diz se você é obrigado a emitir.</strong> A exigência varia por estado, atividade e regime — quem responde isso é o seu contador.",
         "<strong>Não emite NFS-e</strong>, a nota de serviço, que é municipal.",
         "<strong>Certificado digital não está incluso.</strong> Confirme com o suporte qual tipo é aceito.",
         "<strong>Impressora térmica e gaveta não estão confirmadas.</strong> Descreva seu equipamento ao suporte antes de contratar."),
    ),
    sec("NFC-e ou NF-e: qual é a sua",
      p("A confusão é comum e a diferença é simples:"),
      tabela(["", "NFC-e", "NF-e"], [
        ["Para quem", "Consumidor final, no balcão", "Outra empresa (PJ) e operações que exigem documento completo"],
        ["Onde acontece", "Na venda do PDV", "Na venda para revenda, atacado ou órgão público"],
        ["Quem usa mais", "Mercadinho, papelaria, farmácia, loja de roupas", "Distribuidora, autopeças, materiais de construção"],
      ]),
      p("Muita loja precisa das duas. Nesse caso o plano é o mesmo — veja a página de <a href=\"/solucoes/nfe/\">NF-e</a>."),
    ),
    sec("Em qual plano está",
      tabela(["Plano", "Preço", "A emissão neste plano"], [
        ["Nota Fiscal", "R$ 65/mês", "Emissão de NFC-e e NF-e, cadastro fiscal e pacote do contador. <strong>Sem PDV</strong> — para quem já tem outro sistema. Até 2 usuários"],
        ["Comércio", "R$ 69/mês", "<strong>Não emite cupom.</strong> PDV, caixa, fiado e estoque essencial"],
        ["Loja", "R$ 89/mês", "<strong>Não emite cupom.</strong> Estoque avançado, curva ABC, loja online e bot"],
        ["ERP Completo", "R$ 109/mês", "<strong>O plano de quem emite no balcão:</strong> PDV e NFC-e no mesmo sistema. Até 10 usuários"],
      ]),
      p("Se você precisa emitir <em>no ato da venda</em>, o plano é o ERP Completo — o plano Nota Fiscal não tem PDV. Todos com 7 dias grátis, sem cartão. Veja os <a href=\"/#pricing\">planos completos</a>."),
    ),
  ],
  faq=[
    ("O SoftPay emite NFC-e?",
     "A emissão está nos planos Nota Fiscal e ERP Completo, e consta como recurso em ativação. Confirme a situação atual com o suporte antes de contratar contando com ela."),
    ("Qual plano serve para emitir no balcão?",
     "O ERP Completo, de R$ 109/mês, porque junta PDV e emissão. O plano Nota Fiscal, de R$ 65/mês, tem a emissão mas não tem PDV."),
    ("Sou obrigado a emitir NFC-e?",
     "Depende do seu estado, da sua atividade e do seu regime. Quem responde isso é o seu contador — o sistema não faz essa avaliação."),
    ("Qual a diferença entre NFC-e e cupom fiscal antigo?",
     "A NFC-e é o documento eletrônico que substituiu o cupom da impressora fiscal. Ela é transmitida ao fisco e não depende do equipamento antigo."),
    ("Preciso de impressora fiscal?",
     "A NFC-e não exige a impressora fiscal antiga. Sobre impressora térmica e gaveta, confirme a compatibilidade do seu equipamento com o suporte."),
    ("Preciso de certificado digital?",
     "O certificado não está incluso. Confirme com o suporte qual tipo é aceito e o que você precisa providenciar."),
    ("O sistema calcula os impostos do cupom?",
     "Não. Ele emite com a configuração fiscal definida pelo seu contador. Apuração e guias continuam com ele."),
    ("Emite nota de serviço?",
     "Não. A NFS-e é municipal e fica fora do SoftPay."),
    ("A venda e o cupom podem ficar diferentes?",
     "Não, porque a NFC-e é gerada a partir da venda registrada no PDV. É um registro só — o que passou no caixa é o que vai no documento."),
  ],
  cta_title="Confirme a emissão antes de assinar",
  cta_text="Fale com o suporte sobre a situação do cupom fiscal no seu estado, e use os 7 dias grátis para testar o PDV e o resto do sistema. Sem cartão.",
  related=[("NF-e", "/solucoes/nfe/", "A nota entre empresas"),
           ("Sistema PDV", "/solucoes/sistema-pdv/", "A venda que gera o cupom"),
           ("Papelaria", "/segmentos/papelaria/", "Cupom no pico da temporada"),
           ("Farmácia", "/segmentos/farmacia/", "Balcão e cupom"),
           ("Mercadinho", "/segmentos/mercadinho/", "Venda ao consumidor final"),
           ("Preços", "/#pricing", "O que tem em cada plano")],
),

dict(
  slug="solucoes/loja-online",
  figura=("/assets/lojistas/celular-balcao.webp",
          "Mãos de um comerciante usando o celular sobre o balcão"),
  title="Loja Online com Catálogo e Pix | SoftPay",
  description="Loja online integrada ao seu estoque, com catálogo, pagamento por Pix e confirmação automática do pedido. A partir do plano Loja. Teste grátis 7 dias.",
  h1="Loja online com Pix",
  intro="Nem todo cliente vai até o balcão. Com a loja online do SoftPay, seu catálogo fica disponível para quem prefere escolher pelo celular e pagar por Pix — usando o mesmo estoque da loja física.",
  breadcrumbs=_c("Loja online"),
  blocks=[
    sec("O problema",
      p("Vender pela internet costuma significar montar uma segunda loja: outro cadastro de produtos, outro estoque para atualizar e outro lugar para conferir pedido. Na prática, quem tenta acaba com dois números de estoque que nunca batem."),
      p("O resultado mais comum é o pior possível: vender online algo que acabou de sair no balcão, e ter que desmarcar a venda com o cliente."),
    ),
    sec("Como isso aparece na sua loja",
      ul("<strong>O cliente pergunta preço pelo WhatsApp</strong> e alguém digita a resposta de novo, uma por uma, o dia inteiro.",
         "<strong>A foto está no Instagram, o preço não.</strong> E o que estava no post já mudou.",
         "<strong>Você vende o que não tem.</strong> O item saiu no balcão e o anúncio continua no ar.",
         "<strong>O pagamento vira conversa.</strong> Mandar chave Pix, esperar comprovante, conferir na mão.",
         "<strong>O pedido não vira registro.</strong> A venda online fica fora do estoque e do relatório."),
    ),
    sec("Como o SoftPay resolve",
      h3("Um estoque, dois canais"),
      p("O catálogo online usa os mesmos produtos já cadastrados. A venda online e a venda do balcão baixam o mesmo saldo — não existem dois números para conciliar."),
      h3("Catálogo sem cadastro dobrado"),
      p("Produto, foto, preço e descrição são os do sistema. Se você mudou o preço no cadastro, mudou na loja online. Nada de manter dois lugares atualizados."),
      h3("Pix com confirmação automática"),
      p("O cliente paga por Pix e o pedido é confirmado sem você ficar conferindo comprovante. É a parte que mais consome tempo na venda por WhatsApp."),
      h3("O pedido entra no seu resultado"),
      p("Venda online é venda: baixa estoque, entra no caixa e aparece nos relatórios junto com o resto. O canal muda, o registro não."),
      h3("Ligado ao cadastro de clientes"),
      p("Quem compra online alimenta o mesmo histórico de quem compra no balcão. Veja o <a href=\"/solucoes/controle-de-clientes/\">controle de clientes</a>."),
      nota("A loja online está disponível <strong>a partir do plano Loja</strong> (R$ 89/mês). Não existe no plano Comércio.", "Em qual plano"),
    ),
    sec("O que a loja online não é",
      p("Ela é um catálogo que vende com Pix, não uma plataforma de e-commerce. Vale ser exato:"),
      ul("<strong>Não calcula frete nem integra com transportadora.</strong> Não há cálculo por CEP, etiqueta nem rastreio.",
         "<strong>Não gerencia entrega.</strong> Combinação de retirada ou entrega acontece fora do sistema.",
         "<strong>Não tem checkout com cartão parcelado.</strong> O pagamento é por Pix.",
         "<strong>Não tem domínio próprio confirmado.</strong> Se você precisa da loja em um endereço seu, confirme com o suporte antes de contratar.",
         "<strong>Não faz marketplace nem integra com Mercado Livre, Shopee ou Nuvemshop.</strong>",
         "<strong>Não tem recuperação de carrinho, cupom de frete nem ferramentas de conversão</strong> de e-commerce."),
      p("Se você precisa de operação de e-commerce completa, ela não substitui uma plataforma dedicada. Se você quer parar de responder preço no WhatsApp e receber por Pix sem conferir comprovante, resolve exatamente isso."),
    ),
    sec("Onde ela rende mais",
      p("O ganho não é abrir um canal novo — é tirar trabalho manual de um canal que você já usa:"),
      ol("O cliente pergunta pelo WhatsApp se tem determinado produto.",
         "Em vez de digitar preço e disponibilidade, você manda o link do catálogo.",
         "Ele escolhe, vê o que realmente tem em estoque e paga por Pix.",
         "A confirmação é automática — sem esperar comprovante.",
         "O pedido baixa o estoque e entra no seu relatório como qualquer venda.",
         "A compra fica no histórico daquele cliente."),
      nota("Exemplo ilustrativo do fluxo. O quanto isso rende depende de quanto do seu atendimento hoje acontece por mensagem.", "Sobre este exemplo"),
    ),
    sec("O que você passa a conseguir responder",
      ul("Quanto vendi online neste mês?",
         "Qual produto sai mais pelo catálogo e qual sai mais no balcão?",
         "O estoque do site bate com o da loja?",
         "Quem são os clientes que compram pela internet?",
         "Quanto do meu faturamento já vem de fora do balcão?"),
    ),
    sec("Em qual plano está",
      tabela(["Plano", "Preço", "Loja online neste plano"], [
        ["Comércio", "R$ 69/mês", "<strong>Não inclui loja online.</strong> Só a operação do balcão"],
        ["Loja", "R$ 89/mês", "<strong>O plano que libera a loja online:</strong> catálogo, Pix com confirmação automática, cupons e fidelidade. Até 3 usuários"],
        ["ERP Completo", "R$ 109/mês", "Tudo da Loja mais emissão de NF-e e NFC-e. Até 10 usuários"],
      ]),
      p("Todos podem ser testados por 7 dias, sem cartão de crédito. Veja os <a href=\"/#pricing\">planos completos</a>."),
    ),
  ],
  faq=[
    ("A loja online usa o mesmo estoque da loja física?",
     "Sim. O catálogo usa os produtos já cadastrados, e a venda online baixa o mesmo saldo da venda do balcão. Não existem dois estoques para conciliar."),
    ("Em qual plano está a loja online?",
     "A partir do plano Loja, de R$ 89/mês. O plano Comércio não inclui esse recurso."),
    ("Como o cliente paga?",
     "Por Pix, com confirmação automática do pedido — sem você precisar conferir comprovante."),
    ("Aceita cartão parcelado?",
     "Não. O pagamento na loja online é por Pix."),
    ("Calcula frete e integra com transportadora?",
     "Não. Não há cálculo por CEP, emissão de etiqueta nem rastreio. A entrega é combinada fora do sistema."),
    ("Posso usar meu próprio domínio?",
     "Esse ponto não está confirmado. Se ter a loja num endereço seu é importante, verifique com o suporte antes de contratar."),
    ("Integra com Mercado Livre, Shopee ou Nuvemshop?",
     "Não. A loja online é um catálogo próprio ligado ao seu estoque, sem integração com marketplace."),
    ("Preciso cadastrar os produtos de novo?",
     "Não. O catálogo usa os produtos que já estão no sistema, com o preço do cadastro."),
    ("A venda online entra no meu relatório?",
     "Sim. Ela baixa estoque, entra no caixa e aparece nos relatórios junto com as vendas do balcão."),
  ],
  cta_title="Pare de digitar preço no WhatsApp",
  cta_text="Publique o catálogo com os produtos que você já cadastrou e mande o link em vez da resposta. 7 dias grátis, sem cartão.",
  related=[("Controle de estoque", "/solucoes/sistema-de-estoque/", "O estoque que os dois canais usam"),
           ("Controle de clientes", "/solucoes/controle-de-clientes/", "Quem compra pela internet"),
           ("Sistema PDV", "/solucoes/sistema-pdv/", "A venda do balcão"),
           ("Loja de roupas", "/segmentos/loja-de-roupas/", "Catálogo com grade"),
           ("Loja de variedades", "/segmentos/loja-de-variedades/", "Catálogo grande"),
           ("Loja de joias", "/segmentos/loja-de-joias/", "Peça de alto valor online")],
),

dict(
  slug="solucoes/controle-de-clientes",
  figura=("/assets/lojistas/loja-de-roupas.webp",
          "Lojista atendendo com o tablet na mão numa loja de roupas"),
  title="Controle de Clientes e CRM para Loja | SoftPay",
  description="Cadastro de clientes com histórico de compras, base para fiado, cupons e fidelidade. Saiba quem volta a comprar. Teste grátis por 7 dias.",
  h1="Controle de clientes (CRM)",
  intro="Conquistar cliente novo custa caro. O cliente que já comprou é o mais barato de trazer de volta — desde que você saiba quem ele é e o que ele comprou.",
  breadcrumbs=_c("Controle de clientes"),
  blocks=[
    sec("O problema",
      p("Na maior parte das lojas pequenas, o cliente é anônimo. Ele compra, vai embora e some do registro. A loja sabe quanto vendeu, mas não sabe para quem — e por isso trata quem volta pela décima vez igual a quem entrou pela primeira."),
      p("O custo disso é invisível porque nunca aparece numa conta. Não existe a linha \"clientes que deixaram de voltar\". Existe só um faturamento que não cresce e ninguém sabe explicar."),
    ),
    sec("Como isso aparece na sua loja",
      ul("<strong>A cliente que volta é atendida como nova.</strong> Ninguém lembra do que ela levou, nem do tamanho dela.",
         "<strong>Você não sabe quem sumiu.</strong> O cliente de todo mês parou de vir e a queda só aparece no trimestre.",
         "<strong>A promoção vai para todo mundo.</strong> Sem histórico, o desconto é disparado para uma lista inteira — inclusive para quem já ia comprar.",
         "<strong>O fiado não tem dono.</strong> A dívida existe, mas não está ligada a um cadastro com histórico.",
         "<strong>Você não sabe quanto vale um cliente.</strong> Quem gasta R$ 2.000 por ano e quem gastou R$ 40 uma vez são a mesma coisa no seu sistema."),
    ),
    sec("Como o SoftPay resolve",
      h3("Cadastro ligado à venda"),
      p("O cliente é identificado no PDV e a compra entra no histórico dele. Não é um cadastro morto num canto do sistema: é o registro do que aquela pessoa comprou e quando."),
      h3("Histórico que responde na hora"),
      p("Quando ele volta, você vê o que levou da última vez. Numa loja de roupas isso é o tamanho e a preferência; numa joalheria, a data da compra que se repete no ano seguinte."),
      h3("Base do fiado"),
      p("O saldo devedor vive no cadastro do cliente, com as compras que o formam. Veja o <a href=\"/solucoes/controle-de-fiado/\">controle de fiado</a>."),
      h3("Cupom e fidelidade"),
      p("A partir do plano Loja, o histórico sustenta cupom e programa de fidelidade. A diferença entre disparar desconto para uma lista e falar com quem tem motivo para voltar está inteira aqui."),
      h3("Quem comprou o quê"),
      p("Cruzar cliente e produto mostra qual público sustenta cada parte do seu catálogo — e é o que transforma uma coleção nova em contato com propósito em vez de mensagem em massa."),
    ),
    sec("O que o CRM do SoftPay não faz",
      p("É um cadastro de clientes com histórico, não uma plataforma de marketing. O que fica de fora:"),
      ul("<strong>Não dispara e-mail marketing nem campanha automática.</strong> Não há régua de mensagens nem automação de envio.",
         "<strong>Não tem funil de vendas.</strong> Sem etapas, oportunidades ou previsão — é varejo, não venda consultiva.",
         "<strong>Não integra com Instagram, WhatsApp Business ou catálogo de rede social.</strong>",
         "<strong>Não faz segmentação avançada.</strong> Não há criação de públicos por regra combinada.",
         "<strong>Não importa a sua agenda de contatos do celular.</strong>"),
      p("Se você precisa de automação de marketing, o SoftPay é a fonte do dado — não a ferramenta de disparo."),
    ),
    sec("O que muda quando o cliente tem nome",
      p("O raciocínio que o cadastro torna possível:"),
      exemplo("Dois clientes que faturam parecido", [
        ("Cliente A — 1 compra de R$ 900", "R$ 900,00", ""),
        ("Cliente B — 9 compras de R$ 100 no ano", "R$ 900,00", ""),
        ("= Mesmo faturamento", "R$ 900,00", "result"),
        ("Quem vale um contato quando chega coleção nova?", "o B", "result final"),
      ], "Exemplo ilustrativo. Sem cadastro, os dois são a mesma linha no relatório. Com histórico, o B é uma relação e o A foi um evento — e você sabe em qual investir atenção."),
    ),
    sec("O que você passa a conseguir responder",
      ul("Quem são meus clientes que mais compram?",
         "O que esta pessoa levou da última vez?",
         "Quem comprou nesta coleção e pode voltar na próxima?",
         "Quem parou de comprar nos últimos meses?",
         "Quanto este cliente já gastou comigo?",
         "Quem está devendo e desde quando?"),
    ),
    sec("Em qual plano está",
      tabela(["Plano", "Preço", "O cadastro neste plano"], [
        ["Comércio", "R$ 69/mês", "Cadastro de clientes com histórico de compras e saldo de fiado. 1 usuário"],
        ["Loja", "R$ 89/mês", "<strong>Onde o cadastro vira ferramenta:</strong> cupons, fidelidade e cobrança por Pix no WhatsApp. Até 3 usuários"],
        ["ERP Completo", "R$ 109/mês", "Tudo da Loja mais emissão de NF-e e NFC-e. Até 10 usuários"],
      ]),
      p("Todos podem ser testados por 7 dias, sem cartão de crédito. Veja os <a href=\"/#pricing\">planos completos</a>."),
    ),
  ],
  faq=[
    ("O cadastro de clientes está em qual plano?",
     "A partir do plano Comércio, de R$ 69/mês, com histórico de compras e saldo de fiado. Cupons e fidelidade ficam disponíveis a partir do plano Loja."),
    ("O histórico de compras fica ligado ao cliente?",
     "Sim. Identificando o cliente no PDV, a compra entra no histórico dele, com data e valor."),
    ("Dá para trabalhar recompra e fidelidade?",
     "Sim, a partir do plano Loja. Cupom e programa de fidelidade se apoiam no histórico de compras do cadastro."),
    ("O sistema dispara e-mail marketing ou mensagem automática?",
     "Não. O SoftPay guarda o histórico e sustenta cupom e fidelidade, mas não tem régua de campanha nem automação de envio."),
    ("Tem funil de vendas ou CRM de oportunidades?",
     "Não. É um cadastro de clientes de varejo, com histórico de compras — não uma ferramenta de venda consultiva com etapas e previsão."),
    ("Integra com Instagram ou WhatsApp Business?",
     "Não. O bot do WhatsApp fala com você, o dono, para registrar operações — não com o seu cliente final."),
    ("Consigo saber quem parou de comprar?",
     "O histórico com datas permite ver quem não volta há tempo. Não existe alerta automático de cliente inativo."),
    ("Preciso cadastrar todo cliente?",
     "Não. O cadastro faz diferença em quem volta, compra fiado ou tem ticket alto. Para a venda de passagem, ele é opcional."),
    ("Dá para importar minha lista de clientes?",
     "A importação está disponível a partir do plano Loja. Fale com o suporte antes de migrar para conferir o formato do arquivo."),
  ],
  cta_title="Comece pelos clientes que voltam",
  cta_text="Cadastre os dez que você já reconhece de vista, registre as compras deles por um mês e veja o histórico virar argumento. 7 dias grátis, sem cartão.",
  related=[("Controle de fiado", "/solucoes/controle-de-fiado/", "O saldo por cliente"),
           ("Loja online", "/solucoes/loja-online/", "Vender para quem já conhece"),
           ("Sistema PDV", "/solucoes/sistema-pdv/", "Onde o cliente é identificado"),
           ("Loja de roupas", "/segmentos/loja-de-roupas/", "A cliente que volta na coleção"),
           ("Loja de joias", "/segmentos/loja-de-joias/", "Recompra por data"),
           ("Farmácia", "/segmentos/farmacia/", "Uso contínuo e recompra")],
),

dict(
  slug="solucoes/bot-whatsapp",
  figura=("/assets/lojistas/celular-balcao.webp",
          "Comerciante registrando uma venda pelo celular no balcão"),
  title="Registre a Venda pelo WhatsApp | Bot do SoftPay",
  description="Registre venda, despesa, estoque e fiado mandando uma mensagem ou um áudio no WhatsApp. O SoftPay responde em segundos, sem você abrir o sistema.",
  h1="Registre a venda pelo WhatsApp",
  intro="O lojista não deixa de registrar porque o sistema é ruim. Deixa porque registrar exige parar. Com o bot do SoftPay, a venda entra no sistema enquanto o cliente ainda está na sua frente.",
  breadcrumbs=_c("Bot do WhatsApp"),
  blocks=[
    sec("O problema não é o sistema. É o momento.",
      p("Atrás do balcão, com o cliente na frente e a mão no troco, abrir o aplicativo é um movimento que não acontece. Falar, sim. Então a venda acontece e o registro não — e a partir daí a loja inteira desanda:"),
      ul("O <strong>estoque mente</strong>, e você compra o que já tem ou não repõe o que acabou.",
         "O <strong>caixa não fecha</strong>, e você passa a desconfiar do próprio sistema.",
         "O <strong>relatório não decide nada</strong>, porque descreve metade da loja.",
         "E o fiado volta para o caderno de papel."),
      p("Esse buraco entre o que aconteceu na loja e o que o sistema sabe é o problema de verdade. Não falta recurso no painel: falta o momento de abrir o painel."),
    ),
    sec("Como funciona",
      p("Você manda uma mensagem ou um áudio no WhatsApp, como falaria com um funcionário. O SoftPay entende, registra e responde confirmando — em cerca de dois segundos."),
      h3("O que dá para fazer falando"),
      ul("Registrar venda, com forma de pagamento",
         "Lançar despesa",
         "Dar entrada de estoque",
         "Registrar venda fiada no nome do cliente",
         "Dar baixa em dívida de fiado",
         "Lançar suprimento e sangria de caixa",
         "Consultar saldo, estoque e o que foi vendido"),
      p("São 17 operações no total. Um áudio típico de lojista tem <strong>7 a 8 segundos</strong> de fala."),
      nota("O bot está disponível <strong>a partir do plano Loja</strong>. Ele não substitui o painel: correções, configuração e análise mais funda continuam lá.", "Em qual plano"),
    ),
    sec("Uma conversa real, cronometrada",
      p("Esta sequência aconteceu de verdade, em 46 segundos, sem o painel ser aberto uma única vez:"),
      exemplo("Do problema descoberto à venda registrada", [
        ("16:08:12 — “Vendi duas cocas no pix”", "recusado: estoque 0", "minus"),
        ("16:08:27 — “Registre no estoque 10 coca”", "entrada registrada", ""),
        ("16:08:38 — “Vende duas cocas no Pix”", "venda de R$ 10,00", "result final"),
      ], "Repare no mais importante: o bot <strong>recusou</strong> a primeira venda porque o estoque estava zerado. Ele não deixa o sistema mentir para agradar."),
    ),
    sec("Por que dá para confiar dinheiro a ele",
      p("Um bot que registra venda mexe no caixa da sua loja. O que sustenta isso:"),
      h3("Ele prefere perguntar a adivinhar"),
      p("Produto ambíguo, forma de pagamento ausente, cliente homônimo, valor muito alto — em todos, ele pergunta. Chutar “dinheiro” numa venda bagunçaria o seu fechamento em silêncio, e silêncio é o pior defeito num sistema que mexe com dinheiro."),
      h3("Ele recusa em vez de mentir"),
      p("Estoque insuficiente barra a venda. Baixa maior que a dívida é recusada, com o saldo certo na resposta. Fiado sem cliente identificado não entra."),
      h3("Nada acontece duas vezes"),
      p("Se o WhatsApp reentregar a mesma mensagem, ela não é registrada de novo."),
      h3("Dá para desfazer"),
      p("Por 15 minutos, “DESFAZER” cancela o último registro — venda, despesa, cadastro, entrada de estoque, suprimento ou baixa de fiado."),
      h3("A mesma frase dá sempre o mesmo resultado"),
      p("A maior parte das frases é resolvida por regra fixa, não por adivinhação: o mesmo áudio registra sempre a mesma venda."),
    ),
    sec("Onde ele ajuda pouco",
      p("Vale ser honesto sobre o tamanho da coisa:"),
      ul("<strong>Loja com fila constante e movimento alto.</strong> Quem passa centenas de itens por dia precisa de PDV, não de conversa. O bot é para o comércio onde a venda é esparsa o bastante para caber numa frase.",
         "<strong>Quem já registra tudo pelo painel</strong> ganha pouco. O ganho é proporcional ao buraco que existia.",
         "<strong>Configuração continua no painel</strong>, de propósito: é decisão rara e de consequência larga, onde a tela dá um contexto que uma mensagem não dá."),
    ),
    sec("O que ele não é",
      ul("<strong>Não é um chatbot de atendimento.</strong> Ele fala com você, o dono — não com o seu cliente.",
         "<strong>Não é um assistente que conversa.</strong> Fora dos comandos, ele diz o que sabe fazer. Não improvisa.",
         "<strong>Não substitui o painel.</strong> É a porta de entrada rápida; o painel continua sendo onde se corrige, configura e analisa."),
    ),
  ],
  faq=[
    ("Como registro uma venda pelo WhatsApp?",
     "Mandando uma mensagem ou um áudio, como falaria com um funcionário — por exemplo, “vendi duas cocas no pix”. O SoftPay entende, registra e responde confirmando em cerca de dois segundos."),
    ("Preciso falar de um jeito específico?",
     "Não. Você fala do seu jeito. Quando a frase fica ambígua — produto parecido, forma de pagamento não dita — ele pergunta em vez de adivinhar."),
    ("E se eu registrar errado?",
     "Responda DESFAZER em até 15 minutos e o último registro é cancelado, seja venda, despesa, entrada de estoque ou baixa de fiado."),
    ("Ele vende mesmo sem eu ter estoque?",
     "Não. Estoque insuficiente barra a venda e ele avisa quanto há disponível. O bot recusa em vez de deixar o sistema mentir."),
    ("Em qual plano o bot está disponível?",
     "A partir do plano Loja, de R$ 89/mês. Confirme com o suporte a situação da sua conta antes de contratar contando com ele."),
    ("O bot atende meus clientes?",
     "Não. Ele fala com você, o dono da loja. Não é um chatbot de atendimento ao consumidor."),
    ("Funciona por áudio?",
     "Sim. Um áudio típico de lojista tem de 7 a 8 segundos de fala e vira registro em cerca de dois segundos e meio."),
    ("Ele substitui o painel do SoftPay?",
     "Não. É a porta de entrada rápida para registrar no momento em que a coisa acontece. Correções, configuração e análise mais funda continuam no painel."),
  ],
  cta_title="Teste registrando pelo WhatsApp",
  cta_text="Sete dias grátis, sem cartão. Fale uma venda e veja ela aparecer no sistema.",
  related=[("Sistema PDV", "/solucoes/sistema-pdv/", "A venda no balcão"),
           ("Controle de estoque", "/solucoes/sistema-de-estoque/", "O que o registro alimenta"),
           ("Controle de fiado", "/solucoes/controle-de-fiado/", "Fiado também pelo WhatsApp")],
),

dict(
  slug="solucoes/multiplas-lojas",
  figura=("/assets/lojistas/distribuidora.webp",
          "Funcionário conferindo estoque no depósito da distribuidora"),
  title="Sistema para Múltiplas Lojas e Filiais | SoftPay",
  description="Controle de filiais na mesma conta, multi-login por funcionário e acesso de qualquer dispositivo. Até 10 usuários no ERP Completo. Teste grátis 7 dias.",
  h1="Múltiplas lojas e filiais",
  intro="Quando abre o segundo ponto, muita loja acaba com dois sistemas separados e nenhuma visão do conjunto. O SoftPay controla filiais dentro da mesma conta.",
  breadcrumbs=_c("Múltiplas lojas"),
  blocks=[
    sec("O problema",
      p("Dois pontos de venda com sistemas independentes significam dois cadastros de produto, dois estoques que não conversam e dois relatórios que precisam ser somados na mão. O dono passa a gastar tempo consolidando informação em vez de decidir com ela."),
      p("E a consolidação manual tem um defeito que não some com esforço: ela é sempre do passado. Quando a planilha fica pronta, a semana já acabou."),
    ),
    sec("Como isso aparece na rede",
      ul("<strong>Preço diferente na mesma marca.</strong> O item custa uma coisa numa loja e outra na outra, e ninguém decidiu isso.",
         "<strong>Você não sabe qual ponto vai bem.</strong> O faturamento somado esconde que uma loja sustenta a outra.",
         "<strong>Estoque parado num lugar e faltando no outro.</strong> Sem visão do conjunto, a mesma rede compra o que já tem.",
         "<strong>A equipe divide a senha.</strong> Lançamento errado não tem autor — e isso não é sobre desconfiar, é sobre poder corrigir.",
         "<strong>Cadastrar produto vira trabalho dobrado.</strong> Cada novidade precisa entrar duas vezes, e uma delas sempre sai diferente."),
    ),
    sec("Como o SoftPay resolve",
      h3("Filiais na mesma conta"),
      p("O SoftPay permite controlar filiais dentro da mesma conta, sem contratar um sistema separado para cada ponto. É o que acaba com os cadastros paralelos."),
      h3("Um catálogo, um preço"),
      p("Produto cadastrado uma vez vale para a operação inteira, com custo e preço definidos em um lugar só. A padronização deixa de depender de alguém avisar a outra loja."),
      h3("Multi-login"),
      p("Cada pessoa da equipe entra com o próprio acesso, em vez de todo mundo dividir a mesma senha. A quantidade varia por plano: 1 no Comércio, até 3 no Loja e até 10 no ERP Completo."),
      h3("Acesso de qualquer lugar"),
      p("Como os dados ficam na nuvem, você acompanha as duas lojas do celular, sem estar fisicamente em nenhuma delas — que é o problema central de quem tem mais de um ponto."),
      h3("Curva ABC do conjunto"),
      p("A partir do plano Loja, a curva ABC mostra o que sustenta o resultado. Numa rede pequena costuma revelar que o campeão de vendas de um ponto não vende nada no outro — e isso muda a compra."),
      h3("Registrar de qualquer ponto"),
      p("A partir do plano Loja, entrada de estoque, despesa e fiado entram por mensagem ou áudio no WhatsApp, sem a pessoa precisar estar na frente de um computador. Veja o <a href=\"/solucoes/bot-whatsapp/\">bot do WhatsApp</a>."),
    ),
    sec("O que precisa ser confirmado antes de contratar",
      p("Estruturas com filiais variam muito, e aqui é melhor perguntar do que supor. Estes pontos <strong>não estão confirmados</strong>:"),
      ul("<strong>Estoque compartilhado ou separado por filial.</strong> Se cada ponto tem o próprio saldo ou se o estoque é único — a resposta muda toda a operação.",
         "<strong>Perfis de permissão por funcionário.</strong> O multi-login dá acesso individual; se cada perfil precisa ver e fazer coisas diferentes, isso precisa ser verificado.",
         "<strong>Transferência de mercadoria entre lojas</strong> dentro do sistema.",
         "<strong>Relatório separado por filial</strong>, para comparar o desempenho de cada ponto lado a lado."),
      nota("Descreva a sua estrutura ao suporte antes de contratar — quantos pontos, se o estoque é compartilhado, quantas pessoas com acesso. É o tipo de coisa que decide se o sistema serve para você, e não dá para responder no genérico.", "O que perguntar ao suporte"),
    ),
    sec("O que o SoftPay não é",
      p("O tamanho da coisa, antes de você investir tempo num teste:"),
      ul("<strong>Não é um ERP de rede grande.</strong> Não há centro de custo, aprovação de compra, orçamento por unidade nem consolidação contábil.",
         "<strong>O teto é de 10 usuários</strong>, no ERP Completo. Se a sua rede precisa de mais acessos simultâneos, o SoftPay não comporta.",
         "<strong>Não faz gestão de franquia.</strong> Repasse de royalty, contrato e padronização de franqueado ficam fora.",
         "<strong>Não faz transferência entre lojas</strong> de forma confirmada — ver o bloco acima."),
      p("O perfil atendido é o da empresa com dois, três ou quatro pontos: a que passou do controle informal e ainda não virou rede."),
    ),
    sec("O que você passa a conseguir responder",
      ul("Qual das minhas lojas deu mais resultado neste mês?",
         "O mesmo produto está com o mesmo preço nos dois pontos?",
         "Quem lançou este registro?",
         "Quanto de mercadoria a rede inteira tem parada?",
         "O que vende bem num ponto e não vende no outro?",
         "Como está a loja em que eu não estou agora?"),
    ),
    sec("Em qual plano está",
      tabela(["Plano", "Preço", "Para quem tem mais de um ponto"], [
        ["Comércio", "R$ 69/mês", "<strong>1 usuário só</strong> — raramente serve a quem tem mais de uma loja"],
        ["Loja", "R$ 89/mês", "Dois pontos com equipe enxuta: estoque avançado, curva ABC e registro pelo WhatsApp. Até 3 usuários"],
        ["ERP Completo", "R$ 109/mês", "<strong>O plano de quem tem filiais:</strong> tudo da Loja mais NF-e e NFC-e e o teto de 10 usuários — normalmente o limitante"],
      ]),
      p("Todos podem ser testados por 7 dias, sem cartão de crédito. Veja os <a href=\"/#pricing\">planos completos</a>."),
    ),
  ],
  faq=[
    ("Quantas filiais dá para controlar?",
     "O SoftPay permite controlar filiais dentro da mesma conta. Não há um número divulgado — descreva sua estrutura ao suporte. Na prática, o limitante costuma ser a quantidade de usuários do plano."),
    ("Cada loja tem estoque separado?",
     "Esse ponto não está confirmado e depende de como a sua operação funciona. Verifique com o suporte antes de contratar, porque a resposta muda a forma de trabalhar."),
    ("Quantos usuários posso cadastrar?",
     "1 no plano Comércio, até 3 no Loja e até 10 no ERP Completo. O plano Nota Fiscal permite até 2."),
    ("Existem permissões diferentes por funcionário?",
     "O multi-login dá acesso individual a cada pessoa. Sobre perfis de permissão distintos, confirme com o suporte antes de contratar."),
    ("Dá para transferir mercadoria de uma loja para outra?",
     "Não está confirmado. Se a transferência entre pontos é parte da sua rotina, verifique com o suporte antes de decidir."),
    ("Consigo comparar o desempenho de cada loja?",
     "O sistema tem relatórios de venda e de estoque. Se você precisa dos pontos lado a lado num mesmo relatório, confirme o formato com o suporte."),
    ("Serve para franquia?",
     "Não. O SoftPay não faz gestão de franquia: repasse de royalty, contrato e padronização de franqueado ficam fora do sistema."),
    ("Consigo acompanhar as lojas de longe?",
     "Sim. Os dados ficam na nuvem e o sistema é acessado pelo navegador, inclusive no celular. É o caso de uso principal de quem não consegue estar nos dois pontos ao mesmo tempo."),
    ("Qual a diferença para a página de empresas com filiais?",
     "Esta descreve o recurso por dentro: como o controle de filiais e o multi-login funcionam. A página de segmento descreve a empresa — o momento do negócio, a rotina e o que confirmar antes de contratar."),
  ],
  cta_title="Teste com as duas lojas",
  cta_text="Cadastre os produtos uma vez, dê acesso próprio a quem trabalha em cada ponto e veja o conjunto num lugar só. 7 dias grátis, sem cartão.",
  related=[("Empresas com filiais", "/segmentos/empresas-com-filiais/", "Quem é essa empresa"),
           ("Controle de estoque", "/solucoes/sistema-de-estoque/", "Custo, giro e curva ABC"),
           ("Sistema financeiro", "/solucoes/sistema-financeiro/", "O caixa do conjunto"),
           ("Bot do WhatsApp", "/solucoes/bot-whatsapp/", "Registrar de qualquer ponto"),
           ("Distribuidora", "/segmentos/distribuidora/", "Depósito e loja separados"),
           ("Preços", "/#pricing", "Usuários por plano")],
),

]
